### ISSUE TITLE
Performance search rate: change entry cache monitor to recursive pthread mutex

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#4324]
Entry cache (entry and dn) are protected by a PRMonitor. Changing this Monitor into a recursive pthread mutex (cache aligned) increases throughput by 8%

**Comment by Firstyear** [comment]
I think I've looked at this in the past, that PRLock and PRMonitor are both slower than pthread mutex and recursive pthread mutexs. So it's probably not the only place in the code base that this would create a benefit.

**Comment by tbordaz** [comment]
fe0f6152f..abb93243b  master
d641e8528..14f67ebeb  389-ds-base-1.4.4
6c8755687..fc16302d3  389-ds-base-1.4.3

**Comment by mreynolds389** [comment]
8d40f2784..d4c2ab388  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
7f20bccb0..9a93ec7c1  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

Fixes crash on aarch64

**Comment by droideck** [comment]
de65f12a0..6d5537900  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   d4c4ff1b9..8564399c5  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   9a47b3d22..7ba233bf7  389-ds-base-2.0 -> 389-ds-base-2.0
   e28c36c84..6c95604f6  389-ds-base-2.1 -> 389-ds-base-2.1
   3043f85e9..21314ec9e  389-ds-base-2.2 -> 389-ds-base-2.2
