### ISSUE TITLE
Python task timeout updates.

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#4334]
**Issue Description**
Importing a file with 1 million users generates an import task failed message.

**Package Version and Platform:**
 - Platform: Fedora 32 - 5.6.6-300.fc32.x86_64 (Cloud Edition)
 - Package and version: 389-ds-base-1.4.3.12-1.fc32.x86_64

**Steps to Reproduce**
1. Increase the default import cache size from 16M to 100M. Importing the 1 M user file failed when using the default import cache size.
  
    ![image](https://user-images.githubusercontent.com/71395320/93881860-5c9a3680-fcd7-11ea-9e0d-dbd08fd75b95.png)

   ldapmodify -D "cn=dm"  -w password  -f update.ldif

2. Verify updates.
   ldapsearch -D cn=dm  -b "cn=bdb,cn=config,cn=ldbm database,cn=plugins,cn=config" -w password objectclass=* nsslapd-import-cachesize

    
    ![image](https://user-images.githubusercontent.com/71395320/93882190-c3b7eb00-fcd7-11ea-8cb4-a276ffd223a7.png)

3. Generate an ldif file containing 1 million users.
sudo dsctl inst01 ldifgen users --number 1000000 --suffix=dc=example,dc=com --ldif-file users.ldif

4. Import file into instance backend.
sudo dsconf inst01 backend import userroot users.ldif

    ![image](https://user-images.githubusercontent.com/71395320/93880561-98cc9780-fcd5-11ea-89a2-e966c1eb51ad.png)

5. Request a search for everything from the server, works as expected.
ldapsearch -D cn=dm -w password  objectclass=*

    ![image](https://user-images.githubusercontent.com/71395320/93881230-899a1980-fcd6-11ea-8a21-23c71769009d.png)

**Expected results**
It was expected that a search of the server DB would fail following the import task error. This error message could prevent some user automation maybe.

**Additional context**

**Comment by Firstyear** [comment]
Just to be clear, are you saying that the issue is when the nsslapd-import-cachesize is too small the error message on import isn't clear enough? Can you send us the errors you are seeing when the nsslapd-import-cachesize is too small?

**Comment by jchapma** [comment]
Hey,

I'm no expert here but I think there are 2 parts to this story:

1. When the import cache is too small the import generates an error and a subsequent search operation fails. So maybe a message telling the user to increase the import cache size would be useful.

2. When the import cache is big enough the import still generates an error message but a subsequent search operation runs successfully.

**Import operation when import cache size is the default**

1. Check the default import cache size
nsslapd-import-cachesize: 16777216

2. Load the 1 million user file  
    ![image](https://user-images.githubusercontent.com/71395320/93991137-da1b8080-fd83-11ea-8e97-ea05a3725a06.png)

3. Request a search for everything
    ![image](https://user-images.githubusercontent.com/71395320/93991273-00d9b700-fd84-11ea-845d-df56d542cd42.png)

There was nothing relevant in the server logs.

**Comment by Firstyear** [comment]
Can you send the content of the /var/log/dirsrv/slapd-instance/errors for both situations please? That will help understand the difference to case number 2. But yes this should communicate better what's going wrong.

**Comment by jchapma** [comment]
Hey,

While generating the logs for both scenarios I noticed that the import takes 575 seconds with a default import cache size (16M) and 440 seconds when the import cache size is set to 100M, which makes sense. 

Initially I mentioned, a search operation failed when using the default import cache size, this was my mistake, I was running a search operation before the import had finished.

But there is still an error message generated when importing a large user file in both scenarios, when in fact there is no error. 

Here are the logs for both scenarios, bottom left pane is access , bottom right is errors, nothing out of the ordinary.

**Default import cache size**
![default-import-cache](https://user-images.githubusercontent.com/71395320/94396322-9648c280-0159-11eb-9290-b088cf83feb4.png)

**100M import cache size**
![100m-import-cache](https://user-images.githubusercontent.com/71395320/94396333-9b0d7680-0159-11eb-87a6-65ba22e4ad06.png)

**Comment by Firstyear** [comment]
@jchapma Can you point me to the code you saw that has the hardcoded timelimit?

**Comment by jchapma** [comment]
@Firstyear 

Its just the default timeout for the task wait function.

I increased it from 120 to 300 and it imports a 1 million ldif file with no error generated. 

![task-timeout-change](https://user-images.githubusercontent.com/71395320/94584477-95f21980-0276-11eb-94d9-c30938c96527.png)
.

**Comment by Firstyear** [comment]
Right, I think the issue here is we have a hardcoded timeout at all. Especially frm the CLI callers we should really have no timeout on this for exactly this reason. What do you think @droideck?

**Comment by jchapma** [comment]
Maybe there was a good reason the timeout was added, but when it is removed and we use the tasks is_complete function it works fine in my test scenario.

![import-error-remove-timeout](https://user-images.githubusercontent.com/71395320/94675689-05691700-0312-11eb-830b-e3d589b50fd3.png)

**Comment by Firstyear** [comment]
I think that it's better to have the task go to completion especially when a user is interacting with the system. The timeouts are good for tests to prevent stalling or some error conditions. So I'd probably say we need to set timeout=120 but if timeout=None then we have no timeout. Again, @droideck probably has thoughts.

**Comment by droideck** [comment]
I think it's a good idea - to make `timeout=` optional.

We should take care of one issue then:

Here - https://github.com/389ds/389-ds-base/blob/master/src/lib389/lib389/cli_conf/plugins/memberof.py#L80
This code path won't be reached if the task is hanging.

Probably, we can overwrite an interruption signal there with a more descriptive message.

```
    def signal_handler(signal, frame):
        print('\n\nExiting...')  # Describe the possible interrupting issue here
        sys.exit(0)

    if not args.verbose:
        signal.signal(signal.SIGINT, signal_handler)
```

P.S. also, we need to fix all of the tests to use the timeout
P.P.S. bug doesn't seem to be hard. Maybe, it'll be a good low-hanging fruit for @jchapma ;)
P.P.P.S. feel free to rename this issue accordingly to the bug you found

**Comment by jchapma** [comment]
@droideck I agree, I would like to pick this low hanging fruit :)

**Comment by Firstyear** [comment]
@droideck No we don't need to change all the tests to use timeout. I think we just need timeout=120 and then pass timeout=none from the cli front ends when needed? Unless there is a different test you are thinking of.

**Comment by droideck** [comment]
> @droideck No we don't need to change all the tests to use timeout. I think we just need timeout=120 and then pass timeout=none from the cli front ends when needed? Unless there is a different test you are thinking of.

Agree, it'll be more efficient:)
