### ISSUE TITLE
Improvements to dsidm

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#4351]
Some minor issues were raised:

* When group is set to none, ldap_access_filter = None is set which is not valid. We should emita  comment in this case instead. 
* user status has no attribute is_locked. (fixed in master already)
* warn on sssd config if uri is ldapi

**Comment by mreynolds389** [comment]
cherry pick to 1.4.2

**Comment by Firstyear** [comment]
```
   4fdf14c4f..4a8de7537  389-ds-base-1.4.2 -> 389-ds-base-1.4.2
   47fe10fbf..f3317020b  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
```
