### ISSUE TITLE
dsconf chaining may create invalid config when parent suffix does not exist

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#4373]
It is possible that someone wishes to create a chaining config, where no parent suffix already exists. Consider chaining say for dc=example,dc=com and the existing DB is for dc=example,dc=org. In this case, dsconf creates the mapping tree entry with a parent suffix of dc=com, even though no mapping tree entry for dc=com exists.

When the chaining entry is created, the mapping tree must be examined to determine if a parent *does* exist and what it is along the DN path.

**Comment by Firstyear** [comment]
@mreynolds389 Checking with you that it's okay for this to be backported to 1.4.3 and 1.4.4.

**Comment by mreynolds389** [comment]
Yes it can be backported!

**Comment by Firstyear** [comment]
I reran the mapping tree and basic tests on both branches to be 100% sure :) 
```
   9bde84277..66f1a75eb  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   b79419a44..43bcb5616  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
```

Thanks again @mreynolds389!

**Comment by mreynolds389** [comment]
Reopening.  This causes a malloc error in the server right after instance creation:

```
	389-Directory/2.0.1.20201209gitd644ebaa9 B2020.344.2303
	localhost.localdomain:389 (/etc/dirsrv/slapd-localhost)

[10/Dec/2020:11:56:29.862159667 -0500] - ERR - memory allocator - cannot calloc 0 elements;
trying to allocate 0 or a negative number of elements is not portable and
gives different results on different platforms.
[10/Dec/2020:11:56:29.903738247 -0500] - INFO - main - 389-Directory/2.0.1.20201209gitd644ebaa9 B2020.344.2303 starting up
[10/Dec/2020:11:56:29.906456781 -0500] - INFO - main - Setting the maximum file descriptor limit to: 524288
[10/Dec/2020:11:56:29.910923818 -0500] - ERR - allow_operation - Component identity is NULL
[10/Dec/2020:11:56:30.649917222 -0500] - INFO - PBKDF2_SHA256 - Based on CPU performance, chose 2048 rounds
```

**Comment by Firstyear** [comment]
@mreynolds389 Interesting, good catch. I don't know how I missed that ... anyway, I'll fix this today.
