### ISSUE TITLE
allow more than 1 empty AttributeDescription for ldapsearch, without the risk of denial of service

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#4379]
**Issue Description**
https://github.com/389ds/389-ds-base/issues/3028 enforce a strict limit of empty attributeDescription.
This is good but the limit is so low that some application may start failing
This bug is to extend a bit that limit so that application wont break

**Package Version and Platform:**
 - Platform:all 
 - Package and version: since https://github.com/389ds/389-ds-base/issues/3028  (1.4.1)

**Steps to Reproduce**

ldapsearch -LLL.... -b 'dc=example,dc=com' "" "" cn
Protocol error (2)

<pre>
[15/Oct/2020:15:45:00.555817663 +0200] conn=7 op=1 SRCH base="dc=example,dc=com" scope=2 filter="(objectClass=*)", invalid attribute request
</pre>

**Expected results**
It should succeed up to 10 empty attributes

**Comment by tbordaz** [comment]
43c691569..b8b169142  master
311dab59a..4508d3c4d  389-ds-base-1.4.3
f39758817..ab00f9753  389-ds-base-1.4.2
22d67399b..9faf2d77a  389-ds-base-1.3.10

**Comment by tbordaz** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1870624

**Comment by tbordaz** [comment]
@aadhikar would you mind to have a look at the recent PR that possibly creates a regression

268d1c7ed Issue 4379 - Allow more than 1 empty AttributeDescription for ldapsearch, without the risk of denial of service

Test: tests/suites/acl/misc_test.py::test_info_disclosure

**Comment by aadhikar** [comment]
@tbordaz by just looking at it I think it's failing because we changed the filter function to have one more argument that is `attrlist` which is the second argument so we need to explicitly specify `scope=`

**Comment by tbordaz** [comment]
@aadhikar your eyes are much better than mine. Thanks for spotting this. I will test a fix.

**Comment by tbordaz** [comment]
ff830604e..f53b28448  master 
268d1c7ed..ff830604e master
53f372cea..268d1c7ed master
