### ISSUE TITLE
DSE config modify does not call be_postop 

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#4391]
**Issue Description**
During a DSE modify, be_preop callback are called. But be_postop callback are called at the condition dse_call_callback is different that SLAPI_DSE_CALLBACK_DO_NOT_APPLY.

This should systematically call be_postop if be_preop were called. In addition  postop_modify_config_dse returning an invalid rc, systematically prevents DSE modify to call be_postop

**Package Version and Platform:**
 - Platform: all
 - Package and version: since 2010

**Steps to Reproduce**
Under debugger, update any config attribute (ie. nsslapd-auditlog-logging-enabled) and check that be_postop are not called

**Expected results**
If be_preop are called, be_postop should be called

**Comment by Firstyear** [comment]
Yeah, I agree, we should call the postops too to balance this.

**Comment by tbordaz** [comment]
5b0cbddc4..bc92c17bc    master
6e1b7b9d2..f1285d78a    1.4.4
d2dcf85c3..5ea53ebd7    1.4.3

**Comment by mreynolds389** [comment]
@tbordaz can this be closed?

**Comment by tbordaz** [comment]
opss.. forgot to close this one
