### ISSUE TITLE
Remove un-used http client module

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#4407]
This plugin is no longer used or supported, we should remove it.

**Comment by Firstyear** [comment]
Okay, so removing the http client plugin seems easy, and it means we can remove presence which is also defunct. The issue is that template-dse.ldif enables this by default, so we'll need a way to handle this removal in upgrades. Similar removing presence may be affected by space insensitive string being enabled by default too. Perhaps we need a skip-list of plugin paths in loading that we just silently ignore so that we can handle the .so being no longer present.

**Comment by mreynolds389** [comment]
You just need an upgrade function to disable and remove it if present  :-)  That's what I did with upgrade_AES_reverpwd_plugin()

**Comment by mreynolds389** [comment]
> You just need an upgrade function to disable and remove it if present :-) That's what I did with upgrade_AES_reverpwd_plugin()

Hmm, but that might not work if the library is already removed as the server probably won't start.  Might need a new approach for handling these cases.  Like we allow the server to start if the library is missing, then the upgrade code can remove it from the config

**Comment by Firstyear** [comment]
Hmmm actually, I think it can work in upgrade.c. It looks like we call upgrade_server before we call plugin_startall, so actually it may work.

**Comment by Firstyear** [comment]
Okay, scratch that. I think we will need some special handling for this. It looks like we attempt to dlopen the plugin before upgrade_server (it's done in the dse_call_callback handlers for dse_read_one_file). Given we know what plugins we are removing, and where, what would you think about plugin_setup having a "deny list" of initfunction/libs that it won't process and skips past. We could have this as a fn call to put it into upgrade.c to keep it all localised, and then plugin_setup can check if the plugin is in that list or not, and just returns success and shortcuts the return so we never even create the plugin structure etc.
