### ISSUE TITLE
Missing parameters in the command to create an agreement with SSLCLIENTAUTH bind method

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4412]
Document URL:
    https://access.redhat.com/documentation/en-us/red_hat_directory_server/11/html/administration_guide/configuring_replication_partners_to_use_certificate-based_authentication

Section Number and Name:
    5. Create a replication agreement on both servers that use certificate-based authentication:

Describe the issue:
The documented command to create the replication agreement is failing with the following message:
######
Error: You need to set the bind dn (--bind-dn) and the password (--bind-passwd) for bind method (sslclientauth)
######

Suggestions for improvement:
The customer had to add the missing parameters to make the command work.
Please update the commands in the RHDS documentation.

Additional information:
    https://pagure.io/389-ds-base/blob/389-ds-base-1.4.2/f/src/lib389/lib389/cli_conf/replication.py#_691
====================================================================
    # We do need the bind dn and credentials for none-sasl bind methods
    if (bind_method in ('simple', 'sslclientauth')) and (args.bind_dn is None or args.bind_passwd is None):   
        raise ValueError("You need to set the bind dn (--bind-dn) and the password (--bind-passwd) for bind method ({})".format(bind_method))
====================================================================

**Comment by mreynolds389** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1877551

**Comment by droideck** [comment]
53d37df7f..01a576bc4  389-ds-base-1.4.2 -> 389-ds-base-1.4.2
   c5d7865a6..b0594d53e  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   bf454ad07..6e1b7b9d2  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
