### ISSUE TITLE
SIGFPE crash in rhds disk monitoring routine

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4414]
Ticket was cloned from Red Hat Bugzilla: [Bug 1890118](https://bugzilla.redhat.com/show_bug.cgi?id=1890118)

_Please note that this Bug is private and may not be accessible as it contains confidential Red Hat customer information._

```
Description of problem:

A customer reports a crash in RHDS that occurs every day at same time

Version-Release number of selected component (if applicable):

RHDS 11

How reproducible:

Not reproduced in-house. Happens regularly on customer site

Actual results:

Crash happening every morning around 5am

Expected results:

RHDS should not crash

Additional info:

This is the stackframe of the crash

Thread 1 (Thread 0x7f8605bfe700 (LWP 1956012)):
#0  0x000055c19b7fd48f in monitor_disk_info (pb=<optimized out>, e=0x7f860407c5c0, entryAfter=<optimized out>, returncode=0x7f8605bf730c, returntext=<optimized out>, arg=<optimized out>) at /usr/include/bits/stdio2.h:67
        i = <optimized out>
        rc = 0
        dirs = 0x7f8538a14680
        buf = "partition=\"/var/log/dirsrv\" size=\"32201768960\" used=\"6259421184\" available=\"25942347776\" use%=\"19\"\000\247\205\177\000\000\364\372\017&\206\177\000\000\240:\024\247\205\177\000\000\003\000\000\000\003", '\000' <repeats 11 times>, "\200:\016+\206\177\000\000\000\b", '\000' <repeats 14 times>, "@4\024\247\205\177\000\000\033\000\000\000\033", '\000' <repeats 20 times>, "\b\000\000\000\000\000\000"...
        val = {bv_len = 98, bv_val = 0x7f8605bf5220 "partition=\"/var/log/dirsrv\" size=\"32201768960\" used=\"6259421184\" available=\"25942347776\" use%=\"19\""}
        vals = {0x7f8605bf5200, 0x0}
        total_space = 0
        avail_space = 0
        used_space = 0
#1  0x00007f863211c387 in dse_call_callback (pb=pb@entry=0x7f8604000000, operation=operation@entry=4, flags=flags@entry=1, entryBefore=entryBefore@entry=0x7f860407c5c0, entryAfter=entryAfter@entry=0x0, returncode=0x7f8605bf730c, returntext=0x7f8605bf7590 "", pdse=<optimized out>) at ldap/servers/slapd/dse.c:2640


(gdb) p i
$1 = <optimized out>

(gdb) p dirs[0]
$4 = 0x7f860400a250 "/var"
(gdb) p dirs[1]
$5 = 0x7f86040491c0 "/etc/dirsrv"
(gdb) p dirs[2]
$6 = 0x7f86040491b0 "/var/log/dirsrv"
(gdb) p dirs[3]
$7 = 0x7f860400a278 "fs"
(gdb) p dirs[4]
$8 = 0x7f86040eb800 "/sys/fs/cgroup/rdma"
(gdb) p dirs[5]
$9 = 0x7f86040491d0 "/dev/hugepages"
(gdb) p dirs[6]
$10 = 0x0

==> df command from sosreport ( this explains the crash)

cgroup                                         0       0         0    - /sys/fs/cgroup/rdma
hugetlbfs                                     0       0         0    - /dev/hugepages

This explains the dviide by zero crash, but not sure how these partitions are being pulled in.  Something in disk_mon_get_mount_point(char *dir) might not be working as expected
```

**Comment by mreynolds389** [comment]
b0cc33859..ea10cc3e7  389-ds-base-1.4.4 -> 389-ds-base-1.4.4

760983722..c8d311979  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by tbordaz** [comment]
@bsimonova The test case test_produce_division_by_zero looks good and works on 1minutetip. But it fails (systematically?) during PRCI.

The failure occurs while setting auditlog to <instance_log>/tmp/audit directory

    standalone.config.set('nsslapd-auditlog', '/var/log/dirsrv/slapd-{}/tmp/audit'.format(standalone.serverid))
    ldap.UNWILLING_TO_PERFORM: {'msgtype': 103, 'msgid': 6, 'result': 53, 'desc': 'Server is unwilling to perform', 'ctrls': [], 'info': 'Cannot open auditlog directory "/var/log/dirsrv/slapd-standalone1/tmp/audit"'}

The server is unwilling to perform because the open(PR_WRONLY | PR_APPEND | PR_CREATE_FILE) fails.

**Comment by bsimonova** [comment]
@tbordaz 
So it found an issue with setting the audit log directory if I understand correctly?
Or the test needs to be adjusted?
Thanks!

**Comment by tbordaz** [comment]
The failure occurs when the server tries to open the audit file. It fails, errno is logged in error log but error logs are not available (AFAIK) with PRCI

**Comment by tbordaz** [comment]
@bsimonova, @vashirov and I investigate the RC of the failure. It appears that the tests is successful with 1mt (openstack) and fails with prci (container). The reason is that there is a permission denied on prci when access the tmpfs <log>/tmp directory. Would you please add a condition to skip that test with PRCI ( DISK_MONITORING_ACK=False).
