### ISSUE TITLE
ldif2db - offline. Warn the user of skipped entries

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#4418]
**Issue Description**
ldif2db is used to import directory entries from an ldif file to a directory server instance. During the import operation, entries might not conform to various constraints (attribute syntax, schema violation, etc) and be skipped. On completion of the import operation the user receives a success message, with no indication of a skipped entry, apart from a message in the error logs. 

**Package Version and Platform:**
 - Platform: 5.6.6-300.fc32.x86_64
 - Package and version: 389-Directory/1.4.4.4

**Steps to Reproduce**
1. Verify syntax checking is enabled (default)
2. Generate sample ldif file
3. Modify the ldif file to violate a syntax checking rule (An empty fax number)
4. Import ldif file, notice import success message
5. Check the server error logs:
```c
ERR - slapi_entry_syntax_check - "uid=OJeleniewski1000,ou=product development,dc=example,dc=com": (facsimileTelephoneNumber) value #0 invalid per syntax
WARN - import_producer - import userroot: Skipping entry "uid=OJeleniewski1000,ou=product development,dc=example,dc=com" which violates attribute syntax,
```

**Expected results**
The user should get a warning message saying some entries were skipped and the that they should check the logs for more info.

**Additional context**
Parent bug: https://bugzilla.redhat.com/show_bug.cgi?id=1627645
ldif2db can operate in both offline and online modes, the parent bug will be divided into offline and online updates that each will require a different approach.

**Comment by jchapma** [comment]
Updated version

**Comment by droideck** [comment]
Sorry for being a bit late but the test case fails...

```
        ...
            1. ldif2db import returns a warning to signify skipped entries
        """
        import_ldif1 = _create_syntax_err_ldif(topo)
        # Import the offending LDIF data - offline
        topo.standalone.stop()
        ret = topo.standalone.ldif2db('userRoot', None, None, None, import_ldif1)
>       assert ret == TaskWarning.WARN_SKIPPED_IMPORT_ENTRY
E       assert False == <TaskWarning.WARN_SKIPPED_IMPORT_ENTRY: 8>
E         -False
E         +<TaskWarning.WARN_SKIPPED_IMPORT_ENTRY: 8>

dirsrvtests/tests/suites/import/import_test.py:265: AssertionError
```

**Comment by jchapma** [comment]
Hi @droideck 

The changes for this PR don't allocate memory or exit anywhere before memory is normally freed up. I believe ASAN is catching a memory leak that has occurred in another area, causing some tests to fail. There are some other tests failing in import with the same memory trace, they all pass when ASAN is disabled.

From a quick look at the ASAN memory leak trace, it seems the issue stems from where we setup the internal backends. 
https://github.com/389ds/389-ds-base/blob/master/ldap/servers/slapd/fedse.c#L2886

Once I was sure the ASAN errors were not related to the changes in this PR, I disabled it.

But I get your point, the memory leak issue should have been addressed first. I will have a look at it tomorrow.

**Comment by Firstyear** [comment]
I think I opened the issue about the BE leaks recently. See https://github.com/389ds/389-ds-base/issues/4396

**Comment by droideck** [comment]
> Hi @droideck
> 
> The changes for this PR don't allocate memory or exit anywhere before memory is normally freed up. I believe ASAN is catching a memory leak that has occurred in another area, causing some tests to fail. There are some other tests failing in import with the same memory trace, they all pass when ASAN is disabled.
> 
> From a quick look at the ASAN memory leak trace, it seems the issue stems from where we setup the internal backends.
> https://github.com/389ds/389-ds-base/blob/master/ldap/servers/slapd/fedse.c#L2886
> 
> Once I was sure the ASAN errors were not related to the changes in this PR, I disabled it.
> 
> But I get your point, the memory leak issue should have been addressed first. I will have a look at it tomorrow.

RIght, my mistake. 
I missed the ASAN output and I thought that the error I've posted is a separate issue.
I've rerun once again without ASAN and yes, it passes. Closing this issue as @Firstyear has opened the right one.
Thanks and sorry for the fuss :)

**Comment by jchapma** [comment]
@droideck No need for sorry at all, you highlighted a bug in the first version of this PR that I missed because I had ASAN disabled. So thank you.

**Comment by mreynolds389** [comment]
8bd016cc2..09f771bcb  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
c8d311979..c79947c3d  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by mreynolds389** [comment]
53ceb1118..0acda489f  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
