### ISSUE TITLE
ldif2db - online. Warn the user of skipped entries

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#4419]
**Issue Description**
ldif2db is used to import directory entries from an ldif file to a directory server instance. During the import operation, entries might not conform to various constraints (attribute syntax, schema violation, etc) and be skipped. On completion of the import operation the user receives a success message, with no indication of a skipped entry, apart from a message in the error logs. 

**Package Version and Platform:**
 - Platform: 5.6.6-300.fc32.x86_64
 - Package and version: 389-Directory/1.4.4.4

**Steps to Reproduce**
1. Verify syntax checking is enabled (default)
2. Generate sample ldif file
3. Modify the ldif file to violate a syntax checking rule (An empty fax number)
4. Import ldif file, notice import success message
5. Check the server error logs:
```c
ERR - slapi_entry_syntax_check - "uid=OJeleniewski1000,ou=product development,dc=example,dc=com": (facsimileTelephoneNumber) value #0 invalid per syntax
WARN - import_producer - import userroot: Skipping entry "uid=OJeleniewski1000,ou=product development,dc=example,dc=com" which violates attribute syntax,
```

**Expected results**
The user should get a warning message saying some entries were skipped and the that they should check the logs for more info.

**Additional context**
Parent bug: https://bugzilla.redhat.com/show_bug.cgi?id=1627645
ldif2db can operate in both offline and online modes, the parent bug will be divided into offline and online updates that each will require a different approach.

**Comment by jchapma** [comment]
Here is a proposal, for this change. It adds a new nsTaskWarning attribute that has DB version implications as mentioned by @tbordaz @vashirov 
The only other option I can think of is to use the existing nsTaskExitCode attribute to signify a task warning only if there was no task errors.

**Comment by tbordaz** [comment]
This patch looks very nice. Good job.
Some minor comments:

- The patch adds a new attribute (integer) 'nsTaskWarning' that reports if some entries were skipped during import. But this attribute is a flag that can also report event during upgrade task (WARN_UPGRADE). This issue being specific to import (and there is not demand to report upgrade warning), why not just naming this attribute 'nsTaskImportSkipped' for example
- Also it reports a state that some entries were skipped, why not reporting directly the number of skipped entries job->skipped
- During an import some entries are skipped if they do not conform the schema ('skipped') or if they are out of the suffix ('not_here_skipped'), I think we could report the sum of them

**Comment by jchapma** [comment]
@tbordaz 
1) The idea is that over time we might want to capture different kinds of task warning, hence the enum that can be extended for other warnings. 
2) I like that idea, but then we wont be able to identify what warning code corresponds to each warning, Assuming that we will want/need to capture other task warnings in the future.
3) My understanding is that the "not_here_skipped" is used to identify skipped warnings for a different be, and not the be we are currently importing to. Maybe I need to understand it a little better.

**Comment by Firstyear** [comment]
Causes a build failure for me :( 

```
  CC       ldap/servers/slapd/libslapd_la-task.lo
  CC       ldap/servers/slapd/libslapd_la-errormap.lo
/home/william/development/389ds/ds/ldap/servers/slapd/task.c:476:9: error: void function 'slapi_task_set_warning' should not return a value [-Wreturn-type]
        return task->task_warn |= warn;
        ^      ~~~~~~~~~~~~~~~~~~~~~~~
/home/william/development/389ds/ds/ldap/servers/slapd/task.c:1669:32: warning: unused parameter 'pb' [-Wunused-parameter]
task_restore_add(Slapi_PBlock *pb,
                               ^
1 warning and 1 error generated.
sccache: Compiler killed by signal 1
make[2]: *** [Makefile:8529: ldap/servers/slapd/libslapd_la-task.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/william/build/ds'
make[1]: *** [Makefile:3424: all] Error 2
make[1]: Leaving directory '/home/william/build/ds'
make: *** [Makefile:59: ds-build] Error 2
```

**Comment by jchapma** [comment]
Gulp... I didn't heed the advice from a colleague and redirect the output of make to /dev/null to catch silly mistakes like this. I will fix this now, I guess I can merge under the one line rule ?

**Comment by Firstyear** [comment]
> Gulp... I didn't heed the advice from a colleague and redirect the output of make to /dev/null to catch silly mistakes like this. I will fix this now, I guess I can merge under the one line rule ?

Yep, just merge with one line rule. It's no issue mate, we all have made this mistake, it's no harm at all :)

**Comment by mreynolds389** [comment]
> Gulp... I didn't heed the advice from a colleague and redirect the output of make to /dev/null to catch silly mistakes like this. 

:-D

**Comment by jchapma** [comment]
Merged to master

**Comment by mreynolds389** [comment]
ea10cc3e7..8bd016cc2  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
