### ISSUE TITLE
Move DS verison to major/minor/maintenance: X.X.X.X --> X.X.X

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4420]
**Issue Description**

In master branch we are moving to 2.0.0.  Previously we've been using 1.4.4.5, but its really unnecessary.  Our major version should be changing more often than it has, and with bumping this version with each major version of RHEL or major feature change makes sense, and it also obsoletes the 4th version number.  So to simplify things we should just use X.X.X in our versioning

**Comment by Firstyear** [comment]
🎉 I 100% agree with this, and it's a great change. Thanks @mreynolds389!!
