### ISSUE TITLE
Unable to build with Rust enabled in closed environment 

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4421]
**Issue Description**

COPR builds systems as well as RHEL do not allow access to the network to do the build.  Enablign Rust currently still needs to do this and it is breaking the build...

`
SLAPD_HEADER_DIR=/builddir/build/BUILD/389-ds-base-2.0.0.0.20201103git5b0cbddc4/ \
	cargo rustc  --manifest-path=./src/librnsslapd/Cargo.toml \
	--release --verbose -- -C debuginfo=2
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
error: failed to get `libc` as a dependency of package `librslapd v0.1.0 (/builddir/build/BUILD/389-ds-base-2.0.0.0.20201103git5b0cbddc4/src/librslapd)`
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
Caused by:
  failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
make: *** [Makefile:13775: /builddir/build/BUILD/389-ds-base-2.0.0.0.20201103git5b0cbddc4/rs/release/librslapd.a] Error 101
make: *** Waiting for unfinished jobs....
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
error: failed to get `libc` as a dependency of package `librslapd v0.1.0 (/builddir/build/BUILD/389-ds-base-2.0.0.0.20201103git5b0cbddc4/src/librslapd)`
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
Caused by:
  failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
make: *** [Makefile:13786: /builddir/build/BUILD/389-ds-base-2.0.0.0.20201103git5b0cbddc4/rs/release/librnsslapd.a] Error 101
`

So we need to do something like what we do with Cockpit where we pull everything in and build it first when generating an srpm.

**Comment by vashirov** [comment]
Did you do `make -f rpm.mk download-cargo-dependencies` before making srpms?
It was added in https://pagure.io/389-ds-base/pull-request/50633 and should work.

**Comment by mreynolds389** [comment]
> Did you do `make -f rpm.mk download-cargo-dependencies` before making srpms?
> It was added in https://pagure.io/389-ds-base/pull-request/50633 and should work.

Nope :-)  But this should be done by default once Rust is enabled by default.

**Comment by mreynolds389** [comment]
> > Did you do `make -f rpm.mk download-cargo-dependencies` before making srpms?
> > It was added in https://pagure.io/389-ds-base/pull-request/50633 and should work.
> 
> Nope :-) 

This still did not work.  I did:

- SKIP_AUDIT_CI=1 make -f rpm.mk download-cargo-dependencies
- SKIP_AUDIT_CI=1 make -f rpm.mk srpms

During the build it is still trying to download things from github.com.

I even updated the rpm.mk:
diff --git a/rpm.mk b/rpm.mk
index 9cd0a0c05..d4f9593cc 100644
--- a/rpm.mk
+++ b/rpm.mk
@@ -25,7 +25,7 @@ TSAN_ON = 0
 # Undefined Behaviour Sanitizer
 UBSAN_ON = 0

-RUST_ON = 0
+RUST_ON = 1

 COCKPIT_ON = 1

@@ -120,7 +120,7 @@ rpmbuildprep:
                cp dist/sources/$(JEMALLOC_TARBALL) $(RPMBUILD)/SOURCES/ ; \
        fi

-srpms: rpmroot srpmdistdir tarballs rpmbuildprep
+srpms: rpmroot srpmdistdir tarballs rpmbuildprep download-cargo-dependencies
        rpmbuild --define "_topdir $(RPMBUILD)" -bs $(RPMBUILD)/SPECS/$(PACKAGE).spec
        cp $(RPMBUILD)/SRPMS/$(RPM_NAME_VERSION)*.src.rpm dist/srpms/
        rm -rf $(RPMBUILD)


But it still does not work.

**Comment by Firstyear** [comment]
There is a flag for --enable-rust-offline which tells the build how to use the vendor.tar.gz that is created with the download dependencies make option @vashirov mentioned. it's so that as developers we can build online, but packaging we can use --enable-rust-offline for exactly this :)

**Comment by vashirov** [comment]
Yeah, I think we should add it to rpm spec by default when using Rust:
```diff
diff --git a/rpm/389-ds-base.spec.in b/rpm/389-ds-base.spec.in
index a810690cb..83538e049 100644
--- a/rpm/389-ds-base.spec.in
+++ b/rpm/389-ds-base.spec.in
@@ -335,7 +335,7 @@ UBSAN_FLAGS="--enable-ubsan --enable-debug"
 %endif
 
 %if %{use_rust}
-RUST_FLAGS="--enable-rust"
+RUST_FLAGS="--enable-rust --enable-rust-offline"
 %endif
 
 %if !%{use_cockpit}


```
I did a few builds in copr with Rust enabled (and network access disabled): https://copr.fedorainfracloud.org/coprs/vashirov/389ds/builds/

**Comment by mreynolds389** [comment]
This is still failing for me with this flag set (different error though), when I generate an srpm and send it to copr:

```
...
error: failed to get `concread` as a dependency of package `librslapd v0.1.0 (/builddir/build/BUILD/389-ds-base-2.0.0.0.20201104gitfc8a94943/src/librslapd)`
Caused by:
  failed to load source for dependency `concread`
Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`
Caused by:
  failed to update replaced source registry `https://github.com/rust-lang/crates.io-index`
Caused by:
  failed to read root of directory source: /builddir/build/BUILD/389-ds-base-2.0.0.0.20201104gitfc8a94943/vendor
Caused by:
  No such file or directory (os error 2)
make: *** [Makefile:13782: /builddir/build/BUILD/389-ds-base-2.0.0.0.20201104gitfc8a94943/rs/release/librnsslapd.a] Error 101
error: Bad exit status from /var/tmp/rpm-tmp.6Nmhbt (%build)
    Bad exit status from /var/tmp/rpm-tmp.6Nmhbt (%build)
```

**Comment by vashirov** [comment]
`concread` was introduced in #4411, so you need to update cargo dependencies and download them again:
`make -f rpm.mk update-cargo-dependencies download-cargo-dependencies` 

My copr build with #4411 applied on top of master has succeeded: https://download.copr.fedorainfracloud.org/results/vashirov/389ds/fedora-33-x86_64/01744840-389-ds-base/builder-live.log.gz

**Comment by mreynolds389** [comment]
60fb9fa82..488bad576  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
