### ISSUE TITLE
Using ldifgen with --start-idx option fails with unsupported operand

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#4440]
Description of problem:
Using ldifgen with --start-idx option fails with ERROR: Error: unsupported operand type(s) for +=: 'int' and 'str'

Version-Release number of selected component (if applicable):
389-ds-base-1.4.3.8-2.module+el8.3.0+6591+ebfc9766.x86_64

How reproducible:
Always

Steps to Reproduce:
1. Create DS instance
2.

dsctl -v slapd-localhost ldifgen users --suffix dc=example,dc=com --parent ou=people,dc=example,dc=com --number 100000 --generic --start-idx=50
DEBUG: The 389 Directory Server Administration Tool
DEBUG: Inspired by works of: ITS, The University of Adelaide
DEBUG: Called with: Namespace(func=<function dbgen_create_users at 0x7feec90632f0>, generic=True, instance='slapd-localhost', json=False, ldif_file='users.ldif', list=False, localize=False, number='100000', parent='ou=people,dc=example,dc=com', rdn_cn=False, remove_all=False, start_idx='50', suffix='dc=example,dc=com', verbose=True)
DEBUG: Allocate <class 'lib389.DirSrv'> with None
DEBUG: Allocate <class 'lib389.DirSrv'> with b'localhost.localdomain':636
DEBUG: Allocate <class 'lib389.DirSrv'> with b'localhost.localdomain':636
DEBUG: Instance allocated
INFO:
Generating LDIF with the following options:
INFO: - number=100000
INFO: - suffix=dc=example,dc=com
INFO: - parent=ou=people,dc=example,dc=com
INFO: - generic=True
INFO: - start-idx=50
INFO: - rdn-cn=False
INFO: - localize=False
INFO: - ldif-file=/var/lib/dirsrv/slapd-localhost/ldif/users.ldif
INFO:
Writing LDIF ...
DEBUG: unsupported operand type(s) for +=: 'int' and 'str'
Traceback (most recent call last):
File "/usr/sbin/dsctl", line 138, in <module>
result = args.func(inst, log, args)
File "/usr/lib/python3.6/site-packages/lib389/cli_ctl/dbgen.py", line 195, in dbgen_create_users
dbgen_users(inst, args.number, args.ldif_file, args.suffix, generic=args.generic, parent=args.parent, startIdx=args.start_idx, rdnCN=False, pseudol10n=args.localize)
File "/usr/lib/python3.6/site-packages/lib389/dbgen.py", line 249, in dbgen_users
i += startIdx
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
ERROR: Error: unsupported operand type(s) for +=: 'int' and 'str'

Actual results:

Expected results:
No errors.

Additional info:

**Comment by progier389** [comment]
Note: 

I hit the same bug when using --number=100000
and I do not hit the bug when usign:
dsctl -v slapd-localhost ldifgen users --suffix dc=example,dc=com --parent ou=people,dc=example,dc=com --number 100000 --generic --start-idx 50

Apparently by default the parser interpret  option=xxxx as if xxxx is a string rather than an integer while in option xxxx the type is evaluated dynamically. 
It is easily fixed by specifying type=int when adding the option in the parser,
   but IMHO the problem is plaguing most numeric argument of the command. And I suspect it will be painful to tests

**Comment by Firstyear** [comment]
This is classic python. Dynamic typing like this is always problematic ... it likely means we need to wrap the argparse statement where we get the start-idx in a `int()` call.

**Comment by progier389** [comment]
Since this bug has a simple work-around: using --start-idx 50  instead of using --start-idx=50 
I target it only towards 2.0.0 milestone.

**Comment by mreynolds389** [comment]
@progier389 - actually this bug is set for RHEL 8.4, so this needs to be cherry-picked to all the way down to 1.4.3.  Adjusting milestone...
