### ISSUE TITLE
dsconf replication monitor fails to retrieve consumer RUV

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#4449]
**Issue Description**
"dsconf replication monitor" fails to retrieve database RUV entry from consumer and this appears into the Cockpit web UI too

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 389-ds-base-1.4.4.4-20200721git5d41dc5a4.fc32.x86_64

**Steps to Reproduce**
1. Setup a 2 master topology 
2. dsconf -v m1 replication monitor --connections "$HOST_M1:$PORT_M1:cn=directory manager:password" "$HOST_M2:$PORT_M2:cn=directory manager:password"
3. See error: Replication Status: Not in Synchronization: supplier (5f6138dc000000010000) consumer (Unavailable) State (green) Reason (error (0) no replication sessions started since server startup)

The bug is also visible in Cockpit web UI: "Red Hat Directory Server | Monitoring | Replication | Sync Report | Prepare | Generate Report"

**Expected results**
There should be a csn associated with the consumer instead of "Unavailable"

**Comment by progier389** [comment]
Cherry-pick done:
73ee04fa12cd1de3a5e47c109e79e31c1aaaa2ab --> master
4d5915f35..73ee04fa1  --> master
8657fe478..2c89eef7b  --> 389-ds-base-1.4.4
3b6cd3fb3..803462163  --> 389-ds-base-1.4.3  
8ce1c5d2b..d9cbcc267  --> 389-ds-base-1.4.2

(FYI: testcase was not modified in 1.4.3 and 1.4.2 branches because the modified file does not exists in these branches)

**Comment by mreynolds389** [comment]
Thanks Pierre, yeah the test cases typically don't cherry-pick to older branches very well.  Which is usually fine, but in this case the test should go into the 1.4.3 branch since that is what QE is using to test RHEL 8.  It might have to be a separate commit where you just create the file yourself (where it just contains this specific test)

**Comment by progier389** [comment]
Ok, in this case I will push  the whole file (it contains a single test about dsconf monitor)
but anyway I had better test that there is no incompatibility ...

**Comment by progier389** [comment]
Added testcase in 1.4.3 as mark advised:

Added dirsrvtests/tests/suites/clu/repl_monitor_test.py file:
   6fe2ed44d..2af2abcd4  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
