### ISSUE TITLE
Unexpected info returned to ldap request

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#4480]
**Issue Description**
A ldap result can contain additional information. Such information should not allow a client application to guess if an entry exists or not

**Package Version and Platform:**
This bug impacts all release after 1.4.2.3

**Steps to Reproduce**
to be provided with an automatic testcase

**Expected results**
A ldap request should not provide any tips if an entry exists or not

**Comment by tbordaz** [comment]
0b08e6f35..cc0f69283  master
730b30f08..38b97faef  389-ds-base-1.4.4
fe0409325..c8e77b811  389-ds-base-1.4.3

**Comment by mreynolds389** [comment]
@tbordaz - does this also apply to 1.3.10 (RHEL 7.9)?

**Comment by tbordaz** [comment]
@mreynolds389 no it does not apply to 1.3.10 (RHEL 7.9) branch.
A side effect of #49476 (backend refactoring) create this bug. backend refactoring was not backported in 1.3.10

**Comment by carnil** [comment]
@tbordaz 

> @mreynolds389 no it does not apply to 1.3.10 (RHEL 7.9) branch.
> A side effect of #49476 (backend refactoring) create this bug. backend refactoring was not backported in 1.3.10

Is there reference #49476 above correct.

Trying to check which Debian releases are currently affected by this issue.

**Comment by tbordaz** [comment]
@carnil, this issue was a side effect of https://github.com/389ds/389-ds-base/issues/2535 (former pagure #49476). #2535 was applied on 1.4.x branch only. So #4480 does not impact 1.3.x nor 1.2.11 branches.

**Comment by carnil** [comment]
> @carnil, this issue was a side effect of #2535 (former pagure #49476). #2535 was applied on 1.4.x branch only. So #4480 does not impact 1.3.x nor 1.2.11 branches.

@tbordaz: thank you! So we (in Debian) need to only additionally check the 1.4.0.21-1 version we have. Older suites have 1.3.x based and the current unstable was updated to 1.4.4.10 which has the fix.

**Comment by Firstyear** [comment]
@carnil will the 1.4.4.x updates be put into current stable? It would be good to see debian updated here. Thanks,

**Comment by tbordaz** [comment]
b2c67646e..16d9020a8 1.4.2
