### ISSUE TITLE
ipa-replica-install fails with 'single-valued attribute "entryUUID" has multiple values' (master branch)

### ISSUE THREAD

**Issue by flo-renaud** [389ds/389-ds-base#4498]
**Issue Description**
When using 389ds/389-ds-base-nightly copr repo, ipa-replica-install fails with an error related to `single-valued attribute "entryUUID" has multiple values`.

**Package Version and Platform:**
 - Platform: Fedora32
 - Package and version: 389-ds-base-2.0.1-20201212git429c2f85a.fc32.x86_64

**Steps to Reproduce**
1. install ipa on the first server: ipa-server-install --domain ipa.test --realm IPA.TEST --setup-dns --auto-forwarder -a $PASSWORD -p $PASSWORD -U
2. install ipa client on the replica: ipa-client-install --domain ipa.test --realm IPA.TEST --server server.ipa.test --principal admin --password $PASSWORD -U
3. promote client to replica: kinit admin; ipa-replica-install -U
4. See error:
```
[...]
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58] Configuring the web interface (httpd)
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [1/21]: stopping httpd
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [2/21]: backing up ssl.conf
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [3/21]: disabling nss.conf
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [4/21]: configuring mod_ssl certificate paths
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [5/21]: setting mod_ssl protocol list
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [6/21]: configuring mod_ssl log directory
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [7/21]: disabling mod_ssl OCSP
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [8/21]: adding URL rewriting rules
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [9/21]: configuring httpd
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [10/21]: setting up httpd keytab
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [11/21]: configuring Gssproxy
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [12/21]: setting up ssl
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58]   [error] RuntimeError: Certificate issuance failed (CA_UNREACHABLE: Server at https://master.ipa.test/ipa/json failed request, will retry: 4205 (single-valued attribute "entryUUID" has multiple values).)
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58] Certificate issuance failed (CA_UNREACHABLE: Server at https://master.ipa.test/ipa/json failed request, will retry: 4205 (single-valued attribute "entryUUID" has multiple values).)
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58] The ipa-replica-install command failed. See /var/log/ipareplica-install.log for more information
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58] Your system may be partly configured.
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58] Run /usr/sbin/ipa-server-install --uninstall to clean up.
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58] 
[ipatests.pytest_ipa.integration.host.Host.replica0.cmd58] Exit code: 1
```

**Expected results**
ipa-replica-install should succeed.

**Additional context**
The logs are available in PR#[587](https://github.com/freeipa-pr-ci2/freeipa/pull/587), for instance for the test customized_ds_config_install: [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/e9ccc288-3ce8-11eb-be0c-fa163ecad8b9/report.html), [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/e9ccc288-3ce8-11eb-be0c-fa163ecad8b9/test_integration-test_customized_ds_config_install.py-TestCustomDSConfigInstall-test_customized_ds_install_replica/).

Companion issue opened against freeipa: https://pagure.io/freeipa/issue/8619

**Comment by Firstyear** [comment]
I think this is a bug in dogtag, not ds. 

https://ldapwiki.com/wiki/EntryUUID

EntryUUID is single value and NO-USER-MODIFICATION, meaning it should not be getting set by an external application. As we now have an entryUUID plugin, and include the schema this is probably what you are stepping on.

**Comment by flo-renaud** [comment]
Simple test to confirm the origin of the issue:
 - install with the following packages on both master and replica:
389-ds-base-1.4.3.16-1.fc32.x86_64
pki-server-10.10.0-2.fc32.noarch
freeipa-server-4.8.10-6.fc32.x86_64
The replica installation succeeds

- install with the following packages on both master and replica (389ds/389-ds-base-nightly copr enabled):
pki-server-10.10.0-2.fc32.noarch
freeipa-server-4.8.10-6.fc32.x86_64
389-ds-base-2.0.1-20201214git32413b5b1.fc32.x86_64
The replica installation fails. The error happens when the replica requests a certificate for apache.

On the replica side, ipa creates a principal entry for krbprincipalname=HTTP/replica.ipa.test@IPA.TEST,cn=services,cn=accounts,dc=ipa,dc=test, which is then replicated to the master (can be seen in the master [audit log](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/e9ccc288-3ce8-11eb-be0c-fa163ecad8b9/test_integration-test_customized_ds_config_install.py-TestCustomDSConfigInstall-test_customized_ds_install_replica/master.ipa.test/var/log/dirsrv/slapd-IPA-TEST/audit.gz):
```
time: 20201213023045
dn: krbprincipalname=HTTP/replica0.ipa.test@IPA.TEST,cn=services,cn=accounts,dc=ipa,dc=test
result: 0
changetype: add
krbCanonicalName: HTTP/replica0.ipa.test@IPA.TEST
objectClass: krbprincipal
objectClass: krbprincipalaux
objectClass: krbticketpolicyaux
objectClass: ipaobject
objectClass: ipaservice
objectClass: pkiuser
objectClass: ipakrbprincipal
objectClass: top
managedBy: fqdn=replica0.ipa.test,cn=computers,cn=accounts,dc=ipa,dc=test
ipaKrbPrincipalAlias: HTTP/replica0.ipa.test@IPA.TEST
krbPrincipalName: HTTP/replica0.ipa.test@IPA.TEST
creatorsName: cn=Directory Manager
modifiersName: cn=Directory Manager
createTimestamp: 20201213023046Z
modifyTimestamp: 20201213023046Z
ipaUniqueID: 347ab6bc-3ceb-11eb-930b-52540034fc91
parentid: 74
entryid: 481
entryUUID: 96f5831f-21b8-4f46-b60b-0dc64523a8a4
```
and the ipa_pwd_extop plugin is triggered, and performs this modification 
```
time: 20201213023045
dn: krbprincipalname=HTTP/replica0.ipa.test@IPA.TEST,cn=services,cn=accounts,dc=ipa,dc=test
result: 0
changetype: modify
replace: krbPrincipalKey
krbPrincipalKey:: MIHeoAMCAQGhAwIBAaIDAgEBowMCAQGkgccwgcQwaKAbMBmgAwIBBKESBBBq
 JSUkd1RNNFhPaidvfVwtoUkwR6ADAgESoUAEPiAAI8HjvY9q3Pdb+4vHak8bb3q+f56ibuPhmzs1n
 GKyOnElEjkovr4F0Vi1Z21xh2XuzkmpV+9eH3uUMBzUMFigGzAZoAMCAQShEgQQb2UhNy9FPjIyMj
 A2JmFgX6E5MDegAwIBEaEwBC4QAAeJ1QxYOG/eNX7/cAT5d7Tr4aO0YvQLk8KymSMl8bqMDlzR3oL
 vPt9vXuxl
-
replace: krbLastPwdChange
krbLastPwdChange: 20201213023046Z
-
replace: modifiersName
modifiersName: cn=ipa_pwd_extop,cn=plugins,cn=config
-
replace: modifyTimestamp
modifyTimestamp: 20201213023046Z
-
replace: entryusn
entryusn: 1507
-
add: nsds5ReplConflict
nsds5ReplConflict: Schema violation
-
```

I have the feeling that the replication tries to add entryUUID even though the attribute is already present.

**Comment by Firstyear** [comment]
NO-USER-MODIFICATION means that it's invalid for any client to attempt to write to this attribute, so that's why this is an issue in ipa/dogtag, not in 389. We are following the rfc correctly here :(

**Comment by flo-renaud** [comment]
Sorry to insist but here is what I can see:
- replica creates the krbprincipalname=HTTP/replica0.ipa.test@IPA.TEST,cn=services,cn=accounts,dc=ipa,dc=test entry *without setting entryuuid*
- entry creation succeeds on the replica
- entry gets replicated to the master
- the entry on the master contains 2 values for entryuuid

It can be easily reproduced by doing the following:
- on replica:
```
# ldapmodify -Y EXTERNAL -H ldapi://%2fvar%2frun%2fslapd-IPA-TEST.socket
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
dn: cn=test,dc=ipa,dc=test
changetype: add
objectclass: top
objectclass: nscontainer

adding new entry "cn=test,dc=ipa,dc=test"
```
- check the entry on the replica:
```
# ldapsearch -Y EXTERNAL -H ldapi://%2fvar%2frun%2fslapd-IPA-TEST.socket -LLL -o ldif-wrap=no "cn=test" entryuuid
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
dn: cn=test,dc=ipa,dc=test
entryuuid: c35154e7-d4d5-4644-9c1e-8401dd5971bb
```
The entry contains a single value for entryuuid.

- check the entry on the master:
```
# ldapsearch -Y EXTERNAL -H ldapi://%2fvar%2frun%2fslapd-IPA-TEST.socket -LLL -o ldif-wrap=no "cn=test" entryuuid
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
dn: cn=test,dc=ipa,dc=test
entryuuid: c35154e7-d4d5-4644-9c1e-8401dd5971bb
entryuuid: fbd634eb-ec66-4d1e-b15e-13a6a4902be0
```
The entry contains 2 values for entryuuid. So IMO the issue is on ds side because the replication adds a 2nd value to entryuuid.

**Comment by mreynolds389** [comment]
I can easily reproduce this bug by just setting up replication and adding a new entry.  So it's definitely a DS bug.

I also noticed that we are not setting entryUUID during imports, only when we do an ldap ADD.  @Firstyear is that by design or another bug?

**Comment by mreynolds389** [comment]
The entryuuid plugin should not be called for replicated operations.  Looks like we need to extend the Rust slapi_r_plugin pblock code to extract and check the operation flag.

**Comment by Firstyear** [comment]
> I can easily reproduce this bug by just setting up replication and adding a new entry. So it's definitely a DS bug.

I can't reproduce it ... I just added a test case in https://github.com/389ds/389-ds-base/pull/4503 where we create a two node mmr, create an entry on one side and send it over. Can you check if the test seems sane or not? 

> 
> I also noticed that we are not setting entryUUID during imports, only when we do an ldap ADD. @Firstyear is that by design or another bug?

Yes that's by design. There is a fiux up task.

**Comment by Firstyear** [comment]
@mreynolds389 I'll leave it with you to coordinate with @flo-renaud to re-test this?

**Comment by flo-renaud** [comment]
I tested manually with the @389ds/389-ds-base-nightly copr repo (389-ds-base-2.0.1-20201217git0f38410ae.fc32.x86_64) and the replica installation succeeded.
The full regression test suite will be automatically launched Saturday.

**Comment by flo-renaud** [comment]
The full run can be seen [here](https://github.com/freeipa-pr-ci2/freeipa/pull/601) and shows the issue has been fixed. Thanks :)
