### ISSUE TITLE
Test tests/suites/clu/repl_monitor_test.py is failing

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#4504]
Using master branch on fedora, the test: test_dsconf_replication_monitor is failing:
    assertion failure in step 3 when checking that the aliased string is in the result.

> check_value_in_log_and_reset(content_list, alias_content) suites/clu/repl_monitor_test.py:189:
... 
> assert item in file_content E AssertionError: assert 'Supplier: M1 (someHostName.someDomainName:39001)' in 'Run replication monitor with aliases option\ndsrc path: /root/.dsrc\ndsrc container path: /data/config/container.inf\...t Init Status: unavailable\nReap Active: 0\nReplication Status: In Synchronization\nReplication Lag Time: 00:00:00\n\n'

It is a pure testcase issue:
  The hostnames used to generate the aliases and the expected strings are based on the topology (while dsconf replication monitor output is not using these)
and because of some changes in lib389 frameworks master1 nows ends up with localhost.localdomain while the test expects a FQDN.
(Note: it is not the case for master2 because name is got from replication agreement while the first supplier name is computed from dsconf parameters)

So to check the alias functionality it would be more reliable to get the host names from the step 2 output
 (to be sure that the alias will match the host) then compute the alias string and the expected string

 - Platform: Fedora
 - Package and version: master 

1.  Install test framework
2. Run:   1minutetip -p PYTEST_TEST=suites/clu/repl_monitor_test.py fedora
3. See error in report (pytest is failing)

Test should pass

**Comment by progier389** [comment]
b9edaacfa..0b08e6f35 master -> master
   38b97faef..26c6a0b78  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   c8e77b811..7769c89f0  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   no cherry-pick towards 389-ds-base-1.4.2: test case file is not existing.

**Comment by progier389** [comment]
Although the nightly test on master branch is now PASS, a new issue was found on RedHat 2.8:
 the test about #4449 is failing because ldapi is not enabled by default on RedHat pytest instance while they are on Fedora
 We should either bypass the test if ldapi isnot found or enable ldapi

**Comment by Firstyear** [comment]
I think we should enable ldapi IMO.

**Comment by progier389** [comment]
Enabled ldapi and worked around an issue about agreement that are not up to date after instance restart.

**Comment by progier389** [comment]
bcd39f164..279556bc7  master -> master
1485f60b5..f8f52754f  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
7c4b4f132..2acc538f3  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by progier389** [comment]
Still a merging issue . Sigh!

**Comment by Firstyear** [comment]
> Still a merging issue . Sigh!

How much fun is git!
