### ISSUE TITLE
Issue with Fixupmemberof on 389DS 1.3.10.2 - libback-ldbm.so

### ISSUE THREAD

**Issue by Tasiemiec1995** [389ds/389-ds-base#4511]
Hi!

After configured isMemberOf Plugin fixup-memberof.pl commands has been executed.
After that we noticed some errors and instance has been stopped.
![image](https://user-images.githubusercontent.com/76436373/102780025-87a72b80-4395-11eb-8303-0563d26c7ddb.png)

Checking possibility of fix, the one of step was compare libback-ldbm.so library with older 389 DS version (1.3.9.X).
We were surprised that the checksum was different!

We performed simply check with copy - paste library from older version to newer version and.... that was a solution!
![image](https://user-images.githubusercontent.com/76436373/102780439-35b2d580-4396-11eb-8f3d-6bd17445ad14.png)

However, nowadays we are aware of that because we afraid that in the future after yum update 389-ds-base we will appear the same issue and instance will not start.

Now, we used RHEL 7 and 1.3.10.2 is the latest version which we see.
Could  you please verify this issue and confirm that we will safe in the future?

**Comment by Firstyear** [comment]
A better solution here may be use "yum reinstall 389-ds-base" which will force the RPM to re-install all components and validate they are correct. If you are still having checksum issues or symbol issues after that point, I think this is likely not a problem in 389-ds, but indicates some local system error or corruption.

**Comment by Tasiemiec1995** [comment]
Do my instance will removed after yum reinstall 389-ds-base or instance config will changed?
I have a huge experience with LDAP technologies however this is my first time with 389 DS so i need to ask about every, simply topics.

I am not sure that this can be problem with system error because like i said in previous message after copy library from older version and pasted to newer, all suddenly working properly.

**Comment by vashirov** [comment]
This is a known issue: https://bugzilla.redhat.com/show_bug.cgi?id=1905450
It is fixed in https://github.com/389ds/389-ds-base/commit/f917145e1bade16e4a5ab584dbccb52168961c72, but the fix is not yet in the latest RHEL package.
In the meantime I recommend to downgrade to a previous package version or build a package with the patch above.
Sorry for the disruption.

**Comment by Tasiemiec1995** [comment]
Thank you so much for your answer.

I have a one additional question before close - We have any date when corrected packages will appear in the RHEL repo?

**Comment by vashirov** [comment]
Unfortunately, I don't have any particular date. This bug fix is supposed to be released as an ASYNC errata after Batch Update <span>#</span>2 and before <span>#</span>3, which is targeted at the end of January. I really hope we can release it in the first half of January.
HTH

**Comment by Tasiemiec1995** [comment]
Thank you so much for yours answer.
Now, i closed this issues.
