### ISSUE TITLE
Add libsasl debugging

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#4512]
**Is your feature request related to a problem? Please describe.**
SASL provides a logging mechanism and it could be useful to have it.

**Describe the solution you'd like**
Add the functionality to nsslapd-external-libsasl-debug-enabled attribute in 'cn=config'.

**Connected issues**
https://github.com/389ds/389-ds-base/issues/1795
https://github.com/389ds/389-ds-base/commit/926b2e049cde4cc0531f160220094bcf99b83a79

**Comment by progier389** [comment]
In fact the sasl log callback is already implemented.
 It is enabled by turning on both TRACE and CONNS (i.e: 1+8) flags in error log level.
 Note: trace level is not very practical (too verbose) so I propose to improve that in issue [5470](https://github.com/389ds/389-ds-base/issues/5470)

**Comment by mreynolds389** [comment]
> In fact the sasl log callback is already implemented. It is enabled by turning on both TRACE and CONNS (i.e: 1+8) flags in error log level. Note: trace level is not very practical (too verbose) so I propose to improve that in issue [5470](https://github.com/389ds/389-ds-base/issues/5470)

@progier389  Perhaps it should all be CONNS logging as trace function calls grinds the server to a halt?
