### ISSUE TITLE
Random failure in ipa-replica-manage re-initialize

### ISSUE THREAD

**Issue by flo-renaud** [389ds/389-ds-base#4515]
**Issue Description**
The nightly freeIPA test `test_backup_and_restore.py::TestBackupAndRestoreWithReplica::test_full_backup_and_restore_with_replica` is randomly failing, see for instance in [testing_master_latest_selinux] PR #[617](https://github.com/freeipa-pr-ci2/freeipa/pull/617) with the following [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/10c8ed9c-492f-11eb-84d5-fa163e04929f/) and [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/10c8ed9c-492f-11eb-84d5-fa163e04929f/report.html). After a call to `ipa-replica-manage re-initialize`, the following error is seen in the error logs: `Unexpected replication status: Error (11) Replication error acquiring replica: Unable to acquire replica: the replica has the same Replica ID as this one. Replication is aborting. (duplicate replica ID detected).`

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 389-ds-base-1.4.3.16-1.fc32.x86_64

**Steps to Reproduce**
Launch freeIPA nightly test. The scenario is the following:
- install master + replica
- backup master
- delete one entry on master, delete one entry on replica (the entries are saved in the backup)
- add one entry on master, add one entry on replica (the entries are not in the backup)
- stop + uninstall master to simulate master crash
- restore the backup on the master
- add one entry on master, add one entry on replica, the replication isn't working (as expected)
- re-initialize master from replica

**Expected results**
After re-initialize, the replication should resume successfully.

Please see freeipa issue #[8637](https://pagure.io/freeipa/issue/8637).

**Comment by flo-renaud** [comment]
Note: the error does not always happen. I saw the issue only twice in the last weeks.

**Comment by Firstyear** [comment]
@flo-renaud I wonder if this is related to the topology plugin time issue at the moment? Replica-id's are controlled by the client, in this case freeipa, so I wonder if the topoplugin not working due to the monotonic vs epoch clock is causing it not to assign the ids correctly?

**Comment by mreynolds389** [comment]
I'm not sure what the DS team can do for this issue.  The error indicates that there are more than one replica in the topology with the same Replica ID.  That is not a bug, but a configuration mistake.  

@flo-renaud is there something else you'd like us to do?  If not, can this be closed?

**Comment by flo-renaud** [comment]
I didn't see the issue during the last month (testing_ipa-4.6, testing_ipa-4.9_previous, testing_ipa-4.9_latest, testing_ipa-4.9_latest_selinux, testing_master_previous, testing_master_testing_selinux, testing_master_latest). Clsoing as
