### ISSUE TITLE
lib389 - clients of lib389 healthcheck raise exceptions when a backend is not replicated

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4535]
**Issue Description**
Freeipa's healthcheck tool throws errors when processing non-replicated backends.  In dsctl these are caught as part of the CLI and are handled correctly, but not when a client using our API calls these functions directly.

See:  https://github.com/freeipa/freeipa-healthcheck/issues/163

We need to catch an exception when attempting to get the replica:

```
def _lint_cl_trimming(self):
        """Check that cl trimming is at least defined to prevent unbounded growth"""
        suffix = self.get_attr_val_utf8('nsslapd-suffix')
        replicas = Replicas(self._instance)
        replica = replicas.get(suffix)   ---->  Need to catch exception here
        bename = self.lint_uid()
        if replica is not None:
```

**Comment by mreynolds389** [comment]
74a6ce5a4..851878858  389-ds-base-1.4.4 -> 389-ds-base-1.4.4

**Comment by mreynolds389** [comment]
Fix logging function typo

111774dcc..9015bff23  master -> master
e0e1803c2..552c6c68d  389-ds-base-1.4.4 -> 389-ds-base-1.4.4

**Comment by droideck** [comment]
@mreynolds389 do we need this in 1.4.3?
I'm currently fixing test failures in 389-ds-base-1.4.3 branch and the test exists there. And it fails because of the issue...

Or should I disable the test there? (if we don't support it in 1.4.3)
