### ISSUE TITLE
After updating NSS login to ds-admin not working

### ISSUE THREAD

**Issue by mstirnweiss** [389ds/389-ds-base#4554]
**Issue Description**
We are updating our CentOS. In this updates the nss is will update to Version 
 nss                 3.53.1-3.el7_9 
 nss-softokn         3.53.1-6.el7_9
 nss-softokn-freebl  3.53.1-6.el7_9
 nss-sysinit         3.53.1-3.el7_9
 nss-tools    		 3.53.1-3.el7_9
 
After this update, when we start dirsrv-admin we get the following error in:

/var/log/dirsrv/admin-dirsrv/error:
sslinit: NSS is required to use LDAPS, but security initialization failed [-8015:The certificate/key database is in an old, unsupported format or failed to open.]

If you start ds-admin, Java is working but you get an login error. So if we dosngrade the NSS packages its working again.

**Package Version and Platform:**
 - Platform: CentOS Linux release 7.9.2009
 - Package and version: 
 
389-adminutil-1.1.22-2.el7.x86_64
389-admin-1.1.46-4.el7.x86_64
389-admin-console-1.1.12-1.el7.noarch
389-dsgw-1.1.11-5.el7.x86_64
389-ds-console-doc-1.2.16-1.el7.noarch
389-ds-base-libs-1.3.10.2-8.el7_9.x86_64
389-admin-console-doc-1.1.12-1.el7.noarch
389-ds-base-1.3.10.2-8.el7_9.x86_64
389-console-1.1.19-6.el7.noarch
389-ds-1.2.2-6.el7.noarch
389-ds-base-snmp-1.3.10.2-8.el7_9.x86_64
389-ds-console-1.2.16-1.el7.noarch

**Additional context**
I don't know if the error is here or with nss.

**Comment by mreynolds389** [comment]
The problem here is that we are no longer maintaining 389-ds-base-1.3.x.  And the java console has been deprecated and removed in 389-ds-base-1.4.x.

That being said maybe try exporting and importing your certificates after upgrading NSS?

**Comment by Firstyear** [comment]
Just to repeat what @mreynolds389 said here, but we don't support the java console with 1.4.x, so this is going to be a best effort sorry.

**Comment by mstirnweiss** [comment]
Thanks for the quick reply. We use yes CentOS 7.9 There runs only ds 1.3. Is it possible to use the admin with 1.4? 
Otherwise we would have to change quite a few systems to CentOS 8.

**Comment by Firstyear** [comment]
The advice we "generally" give is not to run a mix of different versions for extended period, IE not more than a month.

So you may have to change quite a few systems over in this process, but it's not "end of the world". Just know that for 1.4 you should be using the dsctl/dsconf/dsidm CLI tools or the cockpit webui which replaces the console.

Hope that helps,

**Comment by mstirnweiss** [comment]
Thanks. Is there a repro for 389-ds-base-1.4.x and centos 7.9 or is that not supported?

**Comment by Firstyear** [comment]
You could consider running docker 389-ds on centos 7.9?

**Comment by mreynolds389** [comment]
> Thanks. Is there a repro for 389-ds-base-1.4.x and centos 7.9 or is that not supported?

Sorry there is no 389-ds-base-1.4.x version available for CentOS 7.x.  

Is there anything else we can help you with?

**Comment by tbordaz** [comment]
Closing the ticket as we are not going to fix old console issue. Please reopen it if needed
