### ISSUE TITLE
Nightly failure in ipa-server-install with @389ds/389-ds-base-nightly

### ISSUE THREAD

**Issue by flo-renaud** [389ds/389-ds-base#4565]
**Issue Description**
ipa-server-install CLI is broken when the nightly copr repo @389ds/389-ds-base-nightly is enabled.

**Package Version and Platform:**
 - Platform: Fedora 33
 - Package and version: 389-ds-base-2.0.2-20210123git6546ee60c.fc33.x86_64

**Steps to Reproduce**
Launch ipa-server-install. The command fails with :
```
[...]
  [4/10]: adding default ACIs
Failed to load default-aci.ldif: CalledProcessError(Command ['/usr/bin/ldapmodify', '-v', '-f', '/tmp/tmpue6kga89', '-H', 'ldapi://%2Frun%2Fslapd-IPA-TEST.socket', '-Y', 'EXTERNAL'] returned non-zero exit status 21: 'ldap_initialize( ldapi://%2Frun%2Fslapd-IPA-TEST.socket/??base )\nSASL/EXTERNAL authentication started\nSASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth\nSASL SSF: 0\nldap_modify: Invalid syntax (21)\n\tadditional info: ACL Syntax Error(-5):(targetfilter = \\22(objectClass=ipaGuiConfig)\\22)(targetattr != \\22aci\\22)(version 3.0;acl \\22Admins can change GUI config\\22; allow (read, search, compare, write) groupdn = \\22ldap:///cn=admins,cn=groups,cn=accounts,dc=ipa,dc=test\\22;)\n\n')
  [error] CalledProcessError: CalledProcessError(Command ['/usr/bin/ldapmodify', '-v', '-f', '/tmp/tmpue6kga89', '-H', 'ldapi://%2Frun%2Fslapd-IPA-TEST.socket', '-Y', 'EXTERNAL'] returned non-zero exit status 21: 'ldap_initialize( ldapi://%2Frun%2Fslapd-IPA-TEST.socket/??base )\nSASL/EXTERNAL authentication started\nSASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth\nSASL SSF: 0\nldap_modify: Invalid syntax (21)\n\tadditional info: ACL Syntax Error(-5):(targetfilter = \\22(objectClass=ipaGuiConfig)\\22)(targetattr != \\22aci\\22)(version 3.0;acl \\22Admins can change GUI config\\22; allow (read, search, compare, write) groupdn = \\22ldap:///cn=admins,cn=groups,cn=accounts,dc=ipa,dc=test\\22;)\n\n')
CalledProcessError(Command ['/usr/bin/ldapmodify', '-v', '-f', '/tmp/tmpue6kga89', '-H', 'ldapi://%2Frun%2Fslapd-IPA-TEST.socket', '-Y', 'EXTERNAL'] returned non-zero exit status 21: 'ldap_initialize( ldapi://%2Frun%2Fslapd-IPA-TEST.socket/??base )\nSASL/EXTERNAL authentication started\nSASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth\nSASL SSF: 0\nldap_modify: Invalid syntax (21)\n\tadditional info: ACL Syntax Error(-5):(targetfilter = \\22(objectClass=ipaGuiConfig)\\22)(targetattr != \\22aci\\22)(version 3.0;acl \\22Admins can change GUI config\\22; allow (read, search, compare, write) groupdn = \\22ldap:///cn=admins,cn=groups,cn=accounts,dc=ipa,dc=test\\22;)\n\n')
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
Exit code: 1
```

**Expected results**
Command should complete successfully

For more information please refer to https://pagure.io/freeipa/issue/8679 which contains path to log files.

**Comment by Firstyear** [comment]
@flo-renaud `info: ACL Syntax Error(-5):(targetfilter = \\22(objectClass=ipaGuiConfig)\\22)(targetattr != \\22aci\\22)(version 3.0;acl \\22Admins can change GUI config\\22; allow (read, search, compare, write) groupdn = \\22ldap:///cn=admins,cn=groups,cn=accounts,dc=ipa,dc=test\\22;)\n\n')` 

These escaped 22's look a bit odd? Is it possible to get the audit log enabled in the setup so we can see exactly what was attempted to be written so we can be sure of the format of the acl string? Having the original string would help too as a pretty simple reproducer.

**Comment by flo-renaud** [comment]
@Firstyear something looks strange to me as the git hash (6546ee60c) cannot be found on the master branch. I suspect our nightlies picked a copr build that was done from a personal branch.
I will re-launch our tests tomorrow morning when the infra is not used by the other nightlies and let you know if the issue persists.

**Comment by mreynolds389** [comment]
I was doing copr builds over over the weekend to check for compiler warnings no various platforms, so this could be a regression in a patch I am working on?

**Comment by mreynolds389** [comment]
I can reproduce this with my other PR that is under review.  I will make sure it is fixed before merging.

**Comment by flo-renaud** [comment]
The nightly has been relaunched with the latest @389ds build, issue does not happen any more. We can close this ticket.
