### ISSUE TITLE
Stale libdb-utils dependency

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#4571]
**Issue Description**
`libdb-utils` is a [dependency](https://tiny.distro.builders/view-rpm--view-eln--libdb-utils.html) for 389-ds-base. It was required for `verify-db.pl` to work, but later this script was [ported](https://github.com/389ds/389-ds-base/commit/1676f9b5b6810403496c441a5545c9b361662f34) to dbverify mode of `ns-slapd`.
So it looks like it's no longer needed, but I found one more usage of `db_dump` in [`index_dump.c`](https://github.com/389ds/389-ds-base/blob/abb93243b427ee122a5a80ed095c0118d7b6616e/ldap/servers/slapd/back-ldbm/tools/index_dump/index_dump.c#L21), which is a debug tool that we don't ship or even build in the first place.

I'd like to confirm that this dependency is no longer required and if so, remove it (maybe together with `index_dump`?).

**Package Version and Platform:**
 - Platform: RHEL/Fedora
 - Package and version: 389-ds-base-1.2.1+

**Comment by droideck** [comment]
@vashirov can we close it as https://github.com/389ds/389-ds-base/pull/4583 is merged?
