### ISSUE TITLE
openldap_to_ds improve help and wire in overlay skipping.

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#4591]
Improve the --help to show what overlays we can migrate, and wire in the correct parts for skipping overlays in migration.

**Comment by mreynolds389** [comment]
Please remember to cherry pick your fixes to the milestone branch:

d4c2ab388..b8c4510b1  389-ds-base-1.4.4 -> 389-ds-base-1.4.4

**Comment by Firstyear** [comment]
Opps sorry! Thanks for having my back on this :)
