### ISSUE TITLE
Log an additional message if the server certificate nickname doesn't match nsSSLPersonalitySSL value

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#4593]
**Is your feature request related to a problem? Please describe.**
RHDS instance will fail to start if the TLS server certificate nickname doesn't match the value
of the configuration parameter "nsSSLPersonalitySSL".

The mismatch typically happens when customers copy the NSS DB from a previous instance
or export the certificates data but forget to set the "nsSSLPersonalitySSL" value accordingly.

**Describe the solution you'd like**
It would be nice to log an additional message stating to check if the nickname indeed matches the nsSSLPersonalitySSL.

**Additional context**
Steps to Reproduce:
1. Get the certificate nickname:

```
# certutil -d /etc/dirsrv/slapd-<INSTANCE>/ -L

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

Self-Signed-CA                                               CT,,
Server-Cert                                                  u,u,u
```

2. Stop the RHDS instance and set nsSSLPersonalitySSL to a value different of the actual nickname

```
# grep -i nsSSLPersonalitySSL /etc/dirsrv/slapd-<INSTANCE>/dse.ldif
nsSSLPersonalitySSL: otherNickname
```

3. Try to start the instance

Results:
The startup fails with the following messages in the errors log:

```
[06/Nov/2020:18:37:03.873591352 +0100] - ERR - attrcrypt_fetch_private_key - Can't find certificate otherNickname: -5950 - File not found.
[06/Nov/2020:18:37:03.875333480 +0100] - ERR - attrcrypt_fetch_private_key - Can't get private key from cert otherNickname: -5950 - File not found.
...
[06/Nov/2020:18:37:03.878800070 +0100] - ERR - attrcrypt_fetch_private_key - Can't find certificate otherNickname: -5950 - File not found.
[06/Nov/2020:18:37:03.880365271 +0100] - ERR - attrcrypt_fetch_private_key - Can't get private key from cert otherNickname: -5950 - File not found.
```

**Comment by Firstyear** [comment]
Perhaps the log can be extended to say "to rename a certificate use .... <command>" ?

**Comment by droideck** [comment]
Bz: https://bugzilla.redhat.com/show_bug.cgi?id=1895460

**Comment by droideck** [comment]
To github.com:389ds/389-ds-base.git
   bef0b5bed..7f20bccb0  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
To github.com:389ds/389-ds-base.git
   71cb90303..8d40f2784  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
