### ISSUE TITLE
Paged search lookthroughlimit counter doesnt take read ahead into account

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#4595]
**Issue Description**
During a paged search with lookthroughlimit enabled, a lookthroughlimit counter is used to keep track of how many entries are examined. A paged search reads ahead one entry to catch the end of the search so it doesn't show the prompt when there are no more entries. The lookthroughlimit counter doesn't take read ahead into account when tracking how many entries have been examined.

**Package Version and Platform:**
 - Platform: 5.6.6-300.fc32.x86_64
 - Package and version: 389-ds-base-2.0.2.20210204gitf38b124f0

**Steps to Reproduce**
1. Populate DB with 101 entries.
2. Configure lookthroughlimit attribute to a value of 122. (nsslapd-lookthroughlimit: 122)
3. Run a paged search operation with an unindexed search filter. (... "(uid=test0*)" -E pr=10/noprompt))
4. Paged search fails with admin limit error.  
```
# search result
search: 11
result: 11 Administrative limit exceeded

# numResponses: 108
# numEntries: 98
```

**Expected results**
The paged search returns 101 entries with no error.
```
# search result
search: 12
result: 0 Success
control: 1.2.840.113556.1.4.319 false MAUCAQAEAA==
pagedresults: cookie=

# numResponses: 112
# numEntries: 101
```

**Additional context**
The CI tests highlighted this issue, test parameters are used here to reproduce the issue.

**Comment by jchapma** [comment]
On the subject of search limits, I noticed that when the candidatelist is constructed it contains more (~17) elements than there are entries in the DB. I know its a corner case, but if a lookthroughlimit is set to a value that is the exact number of elements in the DB, the search would generate an admin limit exceeded error. 

Does anyone think its worth the time investigating this ?

**Comment by Firstyear** [comment]
Yes, that's probably worth looking at too.
