### ISSUE TITLE
ACI for targattrfilters add operation fails for MOD_REPLACE

### ISSUE THREAD

**Issue by tiran** [389ds/389-ds-base#4597]
**Issue Description**

An ACI with targattrfilters for an add operation does not work when a client uses MOD_REPLACE to set an attribute.

**Package Version and Platform:**
 - Platform: Fedora 32
 - Package and version: 389-ds-base-1.4.3.12-1.fc32.x86_64, freeipa-server-4.8.10-5.fc32.x86_64

**Steps to Reproduce**

1. Create an ACI with targattrfilters for add operation: ``aci: (targattrfilters = "add=userclass:(userclass=testclass), del=userclass:(userclass=testclass)")(version 3.0;acl "selfservice:testclass";allow (write) userdn = "ldap:///self";)``
2. Set the attribute with IPA command line ``ipa user-mod --setattr=userclass=testclass user0``

The user-mod operation fails with error message ``ipa: ERROR: Insufficient access: Insufficient 'write' privilege to the 'userClass' attribute of entry 'uid=user0,cn=users,cn=accounts,dc=abc,dc=example'.``. The ``audit`` log contains:

```
dn: uid=user0,cn=users,cn=accounts,dc=abc,dc=example
result: 50
changetype: modify
replace: userClass
userClass: testclass
```

I can set the attribute with Apache Directory Studio because it uses MOD_ADD instead of MOD_REPLACE. In the successful case the audit log contains:

```
dn: uid=user0,cn=users,cn=accounts,dc=abc,dc=example
result: 0
changetype: modify
add: userClass
userClass: testclass
```

**Expected results**

I expect that the operation works for both MOD_ADD and MOD_REPLACE operations.

**Additional context**

IPA uses MOD_REPLACE for most operations to avoid concurrency issues. It's used when setting a single value attribute or a multiple value attribute is created.

I also tried other ACI rules. 389-DS refuses to create an ACI with ``del=userclass:(|(userclass=testclass)(!(userclass)))``.

**Comment by tiran** [comment]
@tbordaz proposed an alternative rule. The rule ``(targattrfilters = "add=userclass:(userclass=testclass), del=userclass:(|(userclass=testclass)(!(userclass=*)))")(version 3.0;acl "selfservice:testclass";allow (write) userdn = "ldap:///self";)`` behaves correctly. I can MOD_REPLACE a new attribute value with it.

**Comment by mreynolds389** [comment]
Closing since server is working as expected, reopen if something else needs to be addressed

**Comment by tiran** [comment]
Is it expected to have a ``del=userclass:(!(userclass=*))`` rule to add an entry with MOD_REPLACE? It certainly surprised me.

**Comment by mreynolds389** [comment]
> Is it expected to have a `del=userclass:(!(userclass=*))` rule to add an entry with MOD_REPLACE? It certainly surprised me.

The "source code comments" clearly state for REPLACE operation you need a add & del rule. But none of this is stated in the Admin guide.   You just needed a more complex rule to accomplish what you were trying to do.  So I will open a doc bug to clarify that a "replace" option requires an Add and Del rule.  But before I do, do you feel there is still a bug?

**Comment by tiran** [comment]
It's an inconvenience, but not a code bug. I can work around it with little effort. In retrospective the syntax makes sense, too.

I'd appreciate a documentation update.

**Comment by tbordaz** [comment]
The document says [1] "If the individual values of an attribute already present in the entry are replaced, then both the add and del filters must match. "
So it describe the need of add *and* del filters. the del=userclass:(!(userclass=*)) rule says that the aci is selected at the condition that the target entry of a mod_replace has no 'userclass' attribute (before the operation). Does it match your need ?

[1] https://access.redhat.com/documentation/en-us/red_hat_directory_server/11/html/administration_guide/defining_targets#targeting_attribute_values_using_ldap_filters
