### ISSUE TITLE
Remove problematic language from CLI tools and UI

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4656]
**Issue Description**

Remove terms like "master" and "slave" from UI/CLI tools and replace it with "Supplier/Consumer"

**Comment by mreynolds389** [comment]
e8a4c61b7..f32cd6d1f  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
9e5fe7aec..444ffba00  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

Next, need to make 1.4.4 and 1.4.3 backwards compatible with replication CLI

**Comment by mreynolds389** [comment]
> [e8a4c61](https://github.com/389ds/389-ds-base/commit/e8a4c61b7f0952846b9ff02fc9c1a373249e4e65)..[f32cd6d](https://github.com/389ds/389-ds-base/commit/f32cd6d1fcb4a73825c3554d965115c227b15d0b) 389-ds-base-1.4.4 -> 389-ds-base-1.4.4
> [9e5fe7a](https://github.com/389ds/389-ds-base/commit/9e5fe7aec3bf43ad59f348eb9934cf9275123b4b)..[444ffba](https://github.com/389ds/389-ds-base/commit/444ffba0096a64e4bd5f7c2e7c9b54a733eb81ef) 389-ds-base-1.4.3 -> 389-ds-base-1.4.3
> 
> Next, need to make 1.4.4 and 1.4.3 backwards compatible with replication CLI


444ffba00..6f43954b1  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
f32cd6d1f..6fddab6d6  389-ds-base-1.4.4 -> 389-ds-base-1.4.4

Lastly, ds-replcheck was missed during the original change, need to fix that in master branch...

**Comment by mreynolds389** [comment]
> Lastly, ds-replcheck was missed during the original change, need to fix that in master branch...

f3c131296..d5fdea905  master -> master

**Comment by minexew** [comment]
Is the main Git branch also going to be renamed to... main?

**Comment by mreynolds389** [comment]
> Is the main Git branch also going to be renamed to... main?

No, this is just in the software and documentation that Red Hat ships.

**Comment by Firstyear** [comment]
@mreynolds389 IIRC github have released some tooling to make master -> main change easier.

**Comment by mreynolds389** [comment]
> @mreynolds389 IIRC github have released some tooling to make master -> main change easier.

Technicality this is not a requirement as the repo branch names do not land in our shipped products or in our archived source tar balls.  If you want to do this then maybe it should be a separate ticket?  I personally don't have a strong opinion on it...

**Comment by Firstyear** [comment]
Done, opened #4672 (cc @minexew )

**Comment by minexew** [comment]
Thanks, I don't necessarily care, was just wondering how far this trend is going.

**Comment by mreynolds389** [comment]
backport ds-replcheck changes:

5c88c00d1..f17617d16  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
a627f79f2..8a2c7b88f  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by tbordaz** [comment]
backport test_online_reinit_may_hang changes
6e15e87cb..804b46e06  389-ds-base-1.4.3
fc53c8b22..5d956fcc7  389-ds-base-1.4.4

**Comment by mreynolds389** [comment]
9336bd894..5e8562aed  389-ds-base-2.1 -> 389-ds-base-2.1
d2d6065e1..664b09206  389-ds-base-2.0 -> 389-ds-base-2.0
