### ISSUE TITLE
monitor displays wrong date for connection

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4658]
**Issue Description**

Looks like a epoch date is used for new connections.  Maybe it's related to the REALTIME vs MONOTONIC clock change we did recently?

    # dsconf localhost monitor server
    dn: cn=monitor
    version: 389-Directory/2.0.3.20210306gitf0938dada B2021.065.1543
    connection: 472:19700102065831Z:1:1:-:cn=dm:0:0:0:38323:ip=::1
    connection: 473:19700102065834Z:3:2:-:cn=dm:0:0:0:38324:ip=local

**Comment by Firstyear** [comment]
I think you're right, it's probably that it's trying to format the monotonic clock against epoch here.

**Comment by mreynolds389** [comment]
1827c76da..47a23847b  master -> master
6fddab6d6..a6b7d062b  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
015bcc7d9..11adb2d7b  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by mreynolds389** [comment]
Need to create downstream bugzillas going back to 8.3

**Comment by tbordaz** [comment]
This bug is fixed upstream and the BZ verified => close
1827c76da..47a23847b  master
6fddab6d6..a6b7d062b 1.4.4
015bcc7d9..11adb2d7b 1.4.3
