### ISSUE TITLE
RFE automatique disable of virtual attribute checking

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#4678]
**Is your feature request related to a problem? Please describe.**
During a SRCH, lookup for virtual attribute providers is done during evaluating a filter (against a candidate entry) and also for each returned attribute. The lookup of the virtual attribute hashtable is protected with a rwlock that creates contention, even if it is almost always free (in read). In addition the hashtable lookup is costly even if the search attribute is not present in the hashtable.

This was already detected to be an expensive component and a config attribute 'nsslapd-ignore-virtual-attrs' allows to skip virtual attribute lookup (see https://github.com/389ds/389-ds-base/issues/511).

This attribute is 'off' by default, so most of the deployments, even if they do not use virtual attributes, are paying the cost of virtual attribute

**Describe the solution you'd like**
A first possibility is to set 'nsslapd-ignore-virtual-attrs: on' when there is no virtual attributes.
389-ds server defines virtual attributes with 'cos' and 'role' plugins. If there is cos/role definitions and if there is no custom plugin, then set  'nsslapd-ignore-virtual-attrs: on'.
This should be detected at startup and also requires cos/role plugin to enable the flag if a new definition comes in.

A second possibility is too have healthcheck, detecting the same (no cos/role definitions and no custom plugin)

A third possibility is to set 'nsslapd-ignore-virtual-attrs: on' by default and turn it on when a virtual attribute is inserted (other than 'dummyAttr').

**Describe alternatives you've considered**

**Additional context**

**Comment by Firstyear** [comment]
I think a better option here is that we should set `nsslapd-ignore-virtual-attrs: on` by default, and then at plugin init from cos/role, we enable it internally by writing to the config.

**Comment by tbordaz** [comment]
I am not sure to understand your proposal. ATM cos/roles are enabled by default. Do you suggest to disable them by default ?
Note that even if cos/roles are enabled, it does not mean it exists definitions for virtual attributes.

**Comment by Firstyear** [comment]
Sorry I think my proposal is that roles/cos are enabled by default. By default we set nsslapd-ignore-virtual-attrs: off.

Then if roles / cos have any cos template or roles defined, they internally switch nsslapd-ignore-virtual-attrs: on. 

So that way roles/cos can be "enabled" but until any role or template is defined we don't enable virtual attrs. This way, an administrator doesn't have to change "another setting" to make roles/templates work.

**Comment by tbordaz** [comment]
I agree that we should keep it the simple for the administrator (no healthcheck).
I think we agree but you meant the opposite ;) :

- by default cos/roles are enabled
- by default nsslapd-ignore-virtual-attrs=on
- in cos/roles startup functions, it checks if it exists cos/role definition. If it exists one it sets nsslapd-ignore-virtual-attrs=off
- in cos/role callback if a new definition comes in, it sets nsslapd-ignore-virtual-attrs: off
- Log a warning when 'nsslapd-ignore-virtual-attrs: on' that virtual attribute are not enforced

**Comment by Firstyear** [comment]
Yep this is exactly what I meant! Thanks for understanding me :)
