### ISSUE TITLE
`dscontainer` fails with rootless `podman` (wrong SELinux relabeling)

### ISSUE THREAD

**Issue by ivanov17** [389ds/389-ds-base#4714]
**Issue Description**

Hello! At first, I'd like to thank the developers for their work on making creation of Directory Server container images easier.

Unfortunately, I have some issues with SELinux permissions when I run dscontainer using podman.

Since podman allows running containers in rootless mode, I usually work with containers as an unprivileged user. I use Fedora 33 running with SELinux in enforcing mode on my machine.

If I run 389-ds container with rootless podman, SELinux prevents `dscontainer` from `relabelto` access on the file `slapd-collations.conf` and dscontainer script fails.

If I run 389-ds container in rootfull mode, it works, but I get another issue with `dscontainer`: SELinux labels do not allow to run a new 389-ds container if  the mounted data volume contains files placed by another instance of the container.

I tried to run containers from custom images based on `quay.io/centos/centos:stream8` and `quay.io/fedora/fedora:33-x86_64`, and I got the same result on both.

I believe it isn't a podman issue, because `dscontainer` script tries to relabel files inside a container. Also, it isn't a SELinux issue, because all files on mounted volumes must have only ~~`container_t`~~ `container_file_t` label.

**Package Version and Platform:**
 - Platform: Fedora 33
 - Package and version: 
   - `docker.io/389ds/dirsrv:latest` (389 Directory Server Version: 1.4.4.8) 
   - custom image based on Centos 8-stream (389 Directory Server Version: 1.4.3.16) 
   - custom image based on Fedora 33 (389 Directory Server Version: 1.4.4.14) 

**Steps to Reproduce**
```
$ podman run -dt --volume=389ds:/data:z --publish=3389:3389 --publish=3636:3636 --env='DS_DM_PASSWORD=pass' --env='LDAPBASE=dc=test,dc=internal' --env='LDAPBINDDN=cn="Directory Manager"' docker.io/389ds/dirsrv:latest
```

**Actual results**
```
$ podman ps -a
CONTAINER ID  IMAGE                          COMMAND               CREATED             STATUS                         PORTS                                           NAMES
420076b7af00  docker.io/389ds/dirsrv:latest  /usr/lib/dirsrv/d...  About a minute ago  Exited (1) About a minute ago  0.0.0.0:3389->3389/tcp, 0.0.0.0:3636->3636/tcp  pensive_johnson
```
```
$ podman logs pensive_johnson 
/usr/lib/dirsrv/dscontainer:430: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if begin_healthcheck(None) is (False, True):
INFO: The 389 Directory Server Container Bootstrap
INFO: Inspired by works of: ITS, The University of Adelaide
INFO: 389 Directory Server Version: 1.4.4.8
INFO: Initialising 389-ds-container due to empty volume ...
DEBUG: Running setup with verbose
DEBUG: START: Starting installation...
DEBUG: READY: Preparing installation for localhost...
DEBUG: PASSED: using config settings 999999999
DEBUG: PASSED: user / group checking
DEBUG: PASSED: prefix checking
DEBUG: list instance not found in /etc/dirsrv/slapd-localhost/dse.ldif: localhost

DEBUG: PASSED: instance checking
DEBUG: INFO: temp root password set to ST8yHKDlHivjscrEcSgODFXJEAZGO32TH8XZ70uIqV6F.LaDWNLwWiLJADoQW8b4t
DEBUG: PASSED: root user checking
DEBUG: PASSED: network avaliability checking
DEBUG: READY: Beginning installation for localhost...
DEBUG: ACTION: Creating dse.ldif
DEBUG: ACTION: creating /data/bak
DEBUG: ACTION: creating /etc/dirsrv/slapd-localhost
DEBUG: ACTION: creating /data/db
DEBUG: ACTION: creating /data/ldif
DEBUG: ACTION: creating /data/run/lock
DEBUG: ACTION: creating /data/logs
DEBUG: ACTION: creating /data/run
Traceback (most recent call last):
  File "/usr/lib/dirsrv/dscontainer", line 428, in <module>
    begin_magic()
  File "/usr/lib/dirsrv/dscontainer", line 266, in begin_magic
    if not sds.create_from_args(g2b.collect(), s2b.collect()):
  File "/usr/lib/python3.8/site-packages/lib389/instance/setup.py", line 674, in create_from_args
    self._install_ds(general, slapd, backends)
  File "/usr/lib/python3.8/site-packages/lib389/instance/setup.py", line 796, in _install_ds
    shutil.copy2(srcfile, dstfile)
  File "/usr/lib64/python3.8/shutil.py", line 433, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.8/shutil.py", line 376, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/usr/lib64/python3.8/shutil.py", line 326, in _copyxattr
    os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/etc/dirsrv/slapd-localhost/slapd-collations.conf'
```
```
# ausearch -m avc -c dscontainer
----
time->Fri Apr  2 00:57:37 2021
type=AVC msg=audit(1617314257.503:1253): avc:  denied  { relabelto } for  pid=13372 comm="dscontainer" name="99user.ldif" dev="dm-2" ino=41140913 scontext=system_u:system_r:container_t:s0:c678,c864 tcontext=system_u:object_r:fusefs_t:s0 tclass=file permissive=0
----
time->Fri Apr  2 00:57:37 2021
type=AVC msg=audit(1617314257.504:1254): avc:  denied  { relabelto } for  pid=13372 comm="dscontainer" name="slapd-collations.conf" dev="dm-2" ino=54625891 scontext=system_u:system_r:container_t:s0:c678,c864 tcontext=system_u:object_r:fusefs_t:s0 tclass=file permissive=0
```

**Expected results**
`dscontainer` shouldn't relabel SELinux context on files created in container's volume.

**Additional context**
```
$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33
```
```
$ podman --version
podman version 3.0.1
```
```
$ uname -r
5.11.10-200.fc33.x86_64
```

**Comment by ivanov17** [comment]
I edited the text above because I found an [article of Daniel J Walsh about SELinux labels for container runtimes](
https://opensource.com/article/18/2/understanding-selinux-labels-container-runtimes). He wrote:

> Processes usually run with the `container_t type`, and content is created with the `container_file_t` type. 

Maybe it related to another issue: SELinux is preventing ns-slapd from read access on files slapd-collations.conf and 99user.ldif if I reuse volume with another instance of 389-ds container.  I'll describe it in more detail later.

**Comment by ivanov17** [comment]
I edited the text above because I found the [article of Daniel J Walsh about SELinux labels for container runtimes](
https://opensource.com/article/18/2/understanding-selinux-labels-container-runtimes). He wrote:

> Processes usually run with the `container_t type`, and content is created with the `container_file_t` type. 

Maybe it related to another issue: SELinux is preventing ns-slapd from read access on files slapd-collations.conf and 99user.ldif if I reuse data volume with another instance of 389-ds container.  I'll describe it in more detail later.

**Comment by Firstyear** [comment]
Reading the container init file, selinux is set to "False". Looking at the backtrace, it looks like the issue here is trying to copy the xattrs in shutil, because shutil.copy2 tries to preserve metadata. 

@mreynolds389 Is there a reason we are using copy2 over copy? https://docs.python.org/3/library/shutil.html#shutil.copy

**Comment by mreynolds389** [comment]
> Reading the container init file, selinux is set to "False". Looking at the backtrace, it looks like the issue here is trying to copy the xattrs in shutil, because shutil.copy2 tries to preserve metadata.
> 
> @mreynolds389 Is there a reason we are using copy2 over copy? https://docs.python.org/3/library/shutil.html#shutil.copy

No idea, I don't think I added that code, but if I did, then we needed to preserve the metadata for some reason.  We need to test it with "copy" instead - _if_ that will fix this issue...

**Comment by Firstyear** [comment]
Hmmm ... Well we go and apply our ownership and permission bits on the lines directly after. So I don't see how we'd need to preserve anything else, because selinux will trigger the xattr generation from system policy, so we shouldn't need to rely on the source file xattrs. So I think it will work ...
