### ISSUE TITLE
Errors from certutil are not propagated

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#4736]
**Issue Description**
When an error occurs with `certutil`, stderr output from it is not printed:
```
[root@fedora ~]# dsctl localhost tls generate-server-cert-csr -s "bad" 
Error: Command '['/usr/bin/certutil', '-R', '--keyUsage', 'digitalSignature,nonRepudiation,keyEncipherment,dataEncipherment', '--nsCertType', 'sslClient,sslServer', '--extKeyUsage', 'clientAuth,serverAuth', '-s', 'bad', '-8', 'fedora', '-g', '4096', '-d', '/etc/dirsrv/slapd-localhost', '-z', '/etc/dirsrv/slapd-localhost/noise.txt', '-f', '/etc/dirsrv/slapd-localhost/pwdfile.txt', '-a', '-o', '/etc/dirsrv/slapd-localhost/Server-Cert.csr']' returned non-zero exit status 255.
``` 
It just states that the exit status is 255, but no `certutil` output, which in this case is 
```
certutil -s: improperly formatted name: "bad"
```

In `lib389/nss_ssl.py` we have many places with statements like this that show this behaviour:
```python
        result = ensure_str(check_output(cmd, stderr=subprocess.STDOUT))
        self.log.debug("nss output: %s", result)
```

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 389-ds-base-2.0.3-3.fc34.x86_64

**Steps to Reproduce**
1. `dsctl localhost tls generate-server-cert-csr -s "bad" `

**Expected results**
Instead of a python traceback, a clear error message should be printed.

**Comment by tbordaz** [comment]
Create a BZ RHDS

**Comment by mreynolds389** [comment]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1974226

**Comment by mreynolds389** [comment]
4bd1c9408..b99236af6  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
a68decb96..c0dd585d7  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by vashirov** [comment]
Here `certutil` is called twice:
https://github.com/389ds/389-ds-base/blob/33c815889ec3bc8eacc7df68d57370ce8cee32e0/src/lib389/lib389/nss_ssl.py#L198-L200

On the second call it asks for the password again, because it thinks it is a db upgrade.

**Comment by mreynolds389** [comment]
Yeah that was it, thanks @vashirov !!!!

f4f255d2d..0208b72ea  master -> master
1bbef77aa..c7a67960c  389-ds-base-2.0 -> 389-ds-base-2.0
b99236af6..07b44fe5c  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
c0dd585d7..131414322  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
