### ISSUE TITLE
ACI's Not Working as Expected

### ISSUE THREAD

**Issue by walshg3** [389ds/389-ds-base#4756]
**Package Version and Platform:**
 - Platform: RHEL 8
 - Package and version: 389-ds-base.x86_64 1.4.3.22-1

Hello, I am new to LDAP and have been struggling with user permissions in 389ds. I can't find a working management console for RHEL 8 due to the the 389-console not supported as of yet on RHEL 8 so I have began learning about Access Control Instructions (ACI's).

My goal is to create a user with compare search read write add and delete as well as another user with read search and compare then remove the anon read search and compare.

With the CN=Directory Manager account in **Apache DS** I can browse my directory perfectly fine.
![Picture of working directory search with CN=Directory Manager](https://user-images.githubusercontent.com/26581084/117158025-1177f400-ad8d-11eb-8e84-0ff2a5f560a8.png)

The issue happens when I connect to the LDAP server with another user account say testuser. With the testuser account I can only see the Root DSE folder.

![image](https://user-images.githubusercontent.com/26581084/117158188-32d8e000-ad8d-11eb-9643-44115cab9200.png)

So at this point I figured I would need an ACI. As a test I created a testuser under o=users,c=us as seen in the picture above. I attempted to insert this ACI on the Root DSE:

`(targetattr="*")(version 3.0; aci "allow test user all access"; allow(compare,search,read,write,add,delete) userdn="ldap:///cn=testuser,o=users,c=us";)`

I am giving the user testuser access to all attributes in c=us.

Here is a picture of the ACI in the Root DSE 
![image](https://user-images.githubusercontent.com/26581084/117158756-b4307280-ad8d-11eb-9e22-0c567c204f9f.png)

and I know something in the backend is happening because when I add that ACI I am then able to see the aci's in the DN table. For example without that ACL in place and when I bind to ApacheDS as the testuser I will get a DN view without the aci's

![image](https://user-images.githubusercontent.com/26581084/117158845-c8746f80-ad8d-11eb-9ece-ec14f813a4d1.png)

But if I do bind with the testuser account and the aci in place I get this:
![image](https://user-images.githubusercontent.com/26581084/117158949-de823000-ad8d-11eb-99b2-b0bee5187ee2.png)

My main question / lack of understanding comes from how ACI's work. I can tell the ACI I created does not actually give proper write permissions because if a run an ldapmodify and try to add an object binding as the testuser account I get an error of:

`modifying entry "c=us" ldap_modify: Insufficient access (50) additional info: Insufficient 'write' privilege to the 'aci' attribute of entry 'c=us'.`

What would a good aci be for testuser to have all privileges under c=us and where in the tree should I place the aci?

Does anyone recommend another way of doing things? Should I downgrade to RHEL 7 if that means I can get access to the 389-console and the setup-ds-admin.pl? 

on a side note in my reading i've seen ACI's and ACL's am I correct in assuming I would be using an ACI in this instance?

Thank you ahead of time for taking the time to help me understand. I've seemed to have read every guide / documentation I could find on the internet over the last few days but none seem to work for my situation.

**Comment by Firstyear** [comment]
> On 6 May 2021, at 00:45, Gregory Walsh ***@***.***> wrote:
> 
> 
> Package Version and Platform:
> 
> 	• Platform: RHEL 8
> 	• Package and version: 389-ds-base.x86_64 1.4.3.22-1
> Hello, I am new to LDAP and have been struggling with user permissions in 389ds. I can't find a working management console for RHEL 8 due to the the 389-console not supported as of yet on RHEL 8 so I have began learning about Access Control Instructions (ACI's).

The 389 console is part of cockpit in RHEL 8. 

> 
> My goal is to create a user with compare search read write add and delete as well as another user with read search and compare then remove the anon read search and compare.
> 
> With the CN=Directory Manager account in Apache DS I can browse my directory perfectly fine.
> 
> 
> The issue happens when I connect to the LDAP server with another user account say testuser. With the testuser account I can only see the Root DSE folder.
> 
> 
> 
> So at this point I figured I would need an ACI. As a test I created a testuser under o=users,c=us as seen in the picture above. I attempted to insert this ACI on the Root DSE:

You should not be inserting this on the rootdse - you need to add it to the root of the database (c=us) for it to apply to that database. 

> 
> (targetattr="*")(version 3.0; aci "allow test user all access"; allow(compare,search,read,write,add,delete) userdn="ldap:///cn=testuser,o=users,c=us";)
> 
> I am giving the user testuser access to all attributes in c=us.

This is a pretty dangerous ACI btw, since it will effectively allow this user to create and modify anything in the directory. 

> 
> Here is a picture of the ACI in the Root DSE
> 
> 
> and I know something in the backend is happening because when I add that ACI I am then able to see the aci's in the DN table. For example without that ACL in place and when I bind to ApacheDS as the testuser I will get a DN view without the aci's
> 
> 
> 
> But if I do bind with the testuser account and the aci in place I get this:
> 
> 
> My main question / lack of understanding comes from how ACI's work. I can tell the ACI I created does not actually give proper write permissions because if a run an ldapmodify and try to add an object binding as the testuser account I get an error of:
> 
> modifying entry "c=us" ldap_modify: Insufficient access (50) additional info: Insufficient 'write' privilege to the 'aci' attribute of entry 'c=us'.
> 
> What would a good aci be for testuser to have all privileges under c=us and where in the tree should I place the aci?
> 
> Does anyone recommend another way of doing things? Should I downgrade to RHEL 7 if that means I can get access to the 389-console and the setup-ds-admin.pl?
> 
> on a side note in my reading i've seen ACI's and ACL's am I correct in assuming I would be using an ACI in this instance?
> 
> Thank you ahead of time for taking the time to help me understand. I've seemed to have read every guide / documentation I could find on the internet over the last few days but none seem to work for my situation.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

—
Sincerely,

William Brown

Senior Software Engineer, 389 Directory Server
SUSE Labs, Australia

**Comment by walshg3** [comment]
@Firstyear 
Thank you so much for taking the time to help me! I will try to insert the ACI into c=us and get back to you. I agree that ACI is dangerous. It was meant for testing purposes. My eventual goal is a user that can edit all but not add aci's and a user that has read only access then remove anon read. 

I have cockpit setup but did not see anywhere to edit or add user permissions in the database. Would the correct way to add permissions with cockpit be through adding aci's?

**Comment by Firstyear** [comment]
> On 6 May 2021, at 10:57, Gregory Walsh ***@***.***> wrote:
> 
> 
> @Firstyear
> Thank you so much for taking the time to help me! I will try to insert the ACI into c=us and get back to you. I agree that ACI is dangerous. It was meant for testing purposes. My eventual goal is a user that can edit all but not add aci's and a user that has read only access then remove anon read.

No problem, hope that helps,

> 
> I have cockpit setup but did not see anywhere to edit or add user permissions in the database. Would the correct way to add permissions with cockpit be through adding aci's?
> 

I'm not 100% sure, I'm not much involved in the cockpit side of things. 


> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

—
Sincerely,

William Brown

Senior Software Engineer, 389 Directory Server
SUSE Labs, Australia

**Comment by walshg3** [comment]
Placing the ACI in the root of my database worked flawlessly. Thank you again for your help. Closing this issue.
