### ISSUE TITLE
Fix coverity issue

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#4759]
**Issue Description**
The support of wtime/optime in the access logs, record the hrtime in the operation structure. #/4218 assign the time without checking that operation exists. I triggers failure in coverity scan

**Package Version and Platform:**
since 1.4.3

**Steps to Reproduce**
Run covcan

**Expected results**
No error in opshared.c and extended.c regarding call to slapi_operation_set_time_started

**Comment by droideck** [comment]
@tbordaz can we close it as the PR was merged? Or do you want to leave the issue for future use?

**Comment by tbordaz** [comment]
Opps thanks for the heads up @droideck .

I forgot to add the commit hashes. This bug being fixed in all targeted releases close
9b62aede5..ad3e77d71 master
9b62aede5..ad3e77d71 389-ds-base-2.0
e0cf8a9cb..70c3e9e71 389-ds-base-1.4.4
d0e0ab37a..099c7c27f 389-ds-base-1.4.3
ca3776e63..8b236bc2c 389-ds-base-1.3.10
