### ISSUE TITLE
replicated operation sometime checks ACI

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#4764]
+++ This bug was initially created as a clone of RedHat Bugzilla #1931820 +++

Description of problem:

From time to time (about once per month) a replicated operation failed due to LDAP error 50 
( LDAP_INSUFFICIENT_ACCESS ).

With the error log level 262144 ( Access control summary information ), the following message is logged:
[18/Feb/2021:17:56:22.531733035 +0100] - DEBUG - NSACLPlugin - print_access_control_summary - conn=594722 op=22 (main): Deny write on entry(companyid=123456789,cn=app,dc=example,dc=com).attr(companyID) to cn=replication manager,cn=config: no aci matched the subject by aci(174): aciname= "Admin ACI", acidn="dc=example,dc=com"

Problem was initially reported on RedHat 11.2 but the issue impact all versions on all platform.
 
Replicated operation are supposed to bypass the acl check. A debug build showed that the operation is not flagged as replicated while the connection is seen as a replication session connection. 
The operation is flagged as replicated when allocating an operation struct if its connection is marked as replication session.

Code review showed that there is a race condition and operation may be allocated before its LDAP packet is received.
  if nsslapd-enable-turbo-mode is enabled (which is the default)
  if connection is secured and some data get exchanged at the security protocol level 
 In that case it is possible that the check to set the replicated flags occurs while the replication start session is processed and
  before the connection get marked as replication session.
  
  Workaround:
    a simple work around is to add an aci allowing write to the replication manager 
   
  Proposed fix is to check again to set the replicated flag just before dispatching the operation 
   (i.e after the operation is read but before it get processed):
   
 ```
  diff --git a/ldap/servers/slapd/connection.c b/ldap/servers/slapd/connection.c
index 615aa3dbe..3be6456ab 100644
--- a/ldap/servers/slapd/connection.c
+++ b/ldap/servers/slapd/connection.c
@@ -1771,6 +1771,13 @@ connection_threadmain()
             }
         }
 
+        /*
+         * Fix bz 1931820 issue (check to set OP_FLAG_REPLICATED may be done
+         * before replication session is properly set set.
+         */
+        if (replication_connection) {
+                       operation_set_flag(op, OP_FLAG_REPLICATED);
+        }
         /*
          * Call the do_<operation> function to process this request.
          */

```

**Comment by tbordaz** [comment]
@progier389 , do you mind to have a look at the following regression introduced by the fix ? (in tests/suites/acl/keywords_part2_test.py::test_access_from_certain_network_only_ip)

<pre>
___________________ test_access_from_certain_network_only_ip ___________________

topo = <lib389.topologies.TopologyMain object at 0x7fe756c80cd0>
add_user = None, aci_of_user = None

    def test_access_from_certain_network_only_ip(topo, add_user, aci_of_user):
        """
        User can access the data when connecting from certain network only as per the ACI.
    
        :id: 4ec38296-7ac5-11e8-9816-8c16451d917b
        :customerscenario: True
        :setup: Standalone Server
        :steps:
            1. Add test entry
            2. Add ACI
            3. User should follow ACI role
        :expectedresults:
            1. Entry should be added
            2. Operation should  succeed
            3. Operation should  succeed
        """
        # Turn access log buffering off to make less time consuming
        topo.standalone.config.set('nsslapd-accesslog-logbuffering', 'off')
    
        # Find the ip from ds logs , as we need to know the exact ip used by ds to run the instances.
        # Wait till Access Log is generated
        topo.standalone.restart()
    
        hostname = socket.gethostname()
        IP = socket.gethostbyname(hostname)
    
        # Add ACI
        domain = Domain(topo.standalone, DEFAULT_SUFFIX)
        domain.add("aci", f'(target = "ldap:///{IP_OU_KEY}")(targetattr=\"*\")(version 3.0; aci "IP aci"; '
                          f'allow(all)userdn = "ldap:///{NETSCAPEIP_KEY}" and (ip = "127.0.0.1" or ip = "::1" or ip = "{IP}") ;)')
    
        # create a new connection for the test
        conn = UserAccount(topo.standalone, NETSCAPEIP_KEY).bind(PW_DM)
        # Perform Operation
        org = OrganizationalUnit(conn, IP_OU_KEY)
        org.replace("seeAlso", "cn=1")
    
        # remove the aci
        domain.ensure_removed("aci", f'(target = "ldap:///{IP_OU_KEY}")(targetattr=\"*\")(version 3.0; aci '
                                     f'"IP aci"; allow(all)userdn = "ldap:///{NETSCAPEIP_KEY}" and '
                                     f'(ip = "127.0.0.1" or ip = "::1" or ip = "{IP}") ;)')
        # Now add aci with new ip
        domain.add("aci", f'(target = "ldap:///{IP_OU_KEY}")(targetattr="*")(version 3.0; aci "IP aci"; '
                          f'allow(all)userdn = "ldap:///{NETSCAPEIP_KEY}" and ip = "100.1.1.1" ;)')
    
        # After changing  the ip user cant access data
        with pytest.raises(ldap.INSUFFICIENT_ACCESS):
>           org.replace("seeAlso", "cn=1")
E           Failed: DID NOT RAISE <class 'ldap.INSUFFICIENT_ACCESS'>


</pre>

**Comment by progier389** [comment]
Hi Thierry, 
 The fix is too trivial to generate a regression (it only set the OP_FLAG_REPLICATED flags on operation 
     associated with replication connection (i.e: having conn->c_isreplication_session))
         (knowing that usually the flag is already set anyway (only in the rare race condition case the flag is not set as it should)
 So in test_access_from_certain_network_only_ip scenario the fix does absolutely nothing.
   (if replication is not enabled it cannot flag a connection as replicated ! -;) )

I rather suspect that the testcase is not reliable (I when pushing PR we always got error in the acl test and I think that this one 
  is often failing:
For example in PR 4715 (pushed in April I see: )

dirsrvtests/tests/suites/acl/keywords_test.py::test_user_can_access_the_data_when_connecting_from_some_network_only FAILED [ 35%]

**Comment by progier389** [comment]
@aivanov389 discovered that this fix revealed an issue that was lying in the code for a couple of years.
So the fix for issue 4797 is also needed. (and btw 4797 which is triggered by ip acl evaluation could be a reason why test_access_from_certain_network_only_ip is sometime failing (with or without 4764 fix)
