### ISSUE TITLE
Lower fips error message severity when fips is not not found

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4770]
**Issue Description**

This is not an "error":

[17/May/2021:10:57:02.753271017 +0000] - ERR - slapd_system_isFIPS - Can not access /proc/sys/crypto/fips_enabled - assuming FIPS is OFF

We should change this to NOTICE severity level

**Comment by mreynolds389** [comment]
2a12316b7..6ca3fb977  master -> master
db47dfcb5..56299aef7  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
f53d0132b..d6fc1a364  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
0bdc258b9..61d76bbfa  389-ds-base-1.4.2 -> 389-ds-base-1.4.2

**Comment by muzzol** [comment]
thanks a lot guys.

If you ever come to Mallorca send me a message and we'll go to take some beers. :)

**Comment by Firstyear** [comment]
@muzzol It's a little bit far away from Australia, but if I'm around I'll let you know :)
