### ISSUE TITLE
[RFE] Enable interval feature of DNA plugin to support  intervals sizes for subuids

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#4773]
DNA plugin should support dnaInterval. This attribute is helpful for support [sub uids/gids](https://pagure.io/freeipa/issue/8361).
Actually DNA plugin already implement that attribute in stepping next granted values and management of ranges. The only restriction is that the setting was disabled (into ifdef) and so step was always dnaInterval=1

**Describe the solution you'd like**
suppress DNA_ENABLE_INTERVAL or define DNA_ENABLE_INTERVAL in dna.c

**Describe alternatives you've considered**
Long discussion in BZ. THe possibility to dereference the dnaInterval into the entries was abandoned as it will break range management (granting/acquisition)

**Comment by mreynolds389** [comment]
3cbad9e89..58a1591b9  master -> master
e3104967d..a80d67704  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
3eeeb1c7f..4cd55311f  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

Still need CI tests

**Comment by mreynolds389** [comment]
CI test

a08540a82..bfb3880cf  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
aa1bceb76..703b39aef  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
