### ISSUE TITLE
There are some typos in man-pages

### ISSUE THREAD

**Issue by miztake** [389ds/389-ds-base#4781]
**Issue Description**
There are some typos in following man-pages:
 - dbscan(1)
 - ldclt(1)
 - rsearch(1)
 - 99user.ldif(5)
 - dirsrv.systemd(5)

**Comment by mreynolds389** [comment]
a80d67704..50606d85f  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
4cd55311f..e05afabbb  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

Thanks for the contribution @miztake !
