### ISSUE TITLE
container: backup task via dsconf hangs after a while

### ISSUE THREAD

**Issue by last-ninjai** [389ds/389-ds-base#4794]
It seems to be depending on whatever backup task will crash after a while and ldap server does not work properly anymore. I got the misbehavior running backup task in a schedule once per hour but I can reproduce it also in another way. Dockerfile and steps provided.

Fedora 35 - LDAP vendorVersion: 389-Directory/2.0.4 B2021.140.0000

### Dockerfile

```Dockerfile
FROM fedora:35

# password configuration manger
ENV DS_DM_PASSWORD=password

RUN set -exo pipefail \
    && echo "Configure DNF..." \
    && echo "install_weak_deps=False" >> /etc/dnf/dnf.conf \
    && echo "max_parallel_downloads=10" >> /etc/dnf/dnf.conf \
    && echo "assumeyes=True" >> /etc/dnf/dnf.conf \
    && echo "Update DNF caches..." \
    && time dnf makecache \
    && echo "Install security updates and bug fixes..." \
    && time dnf upgrade-minimal \
    && echo "Install packages..." \
    && time dnf install \
        389-ds-base \
    && dnf clean all \
    && echo "Configure 389-ds..." \
    && mkdir -p /data/bak \
    && mkdir -p /data/config \
    && mkdir -p /data/db \
    && mkdir -p /data/ldif \
    && mkdir -p /data/logs \
    && mkdir -p /data/run \
    && mkdir -p /data/ssca \
    && mkdir -p /etc/dirsrv \
    && mkdir -p /var/run/dirsrv \
    && ln -s /data/config /etc/dirsrv/slapd-localhost \
    && ln -s /data/ssca /etc/dirsrv/ssca \
    && ln -s /data/run /var/run/dirsrv

EXPOSE 3389 3636

VOLUME /data

HEALTHCHECK --start-period=10s --timeout=5s --interval=15s --retries=2 \
    CMD /usr/libexec/dirsrv/dscontainer -H
```

### steps to reproduce

```shell
docker build --tag ds389 .

# or with args
docker build \
    --build_args http_proxy=value \
    --tag ds389 .

# initial run container
docker run -ti -p 1389:3389 --rm \
    --name testldap \
    ds389 bash

# then inside start ldap server
/usr/libexec/dirsrv/dscontainer -r

# for run other commands inside container
docker exec -ti testldap bash

# create data
echo "create backend" \
&& dsconf localhost backend create --suffix 'o=test,dc=org' --be-name 'testbackend' --create-suffix

echo "set basedn" \
&& echo -e "\nbasedn = o=test,dc=org" >> /data/config/container.inf

echo "create data - organizational units" \
&& dsidm localhost organizationalunit create --ou groups \
&& dsidm localhost organizationalunit create --ou people

echo "optional check entries" \
&& dsconf localhost backend suffix list \
&& dsidm localhost organizationalunit list \
&& cat /data/config/container.inf

# health check
/usr/libexec/dirsrv/dscontainer -H

```

outside container you can check other stuff e.g.:

```shell
# healthcheck state
docker ps --filter name=testldap

# monitor every 5 sec results via ldapsearch
watch -n 5 'ldapsearch -h localhost -p 1389   -D "cn=Directory Manager" -x -w password -b "cn=config" -s sub | tail -n 6'
watch -n 5 'ldapsearch -h localhost -p 1389   -D "cn=Directory Manager" -x -w password -b "o=test,dc=org" -s sub | tail -n 6'
```

*hint*: when you use ldapsearch inside container you must change port from 1389 to 3389

**now we are able to create some backup's running into failure:**

```shell
# inside container
# start create some backup's
for i in {1..30}; do
    echo -e "\n\n==| ${i} ===================================\n\n";
    /bin/sh -c 'dsconf localhost -v backup create';
done
```

after a while seems to be backup task hanged up but will crash with:

```log
DEBUG: The 389 Directory Server Configuration Tool
DEBUG: Inspired by works of: ITS, The University of Adelaide
DEBUG: dsrc path: /root/.dsrc
DEBUG: dsrc container path: /data/config/container.inf
DEBUG: dsrc instances: ['localhost']
DEBUG: dsrc completed with {'args': {'server-id': 'localhost', 'ldapurl': 'ldapi://%2fdata%2frun%2fslapd-localhost.socket', 'root-dn': 'cn=Directory Manager', 'ldapi_enabled': 'on', 'ldapi_socket': '2fdata%2frun%2fslapd-localhost.socket', 'ldapi_autobind': 'on'}, 'uri': 'ldapi://%2fdata%2frun%2fslapd-localhost.socket', 'basedn': 'o=test,dc=org', 'binddn': 'cn=Directory Manager', 'saslmech': None, 'tls_cacertdir': None, 'tls_cert': None, 'tls_key': None, 'tls_reqcert': None, 'starttls': False, 'pwdfile': None, 'prompt': False}
DEBUG: Called with: Namespace(instance='localhost', verbose=True, binddn=None, bindpw=None, prompt=False, pwdfile=None, basedn=None, starttls=False, json=False, archive=None, db_type='ldbm database', func=<function backup_create at 0x7fa62723cf70>)
DEBUG: Instance details: {'args': {'server-id': 'localhost', 'ldapurl': 'ldapi://%2fdata%2frun%2fslapd-localhost.socket', 'root-dn': 'cn=Directory Manager', 'ldapi_enabled': 'on', 'ldapi_socket': '2fdata%2frun%2fslapd-localhost.socket', 'ldapi_autobind': 'on'}, 'uri': 'ldapi://%2fdata%2frun%2fslapd-localhost.socket', 'basedn': 'o=test,dc=org', 'binddn': 'cn=Directory Manager', 'saslmech': None, 'tls_cacertdir': None, 'tls_cert': None, 'tls_key': None, 'tls_reqcert': None, 'starttls': False, 'pwdfile': None, 'prompt': False}
DEBUG: Allocate <class 'lib389.DirSrv'> with ldapi://%2fdata%2frun%2fslapd-localhost.socket
DEBUG: Allocate <class 'lib389.DirSrv'> with 2fdata%2frun%2fslapd-localhost.socket
DEBUG: Allocate <class 'lib389.DirSrv'> with 1c575a259a5d:389
DEBUG: Allocate <class 'lib389.DirSrv'> with 1c575a259a5d:389
DEBUG: Allocate <class 'lib389.DirSrv'> with ldapi://%2fdata%2frun%2fslapd-localhost.socket
DEBUG: Allocate <class 'lib389.DirSrv'> with 2fdata%2frun%2fslapd-localhost.socket
DEBUG: Allocate <class 'lib389.DirSrv'> with 1c575a259a5d:389
DEBUG: Allocate <class 'lib389.DirSrv'> with 1c575a259a5d:389
DEBUG: open(): Connecting to uri ldapi://%2fdata%2frun%2fslapd-localhost.socket
DEBUG: Using dirsrv ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using external ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using external ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using /etc/openldap/ldap.conf certificate policy
DEBUG: ldap.OPT_X_TLS_REQUIRE_CERT = 2
DEBUG: open(): Using root autobind ...
DEBUG: open(): bound as cn=Directory Manager
DEBUG: Retrieving entry with [('',)]
DEBUG: Retrieved entry [dn:
vendorVersion: 389-Directory/2.0.4 B2021.140.0000

]
DEBUG: Retrieving entry with [('cn=config',)]
DEBUG: Retrieved entry [dn: cn=config
nsslapd-bakdir: /data/bak

]
DEBUG: Checking "None" under None : {'nsArchiveDir': '/data/bak/localhost-2021_06_04_12_54_40', 'nsDatabaseType': 'ldbm database', 'cn': 'backup_2021-06-04T12:54:40.064223'}
DEBUG: Validated dn cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config
DEBUG: Creating cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config
DEBUG: updating dn: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config
DEBUG: updated dn: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config with {'objectclass': [b'top', b'extensibleObject']}
DEBUG: updating dn: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config
DEBUG: updated dn: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config with {'nsArchiveDir': [b'/data/bak/localhost-2021_06_04_12_54_40'], 'nsDatabaseType': [b'ldbm database'], 'cn': [b'backup_2021-06-04T12:54:40.064223']}
DEBUG: Created entry cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config : {'objectclass': [b'top', b'extensibleObject'], 'nsArchiveDir': [b'/data/bak/localhost-2021_06_04_12_54_40'], 'nsDatabaseType': [b'ldbm database'], 'cn': [b'backup_2021-06-04T12:54:40.064223']}
DEBUG: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config getVal('nsTaskExitCode')
DEBUG: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config getVal('nsTaskLog')
DEBUG: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config getVal('nsTaskWarning')
DEBUG: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config getVal('nsTaskExitCode')
DEBUG: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config getVal('nsTaskLog')
DEBUG: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config getVal('nsTaskWarning')
<snip tons of equal entries>
DEBUG: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config getVal('nsTaskExitCode')
DEBUG: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config getVal('nsTaskLog')
DEBUG: cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config getVal('nsTaskWarning')
DEBUG: The backup create task has failed with the error code: (None)
Traceback (most recent call last):
  File "/usr/sbin/dsconf", line 134, in <module>
    result = args.func(inst, None, log, args)
  File "/usr/lib/python3.9/site-packages/lib389/cli_conf/backup.py", line 20, in backup_create
    raise ValueError("The backup create task has failed with the error code: ({})".format(result))
ValueError: The backup create task has failed with the error code: (None)
ERROR: Error: The backup create task has failed with the error code: (None)
```

### result/state

* asking "o=test,dc=org" via ldapsearch works
* asking "cn=config" via ldapsearch does not work anymore
* trigger new backup task does not work due cannot access "cn=config" anymore
* container can be stopped via "docker stop testldap"

### conclusion

So I cannot rely on creating backups in that way (dsconf).

### questions

1. Is it a bug or known issue?
1. Is it possible to fix by changing some configuration entries?
1. Does anyone have similar behavior?

**Comment by Firstyear** [comment]
There are two places immediately to look at. If you look at the task-entry in cn=config `cn=backup_2021-06-04T12:54:40.064223,cn=backup,cn=tasks,cn=config` in this case, it has a status field that can give extra details. Additionally, check the content of /data/logs/errors for anything. And finally, if it's hanging or crashing, we made you need to use gdb to get stack traces, but let's check the error logs first.

**Comment by last-ninjai** [comment]
Thanks for your fast response. I had to rebuild environment so timestamps are different. Here are requested information:

1. I have a lot of successful finished task entries (cn=backup/cn=tasks/cn=config) until the uncomplete one:

```log
nsTaskStatus: Backing up file 3 (/data/bak/localhost-2021_06_07_08_24_50/testbackend/entryrdn.db)
```

2. error log looks like:

```log
[07/Jun/2021:08:38:20.805303783 +0000] - INFO - task_backup_thread - Backup finished.
[07/Jun/2021:08:38:23.345060916 +0000] - INFO - task_backup_thread - Beginning backup of 'ldbm database'
[07/Jun/2021:08:38:23.349106377 +0000] - INFO - bdb_copy_directory - Backing up file 1 (/data/bak/localhost-2021_06_07_08_38_23/testbackend/DBVERSION)
[07/Jun/2021:08:38:23.350733692 +0000] - INFO - dblayer_copyfile - Copying /data/db/testbackend/DBVERSION to /data/bak/localhost-2021_06_07_08_38_23/testbackend/DBVERSION
[07/Jun/2021:08:38:23.351087963 +0000] - INFO - bdb_copy_directory - Backing up file 2 (/data/bak/localhost-2021_06_07_08_38_23/testbackend/id2entry.db)
[07/Jun/2021:08:38:23.352776514 +0000] - INFO - dblayer_copyfile - Copying /data/db/testbackend/id2entry.db to /data/bak/localhost-2021_06_07_08_38_23/testbackend/id2entry.db
[07/Jun/2021:08:38:23.353204705 +0000] - INFO - bdb_copy_directory - Backing up file 3 (/data/bak/localhost-2021_06_07_08_38_23/testbackend/entryrdn.db)
[07/Jun/2021:08:38:23.354684248 +0000] - INFO - dblayer_copyfile - Copying /data/db/testbackend/entryrdn.db to /data/bak/localhost-2021_06_07_08_38_23/testbackend/entryrdn.db
```

FYI: I observed in different tries behavior appears not even on backup file 3 (entryrdn). Sometime it happened already on backup file 2 (id2entry).

I am not so familiar with gdb but I guess first step need to install

```shell
dnf install gdb
```

Then it is necessary getting a little bit assistance for more investigation.

* ? install other tools
* ? start dscontainer in different way
* ? other locations to look at for stacktraces

Thanks for your help.

**Comment by Firstyear** [comment]
> Thanks for your fast response. I had to rebuild environment so timestamps are different. Here are requested information:
> 
> 1. I have a lot of successful finished task entries (cn=backup/cn=tasks/cn=config) until the uncomplete one:
> 
> ```
> nsTaskStatus: Backing up file 3 (/data/bak/localhost-2021_06_07_08_24_50/testbackend/entryrdn.db)
> ```
> 
> 1. error log looks like:
> 
> ```
> [07/Jun/2021:08:38:20.805303783 +0000] - INFO - task_backup_thread - Backup finished.
> [07/Jun/2021:08:38:23.345060916 +0000] - INFO - task_backup_thread - Beginning backup of 'ldbm database'
> [07/Jun/2021:08:38:23.349106377 +0000] - INFO - bdb_copy_directory - Backing up file 1 (/data/bak/localhost-2021_06_07_08_38_23/testbackend/DBVERSION)
> [07/Jun/2021:08:38:23.350733692 +0000] - INFO - dblayer_copyfile - Copying /data/db/testbackend/DBVERSION to /data/bak/localhost-2021_06_07_08_38_23/testbackend/DBVERSION
> [07/Jun/2021:08:38:23.351087963 +0000] - INFO - bdb_copy_directory - Backing up file 2 (/data/bak/localhost-2021_06_07_08_38_23/testbackend/id2entry.db)
> [07/Jun/2021:08:38:23.352776514 +0000] - INFO - dblayer_copyfile - Copying /data/db/testbackend/id2entry.db to /data/bak/localhost-2021_06_07_08_38_23/testbackend/id2entry.db
> [07/Jun/2021:08:38:23.353204705 +0000] - INFO - bdb_copy_directory - Backing up file 3 (/data/bak/localhost-2021_06_07_08_38_23/testbackend/entryrdn.db)
> [07/Jun/2021:08:38:23.354684248 +0000] - INFO - dblayer_copyfile - Copying /data/db/testbackend/entryrdn.db to /data/bak/localhost-2021_06_07_08_38_23/testbackend/entryrdn.db
> ```
> 
> FYI: I observed in different tries behavior appears not even on backup file 3 (entryrdn). Sometime it happened already on backup file 2 (id2entry).

This makes me immediately suspect some kind of db locking or contention. Could you consider LDIF backups instead?


```
dsconf instance backend export -l <foo.ldif> -r
```

This exports with all the needed replication metadata so you can restore just the same as a db-file backup that you are attempting. 


> 
> I am not so familiar with gdb but I guess first step need to install
> 
> ```shell
> dnf install gdb
> ```
> 
> Then it is necessary getting a little bit assistance for more investigation.
> 
> * ? install other tools
> * ? start dscontainer in different way
> * ? other locations to look at for stacktraces

You'll need to install gdb inside the container, but let's check about ldif backups first before we go down the gdb rabbit hole. 


> 
> Thanks for your help.

**Comment by vashirov** [comment]
I was able to reproduce the issue
[pstack.txt](https://github.com/389ds/389-ds-base/files/6622706/pstack.txt)

**Comment by vashirov** [comment]
`stderr` buffer gets filled up because we redirect it to a pipe, but nothing is reading it:
https://github.com/389ds/389-ds-base/blob/2120af0cc3940d4669ebe57d4afa680e6b6dd95f/src/lib389/cli/dscontainer#L313 

If I flush the buffer in the container, the backup task completes: 
`tail -F /proc/$(pidof ns-slapd)/fd/2`
Or if I remove the redirects of `stderr` and `stdout` in `dscontainer`.

@Firstyear, perhaps we should not be redirecting `stdout` and `stderr` to pipe and let container runtime handle them? WDYT?

**Comment by Firstyear** [comment]
Ahhh yes. That would make sense. I'll make that change now.

**Comment by last-ninjai** [comment]
Thanks for your investigation. Possible solution (#4798) sounds well.

Anyway I tried your suggestion:

> This makes me immediately suspect some kind of db locking or contention. Could you consider LDIF backups instead?
> 
> ```
> dsconf instance backend export -l <foo.ldif> -r
> ```
> 
> This exports with all the needed replication metadata so you can restore just the same as a db-file backup that you are attempting.
> 

It seems to be also a valid workaround. I run a loop of 50 without any misbehavior:

```
for i in {1..50}; do
    /bin/sh -c "dsconf localhost backend export -l backup-$(date +%s).ldif -r testbackend"
done
```
