### ISSUE TITLE
nsslapd-ndn-cache-max-size wrong success result

### ISSUE THREAD

**Issue by falon** [389ds/389-ds-base#4802]
I see it on `nsslapd-ndn-cache-max-size` and python3-lib389 **1.4.3.16** and 389-ds-base **1.4.3.22**.

`nsslapd-ndn-cache-max-size` has a max size of 2147483647. If I try to set a wrong value, 0 is set and _success_ is returned:

```
dsconf -D "cn=directory manager" -w **** ldap://ldap.example.com:389 config replace nsslapd-ndn-cache-max-size=4294967296
selinux is disabled, will not relabel ports or files.
Successfully replaced "nsslapd-ndn-cache-max-size"

dsconf -D "cn=directory manager" -w **** ldap://ldap.example.com:389 config get nsslapd-ndn-cache-max-size
nsslapd-ndn-cache-max-size: 0

dsconf -D "cn=directory manager" -w **** ldap://ldap.example.com:389 config replace nsslapd-ndn-cache-max-size=2147483647
selinux is disabled, will not relabel ports or files.
Successfully replaced "nsslapd-ndn-cache-max-size"

dsconf -D "cn=directory manager" -w **** ldap://ldap.example.com:389 config get nsslapd-ndn-cache-max-size
nsslapd-ndn-cache-max-size: 2147483647
```
Maybe related to #1121 (it seems fixed on 1.3 already, but the current behavior on 1.4 is still wrong).

**Comment by mreynolds389** [comment]
In the latest 1.4.3 branch we started using a new NDN cache (in Rust), and this sizing limit no longer exists.  All newer versions of 389 are using the new rust cache.

Closing issue.
