### ISSUE TITLE
Cannot install 389-admin-console on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by Maxxil** [389ds/389-ds-base#4811]
**Issue Description**
Every time I try to install 389-admin-console on Ubuntu 20.04.2 LTS i get this error:
**_E: Unable to locate package 389-admin-console_**

**Package Version and Platform:**
 - Platform: Ubuntu 20.04.2 LTS
 - Package and version: 389-ds latest version
 - Browser: No

**Steps to Reproduce**
1. Go to the console of your Ubuntu
2. Connect a su by typing sudo su
3. Type the command: apt-get install 389-admin-console

**Comment by mreynolds389** [comment]
Sorry the old java console (389-console) was deprecated a few years ago and has been completely removed from recent versions.  There is now a Cockpit plugin (cockpit-389-ds) for DS configuration and management.  See:  https://access.redhat.com/documentation/en-us/red_hat_directory_server/11/html/administration_guide/index

**Comment by mreynolds389** [comment]
Closing since 389-console is not longer provided
