### ISSUE TITLE
Source download for 2.0.4+ not available

### ISSUE THREAD

**Issue by rillig** [389ds/389-ds-base#4813]
https://www.port389.org/docs/389ds/development/source.html#389-directory-server-200 lists download links for versions 2.0.4, 2.0.5 and 2.0.6. These links result in a 404. Earlier versions work though.

**Comment by mreynolds389** [comment]
Thanks for pointing this out!  All our new source tar balls are on github now.  So I need to update these links to stop pointing at pagure.io.

**Comment by mreynolds389** [comment]
Fixed
