### ISSUE TITLE
ns-slapd reports error about missing libentryuuid-syntax-plugin

### ISSUE THREAD

**Issue by stanislavlevin** [389ds/389-ds-base#4815]
**Issue Description**
ns-slapd reports error about missing `libentryuuid-syntax-plugin` on startup:
```
Jun 28 10:48:49 master1.ipa.test systemd[1]: Starting 389 Directory Server IPA-TEST....
Jun 28 10:48:50 master1.ipa.test ns-slapd[505]: [28/Jun/2021:10:48:50.111164363 +0000] - ERR - symload_report_error - Netscape Portable Runtime error -5977: /usr/lib64/dirsrv/plugins/libentryuuid-syntax-plugin.so: cannot open shared object file: No such file or directory
Jun 28 10:48:50 master1.ipa.test ns-slapd[505]: [28/Jun/2021:10:48:50.112020602 +0000] - ERR - symload_report_error - Could not open library "/usr/lib64/dirsrv/plugins/libentryuuid-syntax-plugin.so" for plugin entryuuid_syntax
Jun 28 10:48:50 master1.ipa.test ns-slapd[505]: [28/Jun/2021:10:48:50.113279760 +0000] - ERR - slapd_bootstrap_config - The plugin entry [cn=entryuuid_syntax,cn=plugins,cn=config] in the configfile /etc/dirsrv/slapd-IPA-TEST/dse.ldif was invalid. Failed to load plugin's init function.
```

**Package Version and Platform:**
 - Platform: ALTLinux
 - Package and version: 1.4.3.24
 **built _without_ rust.**

**Expected results**
no errors

**Additional context**
error appears after upgrade 1.4.3.23 -> 1.4.3.24.

**Comment by vashirov** [comment]
I think we need to backport https://github.com/389ds/389-ds-base/commit/4cfa3745e864e5a7fbf61c2d7cde005b5fe1eff5 (it was fixed only in >=1.4.4.x and master)

**Comment by stanislavlevin** [comment]
I confirm, that commit fixed my issue.

**Comment by stanislavlevin** [comment]
thank you, @vashirov.

**Comment by vashirov** [comment]
Thank you for confirming, @stanislavlevin!
Mark fixed it in https://github.com/389ds/389-ds-base/commit/03e2b8aabb5e7b1dd1c19b1601ffa1fd7271f849 
Closing.
