### ISSUE TITLE
RFE dscreate should provide a fast creation option

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#4839]
**Issue Description**
Would it be possible to create an option 'dscreate fast' that does

    dscreate create-template | sed -e 's/;suffix =/suffix = dc=example,dc=com/' -e 's/;sample_entries = no/sample_entries = yes/' -e 's/;create_suffix_entry = False/create_suffix_entry = True/' -e 's/;root_password = Directory_Manager_Password/root_password = password/' >/tmp/foo2 ; dscreate from-file /tmp/foo2

**Package Version and Platform:**
 since 1.4.3

**Steps to Reproduce**
see description

**Expected results**
'dscreate fast' creates and start an instance slapd-localhost with dc=example,dc=com sample entries

**Comment by q2dg** [comment]
You could add an alias to your .bashrc....but maybe it'd be worthy to add this oneliner in 389ds's documentation

**Comment by tbordaz** [comment]
@q2dg, thanks for this nice idea. Alias is good enough. Closing that ticket
