### ISSUE TITLE
Typos in "dsconf pwpolicy set --help"

### ISSUE THREAD

**Issue by mmuehlfeldRH** [389ds/389-ds-base#4851]
**Issue Description**
There are some typos in the output of "dsconf instance_name pwpolicy set --help":

```
  --pwdmustchange PWDMUSTCHANGE
                        User must change their passwrod after it is reset by
                        an Administrator
```
-> User**s** must change their **password** after it **was** reset by an **a**dministrator

```
  --pwdhistorycount PWDHISTORYCOUNT
                        The number of password to keep in history
```
-> The number of password**s** to keep in history

```
  --pwdchecksyntax PWDCHECKSYNTAX
                        Set to "on" to Enable password syntax checking
```
-> Set to "on" to **e**nable password syntax checking.

```
  --pwdisglobal PWDISGLOBAL
                        Set to "on" to enable password policy state
                        attributesto be replicated
```
-> Set to "on" to enable password policy state **attributes to** be replicated

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 389-ds-base-2.0.7-20210716git0f443bf33.fc34.x86_64

**Comment by mreynolds389** [comment]
Downstream bug:

https://bugzilla.redhat.com/show_bug.cgi?id=1989994

**Comment by droideck** [comment]
131414322..3edfd02ee  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   07b44fe5c..4c5a75ff4  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
