### ISSUE TITLE
Retro Changelog is not trimming changes

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4869]
**Issue Description**

Retro changelog is not trimming changes under some circumstances because we are mixing monotonic and utc times

[11/Aug/2021:11:01:49.792450548 +0200] - DEBUG - DSRetroclPlugin - cltrim: ldrc=0, first_time=1622032141, cur_time=3702600
[11/Aug/2021:11:01:49.842339467 +0200] - DEBUG - DSRetroclPlugin - retrocl_housekeeping - changelog does not need to be trimmed
[11/Aug/2021:11:06:49.953401407 +0200] - DEBUG - DSRetroclPlugin - cltrim: ldrc=0, first_time=1622032141, cur_time=3702900
[11/Aug/2021:11:06:50.012249703 +0200] - DEBUG - DSRetroclPlugin - retrocl_housekeeping - changelog does not need to be trimmed

Look at cur_time. That is the "uptime" of the system, not UTC.

[root@linge ~]# uptime
 11:21:42 up 42 days, 20:49,  2 users,  load average: 0.15, 0.14, 0.16 

In the retro changelog code (trim_changelog) we are using the same monotonic time for the interval and checking for the age of an entry.  We need to use the current time when checking the age and not the monotonic time.

**Comment by keestux** [comment]
Maybe we need to look at the tests too. Is there a test that should have caught this? Whatever the answer (yes or no), we need to investigate.

Is it `nsslapd-changelog-trim-interval` or `nsslapd-changelogtrim-interval`?
```
$ git grep changelog-trim
dirsrvtests/tests/suites/password/regression_test.py:                                         (ldap.MOD_REPLACE, 'nsslapd-changelog-trim-interval', b"5s"),
dirsrvtests/tests/tickets/ticket47871_test.py:           (ldap.MOD_REPLACE, 'nsslapd-changelog-trim-interval', b"5s")]
ldap/servers/plugins/retrocl/retrocl.h:#define CONFIG_CHANGELOG_TRIM_INTERVAL "nsslapd-changelog-trim-interval"
```

**Comment by mreynolds389** [comment]
@keestux - agreed our tests are not robust enough to pick up on this failure

**Comment by vashirov** [comment]
> Is it `nsslapd-changelog-trim-interval` or `nsslapd-changelogtrim-interval`?
> 
`nsslapd-changelog-trim-interval` is for retro changelog and `nsslapd-changelogtrim-interval` is for changelog5: 
```
$ grep -inr  "define CONFIG_CHANGELOG_TRIM"
ldap/servers/plugins/retrocl/retrocl.h:56:#define CONFIG_CHANGELOG_TRIM_INTERVAL "nsslapd-changelog-trim-interval"
ldap/servers/plugins/replication/repl_shared.h:34:#define CONFIG_CHANGELOG_TRIM_ATTRIBUTE "nsslapd-changelogtrim-interval"
```

**Comment by keestux** [comment]
@vashirov What? Now that is a good way to confuse users.

**Comment by Firstyear** [comment]
> @vashirov What? Now that is a good way to confuse users.

Yes, we know. But sadly some of these decisions were made many years ago and it can be hard to change in existing releases. We do want to improve these.

IMO I'd love to rename these - are we still able to make breaking changes for 2.x @mreynolds389 ? 

A part of the issue here is our tests can't easily manipulate "time" to check this, but I'd be open to some other ideas.

**Comment by mreynolds389** [comment]
549d9c652..3f7a2fa37  389-ds-base-2.0 -> 389-ds-base-2.0
0491c2175..03a675208  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
790096a87..532191107  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
