### ISSUE TITLE
entryuuid needs to be "off" by default

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4872]
**Issue Description**

The entryuuid plugin and it's Rust implementation creates and uses a new attribute syntax OID and new schema.  But if you are using replication with a server that does not have the entryuuid plugin then replication breaks because that older replica can not learn the new schema because the its not aware of the syntax OID (from cn=entryuuid_syntax,cn=plugins,cn=config) used in the new schema.

So we need to disable the entryuuid plugin by default, and document that it only works with replication if all the servers in the topology have the new syntax plugin/entryuuid plugin.

**Comment by mreynolds389** [comment]
Turns out this will not work either.  We can not add the entryuuid schema since it references the new syntax OID (regardless if the plugin is enabled).

**Comment by Firstyear** [comment]
Yeahhh I was going to say that would be an issue. Isn't this really just about upgrading replicas in a timely-ish manner though? Or is someone trying to run mixed versions.

**Comment by mreynolds389** [comment]
> Yeahhh I was going to say that would be an issue. Isn't this really just about upgrading replicas in a timely-ish manner though? Or is someone trying to run mixed versions.

We have to support migration, upgrade, and mixed version environments.  That's the reality of many of our customers.   And I think we will need to a big change to schema replication and detecting versions of replicas in replication.  There used to be this in the code but it was removed, but we are going to need it again. On some level.  Ugh...

This is a huge problem actually :-(  Unless we don't "need" the new syntax plugin...

**Comment by vashirov** [comment]
Can we make entryUUID plugin, entryUUID syntax plugin and their schema optional via packaging? Those who need it, can install it separately. Those who don't can safely migrate from older versions. And install/enable it later if/when they need it.

**Comment by mreynolds389** [comment]
> Can we make entryUUID plugin, entryUUID syntax plugin and their schema optional via packaging? Those who need it, can install it separately. Those who don't can safely migrate from older versions. And install/enable it later if/when they need it.

I like this approach alot...  I was able to get this working on the packaging level(specfile), but overall it needs polishing.  Like, how do we handle the plugin config entry in dse.ldif?  Leave it there, but off?  Or do we need an upgrade script in the new subpackage, and remove entryuuid from upgrade.c/fedse.c (not desirable)?  

Also, current CI tests will need a little work too.

Feedback/thoughts are welcome, and I will continue to think about this...

**Comment by mreynolds389** [comment]
> > Can we make entryUUID plugin, entryUUID syntax plugin and their schema optional via packaging? Those who need it, can install it separately. Those who don't can safely migrate from older versions. And install/enable it later if/when they need it.
> 
> I like this approach alot... I was able to get this working on the packaging level(specfile), but overall it needs polishing. Like, how do we handle the plugin config entry in dse.ldif? Leave it there, but off? Or do we need an upgrade script in the new subpackage, and remove entryuuid from upgrade.c/fedse.c (not desirable)?
> 
> Also, current CI tests will need a little work too.
> 
> Feedback/thoughts are welcome, and I will continue to think about this...

Okay working on a fix for all of this using new CLI commands that will be called from the specfile scriptlets to update the config during install and uninstall.  But with this approach you still need all the servers in a replicated environment to have the entryUUID plugin present.  If we stray from the spec as @Firstyear suggested, it would not break replication with older replicas, but then those other replicas would not be compliant.  There would be no syntax or hack normalization.  The entryuuid attribute would be present, but no syntax matching rules to go with it.  

So I think the current approach is acceptable, but it needs serious documentation/release notes to warn people that using it in replication requires all the servers to be at minimum version for replication to work.

I'll have a PR request ready soon for review, but I am also okay going in a different direction.   We are just in a serious time crunch if it is to make some upcoming deadlines.

**Comment by mreynolds389** [comment]
a5c04a8fe..bce941ec3  389-ds-base-2.0 -> 389-ds-base-2.0
a3d4f63e5..a7ca0280f  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
2aff98c75..f370a281b  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
