### ISSUE TITLE
Can't promote consumer to supplier using dsconf

### ISSUE THREAD

**Issue by raymuncb** [389ds/389-ds-base#4899]
**Issue Description**
Can't promote consumer to supplier using dsconf

**Package Version and Platform:**
 - Platform: CentOS
 - Package and version: 389-ds-base-2.0.6-1.module_el8+12264+8a44fa21
 - Browser: Chrome

**Steps to Reproduce**
1. Execute the command: dsconf _instance_ replication promote --suffix cn=example --newrole supplier --replica-id 10
2. Result of command: Error: Failed to create changelog: {'msgtype': 105, 'msgid': 8, 'result': 53, 'desc': 'Server is unwilling to perform', 'ctrls': [], 'info': 'Changelog configuration is part of the backend configuration'}
3. In audit log:
time: 20210904194247
dn: cn=changelog5,cn=config
result: 53
changetype: add
objectClass: top
objectClass: nsChangelogConfig
cn: changelog5
nsslapd-changelogdir: /var/lib/dirsrv/slapd-_instance_/changelogdb
creatorsName: cn=Directory Manager
modifiersName: cn=Directory Manager
createTimestamp: 20210904224247Z
modifyTimestamp: 20210904224247Z

**Expected results**
Instance promoted.

**Additional context**
In this version [*Integrate Changelog and Backend Database*](https://directory.fedoraproject.org/docs/389ds/design/integrate-changelog-database-and-backend-database.html) is applied, correct? But the dsconf script does not recognized this and tries to create the changelog in the wrong place.

Any thoughts?
Thanks.

**Comment by mreynolds389** [comment]
Right it should not be adding the changelog as that is now done automatically.  I think this is a known issue, but just to confirm, is the version of python-lib389 the same as 389-ds-base?

**Comment by raymuncb** [comment]
> Right it should not be adding the changelog as that is now done automatically. I think this is a known issue, but just to confirm, is the version of python-lib389 the same as 389-ds-base?

Yes. Output of _yum info python3-lib389_: 
Pacotes instalados
*Nome         : python3-lib389
Versão       : 2.0.6
Lançamento   : 1.module_el8+12264+8a44fa21*
Arquitetura  : noarch
Tamanho      : 4.0 M
Origem       : 389-ds-base-2.0.6-1.module_el8+12264+8a44fa21.src.rpm
Repositório  : @System
A partir do  : epel-modular
Resumo       : A library for accessing, testing, and configuring the 389 Directory Server
URL          : https://www.port389.org
Licença      : GPLv3+ and MIT and (ASL 2.0 or MIT) and (ASL 2.0 or Boost) and MPLv2.0 and ASL 2.0
             : and BSD and (ASL 2.0 with exceptions or ASL 2.0 or MIT) and (Unlicense or MIT)
Descrição    : This module contains tools and libraries for accessing, testing,
             :  and configuring the 389 Directory Server.

**Comment by mreynolds389** [comment]
I thought it might have been this issue, but it is different:  https://github.com/389ds/389-ds-base/issues/4731

Anyway this is a simple fix, and we'll get it addressed next week...

**Comment by raymuncb** [comment]
Very well. Thanks Mark. I'll wait.
Have a good day.

**Comment by mreynolds389** [comment]
This was fixed some time ago, closing ticket.
