### ISSUE TITLE
ipa-replica-install with 389ds copr repo

### ISSUE THREAD

**Issue by flo-renaud** [389ds/389-ds-base#4903]
**Issue Description**
ipa-replica-install is failing when using the copr repo https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/

**Package Version and Platform:**
 - Platform: Fedora 34
 - Package and version: 389-ds-base-2.1.0-20210906gitd54862122.fc34.x86_64

**Steps to Reproduce**
1. enable the copr repo with `dnf copr enable @389ds/389-ds-base-nightly`
2. update the packages: `dnf update -y`
3. install freeipa packages: `dnf install -y freeipa-server`
4. install the replica with `ipa client-install --domain ipa.test --realm IPA.TEST --principal admin --password Secret123; kinit admin; ipa-replica-install -U`

**Expected results**
replica installation should succeed

`ipa-replica-install` fails with the following output:
```
[...]
Configuring directory server (dirsrv)
  [1/3]: configuring TLS for DS instance
  [error] NetworkError: cannot connect to 'ldapi://%2Frun%2Fslapd-IPA-TEST.socket': Connection refused
Your system may be partly configured.
Run /usr/sbin/ipa-server-install --uninstall to clean up.

cannot connect to 'ldapi://%2Frun%2Fslapd-IPA-TEST.socket': Connection refused
The ipa-replica-install command failed. See /var/log/ipareplica-install.log for more information
```

replica's dirsrv error log contains:
```
[06/Sep/2021:11:42:55.948181876 -0400] - ERR - dse_read_one_file - The entry cn=schema in file /etc/dirsrv/slapd-IPA-TEST/schema/99user.ldif (lineno: 1) is invalid, error code 21 (Invalid syntax) - attribute type ( 2.16.840.1.113730.3.8.11.61 NAME 'ipaWrappingKey' DESC 'PKCS 115.121.1.15 SINGLE-VALUE X-ORIGIN ( 'IPA v4.1' 'user defined' ) ): Failed to parse attribute, error(2 - Unexpected token) at ( v4.1' 'user defined' ) ))
[06/Sep/2021:11:42:55.953446331 -0400] - ERR - setup_internal_backends - Please edit the file to correct the reported problems and then restart the server.
```

Extract of 99user.ldif:
```
attributeTypes: ( 2.16.840.1.113730.3.8.11.61 NAME 'ipaWrappingKey' DESC 'PKCS
 #11 URI of the wrapping key' EQUALITY caseExactMatch SYNTAX 1.3.6.1.4.1.1466.
 115.121.1.15 SINGLE-VALUE X-ORIGIN ( 'IPA v4.1' 'user defined' ) )
```
It looks like the # is considered as a comment and part of the definition is not taken into account. See the error log which is missing "#11 ...".

**Comment by flo-renaud** [comment]
Companion issue on IPA side: https://pagure.io/freeipa/issue/8982

**Comment by tbordaz** [comment]
It looks ldap_str2attributetype does not support that '#' in ipaWrappingKey definition. ipaWrappingKey definition is old (2015) and always contained that '#'. Was the schema file 60basev3.ldif installed before ?

The openldap function ldap_str2attributetype fails to parse it (openldap-2.4.57-5.fc34.x86_64). Do you know if nsslapd-enquote-sup-oc is 'on' ?

**Comment by flo-renaud** [comment]
@tbordaz 
the main difference I see with previous versions is that the line break appears at a different place. If the # is the first character of the line, we see the issue.
`nsslapd-enquote-sup-oc` is not set on the master/replica (meaning it defaults to off)
It's puzzling me that the attribute is defined in 60basev3.ldif on both servers and appears also in 99-user.ldif. Is it expected?

**Comment by tbordaz** [comment]
It started failing on 389-ds-base-2.1.0-20210906gitd54862122.fc34.x86_64 (https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/package/389-ds-base/) we can check changes that happened in the week before

**Comment by progier389** [comment]
I  wonder if we do not have a bug in the ldif parser
 dup_ldif_line() is wrong as it also checks for the '#' after skipping the space (now I am not sure whether we use openldap parser or  dup_ldif_line for the schema 
 if I remember rightly I added dup_ldif_line to parse the entries from lmdb (because that is read-only memory in lmdb map) and  the code is roughly based on openldap code

**Comment by tbordaz** [comment]
Nice finding. Indeed that [change](https://github.com/389ds/389-ds-base/commit/8e5d4789e6220667009539349f7cfa0343c68473#diff-bb2cafe48e3d7c0c9fe3b801e7c678e3b62b5e3c01f5ad3a02611bb62d8c6dd5R1656) looks a good candidate. I think a testcase could be to create a regular instance, add a problematic attribute definition in 99user.ldif, and restart the instance
<pre>
attributeTypes: ( 2.16.840.1.113730.3.8.11.61 NAME 'ipaWrappingKey' DESC 'PKCS
 #11 URI of the wrapping key' EQUALITY caseExactMatch SYNTAX 1.3.6.1.4.1.1466.
 115.121.1.15 SINGLE-VALUE X-ORIGIN ( 'IPA v4.1' 'user defined' ) )
</pre>

**Comment by progier389** [comment]
Indeed that is the root cause.
 FYI: The schema read use str2entry function exactly as we do as when decoding an entry from the database and is now using dup_ldif_line. I tested successfully a trivial fix (ignore comment only if pos==0 (i.e: if we are at the start of the record))
 Will add a nice CI test implementing @[tbordaz](https://github.com/tbordaz) idea

**Comment by mreynolds389** [comment]
please cherry-pick to: 2.0, 1.4.4, 1.4.3, and 1.3.10  Thanks!

**Comment by progier389** [comment]
merged in master branch -  no cherrypick needed as dup_ldif_line exists only in master branch.

**Comment by flo-renaud** [comment]
@progier389 thanks for the fix, I'll monitor the FreeIPA tests over the week-end and let you know if the issue is gone.

**Comment by flo-renaud** [comment]
@progier389 
the test is still failing, even with the fix. See PR #[1444](https://github.com/freeipa-pr-ci2/freeipa/pull/1444), with for instance the test `simple_replication`: [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/0c3b11d2-7689-11ec-9e69-fa163ec89814/report.html), [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/0c3b11d2-7689-11ec-9e69-fa163ec89814/).

From the [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/0c3b11d2-7689-11ec-9e69-fa163ec89814/installed_packages/installed_packages_master.log.gz), one can see that the installed 389-ds version is `389-ds-base-2.1.0-20220114.fc35.x86_64` taken from the [copr](https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/build/3167828/) repo, which contain the patch 9a6a0c3f8ce2425bf8c028e1a6855b3be5123509.
The replica [error log](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/0c3b11d2-7689-11ec-9e69-fa163ec89814/test_integration-test_simple_replication.py-TestSimpleReplication-install/replica0.ipa.test/var/log/dirsrv/slapd-IPA-TEST/errors.gz) shows a different error message:
```
[16/Jan/2022:05:15:04.841715446 +0000] - ERR - dse_read_one_file - The entry cn=schema in file /etc/dirsrv/slapd-IPA-TEST/schema/99user.ldif (lineno: 1) is invalid, error code 21 (Invalid syntax) - attribute type ( 2.16.840.1.113730.3.8.11.61 NAME 'ipaWrappingKey' DESC 'PKCS 115.121.1.15 SINGLE-VALUE X-ORIGIN ( 'IPA v4.1' 'user defined' ) ): Failed to parse attribute, error(2 - Unexpected token) at ( v4.1' 'user defined' ) ))
```
The attribute type definition on the replica is missing some parts and has lost a closing quote after the DESC field, it should be 
```
attributetypes: ( 2.16.840.1.113730.3.8.11.61 NAME 'ipaWrappingKey' DESC 'PKCS#11 URI of the wrapping key' EQUALITY caseExactMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE X-ORIGIN 'IPA v4.1' )
```

**Comment by progier389** [comment]
Looks like there is a version collision on copr builds: 
The package installed on the test machine does not contans the fix:
vi +1730 /usr/src/debug/389-ds-base-2.1.0-20220114.fc35.x86_64/ldap/servers/slapd/util.c 
does not contains the fix (it should be:         if (*line == '#' && pos == 0) {        )

And https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/builds/ shows 2 builds with version 2.1.0-20220114.fc34
There is probably an issue with the way we generates the copr package names (maybe we should increase the timestamp precision ?)

**Comment by flo-renaud** [comment]
@progier389 the tests have been relaunched, this time with a more recent build containing your fix, and they are now green:
`test_simple_replication`: [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ed92d998-77cf-11ec-b2b6-fa163ec89814/report.html), with the package `389-ds-base-2.1.0-20220117.fc35.x86_64`.

**Comment by vashirov** [comment]
> There is probably an issue with the way we generates the copr package names (maybe we should increase the timestamp precision ?)

+1 to increase the precision and at least add hours and minutes to the version. This is also useful (at least for me) during git bisect runs, so that generated packages can be always upgraded, as the version number grows monotonically.
 
Copr builds are done on each commit. So if there are several commits on the same day, they would all have the same version. Not sure why, but version also has a missing commit hash. I'll investigate it.
