### ISSUE TITLE
Performance ACI: targetfilter evaluation result can be reused

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#4925]
**Issue Description**
An ACI may contain _targetfilter_. For a given operation (like search) a same targetfilter is evaluated many times. This evaluation is expensive (syntax/matching rule specific), especially in case of substring matching.

Some evaluation result can be cached and reused

**Package Version and Platform:**
all version

**Steps to Reproduce**
Provision a subtree of large number of entries with large number of attributes and a bind account that is allowed to read those entries/attributes.
Add ACIs with large dummy targetfilter granting access to entries. For example '...(&(description=*lrd)(description=*orld)...(description=*ello world))...'

a ldapsearch with the bind account and retrieve all the subtree entries with all attributes. The search should is slow.

**Expected results**
Search should not be extremely long

**Comment by tbordaz** [comment]
22156fcdd..96dbbb214  master
ce00d6fb3..aaeff2d1c  389-ds-base-1.4.4
e6a06390c..53582d12f  389-ds-base-1.4.3

**Comment by mreynolds389** [comment]
@tbordaz please cherry pick this to 389-ds-base-2.0 as well :-)

**Comment by mreynolds389** [comment]
> @tbordaz please cherry pick this to 389-ds-base-2.0 as well :-)

done:

54d7cc78c..c661024b3  389-ds-base-2.0 -> 389-ds-base-2.0

**Comment by tbordaz** [comment]
backport to 1.3.10
a2c73838d..d09cd92cc  389-ds-base-1.3.10
