### ISSUE TITLE
RFE: `dsidm` - add creation of service accounts and accounts under a different OU

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#4931]
`dsidm` can create OUs, but user entries can be created only under `ou=people`. If one needs a user entry under a different OU, they need to create OU first, then create an account and then move it (`dsidm localhost account rename-by-dn ...`).

We also have `ou=services` created by default. It would be good to add first class management of entries under there with the corresponding objectClasses.

**Comment by mreynolds389** [comment]
Changing milestone to 1.4.3

**Comment by vashirov** [comment]
e6068c07a..c2b0abaf8  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   4290afd68..2dfd15e07  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   43ac925f9..1a52a366e  389-ds-base-2.0 -> 389-ds-base-2.0
