### ISSUE TITLE
RFE: `dsidm` - add shortcuts for `initalise` and `organizationalunit` 

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#4932]
It's tiresome to type these subcommands, especially when they use different spelling next to each other. I regularly type `initialize` or `organisationalunit`. It would be nice to have `init` and `ou` aliases in addition to alternative spelling variants.

**Comment by mreynolds389** [comment]
4d9d18cae..7c658cd63  389-ds-base-2.1 -> 389-ds-base-2.1
e59e67444..cc5aeb14e  389-ds-base-2.0 -> 389-ds-base-2.0
