### ISSUE TITLE
max_failure_count can be reached in dscontainer on slow machine with missing debug exception trace

### ISSUE THREAD

**Issue by ecureuil** [389ds/389-ds-base#4938]
Hello,
On a very slow machine, the ldapi instance is very long to be available and the timeout can be reached in dscontainer.
The number of attempts is hardcoded in max_failure_count.
Is it possible to allow to modify the max_failure_count value, please?
The diagnostic is complicated by the fact that when max_failure_count is reached, the exception is hidden in logs:
 try:
    inst = _gen_instance()
    inst.open()
    if "dn: cn=Directory Manager" == inst.whoami_s():
        return (False, True)
    else:
        log.error("The instance may be misconfigured, unable to cn=Directory Manager autobind.")
        return (False, False)
**except:
    log.debug("Instance LDAPI not functional (yet?)")
    pass**

Perhaps when timeout is reached, this exception could be printed?
Best regards,
Loris

**Comment by vashirov** [comment]
Hi,
thank you for your report.

How slow is this machine? If it takes more than 1 minute for ns-slapd to start, the server won't be very usable. 
But I agree that this timeout should be tunable for diagnostics and troubleshooting purposes.

Regarding the exception message, where do you expect it to be printed if not in the logs? 
How do you run your container (standalone podman/docker or k8s or something else)? 

Thanks.

**Comment by ecureuil** [comment]
Hi,
The slowness is random, I investigate and I agree it is not a good state :) I was blocked in my diagnostics by the fact that the timeout is hardcoded and the exception hidden.
If the exception message is printed in the logs it is enough for me (I have patched the file dscontainer to do that).
The container is created by k8s.
Best regards,
Loris

**Comment by vashirov** [comment]
I see that the message is printed:
```
INFO: Starting 389-ds-container ...
DEBUG: Allocate local instance <class 'lib389.DirSrv'> with None
DEBUG: open(): Connecting to uri ldapi://%2Fdata%2Frun%2Fslapd-localhost.socket
DEBUG: Using dirsrv ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using external ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using /etc/openldap/ldap.conf certificate policy
DEBUG: ldap.OPT_X_TLS_REQUIRE_CERT = 2
DEBUG: open(): Using root autobind ...
DEBUG: Instance LDAPI not functional (yet?)       <-----
ERROR: 389-ds-container failed to start
INFO: STOPPING: Sent SIGTERM to ns-slapd ...
INFO: STOPPING: Shutting down 389-ds-container ...
INFO: STOPPED: Shut down 389-ds-container
```

Could you please show exactly what you have patched? 
Thanks.

**Comment by ecureuil** [comment]
The exception is hidden in your log message.
My workaround:
def begin_healthcheck(ds_proc):
        # We skip the pid check if ds_proc is none because that means it's coming from the
        # container healthcheck.
        if ds_proc is not None and ds_proc.poll() is not None:
            # Ruh-Roh
            log.warning("ns-slapd pid has completed, you should check the error log ...")
            return (False, False)
        # Now do an ldapi check, make sure we are dm.
        try:
            inst = _gen_instance()
            inst.open()
            if "dn: cn=Directory Manager" == inst.whoami_s():
                return (False, True)
            else:
                log.error("The instance may be misconfigured, unable to cn=Directory Manager autobind.")
                return (False, False)
        except:
            **logging.exception("Instance LDAPI not functional (yet?)")**
            log.debug("Instance LDAPI not functional (yet?)")
            pass
        return (True, False)

**Comment by vashirov** [comment]
Ah, so you're interested in the actual traceback?
A problem with this approach is that it will print traceback on each try to connect to ldapi socket during the startup, which will pollute the logs. I think instead we can improve the error message in https://github.com/389ds/389-ds-base/blob/6cac256b28ef587770fcb89fd797a19ccb36e28f/src/lib389/cli/dscontainer#L334-L348 to say that the timeout was reached and connection over ldapi was not successful. Will that work for you?

**Comment by vashirov** [comment]
Something like this:
```diff
diff --git a/src/lib389/cli/dscontainer b/src/lib389/cli/dscontainer
index 170aa08ce..8873f6d26 100755
--- a/src/lib389/cli/dscontainer
+++ b/src/lib389/cli/dscontainer
@@ -333,7 +333,8 @@ binddn = cn=Directory Manager
 
     # Wait on the health check to show we are ready for ldapi.
     healthy = False
-    max_failure_count = 20
+    startup_timeout = os.getenv("DS_STARTUP_TIMEOUT", 60)
+    max_failure_count = int(startup_timeout / 3)
     for i in range(0, max_failure_count):
         if ds_proc is None:
             log.warning("ns-slapd pid has disappeared ...")
@@ -344,6 +345,8 @@ binddn = cn=Directory Manager
         time.sleep(3)
         # Check again then ....
     if not healthy:
+        log.error(f"Timeout of {startup_timeout} seconds was reached")
+        log.error("Couldn't connect via LDAPI socket")
         log.error("389-ds-container failed to start")
         sys.exit(1)
 

```

```
INFO: Starting 389-ds-container ...
DEBUG: Allocate local instance <class 'lib389.DirSrv'> with None
DEBUG: open(): Connecting to uri ldapi://%2Fdata%2Frun%2Fslapd-localhost.socket
DEBUG: Using dirsrv ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using external ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using /etc/openldap/ldap.conf certificate policy
DEBUG: ldap.OPT_X_TLS_REQUIRE_CERT = 2
DEBUG: open(): Using root autobind ...
DEBUG: Instance LDAPI not functional (yet?)
DEBUG: Allocate local instance <class 'lib389.DirSrv'> with None
DEBUG: open(): Connecting to uri ldapi://%2Fdata%2Frun%2Fslapd-localhost.socket
DEBUG: Using dirsrv ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using external ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using /etc/openldap/ldap.conf certificate policy
DEBUG: ldap.OPT_X_TLS_REQUIRE_CERT = 2
DEBUG: open(): Using root autobind ...
DEBUG: Instance LDAPI not functional (yet?)
DEBUG: Allocate local instance <class 'lib389.DirSrv'> with None
DEBUG: open(): Connecting to uri ldapi://%2Fdata%2Frun%2Fslapd-localhost.socket
DEBUG: Using dirsrv ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using external ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using /etc/openldap/ldap.conf certificate policy
DEBUG: ldap.OPT_X_TLS_REQUIRE_CERT = 2
DEBUG: open(): Using root autobind ...
DEBUG: Instance LDAPI not functional (yet?)
ERROR: Timeout of 60 seconds was reached
ERROR: Couldn't connect via LDAPI socket
ERROR: 389-ds-container failed to start
```

**Comment by ecureuil** [comment]
To avoid to pollute the log messages, we could add a param to indicate when to log the exception:
```python
def begin_healthcheck(ds_proc, log_exception):
        # We skip the pid check if ds_proc is none because that means it's coming from the
        # container healthcheck.
        if ds_proc is not None and ds_proc.poll() is not None:
            # Ruh-Roh
            log.warning("ns-slapd pid has completed, you should check the error log ...")
            return (False, False)
        # Now do an ldapi check, make sure we are dm.
        try:
            inst = _gen_instance()
            inst.open()
            if "dn: cn=Directory Manager" == inst.whoami_s():
                return (False, True)
            else:
                log.error("The instance may be misconfigured, unable to cn=Directory Manager autobind.")
                return (False, False)
        except:
            if log_exception:
                logging.exception("Instance LDAPI not functional (yet?)")
            else:
                log.debug("Instance LDAPI not functional (yet?)")
            pass
        return (True, False)
```

And we can use the var check_again to indicate to log or not the exception:

```python
(check_again, healthy) = begin_healthcheck(ds_proc, !check_again)
```

**Comment by Firstyear** [comment]
That all sounds reasonable to me?

**Comment by vashirov** [comment]
Yes, that looks good to me too. I filed a PR https://github.com/389ds/389-ds-base/pull/4941
