### ISSUE TITLE
Redesign LMDB Import

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#4939]
**Issue Description**
dirsrvtests/tests/suites/import/regression_test.py::test_large_ldif2db_ancestorid_index_creation shows a strange behavior on lmdb:
 map size grows a bit more than 32 Gb while importing a 150 Mb ldif file containing 130 K entries

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: [e.g. 389-ds-base-1.4.4.4-20200721git5d41dc5a4.fc32.x86_64]

**Steps to Reproduce**
1. cd dirsrvtests/tests/suites/import
2. pytest $PWD -k test_large_ldif2db_ancestorid_index_creation

**Expected results**
A more reasonable map size should be enough

**Comment by Firstyear** [comment]
Have you looked at which tables in the map have this growth? It seems very odd ...

**Comment by progier389** [comment]
it is hard to get that data:
The painful thing is that the mdb_stat() function requires a txn and I am not sure to get the data about pages alloced in other active txns
Should maybe log the statistics of all dbis just before aborting/commiting a r/w txn 
Another point is that the page consumption is transient: 
 The total used page statistics once the import was finished seems normal (and below 1GB) 

In fact I suspect that it is a case where the btree need very often to be rebalanced and an open read txn prevent to reuse the free pages ( If that is the case the whole import should be done in a single foreman thread ) with a single write txn that is commited then reopen after a given number of operations (or entries)  a bit like reindex works.

**Comment by Firstyear** [comment]
That would certainly cause it. Internally LMDB uses a hazard-pointer style table with txn ages, and it can't clear old transaction nodes until the oldest txns are released. 

Additionally *internal* transactions to a write would also cause this because it can't collapse all the txns until the end. So that would also cause a huge amount of tree growth as it can't free down til the final outer commit.
