### ISSUE TITLE
Automember allows invalid regex, and does not log proper error

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4956]
**Issue Description**

When logging an error message about invalid Auto Member rules, it would be useful to add also the name of the rule and the invalid regular expression.

Steps to Reproduce:
1. Add an invalid regex to a rule:   cn=*value*
2. Check in the LDAP errors log. The related message doesn't contain the actual invalid regex:
 
[15/Oct/2021:21:44:12.657912921 +0200] - ERR - auto-membership-plugin - automember_parse_regex_rule - Unable to parse regex rule (invalid regex).  Error "nothing to repeat".

The problem is that don't bail when an invalid regex is parsed:

```
diff --git a/ldap/servers/plugins/automember/automember.c b/ldap/servers/plugins/automember/automember.c
index 39350ad53..b92b89bd5 100644
--- a/ldap/servers/plugins/automember/automember.c
+++ b/ldap/servers/plugins/automember/automember.c
@@ -1217,6 +1217,7 @@ automember_parse_regex_rule(char *rule_string)
                       "automember_parse_regex_rule - Unable to parse "
                       "regex rule (invalid regex).  Error \"%s\".\n",
                       recomp_result ? recomp_result : "unknown");
+        goto bail;
     }
 
     /* Validation has passed, so create the regex rule struct and fill it in.
```

**Comment by tbordaz** [comment]
169987290..7eca61ace  389-ds-base-1.3.10
