### ISSUE TITLE
Invalid /etc/hosts setup can cause isLocalHost to fail. 

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#4959]
```
DEBUG: no ip address for b'susetest'
DEBUG: Allocate <class 'lib389.DirSrv'> with b'susetest':636
DEBUG: Allocate <class 'lib389.DirSrv'> with b'susetest':636
DEBUG: Instance allocated
DEBUG: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/sbin/dsctl", line 142, in <module>
    result = args.func(inst, log, args)
  File "/usr/lib/python3.8/site-packages/lib389/cli_ctl/instance.py", line 55, in instance_status
    if inst.status() is True:
  File "/usr/lib/python3.8/site-packages/lib389/__init__.py", line 1185, in status
    if self.with_systemd():
  File "/usr/lib/python3.8/site-packages/lib389/__init__.py", line 1678, in with_systemd
    return self.ds_paths.with_systemd
  File "/usr/lib/python3.8/site-packages/lib389/paths.py", line 221, in __getattr__
    return ensure_str(self._config.get(SECTION, name).format(instance_name=self._serverid))
AttributeError: 'NoneType' object has no attribute 'get'
ERROR: Error: 'NoneType' object has no attribute 'get'

```

This was found in the suse openqa environment, which appears to have a very odd method to setup the hostname where the hostname is never set into /etc/hosts. I think we can't fully defend from a broken setup like this, but we also shouldn't raise an exception like this.

**Comment by vashirov** [comment]
We have a Fedora bugzilla open with a similar issue: https://bugzilla.redhat.com/show_bug.cgi?id=2018812

Even with the PR #4960 applied, instance locality check [fails](https://bugzilla.redhat.com/show_bug.cgi?id=2018812#c11), because there is only AAAA DNS record (nothing in /etc/hosts), but we check only for IPv4 addresses:
https://github.com/389ds/389-ds-base/blob/0552081fe736b5c86d3c7e3d640f8a8b170d1dc6/src/lib389/lib389/utils.py#L673-L681

It's not possible to stop such instance:
```
# dsctl localhost stop 
This is a remote instance!
Press Enter when the instance has stopped ...
```
or even remove it:
```
Failed to remove slapd-localhost - Error: 'NoneType' object has no attribute 'get'
```

Furthermore, there is a case during automated provision, when there is DNS record created, but not available yet, but the DS instance is created.

**Comment by Firstyear** [comment]
Well, even if there was a AAAA record, say ... foo.example.com AAAA 2001:db8::100, that's not going to detect as localhost anyway, because we don't lookup if arbitrary addresses are defined. So I think thats a case of fixing /etc/hosts to map correctly to localhost.

**Comment by spike77453** [comment]
> Even with the PR #4960 applied, instance locality check [fails](https://bugzilla.redhat.com/show_bug.cgi?id=2018812#c11), because there is only AAAA DNS record (nothing in /etc/hosts), but we check only for IPv4 addresses:

This might be a bit misleading. To clarify: the `/etc/hosts` file I'm using when seeing this error is the default one set by the OS (Fedora 35 in this case):

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

So `localhost` is (correctly) resolved to `::1`. The only other addresses present though are a public routable IPv6 address and an IPv6 link local address.

> Well, even if there was a AAAA record, say ... foo.example.com AAAA 2001:db8::100, that's not going to detect as localhost anyway, because we don't lookup if arbitrary addresses are defined. So I think thats a case of fixing /etc/hosts to map correctly to localhost.

How would you suggest a 'fixed' `/etc/hosts` file would look like in this case?

To add more potential confusion, `localhost` is also the instance name in the example above. So

```
# dsctl localhost stop 
This is a remote instance!
Press Enter when the instance has stopped ...
```

is really

```
# dsctl <instancename> stop 
This is a remote instance!
Press Enter when the instance has stopped ...
```

and a removal attempt results in 

```
Failed to remove slapd-<instancename> - Error: 'NoneType' object has no attribute 'get'
```

**Comment by Firstyear** [comment]
Now I'm even more confused why this is failing then ... we should be listing the local instances with dsctl which bypasses some of this, but yes, it shouldn't be dynamic, it should be using remote-allocate and local-allocate.

**Comment by spike77453** [comment]
> Now I'm even more confused why this is failing then ...

Here's one problem: https://github.com/389ds/389-ds-base/blob/master/src/lib389/lib389/__init__.py#L559
That compares a byte object to a string. So even if `self.ldapi_enabled` is `b'on'`, `self.ldapi_enabled == 'on'` will be `False` (which is the case in the example provided above)

**Comment by Firstyear** [comment]
I think also @droideck is putting in a PR to correctly use the local allocate anyway, so that should resolve this anyway :)

**Comment by spike77453** [comment]
> I think also @droideck is putting in a PR to correctly use the local allocate anyway, so that should resolve this anyway :)

So you'd suggest leaving this as is?

**Comment by Firstyear** [comment]
It's still a good idea to fix it :)

**Comment by mreynolds389** [comment]
8a2b4c7d5..172dd04e0  389-ds-base-2.0 -> 389-ds-base-2.0
9658e9367..08da0c0d4  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
e7bc3b530..c600ddcab  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by spike77453** [comment]
> It's still a good idea to fix it :)

I've submitted a fix here: https://github.com/389ds/389-ds-base/pull/5003
Maybe it's a good idea to leave this opened until the root cause of this is fixed?
