### ISSUE TITLE
Fix various UI bugs

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4962]
**Issue Description**

During testing of cockpit-389-ds-2.0.10 several bugs have been found.  We can use this ticket for all those bugs fixes

**Comment by droideck** [comment]
c30ebb570..769e591bf  389-ds-base-2.0 -> 389-ds-base-2.0
  18ee387c7..cb8341d90  389-ds-base-1.4.4 -> 389-ds-base-1.4.4

**Comment by droideck** [comment]
33c85c560..f53793d37  389-ds-base-2.0 -> 389-ds-base-2.0
   2499a379d..78b5bc996  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
