### ISSUE TITLE
Replication promotion/demotion is fragile

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4971]
**Issue Description**

When demoting a supplier/hub to consumer can leave things is an odd state with the replication agreements and changelog.

Some of this can be seen here https://github.com/389ds/389-ds-base/issues/4731

But there is still work needed around agreements (disable or delete them?), and checking for changelog existence can probably be improved.

**Comment by jchapma** [comment]
https://github.com/389ds/389-ds-base/issues/4731#issuecomment-953163057

**Comment by mreynolds389** [comment]
Not sure what other issues there are.  Seems to be working now.  Closing until new issues arise.
