### ISSUE TITLE
Failure in suites/import/import_test.py::test_fast_slow_import

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#4976]
**Issue Description**
I noticed that `test_fast_slow_import` started to fail recently. I narrowed it down to the following conditions:
```
nsslapd-import-cache-autosize: -1
nsslapd-db-private-import-mem: off
```

More specifically, with `nsslapd-import-cache-autosize: 0` the import is fast:
```
[root@server ds]# time /usr/sbin/ns-slapd ldif2db -D /etc/dirsrv/slapd-standalone1 -i /var/lib/dirsrv/slapd-standalone1/ldif/basic_import.ldif -n userroot 

real    0m1.561s
user    0m0.493s
sys     0m0.072s

```
With `nsslapd-import-cache-autosize: -1` it's a bit slower:
```
[root@server ds]# time /usr/sbin/ns-slapd ldif2db -D /etc/dirsrv/slapd-standalone1 -i /var/lib/dirsrv/slapd-standalone1/ldif/basic_import.ldif -n userroot 

real    0m7.961s
user    0m2.111s
sys     0m3.872s
```

However, the errors log reports that the actual import duration was shorter:
```
[01/Nov/2021:20:38:33.943914942 +0000] - INFO - bdb_import_main - import userRoot: Import complete.  Processed 1008 entries in 2 seconds. (504.00 entries/sec)
```

So the rest of the time ns-slapd spends doing something else, but the test measures the execution time of ldif2db as a whole.

Moreover, situation got worse with the update to libdb-5.3.28-49.fc34.x86_64 (from -46) which has a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1992402:
```
[root@server ds]# time /usr/sbin/ns-slapd ldif2db -D /etc/dirsrv/slapd-standalone1 -i /var/lib/dirsrv/slapd-standalone1/ldif/basic_import.ldif -n userroot 

real    1m49.112s
user    0m7.478s
sys     1m1.501s
```

In the errors log:
```
[01/Nov/2021:20:53:14.190347495 +0000] - INFO - bdb_import_main - import userRoot: Import complete.  Processed 1008 entries in 16 seconds. (63.00 entries/sec)
```

I will open a bug for libdb, but we should also investigate why there is such big difference with `nsslapd-import-cache-autosize: -1` and `nsslapd-db-private-import-mem: off` vs. `nsslapd-db-private-import-mem: on`.

**Comment by tbordaz** [comment]
@vashirov, https://bugzilla.redhat.com/show_bug.cgi?id=1992402 is definitely looking as a killer for us. 

Regarding nsslapd-import-cache-autosize: -1 and nsslapd-db-private-import-mem: off being slower vs autosize=0 and nsslapd-db-private-import-mem: on.
A possibility is that autosize=-1 => memory region will be much larger (50% memory) than configured dbcache, that may put memory pressure (mmap) and filesystem pressure (dbenv being much larger).

**Comment by vashirov** [comment]
a123c215c..b0e890bf6  389-ds-base-2.0 -> 389-ds-base-2.0
