### ISSUE TITLE
Fix next round of UI bugs

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5001]
**Issue Description**

Addressing a series of bugs found by QE:

Bug 2016526 - LDAPI & Autobind save btn misbehaving
Bug 2016481 - Disabling Security leaves the pop-up window open
Bug 2016026 - Selecting existing certificate in Security Configuration crashes browser
Bug 2017402 - Adding several allowed SASL mechanisms does not behave correctly
Bug 2017411 - cockpit crashes because invalid SASL mapping regex was saved
Bug 2022117 - Cockpit UI: Editing an Objectclass name causes an error in Cockpit UI
Bug 2021194 - Searching "matching rules" in the "Schema" Tab crashes browser
Bug 2021591 - cockpit : audit and audit failure log enablement status is not persistent

**Comment by mreynolds389** [comment]
f53793d37..8a2b4c7d5  389-ds-base-2.0 -> 389-ds-base-2.0
78b5bc996..9658e9367  389-ds-base-1.4.4 -> 389-ds-base-1.4.4

**Comment by mreynolds389** [comment]
18a127491..a033e0269  389-ds-base-2.0 -> 389-ds-base-2.0
151ac7efb..b633f727b  389-ds-base-1.4.4 -> 389-ds-base-1.4.4

**Comment by droideck** [comment]
5ba2b8b21..706d95fa1  389-ds-base-2.0 -> 389-ds-base-2.0
   8bff82793..adc2478d0  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
