### ISSUE TITLE
Missing dsctl tls export-ca nickname filename sub command.

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5010]
For topology using self signed certificates,  (and especially for test setup) it is important to be able to export the server CA certificate
 (to import it on client application or on other slapd instance )
It can be done with certutil -L -d  ... -n nickname -a > filename
but there is no way to do that with dsctl. 

We should had a subcommand :  dsctl instance tls export-ca nickname filename 
  (quite similar to the show subcommand except that certutil  has -a option and output redirected to filename )

**Comment by mreynolds389** [comment]
Fixed in ticket: 

https://github.com/389ds/389-ds-base/issues/5624
