### ISSUE TITLE
windows sync can cause SIGSEGV when replica is configured as hub or consumer.

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#5024]
After 1.4.3, the changelog moves into the main database rather than being a seperate entity. This caused a situation where it was possible to create and configure a changelog while also acting as a read-only replica. This allows individuals to create a windows sync agreement, however during the upgrade to 1.4.4 where we move the changelog into the main DB, I can only assume we either delete or ignore the CL if the replica is readonly.

As a result, this caused a situation where the replica information and agreement existed, but the changelog did not. During startup as the agreement was processed, an attempt to open the CL was made, but caused a NULL pointer dereference which prevented server startup. 

This is currently blocking and affecting a SUSE customer so I would appreciate a quick review so we can send a hotfix.

**Comment by abbra** [comment]
This fix broke FreeIPA and an issue is reported as https://github.com/389ds/389-ds-base/issues/5079

**Comment by Firstyear** [comment]
I have a fix but I'm not working until early next year.

**Comment by abbra** [comment]
Thank you, this can wait next year. Happy holidays!

**Comment by Firstyear** [comment]
@abbra https://github.com/389ds/389-ds-base/pull/5087

**Comment by mreynolds389** [comment]
@Firstyear FYI your commit to 1.4.3 did not apply cleanly and you pushed a change with merge errors in it:  https://github.com/389ds/389-ds-base/commit/e6068c07ac2769cb3da191169502ae58489a1ad4

I'm fixing it now...

**Comment by Firstyear** [comment]
@mreynolds389 So sorry, thanks for this. Currently stressing about an unrelated issue here ....

**Comment by mreynolds389** [comment]
> @mreynolds389 So sorry, thanks for this. Currently stressing about an unrelated issue here ....

Not trying to add stress mate :-)  But had to let you know about the minor slip up.
