### ISSUE TITLE
CN for Root CA of Self Signed Certificates is hard coded to ssca.389ds.example.com

### ISSUE THREAD

**Issue by captainfalcon23** [389ds/389-ds-base#5058]
In file https://github.com/389ds/389-ds-base/blob/master/src/lib389/lib389/nss_ssl.py, the ISSUER is hard coded to ssca.389ds.example.com. This means, if we set up two servers using self signed certificates generated by dscreate, when we import the Root CA's into the other server, the wrong Root CA is used to validate the server certificate as the names match and it confuses NSS. The easiest thing would be to make ISSUER a value which can be provided by the user in input file or interactive mode, and this issue would be resolved, as both servers would have a completely unique Root CA. Alternatively, add a random identifier (e.g. the server name) to ISSUER variable.

I spent alot of time tinkering with the certs and finally identified this issue. After updating the above file, rerun install, import Root CA's and configure replication, it all worked fine.

**Comment by Firstyear** [comment]
@captainfalcon23 Our goal with the ssca code was to have something reliable for test cases, and a initial "getting started", not so much a production ready CA that could be used. @droideck What do you think about this?

**Comment by msauton** [comment]
I had this article for this issue ( need login)
https://access.redhat.com/solutions/6449561
How To test LDAPS with RHDS instances on 2 systems and default test CA

in PKI when issuers are independent, the idea is to cross trust each CA on each other system.
use the RHEL trust command to add the issuers and trust them on the system.
like on m1:
trust anchor ~/m2.ca.crt
and on m2:
trust anchor ~/m1.ca.crt

then verify
trust list | grep "test|Self-Signed-CA"

and test

**Comment by captainfalcon23** [comment]
> I had this article for this issue ( need login) https://access.redhat.com/solutions/6449561 How To test LDAPS with RHDS instances on 2 systems and default test CA
> 
> in PKI when issuers are independent, the idea is to cross trust each CA on each other system. use the RHEL trust command to add the issuers and trust them on the system. like on m1: trust anchor ~/m2.ca.crt and on m2: trust anchor ~/m1.ca.crt
> 
> then verify trust list | grep "test|Self-Signed-CA"
> 
> and test

Yep, I tried this originally, but the issue is both the Root CA's have the same name, and this confuses NSS as after you import server B's Root CA into server A, it breaks the relationship with Server A Server Cert and Server A Root CA.

Anyways, if each CA had a unique name, this issue would go away.

**Comment by Firstyear** [comment]
@captainfalcon23 The ssca isn't meant for production usage. It's meant to give you quick access to TLS for demonstration and easy setup. If you are doing this in production, you need to remove the ssca and use a different CA/Cert setup.

**Comment by captainfalcon23** [comment]
> @captainfalcon23 The ssca isn't meant for production usage. It's meant to give you quick access to TLS for demonstration and easy setup. If you are doing this in production, you need to remove the ssca and use a different CA/Cert setup.

Hey @Firstyear, yeah just for a lab environment or to showcase replication I think it would be good to expose this as a var/assign a random value. Definately not saying to use it for production. :)

**Comment by Firstyear** [comment]
I think it's waayyyyy too many layers deep in the setup to really be worth wiring it in to an env variable, when you can just delete the ca and add a new one for those cases :(

**Comment by captainfalcon23** [comment]
Ahh all good. FYI (and for anyone coming here via google), this is how I fixed it for my testing:

sed -i "s/ISSUER = 'CN=ssca.389ds.example.com,%s' % CERT_SUFFIX/ISSUER = 'CN=ldap01-ca.ssg.int,%s' % CERT_SUFFIX/g" /usr/lib/python3.6/site-packages/lib389/nss_ssl.py
