### ISSUE TITLE
RFC 3928 Support

### ISSUE THREAD

**Issue by mmoser-aires** [389ds/389-ds-base#5068]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like** 
If possible, add RFC 3928 support to 389 DS.

**Describe alternatives you've considered**
None are possible to my knowledge.

**Additional context**
I used to be a DNS administrator who ran PowerDNS. With the 4.0 version of the Authoritative server, the LDAP backend was made available. Due to the absence of RFC3928 features in OSS LDAP servers (At least 389 DS & OpenLDAP), PowerDNS cannot be configured as a slave server:

>**DNS notification support**
As soon as the LDAP server implementations begin to provide the features of the LDAP client update protocol (LCUP, RFC 3928), it will be possible to support the DNS notification feature for the LDAP DNS backend in case a record in the LDAP directory was changed.

[Reference](https://doc.powerdns.com/authoritative/backends/ldap.html#future).

I'm hopeful that if reasonably possible, LCUP support could be added to 389-DS so that such features can be implemented on PowerDNS, and would assume other applications/uses would stand to benefit.

**Comment by Firstyear** [comment]
It's really not a trivial feature. Reading the RFC, this is a more advanced form of syncrepl (which we do currently support). It appears neither openldap or 389-ds support this, and I think it would be a lot of work for what is really, a relatively niche use case. 

I'd suggest you look if syncrepl or persistent search are viable for powerdns instead as these already exist today.

**Comment by Mose-** [comment]
I'll see if I can get information on that, my knowledge of LDAP is not that deep to know all of the caveats, demand, pros/cons, etc. I really like the idea of using LDAP backends for as much as possible.

**Comment by Firstyear** [comment]
I don't think any ldap server supports this rfc. It looks like it's dead since it's existed since 2004 with no implementors. Even on the openldap mailing list they call it "dead".

https://www.openldap.org/lists/openldap-software/200907/msg00026.html

**Comment by Mose-** [comment]
I think the only DS server that I've ever seen list it as supported is Apache DS, and I've not looked at that in some time.
