### ISSUE TITLE
"dscontainer -r" creates a socket file /data/run/slapd.socket while it should be /data/run/slapd-localhost.socket

### ISSUE THREAD

**Issue by ecureuil** [389ds/389-ds-base#5073]
**Issue Description**
I have created an image based on ubi 8.5 with the tagged version 389-ds-base-1.4.4.18.
slapd starts but in this version the last log is:
[20/Dec/2021:11:08:45.724451062 +0100] - INFO - slapd_daemon - Listening on /data/run/slapd.socket for LDAPI requests

This is very strange since in the generated container.inf file, I have:
```
[root@directory-5d8d9c9f78-77ng4 389-ds-base]# cat /data/config/container.inf

[localhost]
# Note that '/' is replaced to '%%2f' for ldapi url format.
# So this is pointing to /data/run/slapd-localhost.socket
uri = ldapi://%%2fdata%%2frun%%2fslapd-localhost.socket
binddn = cn=Directory Manager
```

In the directory containing the socket file:
```
[root@directory-5d8d9c9f78-77ng4 389-ds-base]# ls /data/run/
dbhome  lock  slapd-localhost.stats  slapd.socket
```

It results that every accesses with "dsctl localhost" fails with "No such file or directory" since slapd-localhost.socket is missing.

In the version 389-ds-base-1.4.4.17, I have no issue since  slapd-localhost.socket is created and not slapd.socket

**Package Version and Platform:**
 - Platform: RHEL 8.5
 - Package and version: 389-ds-base-1.4.4.18
 - Browser N/A

**Steps to Reproduce**
1. Create an image on ubi 8.5 with the tagged version 389-ds-base-1.4.4.18, with a Dockerfile finishing by `CMD [ "/usr/libexec/dirsrv/dscontainer", "-r" ]`.
2. Create a container for this image
3. Run dsctl localhost healthcheck
4. Observe the log:
`Error: Failed to connect to Directory Server instance: {'result': -1, 'desc': "Can't contact LDAP server", 'errno': 2, 'ctrls': [], 'info': 'No such file or directory'}`

**Expected results**
dsctl localhost shall connect to the instance localhost.

**Comment by Firstyear** [comment]
Where did you get this image from? You built it yourself? 

A lot of the container work/investment is in the 2.x branch rather than 1.4.x so if you are building this yourself, consider using 2.x instead.

Otherwise, can you try with 389ds/dirsrv:2.0 ? 

> On 20 Dec 2021, at 21:30, ecureuil ***@***.***> wrote:
> 
> 
> Issue Description
> I have created an image based on ubi 8.5 with the tagged version 389-ds-base-1.4.4.18.
> splapd starts but in this version the last log is:
> [20/Dec/2021:11:08:45.724451062 +0100] - INFO - slapd_daemon - Listening on /data/run/slapd.socket for LDAPI requests
> 
> This is very strange since in the generated container.inf file, I have:
> 
> ***@***.*** 389-ds-base]# cat /data/config/container.inf
> 
> [localhost]
> # Note that '/' is replaced to '%%2f' for ldapi url format.
> # So this is pointing to /data/run/slapd-localhost.socket
> uri = ldapi://%%2fdata%%2frun%%2fslapd-localhost.socket
> binddn = cn=Directory Manager
> 
> In the directory containing the socket file:
> 
> ***@***.*** 389-ds-base]# ls /data/run/
> dbhome  lock  slapd-localhost.stats  slapd.socket
> 
> It results that every accesses with "dsctl localhost" fails with "No such file or directory" since slapd-localhost.socket is missing.
> 
> In the version 389-ds-base-1.4.4.17, I have no issue since slapd-localhost.socket is created and not slapd.socket
> 
> Package Version and Platform:
> 
> 	• Platform: RHEL 8.5
> 	• Package and version: 389-ds-base-1.4.4.18
> 	• Browser N/A
> Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 	• Create an image on ubi 8.5 with the tagged version 389-ds-base-1.4.4.18, with a Dockerfile finishing by CMD [ "/usr/libexec/dirsrv/dscontainer", "-r" ].
> 	• Create a container for this image
> 	• Run dsctl localhost healthcheck
> 	• Observe the log:
> Error: Failed to connect to Directory Server instance: {'result': -1, 'desc': "Can't contact LDAP server", 'errno': 2, 'ctrls': [], 'info': 'No such file or directory'}
> Expected results
> dsctl localhost shall connect to the instance localhost.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you are subscribed to this thread.
> 

--
Sincerely,

William Brown

Senior Software Engineer, Identity and Access Management
SUSE Labs, Australia

**Comment by ecureuil** [comment]
Thank you for your response, yes I have defined the Dockerfile to build the image.
So i have tried with the HEAD of 2.0 and unfortunately I have the same issue.

**Comment by Firstyear** [comment]
> On 21 Dec 2021, at 21:00, ecureuil ***@***.***> wrote:
> 
> 
> Thank you for your response, yes I have defined the Dockerfile to build the image.
> So i have tried with the HEAD of 2.0 and unfortunately I have the same issue.


DEBUG: Allocate local instance <class 'lib389.DirSrv'> with None
DEBUG: open(): Connecting to uri ldapi://%2Fdata%2Frun%2Fslapd-localhost.socket
DEBUG: Using dirsrv ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using external ca certificate /etc/dirsrv/slapd-localhost
DEBUG: Using /etc/openldap/ldap.conf certificate policy
DEBUG: ldap.OPT_X_TLS_REQUIRE_CERT = 2
DEBUG: open(): Using root autobind ...
DEBUG: open(): bound as cn=Directory Manager
DEBUG: Retrieving entry with [('',)]
DEBUG: Retrieved entry [dn:
vendorVersion: 389-Directory/2.0.10 B2021.285.0000

]
INFO: Applying environment configuration (if present) ...
DEBUG: Allocate local instance <class 'lib389.DirSrv'> with None
DEBUG: open(): Connecting to uri ldapi://%2Fdata%2Frun%2Fslapd-localhost.socket
DEBUG: Using dirsrv ca certificate /etc/dirsrv/slapd-localhost



I'm not seeing the same behaviour? It's working here. So something else is going on that I'd like to know more about. 

Can you send me your Dockerfile and what command you are running docker with exactly so I can try to reproduce? 




> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you commented.
> 

--
Sincerely,

William Brown

Senior Software Engineer, Identity and Access Management
SUSE Labs, Australia

**Comment by ecureuil** [comment]
Thank you for your response.

The image is built with Jenkins through a Jenkinsfile, but basically it checkouts 389s from branch 389-ds-base-2.0.11 and triggers an image build by using the following Dockerfile (NB: in the Docker the current directory (.) is the local clone of 389ds repo and the yum.repo.d stuff is used for adding our mirror servers):

```
ARG BASE_IMAGE_NAME=registry.access.redhat.com/ubi8
ARG BASE_IMAGE_VERSION=8.5

FROM ${BASE_IMAGE_NAME}:${BASE_IMAGE_VERSION}
EXPOSE 389 636

COPY ./yum.repos.d/* /etc/yum.repos.d/

ADD ./ /usr/local/src/389-ds-base
WORKDIR /usr/local/src/389-ds-base

ENV SKIP_AUDIT_CI="true"

# install dependencies
RUN dnf -y module enable 389-ds
RUN dnf upgrade -y \
  && dnf install --setopt=strict=False -y rpm-build make bzip2 git rsync \
  `grep -E "^(Build)?Requires" rpm/389-ds-base.spec.in \
  | grep -v -E '(name|MODULE)' \
  | awk '{ print $2 }' \
  | sed 's/%{python3_pkgversion}/3/g' \
  | grep -v "^/" \
  | grep -v pkgversion \
  | sort | uniq \
  | tr '\n' ' '` \
  && dnf clean all

# build
RUN make -f rpm.mk update-cargo-dependencies download-cargo-dependencies rpms

RUN dnf install -y dist/rpms/*389*.rpm && \
    dnf clean all

RUN rm -rf /usr/local/src/389-ds-base

# Link some known static locations to point to /data
RUN mkdir -p /data/config && \
  mkdir -p /data/ssca && \
  mkdir -p /data/run && \
  mkdir -p /var/run/dirsrv && \
  ln -s /data/config /etc/dirsrv/slapd-localhost && \
  ln -s /data/ssca /etc/dirsrv/ssca && \
  ln -s /data/run /var/run/dirsrv

VOLUME /data

HEALTHCHECK --start-period=5m --timeout=5s --interval=5s --retries=2 \
  CMD /usr/libexec/dirsrv/dscontainer -H

CMD [ "/usr/libexec/dirsrv/dscontainer", "-r" ]
```

**Comment by vashirov** [comment]
I think a16831478f0aa88ffd7a527235dacf0a8cf3f916 is missing in 389-ds-base-1.4.4.18 and 389-ds-base-2.0.

**Comment by Firstyear** [comment]
@vashirov Good spot! I have cherry-picked that back now.

**Comment by Firstyear** [comment]
@ecureuil Can you try from git branch 389-ds-base-1.4.4 now?

**Comment by ecureuil** [comment]
Unfortunately the build now fails, but it is related to the Cargo/Rust stuff:
```
cargo update --manifest-path=./src/Cargo.toml
    Updating crates.io index
    Updating concread v0.2.20 -> v0.2.21
    Updating hermit-abi v0.1.20 -> v0.1.19
    Updating itoa v0.4.8 -> v1.0.1
    Updating libc v0.2.109 -> v0.2.112
    Updating lru v0.6.6 -> v0.7.2
    Updating once_cell v1.8.0 -> v1.9.0
    Updating openssl-sys v0.9.71 -> v0.9.72
    Updating pin-project-lite v0.2.7 -> v0.2.8
    Updating pkg-config v0.3.23 -> v0.3.24
    Updating ppv-lite86 v0.2.15 -> v0.2.16
    Updating proc-macro2 v1.0.33 -> v1.0.36
    Updating quote v1.0.10 -> v1.0.14
    Updating ryu v1.0.6 -> v1.0.9
    Updating serde v1.0.131 -> v1.0.133
    Updating serde_derive v1.0.131 -> v1.0.133
    Updating serde_json v1.0.72 -> v1.0.74
    Updating syn v1.0.82 -> v1.0.85
    Updating tokio v1.14.0 -> v1.15.0
    Updating tokio-macros v1.6.0 -> v1.7.0
    Updating version_check v0.9.3 -> v0.9.4
cargo update --manifest-path=./src/Cargo.toml
    Updating crates.io index
cargo vendor --manifest-path=./src/Cargo.toml
 Downloading crates ...
  Downloaded ahash v0.7.6
  Downloaded hermit-abi v0.1.19
  Downloaded bitflags v1.3.2
  Downloaded clap v2.34.0
  Downloaded autocfg v1.0.1
  Downloaded lock_api v0.4.5
  Downloaded crossbeam-utils v0.8.5
  Downloaded jobserver v0.1.24
  Downloaded crossbeam-channel v0.5.1
  Downloaded getrandom v0.2.3
  Downloaded crossbeam-queue v0.3.2
  Downloaded cc v1.0.72
  Downloaded foreign-types-shared v0.1.1
  Downloaded atty v0.2.14
  Downloaded log v0.4.14
  Downloaded hashbrown v0.11.2
  Downloaded crossbeam-epoch v0.9.5
  Downloaded memoffset v0.6.5
  Downloaded once_cell v1.9.0
  Downloaded lazy_static v1.4.0
  Downloaded cfg-if v1.0.0
  Downloaded byteorder v1.4.3
  Downloaded libc v0.2.112
  Downloaded foreign-types v0.3.2
  Downloaded crossbeam v0.8.1
  Downloaded fernet v0.1.4
  Downloaded openssl-sys v0.9.72
  Downloaded synstructure v0.12.6
  Downloaded strsim v0.8.0
  Downloaded unicode-width v0.1.9
  Downloaded rand v0.8.4
  Downloaded syn v1.0.85
  Downloaded tokio-macros v1.7.0
  Downloaded tokio v1.15.0
  Downloaded serde v1.0.133
  Downloaded vcpkg v0.2.15
  Downloaded toml v0.5.8
  Downloaded paste-impl v0.1.18
  Downloaded vec_map v0.8.2
  Downloaded proc-macro-hack v0.5.19
  Downloaded parking_lot_core v0.8.5
  Downloaded uuid v0.8.2
  Downloaded rand_hc v0.3.1
  Downloaded zeroize_derive v1.2.2
  Downloaded remove_dir_all v0.5.3
  Downloaded unicode-xid v0.2.2
  Downloaded serde_derive v1.0.133
  Downloaded zeroize v1.4.3
  Downloaded version_check v0.9.4
  Downloaded crossbeam-deque v0.8.1
  Downloaded wasi v0.10.2+wasi-snapshot-preview1
  Downloaded pin-project-lite v0.2.8
  Downloaded winapi-i686-pc-windows-gnu v0.4.0
  Downloaded redox_syscall v0.2.10
  Downloaded rand_chacha v0.3.1
  Downloaded ppv-lite86 v0.2.16
  Downloaded tempfile v3.2.0
  Downloaded serde_json v1.0.74
  Downloaded winapi-x86_64-pc-windows-gnu v0.4.0
  Downloaded winapi v0.3.9
  Downloaded parking_lot v0.11.2
  Downloaded textwrap v0.11.0
  Downloaded paste v0.1.18
  Downloaded quote v1.0.14
  Downloaded proc-macro2 v1.0.36
  Downloaded openssl v0.10.38
  Downloaded smallvec v1.7.0
  Downloaded rand_core v0.6.3
  Downloaded scopeguard v1.1.0
  Downloaded pkg-config v0.3.24
  Downloaded ryu v1.0.9
  Downloaded lru v0.7.2
  Downloaded concread v0.2.21
error: failed to sync

Caused by:
  failed to download packages

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/concread-0.2.21/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature
make: *** [rpm.mk:43: download-cargo-dependencies] Error 101 
```

**Comment by vashirov** [comment]
@ecureuil, looks like concread requires rust-1.56+ to build, but it's not available in RHEL-8.5 yet, only in RHEL-8.6.
For now, as a workaround, try to downgrade it:
```diff
diff --git a/src/librslapd/Cargo.toml b/src/librslapd/Cargo.toml
index 15c00a47b..cf1246306 100644
--- a/src/librslapd/Cargo.toml
+++ b/src/librslapd/Cargo.toml
@@ -15,7 +15,7 @@ crate-type = ["staticlib", "lib"]
 [dependencies]
 slapd = { path = "../slapd" }
 libc = "0.2"
-concread =  "^0.2.20"
+concread =  "=0.2.20"
 
 [build-dependencies]
 cbindgen = "0.9"
```

@Firstyear, is 2021 edition necessary for concread? I tried to cargo build master with edition2018 and it succeeded.
This affects current RHEL-8.5 release and future z-stream releases for older RHEL versions where newer rust toolchain is not available. Or we should pin concread to edition2018 version?

**Comment by ecureuil** [comment]
Thank you for your response.
The build still fails with:
```
cd dist/sources ; \
if [ 1 -eq 1 ]; then \
	curl -LO https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2 ; \
fi
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   659  100   659    0     0   3581      0 --:--:-- --:--:-- --:--:--  3581

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  541k  100  541k    0     0  1250k      0 --:--:-- --:--:-- --:--:-- 12.0M
cp dist/sources/389-ds-base-1.4.4.18.tar.bz2 /usr/local/src/389-ds-base/rpmbuild/SOURCES/
cp rpm/389-ds-base-* /usr/local/src/389-ds-base/rpmbuild/SOURCES/
if [ 1 -eq 1 ]; then \
	cp dist/sources/jemalloc-5.2.1.tar.bz2 /usr/local/src/389-ds-base/rpmbuild/SOURCES/ ; \
fi
rpmbuild --define "_topdir /usr/local/src/389-ds-base/rpmbuild" -ba /usr/local/src/389-ds-base/rpmbuild/SPECS/389-ds-base.spec
error: Failed build dependencies:
	net-snmp-devel is needed by 389-ds-base-1.4.4.18-20220106.el8.x86_64
	nss-devel >= 3.34 is needed by 389-ds-base-1.4.4.18-20220106.el8.x86_64
	openssl-devel is needed by 389-ds-base-1.4.4.18-20220106.el8.x86_64
make: *** [rpm.mk:136: rpms] Error 1
```

**Comment by Firstyear** [comment]
> @ecureuil, looks like concread requires rust-1.56+ to build, but it's not available in RHEL-8.5 yet, only in RHEL-8.6. For now, as a workaround, try to downgrade it:
> 
> ```diff
> diff --git a/src/librslapd/Cargo.toml b/src/librslapd/Cargo.toml
> index 15c00a47b..cf1246306 100644
> --- a/src/librslapd/Cargo.toml
> +++ b/src/librslapd/Cargo.toml
> @@ -15,7 +15,7 @@ crate-type = ["staticlib", "lib"]
>  [dependencies]
>  slapd = { path = "../slapd" }
>  libc = "0.2"
> -concread =  "^0.2.20"
> +concread =  "=0.2.20"
>  
>  [build-dependencies]
>  cbindgen = "0.9"
> ```
> 
> @Firstyear, is 2021 edition necessary for concread? I tried to cargo build master with edition2018 and it succeeded. This affects current RHEL-8.5 release and future z-stream releases for older RHEL versions where newer rust toolchain is not available. Or we should pin concread to edition2018 version?

We probably need to pin it in this case. There will be other libraries that need edition upgrades. This for 1.4.4 or 2.0?

**Comment by vashirov** [comment]
This is for 1.4.3 and 1.4.4.

**Comment by ecureuil** [comment]
@Firstyear The fix works, thank you! Looking forward the tag 1.4.4.19 :)
