### ISSUE TITLE
Retro changelog plug-in cli needs to be updated

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#5074]
**Issue Description**
1) The cli does not allow for the creation of multiple exclude attributes in one call. 

2) When there are multiple exclude attributes defined, the cli doesn't allow removal of an individual exclude attribute. Using the set command deletes all excluded attributes.

**Package Version and Platform:**
 - Platform: Fedora 32
 - Package and version: 389-Directory/2.1.0

How reproducible:
Always.

**Steps to Reproduce**
1.1. Attempt to add multiple exclude attributes:
```
sudo dsconf -v  -D "cn=dm" inst01 plugin retro-changelog add --exclude-attrs test1 test2 test3
```
1.2. List the retrocl config, notice only the last exclude attribute has been added.
```
ldapsearch -LLL   -D 'cn=dm' -w password -b "cn=Retro Changelog Plugin,cn=plugins,cn=config"

...
nsslapd-pluginDescription: Retrocl Plugin
nsslapd-exclude-attrs: test3
```

2.1. Define multiple retrocl exclude attributes:
```
...
nsslapd-pluginDescription: Retrocl Plugin
nsslapd-exclude-attrs: test1
nsslapd-exclude-attrs: test2
nsslapd-exclude-attrs: test3
```
2.2. Attempt the removal of test3 exclude attribute:
```
sudo dsconf -v  -D "cn=dm" inst01 plugin retro-changelog set --exclude-attrs test3
```
2.3. Notice that the test3 exclude attribute has not been removed, but all the other exclude attributes have.
```
...
nsslapd-pluginDescription: Retrocl Plugin
nsslapd-exclude-attrs: test3
```

**Expected results**
1) The user should be able to add multiple exclude attributes in a single call.
2) The user should be able to delete a single exclude attribute.

**Comment by mreynolds389** [comment]
please cherry-pick down to 1.4.3

**Comment by jchapma** [comment]
33ea3c17604d62bb704f445986a8f021f0231809 - 389-ds-base-1.4.3
6444e45be59c9008386ebf2e7e34bae8eae9cb14 - 389-ds-base-1.4.4
97b3c32d223656c69baeb8de8680dae802ff92d2 - 389-ds-base-2.0
