### ISSUE TITLE
slugify: ModuleNotFoundError when running test cases.

### ISSUE THREAD

**Issue by aadhikar** [389ds/389-ds-base#5082]
**Issue Description**
slugify: ModuleNotFoundError when running test cases.

```
ImportError while loading conftest '/workspace/ds/dirsrvtests/conftest.py'.
dirsrvtests/conftest.py:12: in <module>
    from slugify import slugify
E   ModuleNotFoundError: No module named 'slugify'
```

**Package Version and Platform:**
- Platform: RHEL 9 (will check for fedora)

**Steps to Reproduce**
1. Run any test case

**Expected results**
Test cases should run without any error.

**Comment by aadhikar** [comment]
I am not sure if we have to make changes in ```/workspace/ds/dirsrvtests/conftest.py``` or in the ```requirements.txt```

**Comment by vashirov** [comment]
1b6745145..4db87ec6f  389-ds-base-2.3 -> 389-ds-base-2.3
   9bffb9d75..fdb3bae34  389-ds-base-2.2 -> 389-ds-base-2.2
   2cc3410d5..28b2b94c3  389-ds-base-2.1 -> 389-ds-base-2.1
