### ISSUE TITLE
sync-repl with openldap may send truncated syncUUID

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#5095]
**Issue Description**
sync-repl generates syncUUID ([SyncInfoMessage](https://datatracker.ietf.org/doc/html/rfc4533#section-2.5), or [syncStateControl](https://datatracker.ietf.org/doc/html/rfc4533#page-10))

According to [syncUUID](https://datatracker.ietf.org/doc/html/rfc4533#section-2.1.1) definition the UUID is a 16bytes octet string value. So it can contain a byte with NULL value

But when sending a syncUUID value containing a NUL bytes it truncated the syncUUID
<pre>
[3] (3 elem)
  OCTET STRING (52 byte) rid=123,csn=21000101020105.000000Z#000000#000#000000
  BOOLEAN true
  SET (1 elem)
    OCTET STRING (5 byte) 7FEF4573FB  <---- syncUUID

syncUUID[0] = 0x7f
syncUUID[1] = 0xef
syncUUID[2] = 0x45
syncUUID[3] = 0x73
syncUUID[4] = 0xfb
syncUUID[5] = 0x00
syncUUID[6] = 0x4a
syncUUID[7] = 0x91
syncUUID[8] = 0xa4
syncUUID[9] = 0x4f
syncUUID[10] = 0x60
syncUUID[11] = 0x0c
syncUUID[12] = 0xa2
syncUUID[13] = 0x87
syncUUID[14] = 0xbc
syncUUID[15] = 0xa1
</pre>

pyasn1 decoding fails when handling a synInfoMessage with a truncated syncUUID

**Package Version and Platform:**
since 1.4.3

**Steps to Reproduce**
run in a loop tests/suites/syncrepl_plugin/openldap_test.py

**Expected results**

**Comment by Firstyear** [comment]
@tbordaz Did you get this from wireshark? Do you have the packet trace? I suspect it's a bug in pyasn or python-ldap since it looks like the data is intact from what you have shown here.

**Comment by mreynolds389** [comment]
This should be cherry-picked down to 1.4.3

**Comment by tbordaz** [comment]
19570bf3d..06dace1d5  master
c2f6c23ba..cb21e1a20  389-ds-base-2.0
3ab042db6..a2a55e8b0  389-ds-base-1.4.4
7a351d036..730977955  389-ds-base-1.4.3
