### ISSUE TITLE
Broken Link in 389 Documentation

### ISSUE THREAD

**Issue by SnailShea** [389ds/389-ds-base#5101]
The [Multi-Master Replication](https://directory.fedoraproject.org/docs/389ds/howto/howto-multimasterreplication.html) page contains a [broken link](https://access.redhat.com/knowledge/docs/en-US/Red_Hat_Directory_Server/9.0/html/Administration_Guide/Managing_Replication.html) that leads to a 404 page. I believe the correct link should be [this one](https://access.redhat.com/documentation/en-us/red_hat_directory_server/11/html/administration_guide/managing_replication) as found by replacing `9.0` with `11`.

**Comment by Firstyear** [comment]
@MxLinux  Thanks for this, I've opened this PR https://github.com/mreynolds389/389wiki/pull/65
