### ISSUE TITLE
Should increase the date precision in package version number

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5119]
**Is your feature request related to a problem? Please describe.**
COPR builds are generated for every commit so if two commit are done the same days we ends up with several build with 
same version number.
The we are often getting tricked when testing a commit because the wrong build (typically the oldest one) get installed

**Describe the solution you'd like**
Increase the VERSION_DATE precision (by adding the hour and minute) to limit the risk of having the same package version 

**Describe alternatives you've considered**

**Additional context**
Extract of discussion in [Issue 4903](https://github.com/389ds/389-ds-base/issues/4903) in which we hit again the problem:

```
There is probably an issue with the way we generates the copr package names (maybe we should increase the timestamp precision ?)

+1 to increase the precision and at least add hours and minutes to the version. This is also useful (at least for me) during git bisect runs, so that generated packages can be always upgraded, as the version number grows monotonically.

Copr builds are done on each commit. So if there are several commits on the same day, they would all have the same version. Not sure why, but version also has a missing commit hash. I'll investigate it.
```

and when I discussed about this topic in the team meeting, Mark told us he also got tricked by that one and increasing the date precision is a good idea ...

**Comment by vashirov** [comment]
I filed https://github.com/389ds/389-ds-base/issues/5113 and submitted PR https://github.com/389ds/389-ds-base/pull/5114 :)
