### ISSUE TITLE
389-ds-base-1.4.3 branch fails to build

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#5123]
**Issue Description**
I'm doing rpm builds on F35, but it fails to compile:
```
ldap/servers/plugins/replication/repl5_agmt.c: In function 'agmt_new_from_entry':
ldap/servers/plugins/replication/repl5_agmt.c:486:30: error: 'replica' undeclared (first use in this function)
  486 |         if (replica_get_type(replica) == REPLICA_TYPE_PRIMARY) {
      |                              ^~~~~~~
ldap/servers/plugins/replication/repl5_agmt.c:486:30: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:9347: ldap/servers/plugins/replication/libreplication_plugin_la-repl5_agmt.lo] Error 1
```

Perhaps some change is not cherry-picked?

**Comment by vashirov** [comment]
Looks like it was https://github.com/389ds/389-ds-base/commit/9cfb5751552297d177a6c17d530224ae7a5062d3 that moved things around with regards to `replica`. After applying this change, it still doesn't compile.

https://github.com/389ds/389-ds-base/commit/e6068c07ac2769cb3da191169502ae58489a1ad4 contains unsolved merge conflicts (look for `<<<<<<<` and `>>>>>>>`.

**Comment by mreynolds389** [comment]
looking into it...

**Comment by mreynolds389** [comment]
Fixed
