### ISSUE TITLE
Memory leak in slapi_ldap_get_lderrno

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5126]
**Issue Description**
Clone of https://bugzilla.redhat.com/show_bug.cgi?id=2032742

The leak is due to a change in libldap API:
Digging in the old man page:
Note  LDAP_OPT_ERROR_STRING returns a pointer to an internal static string table, and ldap_memfree should not be called when using this session option.
And the new one:
LDAP_OPT_DIAGNOSTIC_MESSAGE
Sets/gets a string containing the error string associated to the LDAP handle. This option was formerly known as LDAP_OPT_ERROR_STRING. outvalue must be a char **, and the caller is responsible of freeing the returned string by calling ldap_memfree(3), while invalue must be a char *; the library duplicates the corresponding string.

So it looks like we will have to review the whole code for all slapi_ldap_get_lderrno calls:
  if the call has a message address it should be freed after use  by a call to a new slapi_ldap_free_lderrno_msg function
  that free the message if LDAP_OPT_DIAGNOSTIC_MESSAGE is defined.

**Comment by progier389** [comment]
I am able to reproduce the leak (setting up replication over SASL/Digest-MD5 and exporting SASL_PATH=foo and restarting the instances then perform a change and loop poking on the repl-agmt) but the weird thing is that libasan does not report the leak even if I count more than 200000 occurence of the leaking string when looking in /proc/xxxx/mem  (Furthermore using the debbuger to set up a breakpoint on slapi_ldap_get_lderrno then following the code step by step clearly  shows that here is a leaks (string is  duped then printed and reference is lost because the variable get out of scope ... )

**Comment by mreynolds389** [comment]
I wonder if valgrind might show the leak?  ASAN is "suppose" to be better than valgrind, but this wouldn't be the first time ASAN is not reporting on things it should.

**Comment by progier389** [comment]
Indeed valgrind is slower but it detects the leaks:

==1987883== 15,848 bytes in 283 blocks are definitely lost in loss record 826 of 849
==1987883==    at 0x484086F: malloc (vg_replace_malloc.c:381)
==1987883==    by 0x4BA6F64: ber_memalloc_x (memory.c:228)
==1987883==    by 0x4BA9167: ber_strdup_x (memory.c:643)
==1987883==    by 0x4B7F37F: ldap_get_option (options.c:320)
==1987883==    by 0x48C8BA6: slapi_ldap_get_lderrno (ldaputil.c:381)
==1987883==    by 0x48C90C8: slapd_ldap_sasl_interactive_bind (ldaputil.c:1488)
==1987883==    by 0x48CA08F: slapi_ldap_bind (ldaputil.c:1174)
==1987883==    by 0xA2DB972: bind_and_check_pwp (repl5_connection.c:1880)
==1987883==    by 0xA2DB972: conn_connect_with_bootstrap (repl5_connection.c:1218)
==1987883==    by 0xA2DCD64: conn_connect (repl5_connection.c:1059)
==1987883==    by 0xA2E5DA6: acquire_replica (repl5_protocol_util.c:124)
==1987883==    by 0xA2DF61A: repl5_inc_run (repl5_inc_protocol.c:793)
==1987883==    by 0xA2E5435: prot_thread_main (repl5_protocol.c:252)
==1987883==
==1987883== 15,848 bytes in 283 blocks are definitely lost in loss record 827 of 849
==1987883==    at 0x484086F: malloc (vg_replace_malloc.c:381)
==1987883==    by 0x4BA6F64: ber_memalloc_x (memory.c:228)
==1987883==    by 0x4BA9167: ber_strdup_x (memory.c:643)
==1987883==    by 0x4B7F37F: ldap_get_option (options.c:320)
==1987883==    by 0x48C8BA6: slapi_ldap_get_lderrno (ldaputil.c:381)
==1987883==    by 0xA2DBD0D: bind_and_check_pwp (repl5_connection.c:1933)
==1987883==    by 0xA2DBD0D: conn_connect_with_bootstrap (repl5_connection.c:1218)
==1987883==    by 0xA2DCD64: conn_connect (repl5_connection.c:1059)
==1987883==    by 0xA2E5DA6: acquire_replica (repl5_protocol_util.c:124)
==1987883==    by 0xA2DF61A: repl5_inc_run (repl5_inc_protocol.c:793)
==1987883==    by 0xA2E5435: prot_thread_main (repl5_protocol.c:252)
==1987883==    by 0x4DF3523: _pt_root (ptthread.c:201)
==1987883==    by 0x4E3A298: start_thread (pthread_create.c:481)

**Comment by progier389** [comment]
4d89e11494233d8297896540bc752cfdbab2cc69
   fef7f178b..4d89e1149  master
   f7d59c0b1..5db0b3340  389-ds-base-2.1 -> 389-ds-base-2.1
   148ae116c..ab8e0e7ca  389-ds-base-2.0 -> 389-ds-base-2.0
   302b4b516..3634fee51  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   c95a8ed0a..5c91c897c  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
