### ISSUE TITLE
ns-slapd/dirsrv crashes on start after upgrade unless mkdir /dev/shm/slapd-<instance>

### ISSUE THREAD

**Issue by hcoin** [389ds/389-ds-base#5147]
**Issue Description**
During an upgrade (not fresh install) of a master-master freeipa instance including dirsrv/ns-slapd/389-ds, ns-slapd fails complaining of not finding /dev/shm/slapd-<instance>.

This is a workaround:

#mkdir /dev/shm/slapd-<your kerberos domain with - instead of .>
#chown dirsrv:dirsrv /dev/shm/slapd-<your kerberos domain with - instead of .>
#systemctl restart ipa

Note you may also need to set the SELinux context: restorecon
/dev/shm/slapd-<instance> 

**Package Version and Platform:**
 - Platform:  Fedora
 - Package and version: rawhide
[root@registry1 ~]# dnf info 389-ds-base
Last metadata expiration check: 2:53:57 ago on Wed 02 Feb 2022 06:52:46 AM CST.
Installed Packages
Name         : 389-ds-base
Version      : 2.0.13
Release      : 1.fc36
Architecture : x86_64
Size         : 11 M
Source       : 389-ds-base-2.0.13-1.fc36.src.rpm
Repository   : @System
From repo    : fedora
Summary      : 389 Directory Server (base)
URL          : https://www.port389.org
License      : GPLv3+
Description  : 389 Directory Server is an LDAPv3 compliant server.  The base package includes
             : the LDAP server and command line utilities for server administration.

**Comment by mreynolds389** [comment]
This is probably a duplicate of:

https://github.com/389ds/389-ds-base/pull/5141
https://github.com/389ds/389-ds-base/issues/5127

Can you please provide the errors log, or whatever is "complaining" so we can confirm if it's fixed in 2.0.14

**Comment by mreynolds389** [comment]
@hcoin - this should be fixed in 2.0.14, can you please confirm?

**Comment by hcoin** [comment]
How do you propose I should do that?  Do you need me to delete the directory, which has considerable content, then upgrade?

**Comment by mreynolds389** [comment]
> How do you propose I should do that? Do you need me to delete the directory, which has considerable content, then upgrade?

Just install the latest rpms from rawhide (2.0.14) and restart the server.

**Comment by hcoin** [comment]
from another shell, journalctl -r

Feb 10 11:22:11 registry1.1.quietfountain.com audit[616995]: USER_AUTH pid=616995 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=pubkey_auth grantors=auth-key acct="root" exe="/usr/sbin/sshd" >
Feb 10 11:22:10 registry1.1.quietfountain.com audit[616995]: USER_AUTH pid=616995 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=pubkey acct="root" exe="/usr/sbin/sshd" hostname=? addr=fc00:10>
Feb 10 11:22:10 registry1.1.quietfountain.com audit[616995]: CRYPTO_SESSION pid=616995 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=start direction=from-client cipher=chacha20-poly1305@opens>
Feb 10 11:22:10 registry1.1.quietfountain.com audit[616995]: CRYPTO_SESSION pid=616995 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=start direction=from-server cipher=chacha20-poly1305@opens>
Feb 10 11:22:10 registry1.1.quietfountain.com audit[616996]: CRYPTO_KEY_USER pid=616996 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:00:b1:84:dc:e8:eb:8c:68:43:>
Feb 10 11:21:51 registry1.1.quietfountain.com systemd[1]: sssd-kcm.service: Consumed 1.322s CPU time.
Feb 10 11:21:51 registry1.1.quietfountain.com systemd[1]: sssd-kcm.service: Deactivated successfully.
Feb 10 11:21:51 registry1.1.quietfountain.com audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=sssd-kcm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termina>
Feb 10 11:21:51 registry1.1.quietfountain.com sssd_kcm[616550]: Shutting down (status = 0)
Feb 10 11:20:18 registry1.1.quietfountain.com ns-slapd[616581]: [10/Feb/2022:11:20:18.683996768 -0600] - ERR - NSMMReplicationPlugin - bind_and_check_pwp - agmt="cn=meToregistry2.1.quietfountain.com" (registry2:389) - Replication bind >
Feb 10 11:20:01 registry1.1.quietfountain.com CROND[616990]: (root) CMDEND (test -f /var/lock/subsys/ods-enforcerd && kill -s SIGHUP `cat /var/run/opendnssec/enforcerd.pid` > /dev/null 2> /dev/null)
Feb 10 11:20:01 registry1.1.quietfountain.com CROND[616991]: (root) CMD (test -f /var/lock/subsys/ods-enforcerd && kill -s SIGHUP `cat /var/run/opendnssec/enforcerd.pid` > /dev/null 2> /dev/null)
Feb 10 11:19:39 registry1.1.quietfountain.com ns-slapd[616581]: [10/Feb/2022:11:19:39.019687516 -0600] - WARN - NSMMReplicationPlugin - prot_stop - Incremental protocol for replica "agmt="cn=meToregistry2.1.quietfountain.com" (registry>
Feb 10 11:17:39 registry1.1.quietfountain.com audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dbus-:1.2-org.freedesktop.problems@0 comm="systemd" exe="/usr/lib/systemd/system>
Feb 10 11:17:39 registry1.1.quietfountain.com systemd[1]: dbus-:1.2-org.freedesktop.problems@0.service: Deactivated successfully.
Feb 10 11:17:38 registry1.1.quietfountain.com ns-slapd[616581]: [10/Feb/2022:11:17:38.860270449 -0600] - INFO - slapd_daemon - slapd shutting down - closing down internal subsystems and plugins
Feb 10 11:17:38 registry1.1.quietfountain.com ns-slapd[616581]: [10/Feb/2022:11:17:38.788893594 -0600] - INFO - op_thread_cleanup - slapd shutting down - signaling operation threads - op stack size 4 max work q size 1 max work q stack >
Feb 10 11:17:38 registry1.1.quietfountain.com systemd[1]: Stopping dirsrv@1-QUIETFOUNTAIN-COM.service - 389 Directory Server 1-QUIETFOUNTAIN-COM....
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=0 op=UNLOAD
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=0 op=UNLOAD
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=340 op=LOAD
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=339 op=LOAD
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=0 op=UNLOAD
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=338 op=LOAD
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=0 op=UNLOAD
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=337 op=LOAD
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=0 op=UNLOAD
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=336 op=LOAD
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=0 op=UNLOAD
Feb 10 11:17:38 registry1.1.quietfountain.com audit: BPF prog-id=335 op=LOAD
Feb 10 11:17:37 registry1.1.quietfountain.com audit: BPF prog-id=0 op=UNLOAD

**Comment by hcoin** [comment]
It woke up, were now at
...
Feb 10 11:26:31 registry1.1.quietfountain.com certmonger[617751]: 2022-02-10 11:26:31 [617751] Redirecting stdin to /dev/null, leaving stdout and stderr open for child "/usr/libexec/certmonger/ipa-server-guard".
Feb 10 11:26:31 registry1.1.quietfountain.com certmonger[617751]: 2022-02-10 11:26:31 [617751] Running enrollment helper "/usr/libexec/certmonger/ipa-server-guard".
Feb 10 11:26:31 registry1.1.quietfountain.com ns-slapd[617047]: [10/Feb/2022:11:26:31.616085113 -0600] - INFO - slapd_daemon - slapd shutting down - closing down internal subsystems and plugins
Feb 10 11:26:33 registry1.1.quietfountain.com certmonger[607689]: 2022-02-10 11:26:33 [607689] Certificate submission still ongoing.
Feb 10 11:26:33 registry1.1.quietfountain.com certmonger[617751]: Error obtaining initial credentials: Cannot contact any KDC for requested realm.
Feb 10 11:26:33 registry1.1.quietfountain.com certmonger[617751]: Error setting up ccache at the client: Cannot contact any KDC for requested realm.
Feb 10 11:26:33 registry1.1.quietfountain.com certmonger[607689]: 2022-02-10 11:26:33 [607689] Certificate submission attempt complete.
Feb 10 11:26:33 registry1.1.quietfountain.com certmonger[607689]: 2022-02-10 11:26:33 [607689] Child status = 3.
Feb 10 11:26:33 registry1.1.quietfountain.com certmonger[607689]: 2022-02-10 11:26:33 [607689] Child output:
Feb 10 11:26:33 registry1.1.quietfountain.com certmonger[607689]: "Error setting up ccache for "host" service on client using default keytab: Cannot contact any KDC for requested realm.
Feb 10 11:26:33 registry1.1.quietfountain.com certmonger[607689]: "
Feb 10 11:26:33 registry1.1.quietfountain.com certmonger[607689]: 2022-02-10 11:26:33 [607689] Error setting up ccache for "host" service on client using default keytab: Cannot contact any KDC for requested realm.
Feb 10 11:26:33 registry1.1.quietfountain.com certmonger[607689]: 2022-02-10 11:26:33 [607689] Certificate not (yet?) issued.

...

**Comment by hcoin** [comment]
It's like watching a train wreck in slow motion...

Feb 10 11:27:36 registry1.1.quietfountain.com sssd_be[617731]: Backend is offline
Feb 10 11:28:31 registry1.1.quietfountain.com ns-slapd[617047]: [10/Feb/2022:11:28:31.736958148 -0600] - WARN - NSMMReplicationPlugin - prot_stop - Incremental protocol for replica "agmt="cn=meToregistry2.1.quietfountain.com" (registry2:389)" did not shut down properly.
Feb 10 11:28:45 registry1.1.quietfountain.com ns-slapd[617047]: [10/Feb/2022:11:28:45.921018333 -0600] - ERR - NSMMReplicationPlugin - bind_and_check_pwp - agmt="cn=meToregistry2.1.quietfountain.com" (registry2:389) - Replication bind with GSSAPI auth failed: LDAP error -1 (Can't contact LDAP server) ()

**Comment by hcoin** [comment]
FYI, on the master-master replica we have:
[root@registry2 ~]# systemctl is-system-running
running
[root@registry2 ~]#

**Comment by hcoin** [comment]
The GUI on system 2 is giving me now the dreaded "login has failed for an unknown reason."  The log on system 2 is unremarkable
[root@registry2 ~]# journalctl -f
Feb 10 10:34:19 registry2.1.quietfountain.com systemd[1]: dnf-makecache.service: Consumed 1.329s CPU time.
Feb 10 10:50:01 registry2.1.quietfountain.com CROND[975256]: (root) CMD (test -f /var/lock/subsys/ods-enforcerd && kill -s SIGHUP `cat /var/run/opendnssec/enforcerd.pid` > /dev/null 2> /dev/null)
Feb 10 10:50:01 registry2.1.quietfountain.com CROND[975255]: (root) CMDEND (test -f /var/lock/subsys/ods-enforcerd && kill -s SIGHUP `cat /var/run/opendnssec/enforcerd.pid` > /dev/null 2> /dev/null)
Feb 10 11:01:01 registry2.1.quietfountain.com CROND[976296]: (root) CMD (run-parts /etc/cron.hourly)
Feb 10 11:01:02 registry2.1.quietfountain.com run-parts[976299]: (/etc/cron.hourly) starting 0anacron
Feb 10 11:01:02 registry2.1.quietfountain.com run-parts[976305]: (/etc/cron.hourly) finished 0anacron
Feb 10 11:01:02 registry2.1.quietfountain.com CROND[976295]: (root) CMDEND (run-parts /etc/cron.hourly)
Feb 10 11:19:51 registry2.1.quietfountain.com haveged[569]: haveged: fills: 28, generated: 14 M bytes, RNDADDENTROPY: 13.5 M bytes
Feb 10 11:20:01 registry2.1.quietfountain.com CROND[978094]: (root) CMD (test -f /var/lock/subsys/ods-enforcerd && kill -s SIGHUP `cat /var/run/opendnssec/enforcerd.pid` > /dev/null 2> /dev/null)
Feb 10 11:20:01 registry2.1.quietfountain.com CROND[978093]: (root) CMDEND (test -f /var/lock/subsys/ods-enforcerd && kill -s SIGHUP `cat /var/run/opendnssec/enforcerd.pid` > /dev/null 2> /dev/null)

**Comment by hcoin** [comment]
the system being 'upgraded's logs are now being flooded with the likes of
Feb 10 11:34:42 registry1.1.quietfountain.com ipa-pki-wait-running[617939]: ipa-pki-wait-running: Connection failed: HTTPConnectionPool(host='registry1.1.quietfountain.com', port=8080): Read timed out. (read timeout=1.0)
Feb 10 11:34:44 registry1.1.quietfountain.com named[617872]: zone 8.0.2.0.a.0.0.0.3.0.0.1.0.0.c.f.ip6.arpa/IN: serial (2021083271) write back to LDAP failed
Feb 10 11:34:44 registry1.1.quietfountain.com ipa-pki-wait-running[617939]: ipa-pki-wait-running: Connection failed: HTTPConnectionPool(host='registry1.1.quietfountain.com', port=8080): Read timed out. (read timeout=1.0)
Feb 10 11:34:46 registry1.1.quietfountain.com ipa-pki-wait-running[617939]: ipa-pki-wait-running: Connection failed: HTTPConnectionPool(host='registry1.1.quietfountain.com', port=8080): Read timed out. (read timeout=1.0)
Feb 10 11:34:48 registry1.1.quietfountain.com ipa-pki-wait-running[617939]: ipa-pki-wait-running: Connection failed: HTTPConnectionPool(host='registry1.1.quietfountain.com', port=8080): Read timed out. (read timeout=1.0)
Feb 10 11:34:50 registry1.1.quietfountain.com ipa-pki-wait-running[617939]: ipa-pki-wait-running: Connection failed: HTTPConnectionPool(host='registry1.1.quietfountain.com', port=8080): Read timed out. (read timeout=1.0)
Feb 10 11:34:52 registry1.1.quietfountain.com ipa-pki-wait-running[617939]: ipa-pki-wait-running: Connection failed: HTTPConnectionPool(host='registry1.1.quietfountain.com', port=8080): Read timed out. (read timeout=1.0)
Feb 10 11:34:54 registry1.1.quietfountain.com named[617872]: zone 8.0.3.0.a.0.0.0.3.0.0.1.0.0.c.f.ip6.arpa/IN: serial (2021083270) write back to LDAP failed

**Comment by hcoin** [comment]
Trying
 systemctl restart dirsrv@1-QUIETFOUNTAIN-COM.service 
it returned several minutes later.
The forced restart allowed the dnf upgrade to complete.

And we have:
[root@registry1 ~]# ipa status
ipa: ERROR: cannot connect to 'https://registry1.1.quietfountain.com/ipa/json': [Errno 111] Connection refused
waiting a while:

systemctl status ipa
× ipa.service - Identity, Policy, Audit
     Loaded: loaded (/usr/lib/systemd/system/ipa.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2022-02-10 11:50:51 CST; 4min 11s ago
   Main PID: 616478 (code=exited, status=1/FAILURE)
        CPU: 58.683s

Feb 10 11:50:50 registry1.1.quietfountain.com ipactl[616478]: Starting kadmin Service
Feb 10 11:50:50 registry1.1.quietfountain.com ipactl[616478]: Starting named Service
Feb 10 11:50:50 registry1.1.quietfountain.com ipactl[616478]: Starting httpd Service
Feb 10 11:50:50 registry1.1.quietfountain.com ipactl[616478]: Starting ipa-custodia Service
Feb 10 11:50:50 registry1.1.quietfountain.com ipactl[616478]: Starting pki-tomcatd Service
Feb 10 11:50:50 registry1.1.quietfountain.com ipactl[616478]: Starting smb Service
Feb 10 11:50:51 registry1.1.quietfountain.com systemd[1]: ipa.service: Main process exited, code=exited, status=1/FAILURE
Feb 10 11:50:51 registry1.1.quietfountain.com systemd[1]: ipa.service: Failed with result 'exit-code'.
Feb 10 11:50:51 registry1.1.quietfountain.com systemd[1]: Failed to start ipa.service - Identity, Policy, Audit.
Feb 10 11:50:51 registry1.1.quietfountain.com systemd[1]: ipa.service: Consumed 58.683s CPU time.

systemctl start ipa

disorderly shutdown, recovering database...

...
Feb 10 11:58:15 registry1.1.quietfountain.com ipa-dnskeysyncd[618944]: ipapython.ipautil: DEBUG    stderr=
Feb 10 11:58:15 registry1.1.quietfountain.com ipa-dnskeysyncd[618944]: ipaserver.dnssec.bindmgr: DEBUG    Key metadata in LDAP: {}
Feb 10 11:58:15 registry1.1.quietfountain.com ipa-dnskeysyncd[618944]: ipaserver.dnssec.bindmgr: DEBUG    Zones modified but skipped during bindmgr.sync: set()
Feb 10 11:58:15 registry1.1.quietfountain.com ipa-ods-exporter[618929]: Exception ignored in: <function LocalHSM.__del__ at 0x7f14618988b0>
Feb 10 11:58:15 registry1.1.quietfountain.com ipa-ods-exporter[618929]: Traceback (most recent call last):
Feb 10 11:58:15 registry1.1.quietfountain.com ipa-ods-exporter[618929]:   File "/usr/lib/python3.10/site-packages/ipaserver/dnssec/localhsm.py", line 107, in __del__
Feb 10 11:58:15 registry1.1.quietfountain.com ipa-ods-exporter[618929]:   File "/usr/lib/python3.10/site-packages/ipaserver/p11helper.py", line 939, in finalize
Feb 10 11:58:15 registry1.1.quietfountain.com ipa-ods-exporter[618929]: TypeError: 'NoneType' object is not callable
Feb 10 11:58:16 registry1.1.quietfountain.com systemd[1]: ipa-ods-exporter.service: Deactivated successfully.

...
Feb 10 11:58:16 registry1.1.quietfountain.com systemd[1]: ipa-ods-exporter.service: Consumed 9.910s CPU time.
Feb 10 11:58:59 registry1.1.quietfountain.com ipa-dnskeysyncd[618944]: ipaserver.dnssec.syncrepl: DEBUG    Detected modify of entry: idnsname=_domainkey.quietfountain.com.,cn=dns,dc=1,dc=quietfountain,dc=com 583a3101-0df5-11ec-ba30-ce0f2bb8efe6
Feb 10 11:58:59 registry1.1.quietfountain.com ipa-dnskeysyncd[618944]: ipaserver.dnssec.syncrepl: DEBUG    New cookie is: registry1.1.quietfountain.com:389#krbprincipalname=ipa-dnskeysyncd/registry1.1.quietfountain.com@1.quietfountain.com,cn=services,cn=accounts,dc=1,dc=quietfountain,dc=com:cn=dns,dc=1,dc=quietfountain,dc=com:(|(objectClass=idnsZone)(objectClass=idnsSecKey)(objectClass=ipk11PublicKey))#524434
Feb 10 11:58:59 registry1.1.quietfountain.com ns-slapd[618378]: [10/Feb/2022:11:58:59.517139684 -0600] - WARN - content-sync-plugin - sync_update_persist_betxn_pre_op - DB retried operation targets "changenumber=513385,cn=changelog" (op=0x7fa078264800 idx_pl=0) => op not changed in PL
Feb 10 11:59:09 registry1.1.quietfountain.com named[618449]: zone _domainkey.greekdishesbynausica.com/IN: serial (2021090719) write back to LDAP failed
...

**Comment by mreynolds389** [comment]
This should have been fixed in newer versions by now.  @hcoin have you updated ipa/389 yet?  Is it still an issue for you?

**Comment by hcoin** [comment]
Ran out of time for fighting freeipa bugs in newer versions, reverted to older more stable code.
