### ISSUE TITLE
Add epoll support to 389-ds-base

### ISSUE THREAD

**Issue by lslile** [389ds/389-ds-base#5154]
Add epoll support to 389-ds-base

I tried not to deviate too far from the existing code at this point, the major changes at this point are:

    Listeners moved to a listen_table (setup_epoll_listen_pds)
        listen_table is a list of Connection's so the can be handled in the same way as a client Connection
        Differentiated by Connection->conn_state = CONN_STATE_LISTEN
        Connection_Table->listen_count is no longer maintained
        Eliminates listener pd handing from setup_pr_read_pds

    epoll_arm_listen_pds
        Adds or removes all listener pds from epoll
        Triggered from main event loop based on connection count limits

    Connection_Table->fd is currently only maintained for listeners
        This could likely be fully eliminated, but I'm not sure what to do with signalpipe to accomplish this end

    Connection_Table->epollfd has been added to hold the epoll fd set

    handle_new_connection
        Adds descriptors to epoll immediately
        Eliminates the need for setup in setup_pr_read_pds

    epoll_pr_idle_pds ( timeout related section of setup_pr_read_pds )
        Should only handle client timeouts or special cases for re-adding a descriptor to epoll
        Eliminates the needs from the remainder of setup_pr_read_pds

    setup_pr_read_pds is not used with epoll

**Comment by Firstyear** [comment]
@lslile Thanks! Do you mind submitting a PR as well with your changes? :)

**Comment by mreynolds389** [comment]
> @lslile Thanks! Do you mind submitting a PR as well with your changes? :)

@lslile has a draft here:

https://github.com/lslile/389-ds-base/pull/1

But yes, it should be filed against master following these guidelines:

https://www.port389.org/docs/389ds/howto/howto-do-pull-requests.html  (via https://www.port389.org/docs/389ds/contributing.html)

**Comment by lslile** [comment]
Hi Mark,
I believe I have fulfilled all the requirements in the contributing and hotwo-do-pull-requests documents.  If I have missed something please bring it to my attention and I will get it addressed.

I have changed the PR to ready for review now that I believe I have addressed any outstanding issues in the patch.
I will limit any further updates to the patch to requests and feedback from the 389 team.
Thanks.
--Larry

    On Wednesday, February 9, 2022, 12:34:51 AM EST, Mark Reynolds ***@***.***> wrote:  
 
 



@lslile Thanks! Do you mind submitting a PR as well with your changes? :)


@lslile has a draft here:

lslile/389-ds-base#1

But yes, it should be filed against master following these guidelines:

https://www.port389.org/docs/389ds/howto/howto-do-pull-requests.html (via https://www.port389.org/docs/389ds/contributing.html)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lslile** [comment]
Closing the issue out, will switch to PR directly.

**Comment by Firstyear** [comment]
@lslile I think you need to issue the PR against 389-ds? There should be some UI in github to do that, because I can't follow that link or see your PR.

**Comment by lslile** [comment]
Sorry, I'll resubmit the pull request again as soon as possible.  I was unaware of a process I need to follow at work regarding the submission.

**Comment by Firstyear** [comment]
@lslile All good! We look forward to helping and working with you :)

**Comment by lslile** [comment]
Closing in favor of issue 5181, for administrative reasons.

Thanks.

--Larry
