### ISSUE TITLE
RFE - Provide an option to abort an Auto Member rebuild task

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5155]
Depending of the size of the groups along with the complexity of the rules and the interactions with other plugins ( typically in an IPA context ), the Auto Member rebuild task can generate performance issues ( for instance a high CPU usage when the Schema Compatibility plugin is called ).  Therefore an option to abort the rebuild task would be beneficial.

See:  https://bugzilla.redhat.com/show_bug.cgi?id=2018153

**Comment by mreynolds389** [comment]
e13faa2b4..5716a22ca  389-ds-base-2.0 -> 389-ds-base-2.0
a48da4403..dca050edc  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
bacf9d80a..29a0ce9d7  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by tbordaz** [comment]
@mreynolds389  is not backported in 1.3.10 and cherry-pick looks not immediate. Could you backport it, thanks

**Comment by tbordaz** [comment]
7eca61ace..78d2ef45d  389-ds-base-1.3.10
