### ISSUE TITLE
Importing a ca chain only imports the first certificate

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#5162]
A ca chain pem file is just a series of pem certs concatinated. NSS of course, when presented with a chain file will only import the first certificate, and will silently ignore the rest.

This can create user confusion who expect to be able to import a chain file.

While we can't fix NSS, we CAN fix dsctl instance tls import commands such that when a chain file is presented we can inform the user they need to split it and import the components individually.

**Comment by mreynolds389** [comment]
Related downstream bug:  https://bugzilla.redhat.com/show_bug.cgi?id=1878808

**Comment by mreynolds389** [comment]
Allow CA bundles to be imported

78ee3a5a4..4a1e3bd4d  389-ds-base-2.2 -> 389-ds-base-2.2
b5e5afb7f..007e21509  389-ds-base-2.1 -> 389-ds-base-2.1
ef2ec82e2..98aa09d16  389-ds-base-2.0 -> 389-ds-base-2.0
ce0bda67e..6f77f668f  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
fd904d5e7..1aaed9964  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by mreynolds389** [comment]
Fix regression

dde3fc662..69235d885  389-ds-base-2.2 -> 389-ds-base-2.2
c9c7a014a..7abaa06b8  389-ds-base-2.1 -> 389-ds-base-2.1
98aa09d16..12bca39bf  389-ds-base-2.0 -> 389-ds-base-2.0
6f77f668f..8cf6cfd14  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
1aaed9964..7f311bb1d  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by aivanov389** [comment]
after this commit (at least, in the version 2.0, commit 98aa09d16f545bb3fea2e19d483030d726321393) **security.py** uses the function "log.info()". Apparently it is not defined in the imports of this file. The  result is that it is impossible to set some (any ?) security property:

**Comment by progier389** [comment]
The 'log' typo is now fixed. See issue 5162

**Comment by mreynolds389** [comment]
d9923020d..c6613be07  389-ds-base-2.2 -> 389-ds-base-2.2
fdc7a5777..5f5150277  389-ds-base-2.1 -> 389-ds-base-2.1
9a71f2ba4..332e4872f  389-ds-base-2.0 -> 389-ds-base-2.0
a8cb9f487..b85508b75  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by mreynolds389** [comment]
Fix CI test

064a3f7ea..764a306e4  389-ds-base-2.2 -> 389-ds-base-2.2
055c14da8..9476a78e3  389-ds-base-2.1 -> 389-ds-base-2.1
f8aca8e88..0ffe4abdc  389-ds-base-2.0 -> 389-ds-base-2.0
35b76e0a7..e10f1c6c5  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by progier389** [comment]
[ba7ad9a4f](https://github.com/389ds/389-ds-base/commit/ba7ad9a4f7d1509fa201d39099af342bbaf67aaf)..[ee1e525b0](https://github.com/389ds/389-ds-base/commit/ee1e525b04d812e3e18c9eee614750c8d11efb4e)  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
Because [BZ 2149967](https://bugzilla.redhat.com/show_bug.cgi?id=2149967) part was not included in 1.4.3 branch unlike main and 2.x branches
