### ISSUE TITLE
snmp_collator  tries to unlock NULL mutex - Instance fails to start

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#5180]
**Issue Description**
A failure in a replication CI test is caused by an instance that fails to start, caused by a mutex unlock on a NULL mutex.

**Package Version and Platform:**
 - Platform: 5.6.6-300.fc32.x86_64 and 5.14.0-63.el9.x86_64
 - Package and version: 389-Directory/2.0.14 DEVELOPER BUILD B0000.000.0000

**Steps to Reproduce**
CI test
```
sudo  py.test -s -v dirsrvtests/tests/suites/replication/cleanallruv_test.py::test_clean_force
```
A manual restart identifies the issue as a failed assertion.
```
sudo systemctl status dirsrv@supplier1.service -l
...
Feb 25 17:36:54 shona32 ns-slapd[533700]: Assertion failure: mutex != NULL, at ldap/servers/slapd/slapi2runtime.c:91
Feb 25 17:36:54 shona32 systemd[1]: dirsrv@supplier1.service: Main process exited, code=killed, status=6/ABRT
...
```
Gdb backtrace:
```
(gdb) bt
...
#2  0x00007ffff71a4491 in PR_Assert () at /lib64/libnspr4.so
#3  0x00007ffff7be323c in slapi_unlock_mutex (mutex=0x0) at ldap/servers/slapd/slapi2runtime.c:91
#4  0x00007ffff7be3df2 in set_snmp_interaction_row (host=0x213b740 "shona32", port=39003, error=0) at ldap/servers/slapd/snmp_collator.c:252
...
```
At ldap/servers/slapd/snmp_collator.c +252, a slapi_unlock_mutex is attempted on a NULL mutex.
```
 slapi_unlock_mutex(interaction_table_mutex);
```

**Comment by mreynolds389** [comment]
Don't forget to cherry-pick to 2.1. and 2.0

**Comment by jchapma** [comment]
389-ds-base-2.0 52e6282a50cb3ac1153a806114a7a4474cf30047
389-ds-base-2.1 22b6c00b401623c1877d3705986cc50c9d0697f7

**Comment by jchapma** [comment]
> Don't forget to cherry-pick to 2.1. and 2.0

I already had, thanks
