### ISSUE TITLE
dsconf attr-encrypt fails when be_name is a backend name

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#5183]
**Issue Description**
When the be_name is a backend name (like userRoot), then the command fails because (_get_backend/str2dn) tries to translate it into a dn.
The command succeeds when using a suffix (like dc=example,dc=com)

The RC of the failure is not reported. It only display 'Error:'

**Package Version and Platform:**
since 1.4.3

**Steps to Reproduce**
It occurs with 'dsconf standalone1 backend attr-encrypt --list userRoot' or 'dsconf standalone1 backend attr-encrypt --add-attr legalName userroot'

**Expected results**
backend name and suffix are both supported

**Comment by progier389** [comment]
It is a duplicate:
I fixed _get_backend a few days ago in [issue 5122](https://github.com/389ds/389-ds-base/issues/5122)
