### ISSUE TITLE
ldifgen: make required parameters more specific 

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#5195]
**Issue Description**
When ldifgen is used without required parameters, it drops into interactive mode without telling which required parameters are missing:
```
# dsctl localhost ldifgen mod-load
Missing required parameters, switching to Interactive mode ...
```
It's possible to specify that some of the parameters are required by using [`required=True`](https://docs.python.org/3/library/argparse.html#required) keyword.

The downside of this approach is that it doesn't drop into interactive mode anymore.
Another option is to update `log.info` message to state what parameters are required.

**Comment by mreynolds389** [comment]
d50340ba5..f7f0986de  389-ds-base-2.1 -> 389-ds-base-2.1
4d2d010b8..0ee456ed3  389-ds-base-2.0 -> 389-ds-base-2.0
