### ISSUE TITLE
Simplify instance creation and administration by non root user

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5217]
**Is your feature request related to a problem? Please describe.**
Customer reports that open ldap allowed a non root user to create instance (for example to run tests) and complained that it is not possible with 389DS. (In fact it is possible but that is cumbersome)

**Describe the solution you'd like**
I propose to add a dsconf option to prepare a subtree and wrappers to the  dscreate, dsctl and dsconf command 
 to be able to create/run/administrate 389ds instances.
The idea is very simple: copy what is needed from the standard package installation (as root) to generate the subtree.
  optionally generate wrapper to the standard administration commands (Running the standard command after setting 
   the PREFIX and INSTALL_PREFIX environment variables) and update the template files (typically the dse.ldif and the inf files) so  that dscreate defaults get adjusted for a prefixed install. 

**Limitation**
1. requires that packages get previously installed as root (by using: dnf install 389-ds-base) 
2. selinux not handled (But as we are running as an user in a subtree owned by the user, this should not be an issue)
3. Rust plugins are disabled. 
4. snmp is not supported.

**Describe alternatives you've considered**
I wondered if it would be possible to fully install 389ds in a prefixed variables (to be able to handle different versions of 389ds)
as non root but handling the libraries dependencies became tricky so I rather use a simple solution

**Comment by progier389** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1872451

**Comment by Firstyear** [comment]
It's already pretty much fully possible to install as non-root / partially prefixed, as this is what dscontainer is effectively doing. The main thing is just needing to have write access to the dest paths. setup.inf does have the capability for you to specify all your own paths, the main issue on RHEL is that this will absolutely trash selinux policy.

**Comment by mreynolds389** [comment]
> ... the main issue on RHEL is that this will absolutely trash selinux policy.

We should be able to check for this and log warning or even reject the install before it even starts.

**Comment by progier389** [comment]
I am not really sure about what you perceive as an issue here:
    The fact that these instances are not able to benefit of sepolicy to be able to access resources that the user is not allowed to use is quite expected if we want that any users can run an instance.. 
And IMHO in case of misconfiguration we can rely on the default behavior (getting an error during instance creation because server cannot be started) exactly as if we specify a busy port or a non writable path 
The only problem I know about is the bunch of warning that get logged at startup, and IMHO it is plain bug as this should not happen when the instance configuration files says that selinux is disabled  ...

**Comment by mreynolds389** [comment]
119bc2a6a..b92769252  389-ds-base-2.1 -> 389-ds-base-2.1
29dacfec1..ea52be488  389-ds-base-2.0 -> 389-ds-base-2.0

**Comment by vashirov** [comment]
This commit https://github.com/389ds/389-ds-base/commit/45af34013f8bdd34f939d36b16776413e13c0a51 should be also backported to 2.0 and 2.1.
