### ISSUE TITLE
Remove --durable-txn from dsconf

### ISSUE THREAD

**Issue by mmuehlfeldRH** [389ds/389-ds-base#5232]
**Issue Description**
nsslapd-db-durable-transaction can only be changed when the instance is stopped. The `dsconf backend config set --durable-txn` command makes no sense. Please remove `--durable-txn`.

**Package Version and Platform:**
 - Platform: RHEL 9
 - Package and version: 389-ds-base-2.0.14-3.module+el9dsrv+14387+a6c313de.x86_64

**Steps to Reproduce**
```
dsconf -D "cn=Directory Manager" ldap://server.example.com backend config set --durable-txn off
Error: 103 - 4 - 53 - Server is unwilling to perform - [] - nsslapd-db-durable-transaction can't be modified while the server is running.
```

**Expected results**
The `--durable-txn` should be removed because dsconf requires a running instance, and the setting can't be changed when the server is running.

**Comment by tbordaz** [comment]
I have not look in details why it was unwilling to perform. IMHO, this setting could be done even if the server is running but should only be taken into account at next restart.

Note: this setting --durable-txn=off seem so risky to me, that I see no reason to propose it in the UI/CLI. For risky tuning like this, we may assume that it is done under support control and then experts agree to update dse.ldif.

**Comment by Firstyear** [comment]
Yep, I agree with @tbordaz here :)

**Comment by mreynolds389** [comment]
d50340ba5..f7f0986de  389-ds-base-2.1 -> 389-ds-base-2.1
4d2d010b8..0ee456ed3  389-ds-base-2.0 -> 389-ds-base-2.0
