### ISSUE TITLE
RFE - Add a specific modify form for groups, roles and CoS

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#5236]
There're three part of this issue:

1. We should have a searchable/sortable table for group memberships when editing the group entry (objectclass groupOfName/groupsOfUniqueNames).
2. We should have a searchable/sortable table for nested roles when editing the Role entry.
3. And we should add a template, CoS attributes, CoS specifier functionality to CoS definition editing.

**Comment by mreynolds389** [comment]
578dfdd98..fa25edc39  389-ds-base-2.2 -> 389-ds-base-2.2
ec7ce04ea..021417a90  389-ds-base-2.1 -> 389-ds-base-2.1
05347a99e..ba859c701  389-ds-base-2.0 -> 389-ds-base-2.0
7fd039713..3c49e8e74  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
