### ISSUE TITLE
audit-ci: Cannot convert undefined or null to object                                                                                                        

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#5237]
**Issue Description**
For quite some time I have this error while building rpms:
```
audit-ci version: 3.2.0
Cannot convert undefined or null to object
Exiting...
```
Looks like it's quite an old version of audit-ci that doesn't work well with npm >=7. 
We should update it to the latest version.

**Comment by vashirov** [comment]
26a994544..43bedfc5c  389-ds-base-2.0 -> 389-ds-base-2.0

**Comment by mreynolds389** [comment]
> [26a9945](https://github.com/389ds/389-ds-base/commit/26a994544d77c088cc548ce408fe7b3c33e37f80)..[43bedfc](https://github.com/389ds/389-ds-base/commit/43bedfc5c3925d5706675a18f1e19482a0f43b50) 389-ds-base-2.0 -> 389-ds-base-2.0

Should this also go into the 2.1 branch?

**Comment by vashirov** [comment]
Totally, I missed it we have one now.
   a2f8348d3..b903bc074  389-ds-base-2.1 -> 389-ds-base-2.1
