### ISSUE TITLE
Serialization of pam_passthrough causing high etimes

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#5271]
**Issue Description**
libpam was not thread-safe and 389-ds [serialized](https://github.com/389ds/389-ds-base/commit/87e9a9fc6d8a98e421f2363f97b33afd75f4158e) the calls to pam authentication.
Since a long time now libpam is thread-safe, at the condition each worker uses its own pam_handle. 389-ds workers are using their own pam_handle (obtained from pam_start) so there is no reason to keep the serialization.

This serialization create contention and high etime when pam_authenticate response time is higher than incoming rate of pam_passthrough requests.

**Package Version and Platform:**
all version (since 2008)

**Steps to Reproduce**
Apply parallel pam_passthrough calls

**Expected results**
should not be serialized

**Additional context**

**Comment by mreynolds389** [comment]
49b0ae530..17cc58066  389-ds-base-2.2 -> 389-ds-base-2.2
94d124b0a..7e1d99182  389-ds-base-2.1 -> 389-ds-base-2.1
e05369cbc..4a7dbb44e  389-ds-base-2.0 -> 389-ds-base-2.0
d0a91891c..08c18b373  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
bd566957f..d08a0e414  389-ds-base-1.3.10 -> 389-ds-base-1.3.10

**Comment by droideck** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2170223
