### ISSUE TITLE
HIGH - basic test does not run

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#5281]
In a development environment, where you did a chroot install, basic test no longer functions. This appears to be due to:

pytestmark = pytest.mark.skipif(get_rpm_version("389-ds-base-snmp") == "not installed", reason="389-ds-base-snmp package is not present")

This also makes a lot of assumptions about the distro, which excludes anything that isn't fedora/rhel - we don't have a 389-ds-base-snmp package, in opensuse and suse we have 389-ds-snmp.

In a chroot everything for snmp is present:

```
find /opt/dirsrv | grep -i ldap-agent
/opt/dirsrv/sbin/ldap-agent
/opt/dirsrv/etc/dirsrv/config/ldap-agent.conf
/opt/dirsrv/share/man/man1/ldap-agent.1
```

So I think this needs to be reverted/ fixed.

**Comment by vashirov** [comment]
This test has 2 pytestmarks, while it should have only one. Second one should be a decorator for `test_basic_ldapagent` function. And we can check for the binary presence instead of the package presence.
