### ISSUE TITLE
Replication broken until server restart after password change

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5284]
**Issue Description**
BZ1956987: After changing the replication agreement and the replication manager password, 
replication fails until the  server is restarted (connection fails with Invalid Credential error).

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version:  Master branch

**Steps to Reproduce**
 - On supplier, Change password of replication agreement
 - On consumer: Change password of the replication manager entry
 - On supplier modify an entry within replicated suffix
 - Wait a few seconds
 - On consumer: Check that the entry modification has been replicated.
If the bug exists. 

**Expected results**
- Replication should be still working (after maybe a transient error on replication session started while password where changed).

**Additional context**
The issue is that a clear version of the agmt password is cached within the replication connection struct and not updated 
 when the password is changed.
A solution is to also store a copy of the encrypted password in that struct so it can be quickly compared to the agmt password, then both passwords values get recomputed if the compare failed.

**Comment by progier389** [comment]
FYI: Last time this part of the code get changed (due to a code cleanup) was in 2017, so the bug exists in all versions
But as the work-around is trivial, I am not sure we should back port the fix but just document the bug and its work-round.

**Comment by mreynolds389** [comment]
@progier389 - can you cherry pick this down to 1.4.3 please?

**Comment by progier389** [comment]
b169df29848448c69d42388f213bfeca64b04efc
   4cfefd799..b169df298  master
   88da0060a..ce4963ceb  389-ds-base-2.1 -> 389-ds-base-2.1
   33c3f79a9..0332114cb  389-ds-base-2.0 -> 389-ds-base-2.0
   0b57fbf45..1a12df47c  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   39711d3ad..e1e076de0  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
