### ISSUE TITLE
Importing certificate chain files via "import-server-key-cert" no longer works 

### ISSUE THREAD

**Issue by spike77453** [389ds/389-ds-base#5290]
**Issue Description**
Importing certificate chain files (e.g. the ones EFF's certbot generates) via 
```
dsctl localhost tls import-server-key-cert fullchain.pem privkey.pem
```
no longer works starting with version 2.1.1 and results in an error message:

```
Error: The file fullchain.pem may be a chain file. This is not supported. Break out each certificate and key into unique files, and import them individually.
```

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 389-ds-base-2.1.1-1.fc36.x86_64

**Steps to Reproduce**
1. Create an `instance.inf` file with the following content:
```
[general]
full_machine_name = ldap.example.com
start = False
strict_host_checking = False

[slapd]
instance_name = localhost

root_dn = cn=manager
root_password = supersecretpassword
port = 389
secure_port = 636
self_sign_cert = False

[backend-userroot]
sample_entries = no
suffix = dc=example,dc=com
create_suffix_entry = True
```
3. Run `dscreate from-file instance.inf`
4. Obtain a letsencrypt certificate for the host, e.g. ldap.example.com
5. Run `dsctl localhost tls import-server-key-cert fullchain.pem privkey.pem`

**Expected results**
```
# dsctl localhost tls import-server-key-cert fullchain.pem privkey.pem 
# echo $?
0
```

**Additional context**
Importing only the certificate (instead of the full chain) doesn't work:
```
dscreate from-file instance.inf
dsctl localhost tls import-server-key-cert cert.pem privkey.pem
dsctl localhost start
dsconf localhost config replace nsslapd-securePort=636 nsslapd-security=on
dsctl localhost restart
# openssl s_client -connect ldap.example.com:636 2>&1 | grep Verification
Verification error: unable to verify the first certificate
```

The root cause seems to be this commit: 89d6f2f4884b78f9839ca0098561b33787d64f62  
After disabling the assertion it works as expected
```
--- lib389/nss_ssl.py.orig    2022-05-10 14:16:38.510889852 +0200
+++ lib389/nss_ssl.py 2022-05-10 14:14:43.078526807 +0200
@@ -76,6 +76,7 @@
     def _assert_not_chain(self, pemfile):
         # To work this out, we open the file and count how many
         # begin key and begin cert lines there are. Any more than 1 is bad.
+        return
         count = 0
         with open(pemfile, 'r') as f:
             for line in f:
```

```
dscreate from-file instance.inf
dsctl localhost tls import-server-key-cert fullchain.pem privkey.pem
dsctl localhost start
dsconf localhost config replace nsslapd-securePort=636 nsslapd-security=on
dsctl localhost restart
# openssl s_client -connect ldap.example.com:636 2>&1 | grep Verification
Verification: OK
```

```
# certutil -d /etc/dirsrv/slapd-localhost/ -L

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

Server-Cert                                                  u,u,u
R3 - Internet Security Research Group                        ,,   
ISRG Root X1 - Digital Signature Trust Co.                   ,,
```

**Comment by vashirov** [comment]
Commit https://github.com/389ds/389-ds-base/commit/89d6f2f4884b78f9839ca0098561b33787d64f62 introduced a workaround for `certutil`'s bug https://bugzilla.mozilla.org/show_bug.cgi?id=1664816

But `import-server-key-cert` uses `pk12util`, not `certutil`. So this check in `add_server_key_and_cert()` https://github.com/389ds/389-ds-base/blob/4cfefd799cbdfa228b0c9b91a5cc3c5c6a4e42da/src/lib389/lib389/nss_ssl.py#L1043 might not be needed. Because p12 file can include CA chain certificates too, and `pk12util` has no issues importing such files.
