### ISSUE TITLE
CI Test: Harden ReplicationManager.wait_for_replication lib389 function

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5291]
**Issue Description**
To verify that replication is working , lib389 ReplicationManager.wait_for_replication 
 modify the replication manager group description with a random value on the supplier
then loops until that value is seen on the consumer side.
Unfortunately that is not a good way to check replication (Because of URP there is no way to be absolutly sure that the change we have done will be seen as the ,last change (an change done the same second on another supplier may take precedence.
To harden this code and offer a better diagnostic, I propose: to also check the description value on supplier side
   If the changed, supplier descriptions and consumer description values are the same, Then replication is OK.
   if supplier and consumer values are different then replica are not in sync ==> wait and loop 
   if change and supplier values are different it is probable that change get overwritten ==>
      Redo the change (As we waited 1 second, it should not be overwritten again)
      wait and loop 

**Package Version and Platform:**
 - Platform: Aby
 - Package and version: Master branch

**Steps to Reproduce**
We sometime see error in CI test result (and so far we cannot determine if it is really an error or not)

**Expected results**
Having different debug/info message for the three case so that we  can easilly determine if replication is really broken or not.

**Comment by mreynolds389** [comment]
@progier389 - can you cherry pick this down to 1.4.3 as well?  Thanks!

**Comment by progier389** [comment]
b15004051129c87aa993668cfeecc8dbe9a40e14
   fbcaf84d5..b15004051  masterr
   b6d2fa4e4..88da0060a  389-ds-base-2.1 -> 389-ds-base-2.1
   720c3fe9c..33c3f79a9  389-ds-base-2.0 -> 389-ds-base-2.0
   6342f8654..0b57fbf45  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   6342f8654..0b57fbf45  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
