### ISSUE TITLE
Report Portal 5 is not processing test results XML file

### ISSUE THREAD

**Issue by aadhikar** [389ds/389-ds-base#5294]
**Issue Description**
Report Portal 5 is not processing an XML file with test parameters exceeding 1024 char.

**Steps to Reproduce**
1. Run a test case for example: ```dirsrvtests/tests/suites/filter/large_filter_test.py::test_large_filter```

**Expected results**
Test results XML should be processed correctly.

**Comment by tbordaz** [comment]
682bbfb5c..39d843cc0 : main
f3fd6ec20..05c0a45f9 : main
203085c1c..b165bdfb4  389-ds-base-1.4.3
