### ISSUE TITLE
Release tarballs don't contain cockpit webapp

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#5302]
**Issue Description**
Ubuntu package since 389-ds-base-2.0.15 doesn't contain cockpit webapp: 
https://bugs.launchpad.net/ubuntu/+source/389-ds-base/+bug/1974329

The issue is that release tarballs on GitHub do not contain precompiled webapp. They are generated automatically from the git tags. Prior to that we distributed release tarballs on Pagure, where they were prepared with `dist-bz` target and contained all the required files.

Also, current release tarballs contain top-level directory with the duplicated name such as `389-ds-base-389-ds-base-2.0.15`, because we also use `389-ds-base` in our tag names.

We should generate proper release tarballs and provide source-only and source + vendored dependencies tarballs so that they can be easily consumed by the downstream distributions.

**Comment by vashirov** [comment]
1a12df47c..9951c1101  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   43bedfc5c..1ea6a6803  389-ds-base-2.0 -> 389-ds-base-2.0
   b903bc074..faef73366  389-ds-base-2.1 -> 389-ds-base-2.1

**Comment by tjaalton** [comment]
so it's available only on the release tarballs, not on the tarballs based on tags?

**Comment by vashirov** [comment]
It's not checked in git. Once there is a new tag, a new tarball is generated:
https://github.com/389ds/389-ds-base/releases

**Comment by tjaalton** [comment]
I guess that's fine, it's just harder to automatically grab the release tarball nowadays, but I'll get there..

**Comment by vashirov** [comment]
It should follow scheme https://github.com/389ds/389-ds-base/releases/download/389-ds-base-${VERSION}/389-ds-base-${VERSON}.tar.bz2.
For example, latest release tarballs are at:
https://github.com/389ds/389-ds-base/releases/download/389-ds-base-2.3.0/389-ds-base-2.3.0.tar.bz2
https://github.com/389ds/389-ds-base/releases/download/389-ds-base-2.2.3/389-ds-base-2.2.3.tar.bz2
https://github.com/389ds/389-ds-base/releases/download/389-ds-base-2.1.5/389-ds-base-2.1.5.tar.bz2

**Comment by tjaalton** [comment]
looks like there are two tarballs now, one for the actual source and another for the vendored stuff

**Comment by tjaalton** [comment]
the .bz2 has only the vendored bits, not source

**Comment by vashirov** [comment]
Hmm, looks like the tarball has `vendor` and cockpit stuff, but not the actual 389-ds-base source. I'll investigate.
