### ISSUE TITLE
cockpit_present() assumes rpm is used

### ISSUE THREAD

**Issue by tjaalton** [389ds/389-ds-base#5351]
**Issue Description**
Running 'dsctl ds cockpit enable' fails on Debian, because it's trying to use rpm to see if 'cockpit' is installed.

**Package Version and Platform:**
 - Platform: Debian based distros

**Steps to Reproduce**
# dsctl ds cockpit enable
/bin/sh: 1: rpm: not found
Error: The 'cockpit' package is not installed on this system

cockpit_present() should detect that the distro is based on Debian, and use 'dpkg-query -s cockpit' instead (the command returns an error if a package is not installed, and package metadata if it is)

**Comment by mreynolds389** [comment]
@tjaalton - On Debian does this command still work:

    sudo systemctl enable --now cockpit.socket

**Comment by tjaalton** [comment]
I don't see a reason why it wouldn't work, can't check myself now.
