### ISSUE TITLE
1.4 / 2.0 with openldap migration fails

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#5352]
We recently fixed up the migration to properly handle certain cases such as when it's in containers, but that relies on the _containerised flag being present. This is introduced in 1aaadb8afc9f7a77516d0d62fa3acbb2bbfcfe8a and not in 1.4 and 2.0. It is present in 2.1 and master. 

@mreynolds389 Should we back port this, or should we have a work around in openldap_to_ds to check for hasattr(_containerised) instead?

**Comment by mreynolds389** [comment]
I see no problem backporting it

**Comment by Firstyear** [comment]
Thanks mate :)

**Comment by Firstyear** [comment]
```
   8daae835b..0e5044ece  389-ds-base-2.0 -> 389-ds-base-2.0
   deed28c5f..f519ef753  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
```
