### ISSUE TITLE
dsctl fails with ldap.DECODING_ERROR if there are replication entries with DN containing encoded chars

### ISSUE THREAD

**Issue by resposit** [389ds/389-ds-base#5355]
**Issue Description**
This command, spawned in background by cockpit-389-ds, fails with ldap.DECODING_ERROR:
`
dsctl -j  -v <ds-instance> status
`
**Package Version and Platform:**
 - Rocky Linux 8.6
 - python3-lib389-2.0.15-1.module_el8+14185+adb3f555.noarch
 - cockpit-389-ds-2.0.15-1.module_el8+14185+adb3f555.noarch
 - 389-ds-base-devel-2.0.15-1.module_el8+14185+adb3f555.x86_64
 - 389-ds-base-2.0.15-1.module_el8+14185+adb3f555.x86_64
 - 389-ds-base-libs-2.0.15-1.module_el8+14185+adb3f555.x86_64

**Steps to Reproduce**
Create a replication entriy like the one below (with dn containing encoded chars):

```
dn: cn=ac.infn.it @ dsm2-dev > ds1-dev,cn=replica,cn=dc\3Dac\2Cdc\3Dinfn\2Cdc\3Dit,cn=mapping tree,cn=config
objectClass: top
objectClass: nsDS5ReplicationAgreement
cn: ac.infn.it @ dsm2-dev > ds1-dev
description: Replication of "dc=ac,dc=infn,dc=it" from dsm2-dev.infn.it to ds1-dev.infn.it
nsDS5ReplicaHost: ds1-dev.infn.it
...
...
```

**Expected results**
On a working instance, the output should look like this:
```
[root@ds1 ~]# dsctl -j  -v ds1 status
DEBUG: The 389 Directory Server Administration Tool
DEBUG: Inspired by works of: ITS, The University of Adelaide
DEBUG: Called with: Namespace(func=<function instance_status at 0x7f92742fbf28>, instance='ds1', json=True, list=False, remove_all=False, verbose=True)
DEBUG: Allocate local instance <class 'lib389.DirSrv'> with None
DEBUG: Instance allocated
DEBUG: systemd status -> True
{
    "type": "result",
    "running": true
}
```

On the broken server I get:
```
[root@dsm2-dev ~]# dsctl -j -v dsm2-dev status
DEBUG: The 389 Directory Server Administration Tool
DEBUG: Inspired by works of: ITS, The University of Adelaide
DEBUG: Called with: Namespace(func=<function instance_status at 0x7f0b42503f28>, instance='dsm2-dev', json=True, list=False, remove_all=False, verbose=True)
Traceback (most recent call last):
  File "/usr/sbin/dsctl", line 127, in <module>
    insts = inst.list(serverid=args.instance)
  File "/usr/lib/python3.6/site-packages/lib389/__init__.py", line 740, in list
    instances.append(_parse_configfile(dse_ldif, serverid))
  File "/usr/lib/python3.6/site-packages/lib389/__init__.py", line 686, in _parse_configfile
    ldifconn = LDIFConn(filename)
  File "/usr/lib/python3.6/site-packages/lib389/_ldifconn.py", line 36, in __init__
    self.parse()
  File "/usr/lib64/python3.6/site-packages/ldif.py", line 461, in parse
    return self.parse_entry_records() # parse()
  File "/usr/lib64/python3.6/site-packages/ldif.py", line 451, in parse_entry_records
    self.handle(dn,entry)
  File "/usr/lib/python3.6/site-packages/lib389/_ldifconn.py", line 47, in handle
    self.dndict[normalizeDN(dn)] = newentry
  File "/usr/lib/python3.6/site-packages/lib389/utils.py", line 382, in normalizeDN
    ary = ldap.explode_dn(dn.lower())
  File "/usr/lib64/python3.6/site-packages/ldap/dn.py", line 78, in explode_dn
    dn_decomp = str2dn(dn,flags)
  File "/usr/lib64/python3.6/site-packages/ldap/dn.py", line 52, in str2dn
    return ldap.functions._ldap_function_call(None,_ldap.str2dn,dn,flags)
  File "/usr/lib64/python3.6/site-packages/ldap/functions.py", line 55, in _ldap_function_call
    result = func(*args,**kwargs)
ldap.DECODING_ERROR
```

**Additional context**
Looking at the other issues, this may be related to #5353

**Comment by resposit** [comment]
Hi, any chance someone could take a look at this ? Thanks

**Comment by progier389** [comment]
Hi,
The DN is indeed invalid (according to RFC rfc 4514 the > should be escaped). 
 and BTW the server should also fail to start.

Note: with the latest version from master branch and creating the agreement with dsconf, the dn is ok:
 dn: cn=ac.infn.it @ dsm1-dev \3E ds2-dev,cn=replica,cn=dc\3Dac\2Cdc\3Dinfn\2Cdc\3Dit,cn=mapping tree,cn=config
So either you edited directly the dse.ldif with a wrong dn or your version of dsconf is buggy 
 (but if it is the case that bug is now fixed) 
==> Closing the issue.

**Comment by resposit** [comment]
@progier389 Thank you very much !
Actually, I created repl. agreement entries via ldapadd, using a very old perl script. I didn't realize ">" was not escaped :-(
Strangely the Rocky8 server starts correctly even with those malformed DNs.
Moreover, in my prod evironoment still running on Centos7, everything have been working correctly for ages...
