### ISSUE TITLE
Retro Changelog trimming does not work

### ISSUE THREAD

**Issue by keestux** [389ds/389-ds-base#5368]
**Issue Description**
The changelog trimming uses maxage incorrectly to decide if trimming is needed.

**Package Version and Platform:**
 - Platform: CentOS 8-Stream
 - Package and version: 389-ds-base-1.4.3.28-6.module_el8.6+1102+fe5d910f.x86_64

**Steps to Reproduce**
No exact steps to reproduce

**Expected results**
Old changelog entries must be deleted based on `nsslapd-changelogmaxage`.

**Additional context**
DIscussed on the 389-users mailing list with subject: Retro Changelog trimming not working

The following code in retrocl_trim.c uses maxage incorrectly.
```
        int must_trim = 0;
        /* See if we need to trim */
        /* Has enough time elapsed since our last check? */
        if (cur_time - ts.ts_s_last_trim >= (ts.ts_c_max_age)) {        <<<<<<==== wrong condition
            /* Is the first entry too old? */
            time_t first_time;
            time_t now_maxage = slapi_current_utc_time(); /* real time for trimming candidates */
            /*
             * good we could avoid going to the database to retrieve
             * this time information if we cached the last value we'd read.
             * But a client might have deleted it over protocol.
             */
            first_time = retrocl_getchangetime(SLAPI_SEQ_FIRST, &ldrc);
            slapi_log_err(SLAPI_LOG_PLUGIN, RETROCL_PLUGIN_NAME,
                          "cltrim: ldrc=%d, first_time=%ld, cur_time=%ld\n",
                          ldrc, first_time, cur_time);
            if (LDAP_SUCCESS == ldrc && first_time > (time_t)0L &&
                first_time + ts.ts_c_max_age < now_maxage)
            {
                must_trim = 1;
            }
        }
```
See the line marked with "wrong condition". The check is not needed in the first place. There is already an interval mechanism with which the housekeeping is done. Secondly, `ts_c_max_age` is not the right value to use. If we really want to avoid too many database checks we could use `trim_interval`. That said, we already have `slapi_eq_repeat_rel(retrocl_housekeeping...`, so why bother?

**Comment by mreynolds389** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2124660
