### ISSUE TITLE
Code cleanup: Fix Covscan invalid reference

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5377]
**Issue Description**
 - Fix errors listed at https://cov01.lab.eng.brq.redhat.com/covscanhub/waiving/95389/263550/#defects
 - Jira ticket is: https://issues.redhat.com/browse/IDMDS-2394

**Comment by progier389** [comment]
As a preliminary phase I run a covscan on the main branch build and got the following result: 

Task URL: https://cov01.lab.eng.brq.redhat.com/covscanhub/task/257865/
Comment: None


All defects

ARRAY_VS_SINGLETON        9
BAD_COMPARE               1
BAD_FREE                  2
BUFFER_SIZE               8
CHECKED_RETURN            18
CLANG_WARNING             336
COMPILER_WARNING          26
CONSTANT_EXPRESSION_RESULT 4
COPY_PASTE_ERROR          8
CPPCHECK_WARNING          38
DC.WEAK_CRYPTO            5
DEADCODE                  22
FORWARD_NULL              47
GCC_ANALYZER_WARNING      89
LOCK                      4
MISSING_BREAK             5
MISSING_LOCK              5
NEGATIVE_RETURNS          3
NO_EFFECT                 1
NULL_RETURNS              2
OVERRUN                   18
RESOURCE_LEAK             29
REVERSE_INULL             11
SENSITIVE_DATA_LEAK       1
SHELLCHECK_WARNING        4
SIZEOF_MISMATCH           6
STRING_OVERFLOW           16
TAINTED_SCALAR            4
TAINTED_STRING            1
TOCTOU                    6
UNINIT                    3
UNREACHABLE               2
UNUSED_VALUE              16
USELESS_CALL              3
USE_AFTER_FREE            12

Within this issue, I intend to fix the 
- COMPILER_WARNING (They are in most case serious errors )
- FORWARD_NULL
- NULL_RETURNS
- REVERSE_INULL

Once it is done, merged and cherry picked I will have to redo a covscan on 2.1 branch to insure and fix the remaining issue in this banch

Other issues will be created to fix other error types

**Comment by mreynolds389** [comment]
@progier389 - please cherry pick down to 2.1

**Comment by progier389** [comment]
db3e8c0b2c6c216afffc0149e7d8bacb2b5d6aff
   24d00236e..db3e8c0b2  main       -> origin/main
   22014da3e..e20e862f8  389-ds-base-2.1 -> 389-ds-base-2.1
