### ISSUE TITLE
dscreate fails when using alternative ports in the SELinux `hi_reserved_port_t` label range

### ISSUE THREAD

**Issue by wanderboessenkool** [389ds/389-ds-base#5392]
**Issue Description**
When trying to install a new instance on alterative port numbers the `dscreate` tool fails when one of the ports used is labelled by SELinux as `hi_reserved_port_t`

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 389-ds-base-2.1.3-2.fc36.x86_64.rpm
 - Browser N/A

**Steps to Reproduce**
1. Create an .inf file
2. set secure_port to 637
3. run `dscreate from-file <inf-file>

**Expected results**
An instance is created and configured

**Screenshots**
```
Starting installation ...
Validate installation settings ...
Create file system structures ...
Create self-signed certificate database ...
Error: Instance creation failed!  Port 637 was already labeled with: (hi_reserved_port_t)  Please choose a different port number
```

**Comment by mreynolds389** [comment]
fbcd472dd..22014da3e  389-ds-base-2.1 -> 389-ds-base-2.1
e2a858a86..57392021b  389-ds-base-2.0 -> 389-ds-base-2.0
