### ISSUE TITLE
Sync_repl may crash while managing invalid cookie

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#5418]
**Issue Description**
If a ldapclient sends specific cookie without meta character '#' then sync_repl may crash

**Package Version and Platform:**
since 1.3.9

**Steps to Reproduce**
testcase provided in patch

**Expected results**
It should not crash

**Comment by Firstyear** [comment]
@tbordaz @mreynolds389 this will probably need to be applied to 1.4 as well as 2.0?

**Comment by tbordaz** [comment]
@Firstyear thanks for your review. You are correct it applies to several branches, I set milestone to 1.3.10

**Comment by tbordaz** [comment]
3cda974c1..513a763b5 main
8837f3137..874d2de7e  389-ds-base-2.1
85965d1d0..19632a4b8  389-ds-base-2.0
7a611298d..be599560c  389-ds-base-1.4.4
eebd91b04..b45bdc53c  389-ds-base-1.4.3
5594c3dac..bd566957f  389-ds-base-1.3.10

**Comment by mreynolds389** [comment]
This was not properly cherry-picked to 1.4.3.  The actual fix was removed from the commit.  This is going to impact a lot of releases :-(

**Comment by tbordaz** [comment]
I am really sorry of that. I do not know how I could have wrongly cherry-pick this simple fix. It looks to me that upstream, only 1.4.3 was impacted by this error (fixed now with ac351252f..f5cafd3b5 389-ds-base-1.4.3).
