### ISSUE TITLE
Typo in lib389/instance/options.py

### ISSUE THREAD

**Issue by Elwell** [389ds/389-ds-base#5423]
"If false, the instance is created but started." seems to be missing a 'not' 
(PR incoming)

**Comment by mreynolds389** [comment]
52c1e523f..33a2f0f65  389-ds-base-2.1 -> 389-ds-base-2.1
1ea849966..219f047ae  389-ds-base-2.0 -> 389-ds-base-2.0
e7d5f6b8d..1d8036a57  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
