### ISSUE TITLE
"dsconf instance backend delete" is missing the non-interactive --do-it option

### ISSUE THREAD

**Issue by minfrin** [389ds/389-ds-base#5425]
**Issue Description**
The "dsconf instance backend delete" includes the interactive behaviour "Type 'Yes I am sure' to continue", but lacks the --do-it option used elsewhere in 389ds to allow non-interactive use.

**Package Version and Platform:**
 - Platform: RHEL9
 - Package and version: 389-ds-base-2.0.14-1.el9.x86_64
 - Browser: none

**Steps to Reproduce**
1. Run "dsconf "ldapi://%2frun%2fslapd-${instance}.socket" backend delete "${bename}""
2. See prompt "Type 'Yes I am sure' to continue:"

**Expected results**
The addition of --do-it causes success.

**Comment by mreynolds389** [comment]
In main branch it works without any confirmation:

$ sudo dsconf slapd-localhost backend create --be-name markRoot --suffix o=mark --create-suffix
The database was sucessfully created

$ sudo dsconf slapd-localhost backend delete o=mark
The database, and any sub-suffixes, were sucessfully deleted

The 2.0 branch _should_ behave the same way - I need to confirm that though...

On a side note I noticed we have a typo with "sucessfully" in the result messages:

lib389/cli_conf/backend.py:    log.info("The database was sucessfully created")
lib389/cli_conf/backend.py:    log.info("The database, and any sub-suffixes, were sucessfully deleted")
