### ISSUE TITLE
memberof is slow on update/fixup if there are several 'groupattr'

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#5440]
**Issue Description**
Memberof can be configured with several membership attribute (member, uniquemember,..)
When fixing (create memberof values) an entry, memberof plugin searches the groups owning that entry using a filter that contains all the membership attributes. The drawbacks are

- it mixes the relation, so G2 --member--> G1 -- uniquemember--> U1, then U1.memberof=[G1,G2]
- it forces the internal search to reevaluate the filter (|(member=U1)(uniquemember=U2) although both attributes are index

**Package Version and Platform:**
all version

**Steps to Reproduce**
To be done

**Expected results**
Fixup is very slow

**Comment by tbordaz** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=2123525

**Comment by tbordaz** [comment]
7e701e2c3..7283a57b7 main
0ebbb26f8..78ee3a5a4  389-ds-base-2.2
8fdbe5947..b5e5afb7f  389-ds-base-2.1
d15a0a7f1..ef2ec82e2  389-ds-base-2.0
136fc8448..ce0bda67e  389-ds-base-1.4.4
620f96fb4..9ba2cd33d  389-ds-base-1.4.3

still fighting for 1.3.10...

**Comment by tbordaz** [comment]
d08a0e414..813c8cd6f  389-ds-base-1.3.10

**Comment by droideck** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2170218
