### ISSUE TITLE
Fix some covscan issues

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5446]
**Issue Description**
Civscan reports a number of "Important" issues:
      2	BAD_FREE                                        	incorrect_free
      3	BUFFER_SIZE                                     	buffer_size_warning
      6	COPY_PASTE_ERROR                                	copy_paste_error
      3	CPPCHECK_WARNING                                	error[resourceLeak]
      2	IDENTICAL_BRANCHES                              	identical_branches
     13	RESOURCE_LEAK                                   	leaked_storage
      1	RESOURCE_LEAK                                   	overwrite_var
      4	USE_AFTER_FREE                                  	deref_arg
      3	USE_AFTER_FREE                                  	double_free
      1	USE_AFTER_FREE                                  	pass_freed_arg
Details are in  [https://cov01.lab.eng.brq2.redhat.com/covscanhub/task/260426/log/389-ds-base-2.3.0-202209121502gitd5ba53748.fc36/scan-results-imp.html](https://cov01.lab.eng.brq2.redhat.com/covscanhub/task/260426/log/389-ds-base-2.3.0-202209121502gitd5ba53748.fc36/scan-results-imp.html)

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main branch on 2022, 12 Sept

**Steps to Reproduce**

1. SKIP_AUDIT_CI=1 make -f rpm.mk srpms
2. covscan mock-build --config=fedora-36-x86_64 ./dist/srpms/389-ds-base-*.src.rpm

**Comment by mreynolds389** [comment]
@progier389 please backport this down to 1.4.3 (if it applies)...

**Comment by progier389** [comment]
a0d15b46b7c060b745e2677679aa4c216c462a55

  bb6029d44..a0d15b46b  main -> main
   e57e63d03..2e18a0f2c  389-ds-base-2.2 -> 389-ds-base-2.2
   8989c0209..16a3b0210  389-ds-base-2.1 -> 389-ds-base-2.1
   256404b86..7526129e2  389-ds-base-2.0 -> 389-ds-base-2.0
   c900a28c8..9e6ef10b4  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   9c761421c..d6fca5eaf  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
