### ISSUE TITLE
Missing default indexes

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#5462]
We have encountered a number of issues with users where default indexes for uidNumber and gidNumber are missing, which can affect the performance of SSSD/nss_ldap. We should provide these by default since they are part of our rfc2307compat schema.

**Comment by mreynolds389** [comment]
We already had a ticket open for this.  I've repeated brought this ticket up, but we never seemed to get around to it :-(

https://github.com/389ds/389-ds-base/issues/2464

Just need to check with IPA that it doesn't break their installer

**Comment by Firstyear** [comment]
I think if it breaks their installer, then they should fix that as we also benefit from this change greatly.
