### ISSUE TITLE
Increase the default value of nsslapd-conntablesize

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#5469]
**Description of problem**
There are quite often customer cases about shortage of file descriptors and LDAP client requests not being processed. The shortage is usually caused by a low value set for the nsslapd-conntablesize parameter.

**Solution**
Increase the default value for nsslapd-conntablesize 

**Additional context**
https://issues.redhat.com/browse/IDMDS-2526

**Comment by mreynolds389** [comment]
We also dynamically set the max fd's based off systemd config.  You can see it happening in the errors log:

    [30/Sep/2022:08:39:38.323920871 -0400] - INFO - main - Setting the maximum file descriptor limit to: 524288

Perhaps look into how we are doing it here so that we are consistent with conn table size.

**Comment by jchapma** [comment]
> As far as I understand thing the conntablesize is set to the maximum number of open file for the process, (The one that you get with ulimit -n ) so IMHO we should increase the soft limit to the hard limit (using getrlimit and setrlimit ) when statring up the process

Currently the default conntablesize is obtained from the system fd soft limit, by default this is 1024. Yes we could set the process soft limit to match the hard limit, but as conntable memory is preallocated that might result in a lot of unused memory. Each connection takes roughly 40B, so to match the hard limit on my system would use ~20M of memory. Maybe that's not a big deal, would a default conntablesize of 10k not be enough ?

**Comment by mreynolds389** [comment]
> > As far as I understand thing the conntablesize is set to the maximum number of open file for the process, (The one that you get with ulimit -n ) so IMHO we should increase the soft limit to the hard limit (using getrlimit and setrlimit ) when statring up the process
> 
> Currently the default conntablesize is obtained from the system fd soft limit, by default this is 1024. Yes we could set the process soft limit to match the hard limit, but as conntable memory is preallocated that might result in a lot of unused memory. Each connection takes roughly 40B, so to match the hard limit on my system would use ~20M of memory. Maybe that's not a big deal, would a default conntablesize of 10k not be enough ?

IMHO I think that would be a sufficient default for most deployments, but I'd be curious what other teammates think...
