### ISSUE TITLE
UI - Add rework and finish jpegPhoto functionality

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#5491]
**Description**
Support of binary values, specifically jpegPhoto (and displaying it in the UI) was started in the original code merge from Teko, but it is not complete and should be finished.

**Comment by mreynolds389** [comment]
Please cherry pick down to 1.4.3

**Comment by droideck** [comment]
d6169d044..2cffafe05  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   39b6ad632..f16a61069  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   e5a5308ad..c171b6ad7  389-ds-base-2.0 -> 389-ds-base-2.0
   5d37fd44d..7c3981e2d  389-ds-base-2.1 -> 389-ds-base-2.1
   326a4aa0f..59a9707f4  389-ds-base-2.2 -> 389-ds-base-2.2
