### ISSUE TITLE
Boolean LDAP Attribute Syntax too scrict

### ISSUE THREAD

**Issue by apateczechmeister** [389ds/389-ds-base#5497]
**Issue Description**
[RFC 4517 #3.3.3](https://www.rfc-editor.org/rfc/rfc4517#section-3.3.3) defines the `Boolean` Attribute with OID 1.3.6.1.4.1.1466.115.121.1.7 in the ABNF

    Boolean = "TRUE" / "FALSE"

[RFC 4517 #3.3.3](https://www.rfc-editor.org/rfc/rfc4517#section-3.3.3) refers to [RFC 4512 #1.4](https://www.rfc-editor.org/rfc/rfc4512#section-1.4) for the syntax definition, which further refers to [RFC 4234](https://www.rfc-editor.org/rfc/rfc4234) which defines ABNF as an *case insensitive* syntax - as does [RFC 7405 #1](https://datatracker.ietf.org/doc/html/rfc7405#section-1) which enhances RFC 4234 with a case sensitive description.

**Package Version and Platform:**
 - RHEL 7.9
 - Package and version: 389-ds-base-1.3.10.2-16.el7_9.x86_64
 - Browser firefox

**Steps to Reproduce**
1. To a default installation add the following schema definition
````
[user@host ~]$ sudo -- cat /etc/dirsrv/slapd-ldap1-dev/schema/99user.ldif
# user schema
################################################################################
dn: cn=schema
#
################################################################################
#
attributetypes: ( 1.3.6.1.4.1.59369.1.1
  NAME 'emailVerified'
  DESC 'User has successfully verified his/her current email'
  SYNTAX 1.3.6.1.4.1.1466.115.121.1.7
  SINGLE-VALUE
  USAGE userApplications
  X-ORIGIN ('APA-IT defined' 'user defined') )
#
################################################################################
#
objectclasses: ( 1.3.6.1.4.1.59369.2.1
  NAME 'apaitIamPerson'
  SUP inetOrgPerson
  AUXILIARY
  MAY (emailVerified)
  X-ORIGIN ('APA-IT defined' 'user defined') )
[user@host ~]$
````
2. Create at some path an `apaitIamPerson` object without our new attribute
4. Try to run `ldapmodify` with the following input
````
[user@host ~]$ cat meins.ldif 
dn: uid=user,ou=users,dc=top
changetype: modify
replace: emailVerified
emailVerified: false
-
[user@host ~]$ 
````
5. ds-389 will respond with
````
ldap_initialize( ldaps://host:636/??base )
replace emailVerified:
	false
modifying entry "uid=user,ou=users,dc=top"
ldap_modify: Invalid syntax (21)
	additional info: emailVerified: value #0 invalid per syntax
````

**Expected results**
Boolean values are treated case-insensitive
````
ldap_initialize( ldaps://host:636/??base )
replace emailVerified:
	false
modifying entry "dn: uid=user,ou=users,dc=top"
modify complete
````

**Additional context**
ds-389 is used as user federation storage in our [Keycloak (KC)](https://github.com/keycloak/keycloak) installation configured with vendor typ `rhds`. KC 19.0.3 sends lowercase bools - at least for the `emailVerified` user attribute - which are unfortunately rejected.

**Comment by mreynolds389** [comment]
In our code we have the boolean syntax code in our "Case ignore string" plugin, but we definitely only do case sensitive checks on it.  Fix is out for review...

**Comment by mreynolds389** [comment]
fbafd432f..f79182f84  389-ds-base-2.2 -> 389-ds-base-2.2
2512f7b20..3feb1a3f0  389-ds-base-2.1 -> 389-ds-base-2.1
27df56c42..4e256dbfb  389-ds-base-2.0 -> 389-ds-base-2.0
dcda92f0c..4e50ac091  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
015c9abdf..1afd3eea8  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
8012b9da1..3199c73b8  389-ds-base-1.3.10 -> 389-ds-base-1.3.10

@apateczechmeister Sorry it took so long to get to this one.

**Comment by droideck** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2170221
