### ISSUE TITLE
Compiler warning in retrocl_trim.c

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#5505]
**Issue Description**
Typo causes compiler warning in retrocl_trim.c

**Package Version and Platform:**
 - Platform: Fedora 32
 - Package and version: 389-ds-base-2.3.0

**Steps to Reproduce**
1. Run make on main branch

**Comment by droideck** [comment]
becbfa96b..fde40a6dc  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   6e717b525..a294c1d57  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   1277d90da..604a06aa8  389-ds-base-2.0 -> 389-ds-base-2.0
   64d2f6288..e163db607  389-ds-base-2.1 -> 389-ds-base-2.1
   146d1742a..58dd38812  389-ds-base-2.2 -> 389-ds-base-2.2
