### ISSUE TITLE
Backport `twalk_r` from glibc

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#5510]
**Issue Description**
Since version 2.1 we use `twalk_r` function that is available in glibc-2.30 and newer. This prevents building 389-ds on platforms with older glibc such as EL8.

We should backport it from https://sourceware.org/git/?p=glibc.git;a=blob;f=misc/tsearch.c;h=852cadf7b93e880099a58111c4823df68a450ba4;hb=HEAD

**Comment by progier389** [comment]
Maybe we should then rather replace the twalk_r by twalk and a global variable 
 ( Note the only call to this function is in db-mdb module and protected by a global mutex ( dbis_lock ) so there is no concurrent access issue )

**Comment by progier389** [comment]
a8392bc74eca5a26a5a6ac4874062146a18b16b7

   fdb7393e4..a8392bc74  main -> main
   4a1e3bd4d..dde3fc662  389-ds-base-2.2 -> 389-ds-base-2.2
   007e21509..c9c7a014a  389-ds-base-2.1 -> 389-ds-base-2.1
