### ISSUE TITLE
Pam Pass Through - Multiple issues in setup/config

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#5521]
Setting up Pam Pass Through in it's current form is extremely rocky as a setup process. 

-- rh docs list wrong plugin name.
PAM Pass-Through Auth Plugin
PAM Pass Through Auth

-- dsconf enables the wrong plugin
dsconf localhost plugin pass-through-auth enable
Enables dn: cn=Pass Through Authentication,cn=plugins,cn=config not cn=PAM Pass Through Auth,cn=plugins,cn=config

-- pamMissingSuffix requires a value by default, will be accepted during run time and cause server to fail to start
[11/Nov/2022:11:50:21.048486118 +1000] - ERR - pam_passthru-plugin - pam_passthru_validate_config - Valid values for pamMissingSuffix are ERROR, ALLOW, IGNORE

-- pamSecure when required only emits a plugin trace warn not an error.
[11/Nov/2022:13:35:40.318908742 +1000] - DEBUG - pam_passthru-plugin - pam_passthru_bindpreop - Connection not secure (secure connection required; check config)

**Comment by mreynolds389** [comment]
fa25edc39..3358fd538  389-ds-base-2.2 -> 389-ds-base-2.2
021417a90..e278e74dc  389-ds-base-2.1 -> 389-ds-base-2.1
ba859c701..fae2bf363  389-ds-base-2.0 -> 389-ds-base-2.0
6ad894482..08d57a360  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
