### ISSUE TITLE
Saslauthd migration paths

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#5526]
OpenLDAP is commonly used with saslauthd for external authentication ( https://openldap.org/doc/admin24/security.html#Configuring%20saslauthd ). This is denoted on openldap servers by a config of:

```
 pwcheck_method: saslauthd
 saslauthd_path: /var/run/sasl2/mux
```

Users are then bound to external auth services by a userPassword hash type:

```
 userPassword: {SASL}user@ad.example.com
```

I have now written https://github.com/Firstyear/pam_saslauthd as a "glue" between 389-ds and it's pam pass through infrastructure, and saslauthd. Since it is possible now, we can improve the process of allowing migrations to 389-ds from openldap with these components.

I propose that during an openldap to ds migration, that if a user is detected with the SASL userPassword scheme, then userPassword is removed from the account and we add a "saslauthd_id" field to the entry (along with an extra objectClass). 

We can then use pam pass through with map_method ENTRY and id-attr of saslauthd_id.

The file `/etc/pam.d/saslauthd` would come from the pam_saslauthd package, so it's out of scope here. We just need to do "most of" the configuration at the 389-ds layer.

**Comment by mreynolds389** [comment]
Please backport to:   389-ds-base-2.2, 2.1 and 2.0

**Comment by Firstyear** [comment]
```
   7baa5a15c..7eba9b9d1  389-ds-base-2.2 -> 389-ds-base-2.2
   d8ddb4ac3..66f673d43  389-ds-base-2.1 -> 389-ds-base-2.1
   d9df6a9cc..2ab648697  389-ds-base-2.0 -> 389-ds-base-2.0
```

Thanks @mreynolds389
