### ISSUE TITLE
regression in `lib389.cli_conf.security`

### ISSUE THREAD

**Issue by stanislavlevin** [389ds/389-ds-base#5539]
**Issue Description**

```console
[root@master1 /]# dsconf -v slapd-IPA-TEST security set --tls-protocol-min=TLS1.2
DEBUG: cn=encryption,cn=config set REPLACE: ('sslVersionMin', 'TLS1.2')
DEBUG: name 'log' is not defined
Traceback (most recent call last):
  File "/usr/sbin/dsconf", line 138, in <module>
    result = args.func(inst, None, log, args)
  File "/usr/lib/python3/site-packages/lib389/cli_conf/security.py", line 113, in <lambda>
    p.set_defaults(func=lambda *args: _security_generic_set(*args, attrs_map))
  File "/usr/lib/python3/site-packages/lib389/cli_conf/security.py", line 102, in _security_generic_set
    log.info(f"Successfully updated security configuration ({props.attr})")
NameError: name 'log' is not defined
ERROR: Error: name 'log' is not defined
```
caused by 4a1e3bd4dc51d2dcf25e6907c9a3b5c5e049c14d.

**Package Version and Platform:**
 - Platform: any
 - Package and version: 2.2.4

**Additional context**

**Comment by stanislavlevin** [comment]
Something like this would be enough:
```diff
- def _security_generic_set(inst, basedn, logs, args, attrs_map):
+ def _security_generic_set(inst, basedn, log, args, attrs_map):
```

**Comment by progier389** [comment]
Cherry-picked up to 1.4.3 as Issue 5162
b0f8c322aa926236b85b86afc62e4dfebde4fb0e
   3e814cfba..b0f8c322a  main -> main
   c3e13e2ff..12c14ed15  389-ds-base-2.2 -> 389-ds-base-2.2
   42317b6a3..9fb57346b  389-ds-base-2.1 -> 389-ds-base-2.1
   1fa6f9bac..1349aef84  389-ds-base-2.0 -> 389-ds-base-2.0
   bac154026..114c7cb89  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   e70d77d09..d573ceb2c  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
