### ISSUE TITLE
typo in `lib389.cli_conf.backend._get_backend`

### ISSUE THREAD

**Issue by stanislavlevin** [389ds/389-ds-base#5541]
**Issue Description**
```console
[root@master1 /]# dsconf -v IPA-TEST backend suffix get nonexistent
...
DEBUG: name 'name' is not defined
Traceback (most recent call last):
  File "/usr/sbin/dsconf", line 138, in <module>
    result = args.func(inst, None, log, args)
  File "/usr/lib/python3/site-packages/lib389/cli_conf/backend.py", line 159, in backend_get
    be = _get_backend(inst, rdn)
  File "/usr/lib/python3/site-packages/lib389/cli_conf/backend.py", line 110, in _get_backend
    raise ValueError('Could not find backend suffix: {}'.format(name))
NameError: name 'name' is not defined
ERROR: Error: name 'name' is not defined
```

**Package Version and Platform:**
 - Platform: any
 - Package and version: 2.2.4

`name` should be replaced with `be_name`.

**Comment by progier389** [comment]
3e814cfba6b74a74bb91fe5dfe62486f27613e57

   ba9d8b3b9..3e814cfba  main -> main
   12c14ed15..d25f9eb5e  389-ds-base-2.2 -> 389-ds-base-2.2
   9fb57346b..a5cbae769  389-ds-base-2.1 -> 389-ds-base-2.1
   1349aef84..9447f5fa6  389-ds-base-2.0 -> 389-ds-base-2.0
   114c7cb89..81e110ca4  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   d573ceb2c..990ffe26e  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
