### ISSUE TITLE
automember plugin improvements

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5547]
**Issue Description**

Previously the automember rebuild task you first go through all the automember rules and remove all the memberships, then it would rebuild them from scratch.  This was very expensive, and in the case where several be_txn plugins were enabled it would be even worse.

There was no restriction on how many fixup tasks can be run in parallel - there should only be one allowed at a time.

In the case of memberOf, or other be_txn plguins, being enabled, this could trigger automember plugin to be called more than once even though the user/group was already processed in the same thread.

**Comment by tbordaz** [comment]
@mreynolds389 , any reason to keep the ticket opened. It looks the PR was pushed upstream a long time ago

**Comment by mreynolds389** [comment]
> @mreynolds389 , any reason to keep the ticket opened. It looks the PR was pushed upstream a long time ago

It might have been left open for backporting, but I tihnk thats already happened.  I'll close this ticket for now.
