### ISSUE TITLE
dscreate fails with "Error: Can't contact LDAP server - 111 - Connection refused" when instance doesn't start up fast enough on systemd

### ISSUE THREAD

**Issue by XANi** [389ds/389-ds-base#5557]
Long story short:

    # dscreate from-file main-tpl.inf 
    Starting installation...
    Error: Can't contact LDAP server - 111 - Connection refused

strace shows it tried to open socket before server finished starting, i.e. immediately after systemctl start finishes it tried to get the socket.

my dumb fix was just adding delay after `systemctl start`  in lib389/lib389/__init__.py

```diff
@@ -1071,6 +1079,7 @@
             self.log.debug("systemd status -> True")
             # Do systemd things here ...
             subprocess.check_output(["systemctl", "start", "dirsrv@%s" % self.serverid], stderr=subprocess.STDOUT)
+            time.sleep(10)
         else:
             self.log.debug("systemd status -> False")
             # Start the process.
```
but realistically it should poke a socket few times before giving up, to let the 389-ds actually boot up and start serving requests on socket.

It  happened on current Debian release (so 4.4.11 version) but it doesn't look at first glance that much have changed in code so probably it is still broken

**Comment by Firstyear** [comment]
@XANi Can you show the systemd unit file in use? 389-ds makes use of the systemd notify system so systemctl start will always wait for the server to be ready. Perhaps the debian unit file is missing this?

**Comment by XANi** [comment]
eh, disregard that, I had fix for https://pagure.io/389-ds-base/issue/49298 in our configuration management and didn't revert that fix with new release, it works fine now. sorry for bother

**Comment by Firstyear** [comment]
@XANi No bother at all - let us know if we can do anything else to help :)
