### ISSUE TITLE
Nightly tests are failing

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#5561]
**Issue Description**
Latest working job:
https://github.com/389ds/389-ds-base/actions/runs/3644095039/jobs/6153145448

First failing job:
https://github.com/389ds/389-ds-base/actions/runs/3653344884/jobs/6172866948

**Comment by vashirov** [comment]
442e973a8..36e32f4d1  389-ds-base-2.1 -> 389-ds-base-2.1
   8a6e7be08..216c14d62  389-ds-base-2.2 -> 389-ds-base-2.2

**Comment by progier389** [comment]
The test are once again broken. Sometime else should have changed and some python modules are missing.
See PR 5567
