### ISSUE TITLE
dscreate from-file does not work with custom config_dir

### ISSUE THREAD

**Issue by madfeliks** [389ds/389-ds-base#5564]
**Issue Description**
If set instance_name like ds389-01 and config_dir like /opt/conf/{instance_name} in setup.inf, then after running dscreate an exception will be thrown: 

```
AssertionError: Instance failed to install, does not exist when expected"
```

because: 

```
list() ds389-01 instance not found: missing /etc/dirsrv/slapd-ds389-01/dse.ldif
```

i.e. dscreate looks for dse.ldif in default config_dir: "/etc/dirsrv/slapd-{instance_name}"

**Package Version and Platform:**
 - Platform: docker archlinux:latest
 - Package and version: 389-ds-base 2.3.1-1 .x86_64]

**Steps to Reproduce**
1. Copy /usr/share/dirsrv/inf/defaults.inf to /opt/setup.inf
2. Set:

    ```
    [slapd]
    instance_name = ds389-01
    sysconf_dir = /etc
    config_dir = /opt/conf/{instance_name}
    ```

3. Run
`dscreate -v from-file /opt/setup.inf`

**Expected results**
get whole configuration in /opt/conf/ds389-01 directory

**Comment by vashirov** [comment]
`config_dir` is not meant to be user configurable from the template:
```
$ dscreate create-template | grep config_dir -c
0
```

If you want to run this in a container and separate the data, I recommend to use `dscontainer` as an entry point. It expects all data to be in `/data` volume, so you need to set it up first. See for example this Containerfile: https://github.com/vashirov/ds-container/blob/main/fedora-minimal/Containerfile

**Comment by Firstyear** [comment]
This is intentional. You should use the standard directories. The non-standard config dir is only possible in CI/CD tests due to how the python setup works. In addition, changing any of the directory locations will probably break selinux and DAC permissions. 

Dscontainer as @vashirov mentioned is designed to work with /data/config, so you can use that.

**Comment by madfeliks** [comment]
Ok, thanks for your explanation
