### ISSUE TITLE
lib389 password policy DN handling is incorrect 

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#5585]
**Issue Description**
After a migration between major DS versions, it can happen that already existing password policies will have 'cn' that contains a valid DN in double quote "<DN>".  We need to strip the quotes before processing the DN with python-ldap.

**Comment by droideck** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2150813

**Comment by droideck** [comment]
08d57a360..ddc566d92  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   a294c1d57..dcda92f0c  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   fae2bf363..d9df6a9cc  389-ds-base-2.0 -> 389-ds-base-2.0
   e278e74dc..17ac5d2f5  389-ds-base-2.1 -> 389-ds-base-2.1
   3358fd538..51b0e501f  389-ds-base-2.2 -> 389-ds-base-2.2

**Comment by tbordaz** [comment]
@droideck , rereading the patch I have doubt.
The following dn  'cn=nsPwPolicyEntry,ou=\"my policies\",dc=com' could be the value of 'cn'. The patch strips all quotes and double quotes, not only the heading/ending ones. The result is

- cn=nsPwPolicyEntry
- ou=my policies
- dc=com

Where it was 
- cn=nsPwPolicyEntry
- ou="my policies"
- dc=com

Do you think it could be a problem for password policy handling. (I think it is not as 'cn' is just informational attribute)

**Comment by droideck** [comment]
> The following dn 'cn=nsPwPolicyEntry,ou="my policies",dc=com' could be the value of 'cn'. The patch strips all quotes and double quotes, not only the heading/ending ones.

Odd... Was you able to reproduce the issue?
I've tried this in python3 (3.10.9) and all works as expected:

```
>>> dn = '\'cn=nsPwPolicyEntry,ou="my policies",dc=com\''
>>> print(dn)
'cn=nsPwPolicyEntry,ou="my policies",dc=com'
>>> print(dn.strip("\'").strip("\""))
cn=nsPwPolicyEntry,ou="my policies",dc=com

>>> dn = '\"cn=nsPwPolicyEntry,ou="my policies",dc=com\"'
>>> print(dn)
"cn=nsPwPolicyEntry,ou="my policies",dc=com"
>>> print(dn.strip("\'").strip("\""))
cn=nsPwPolicyEntry,ou="my policies",dc=com

>>> dn = 'cn=nsPwPolicyEntry,ou="my policies",dc=com'
>>> print(dn)
cn=nsPwPolicyEntry,ou="my policies",dc=com
>>> print(dn.strip("\'").strip("\""))
cn=nsPwPolicyEntry,ou="my policies",dc=com
```

But maybe I miss something...

**Comment by tbordaz** [comment]
@droideck , no you did not miss anything. I was guess something about python strip("\'")... and I was wrong. Thanks for your answer and sorry for the noise.

**Comment by droideck** [comment]
> @droideck , no you did not miss anything. I was guess something about python strip("'")... and I was wrong. Thanks for your answer and sorry for the noise.

No worries! Thanks for checking anyway!
