### ISSUE TITLE
[Cockpit 389ds plugin] Edit entry bug

### ISSUE THREAD

**Issue by cold01water** [389ds/389-ds-base#5608]
**Issue Description**
An error occurs when trying to assign a value to a constant in editLdapEntry.jsx.

**Package Version and Platform:**
 - Platform: Almalinux
 - Package and version: master branch
 - Browser Edige

**Steps to Reproduce**
Edit ldap entry.

**Additional context**
Changing the following myVal variable to let works.

* editLdapEntry.jsx

```
 796         for (const datum of updateArray) {
 797             const myAttr = datum.attr;
 798             const myVal = datum.val; //here
 799             const isUserPwd = myAttr.toLowerCase() === "userpassword";
 800             isFilePath = false;

```

**Comment by mreynolds389** [comment]
9b858c608..b15a20598  389-ds-base-2.2 -> 389-ds-base-2.2
51e66263e..6195ce9da  389-ds-base-2.1 -> 389-ds-base-2.1
1e36b3407..12a100f18  389-ds-base-2.0 -> 389-ds-base-2.0
2e8fbde0c..497f721f7  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

Ok think I've fixed all the const vs let issues that have been popping up recently
