### ISSUE TITLE
Build failure on Debian

### ISSUE THREAD

**Issue by tjaalton** [389ds/389-ds-base#5610]
**Issue Description**
I'm trying to update the package and enable rust with the vendored crates, but the build fails, logfile attached. I've forced -j1 there but it didn't help with the linking.

**Package Version and Platform:**
 - Platform: Debian
 - Package and version: 2.3.1
[389-ds-base_2.3.1-1_amd64.build.txt](https://github.com/389ds/389-ds-base/files/10456321/389-ds-base_2.3.1-1_amd64.build.txt)

**Comment by mreynolds389** [comment]
@tjaalton - do you need this fix backported to any other versions besides "main"?

**Comment by tjaalton** [comment]
no, I'm fine with 2.3.x
