### ISSUE TITLE
Changing server certificates for 389 Directory Server throws an Unexpected Error in web gui

### ISSUE THREAD

**Issue by rheaalleen** [389ds/389-ds-base#5611]
**Issue Description**

**Package Version and Platform:**
 - Platform: Fedora 37
 - Package and version: 389-ds-base.x86_64 2.2.5-1.fc37
 - Browser: Chrome-based/Firefox

**Steps to Reproduce**
### Explain what happens

1. Installing 389-ds-base per CLI on Fedora 37
2. Using Cockpit add a server/CA certificate in the 389 Directory Server Application
3. Trying to enable TLS/SSL Cockpit refuses to select the item from drop-down menu and throws an error. The Server-Cert is preinstalled and works, selecting your own certificate from the drop down throws the error every time, making it impossible to use your own certificate through the web gui

![image](https://user-images.githubusercontent.com/52893816/212675807-e8cc87c0-b4a6-4975-b22c-cfa87f17fe13.png)

![image](https://user-images.githubusercontent.com/52893816/212675865-7c6b20ac-5709-48be-8282-c36da92839be.png)

![image](https://user-images.githubusercontent.com/52893816/212675936-68a7f825-9c62-43be-87ee-2551c2cb7f84.png)

![image](https://user-images.githubusercontent.com/52893816/212676020-5b3d60c9-d887-46e3-b0f8-144344ba3e9f.png)

**Comment by mreynolds389** [comment]
Wow, yeah the Security page/modal really had a lot of issues if you try and change the Server Certificate.  Anyway looks like I've fixed your issue as well as a bunch of other issues in this area.  Once this is merged I'll be creating new builds...
