### ISSUE TITLE
plug-in for backward compatibility of passwords

### ISSUE THREAD

**Issue by dorokhinra** [389ds/389-ds-base#5621]
It is necessary to implement a plugin to be able to store an encrypted regular password in a separate attribute. Is it possible to intercept passwords in plain text at the time of changing it via sssd, passwd or when the expiration date has expired. Then encrypt it and put it in a separate attribute or pass it to an external subroutine. Such a project already exists for windows (https://github.com/bshp/passwdhk?ysclid=ldai7ipbq5391527902). I can write a plugin, but I can't figure out how to catch an open password. The extended operation for the OID "1.3.6.1.4.1.4203.1.11.1" allows you to intercept it only using the freeipa cli or using ldappasswd, but I need to use kpasswd or sssd, or when the password is expired.

**Comment by Firstyear** [comment]
This sounds like a large security risk to put it mildly. Storing passwords outside of a hash (kdf) can leave them vulnerable to exposure and compromise.

What are you actually trying to achieve here by the creation of this module? What's the end goal you are trying to satisfy.

**Comment by dorokhinra** [comment]
We have older systems where an encrypted public password is used for authentication.  It also has its own windows synchronization module with freeipa, which uses the dll library mentioned above.  We are already moving to new systems and transferring data, but synchronization is necessary for temporary support.  We want the encrypted public password to be temporarily stored in a separate attribute.  Then the scheduler will take this password, decrypt it and set it on other systems where necessary. I understand all the risks, but for a temporary solution, this is necessary.  I just need a way to do it.  You need a place where you can get the user uid and public password.  this will be enough for my synchronization.

**Comment by Firstyear** [comment]
I'm not sure that we offer those hooks in 389-ds, but freeipa has some way of achieving this given it's krb integration. @mreynolds389 do you know how it works?

**Comment by dorokhinra** [comment]
I know that freeipa has an ipa-pwd-extop, which allows you to catch a password at the time of an extended password operation. This works with the freeipa api (e.g. ipa passwd) but it doesn't work if the password has expired. For example, when a user with an expired password logs in via sssd (su username). The kpasswd operation is started, the ipa-pwd-extop does not work here

**Comment by dorokhinra** [comment]
Anyway, thanks for the answer!

**Comment by Firstyear** [comment]
@dorokhinra Yeah, if you are using freeipa you're pretty well out of luck here. There are just too many hooks all over the place in really messy ways. You won't just have "one place" that can catch the pw change.

The best you *might* get is setting the passwordstoragescheme type to AES which is a  password *encryption* rather than KDF mechanism. 

https://access.redhat.com/documentation/en-us/red_hat_directory_server/11/html/administration_guide/user_account_management-managing_the_password_policy
