### ISSUE TITLE
logconv.pl does not correctly show "Peak Concurrent Connections" after log format changes in 389ds v2.1

### ISSUE THREAD

**Issue by aivanov389** [389ds/389-ds-base#5640]
**Issue Description**
logconv.pl does not correctly show "Peak Concurrent Connections" after log format changes in https://github.com/389ds/389-ds-base/issues/5029 . It does not detect correctly the "Disconnect - Cleanly Closed Connection - U1" string used now in logs instead of  "closed error - U1".

**Steps to Reproduce**
1. Install 389ds server with minimal activity
2. logconv.pl  /.../access

**Expected results**
The number of "Peak Concurrent Connections" should be minimal for a low-activity server. logconv.pl insteads shows a huge number since it considers all the opened connections in access log as concurrent. The reason is the incorrect way to detect when they are closed. 

**How to Fix**
One of the possibilities is to make the "connection closed" event detection case-insensitive.
```
@@ -2249,7 +2249,7 @@
                $fdTaken++;
                if ($1 > $highestFdTaken){ $highestFdTaken = $1; }
        }
-       if (m/ fd=/ && m/closed/){
+       if (m/ fd=/ && m/closed/i){
                ($connID) = $_ =~ /conn=(\d*)\s/;
                handleConnClose($connID);
```

There may be other side effects since in https://github.com/389ds/389-ds-base/issues/5029 the word "closed" was replaced by "Disconnect"

**Comment by aivanov389** [comment]
This commit resolves the problem only partially (probably only cleanly closed connections are counted as closed). As i said in the first message, the commit https://github.com/389ds/389-ds-base/commit/26a1e0c096c3113fc6ef761ba624551939f01698 has replaced the log file key word "closed" by "Disconnect".

The values of "Peak Concurrent Connections"  on our production servers are about 600-800, while the new logconv.pl still displays about 3000-4000.

Here are the changes that take into accounts the replacement of the key word in addition to case sensitivity of the word "closed":

```
@@ -2249,7 +2249,7 @@
                $fdTaken++;
                if ($1 > $highestFdTaken){ $highestFdTaken = $1; }
        }
-       if (m/ fd=/ && m/closed/i){
+       if (m/ fd=/ && m/(closed|disconnect)/i){
                ($connID) = $_ =~ /conn=(\d*)\s/;
                handleConnClose($connID);
        }
@@ -2362,7 +2362,7 @@
                }
                $isVlvNotes = 0;
        }
-       if (m/ closed error 32/i){
+       if (m/ (closed|disconnect) error 32/i){
                $brokenPipeCount++;
                if (m/- T1/){ $hashes->{rc}->{"T1"}++; }
                elsif (m/- T2/){ $hashes->{rc}->{"T2"}++; }
@@ -2377,7 +2377,7 @@
                elsif (m/- U1/){ $hashes->{rc}->{"U1"}++; }
                else { $hashes->{rc}->{"other"}++; }
        }
-       if (m/ closed error 131/i || m/ closed error -5961/i){
+       if (m/ (closed|disconnect) error 131/i || m/ (closed|disconnect) error -5961/i){
                $connResetByPeerCount++;
                if (m/- T1/){ $hashes->{src}->{"T1"}++; }
                elsif (m/- T2/){ $hashes->{src}->{"T2"}++; }
@@ -2392,7 +2392,7 @@
                elsif (m/- U1/){ $hashes->{src}->{"U1"}++; }
                else { $hashes->{src}->{"other"}++; }
        }
-       if (m/ closed error 11/i){
+       if (m/ (closed|disconnect) error 11/i){
                $resourceUnavailCount++;
                if (m/- T1/){ $hashes->{rsrc}->{"T1"}++; }
                elsif (m/- T2/){ $hashes->{rsrc}->{"T2"}++; }
```

**Comment by mreynolds389** [comment]
Sorry @aivanov389 I'll get this fixed right away...

**Comment by mreynolds389** [comment]
acee4ca7c..d4b9fb01b  389-ds-base-2.2 -> 389-ds-base-2.2
9d92f6a86..6de88beaa  389-ds-base-2.1 -> 389-ds-base-2.1
0ffe4abdc..11fa11fc3  389-ds-base-2.0 -> 389-ds-base-2.0
fb49e684f..ce54e8191  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

Ok should be good now...
