### ISSUE TITLE
test_tls_command_returns_error_text CI test fails

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5680]
**Issue Description**
Looks like we got a regression (probably when we added the CA/versus server certificate test)
 and test fails in github actions
 Seems to be a lib389 issue:
 Getting a ValueError exception when file is invalid instead of the expected error message

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main

**Comment by mreynolds389** [comment]
Is this fixed with this pending PR:  https://github.com/389ds/389-ds-base/pull/5677

**Comment by progier389** [comment]
Tests shows that PR: [#5677](https://github.com/389ds/389-ds-base/pull/5677) does fix that issue
