### ISSUE TITLE
SRCH performance drop 2.0 vs 1.4

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#5700]
**Issue Description**
A testcase reveal a significant (~30times) performance drop that was introduced in #5170 [commit](https://github.com/389ds/389-ds-base/commit/40563667e12da3042ea5a0e3771c1e1db1dafa06) 
Sometime an indexed search filter can lead to a candidate list that only contains entries matching the filter. In such case, it is useless to reevaluate the filter against each returned entries. It is called bypass filter (SR_FLAG_MUST_APPLY_FILTER_TEST==0).
The above commit force the evaluation of the filter in all cases.

The problem is that filter evaluation is expensive by itself and become very expensive if the returned entry contains attributes with large number of values. For example a uniquemember of a big group.

**Package Version and Platform:**
2.x

**Steps to Reproduce**
testcase will be provided later

**Expected results**
2.x should be as fast as 1.4

**Comment by Firstyear** [comment]
The filter test has to be forced though for the reasons discussed repeatedly through that issue - previously we actually had potential for query corruption in our search code. So I think any changes here need to be extremely carefully considered.

PS: We pretty much always force filter tests because grok filter is busted and should be removed.

**Comment by tbordaz** [comment]
@Firstyear , I fully agree with you this subject was discussed. However the pointed commit has a severe performance hit. It was pushed with a testcase and reworking the patch the testcase is still pass without the perf hit.
I will send a PR (hopefully today) to check if the orginal patch or original testcase need to be improved

**Comment by tbordaz** [comment]
It is a leftover that I forgot to update. @Firstyear is correct the testcase is not valid and the suggested PR was wrong. I am closing this ticket
