### ISSUE TITLE
RFE - Add config parameter to close client connections on failed BIND

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#5707]
**Problem statement**
Malformed applications that ignore BIND return code can load the server with unnecessary requests.

**Solution**
Add a config option that will allow the closure of a client connection from server side when a BIND is failing.

**Additional context**
https://bugzilla.redhat.com/show_bug.cgi?id=1987471

**Comment by mreynolds389** [comment]
Bugzilla is set for RHEL 9.3, please cherry pick this to the 2.3 branch.  There should probably be a UI update for this as well, but it can wait for now...

**Comment by jchapma** [comment]
> Bugzilla is set for RHEL 9.3, please cherry pick this to the 2.3 branch. There should probably be a UI update for this as well, but it can wait for now...

 fc34eec58..7743b3862  389-ds-base-2.3 -> 389-ds-base-2.3
UI patch ready
