### ISSUE TITLE
RFE When a filter contains 'nsrole', improve response time by rewriting the filter.

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#5722]
**Issue Description**
'nsrole' is a virtual attribute and is not indexed. With a poorly selective filter like below the search may be not indexed 
<pre>
"(&(nsrole=cn=managed_role,cn=suffix)(objectclass=posixAccount)))"
</pre>

The fix is to rewrite filter components containing 'nsrole' type. ATM the fix would be limited to managed/filtered roles

**Package Version and Platform:**
all versions

**Steps to Reproduce**
provide a test case

**Expected results**
Getting faster SRCH when filter uses 'nsrole'

**Comment by tbordaz** [comment]
a55fa3087..bcbad8745  main

**Comment by mreynolds389** [comment]
@tbordaz  please backport to all relevant branches.  This is expected to be in 2.3 branch (and probably a good idea to put it in earlier branches as well).

**Comment by tbordaz** [comment]
cde047740..f2f6c2b9e  389-ds-base-2.3

**Comment by tbordaz** [comment]
Improving the testcase with [PR](https://github.com/389ds/389-ds-base/pull/5904)

475ee01dc..63fd271fa main
11a1ddc8f..1df340797  389-ds-base-2.3
ababe094c..f1eb2f1d6  389-ds-base-2.2
96012932f..0747f7694  389-ds-base-2.1
849cc42b2..5881562a9  389-ds-base-2.0
e721c2f13..c70be2e97  389-ds-base-1.4.4
c5344e8c6..837b47d68  389-ds-base-1.4.3
