### ISSUE TITLE
Opening logs result in a white screen, JavaScript error

### ISSUE THREAD

**Issue by anvilvapre** [389ds/389-ds-base#5736]
Environment:

- Ubuntu 22.04
- Manually extracted dist files from https://github.com/vashirov/389-ds-base/releases/download/389-ds-base-2.3.0/389-ds-base-2.3.0.tar.bz2, as they were missing in 389-ds-base-2.0.15.tar.gz, as suggested in another issue.
- Chromium browser
- 
Issue:
- JavaScript error when clicking any of the log entries under Server > Logging

Impact:
- Empty view, white screen

Reproducable:
- Happens also after reloading the cockpit in the browser

Possiblel cause:
- Incompatibility between newer frontend and an older ds-389 backend (389-ds                             2.0.15-1)? 

JavaScript console, stack trace:
```
dex.js:2 TypeError: Cannot read properties of undefined (reading '0')
    at sU.loadConfig (index.js:2:2135102)
    at sU.componentDidMount (index.js:2:2129114)
    at bo (index.js:2:205544)
    at Ll (index.js:2:222350)
    at t.unstable_runWithPriority (index.js:2:251621)
    at Gs (index.js:2:164539)
    at _l (index.js:2:219089)
    at yl (index.js:2:215200)
    at index.js:2:164762
    at t.unstable_runWithPriority (index.js:2:251621)
co @ index.js:2
a.callback @ index.js:2
mr @ index.js:2
bo @ index.js:2
Ll @ index.js:2
t.unstable_runWithPriority @ index.js:2
Gs @ index.js:2
_l @ index.js:2
yl @ index.js:2
(anonymous) @ index.js:2
t.unstable_runWithPriority @ index.js:2
Gs @ index.js:2
$s @ index.js:2
Ks @ index.js:2
Pe @ index.js:2
Jt @ index.js:2
index.js:2 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at sU.loadConfig (index.js:2:2135102)
    at sU.componentDidMount (index.js:2:2129114)
    at bo (index.js:2:205544)
    at Ll (index.js:2:222350)
    at t.unstable_runWithPriority (index.js:2:251621)
    at Gs (index.js:2:164539)
    at _l (index.js:2:219089)
    at yl (index.js:2:215200)
    at index.js:2:164762
    at t.unstable_runWithPriority (index.js:2:251621)
```

Opening location of exception:
```
           loadConfig() {
                var e = this.state.attrs
                  , t = !1
                  , a = !1
                  , n = !1
                  , s = parseInt(e["nsslapd-accesslog-level"][0])
                  , r = [...this.state.rows];
                for (var i in "on" == e["nsslapd-accesslog-logging-enabled"][0] && (t = !0),
                "on" == e["nsslapd-accesslog-logbuffering"][0] && (a = !0),
                "on" == e["nsslapd-accesslog-compress"][0] && (n = !0),
                r)
```
Error location is second last line, end of: `"on" == e["nsslapd-accesslog-compress"][0]`.

Suggesting `e["nsslapd-accesslog-compress"]` is undefined.

No http errors in the network view prior.

**Comment by anvilvapre** [comment]
Likey caused by imcompatability between backend. Because i now also notice that the older version of dsidm does not output json for `account entry-status` which also breaks the ldap browser.

**Comment by mreynolds389** [comment]
You MUST use the same version for 389-ds-base and cockpit-389-ds.  2.0.15 does not have the log compression feature that is present 2.3.0, as well as many other features/fixes.
