### ISSUE TITLE
 BZ 2184599 - Disabling replication crashes the server

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5743]
**Issue Description**

**Package Version and Platform:**
 - Platform:  Any 
 - Package and version: main branch

**Steps to Reproduce**
1. dsconf standalone1 replication enable --suffix 'dc=example,dc=com' --role consumer 
Replication successfully enabled for "dc=example,dc=com"
2. dsconf standalone1 replication disable --suffix 'dc=example,dc=com'
Error: -1 - Can't contact LDAP server - [] - delete_ext_s(('cn=replica,cn=dc\\3Dexample\\2Cdc\\3Dcom,cn=mapping tree,cn=config',),{'serverctrls': None, 'clientctrls': None, 'escapehatch': 'i am sure'}) on instance standalone1

**Expected results**
No error.

**Screenshots**

**Additional context**
[BZ 2184599](https://bugzilla.redhat.com/show_bug.cgi?id=2184599
)

**Comment by stanislavlevin** [comment]
Any chance for backport this on 2.2 branch please?
The original report (BZ) was about 2.2.7.

**Comment by progier389** [comment]
Sure: 

0f9a80ac6..9132f07b8 main
aa50e5bbf..dcae9421a  389-ds-base-2.3 -> 389-ds-base-2.3
7f8480894..957f837de  389-ds-base-2.2 -> 389-ds-base-2.2

**Comment by stanislavlevin** [comment]
@progier389, thank you!
