### ISSUE TITLE
Log rotationinfo file not being properly updated when logs are compressed

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5760]
**Issue Description**

After using ldclt (with small log sizes) the access log rotationinfo file has duplicate logs listed:

    # dsconf slapd-localhost config replace nsslapd-accesslog-compress=on nsslapd-accesslog-logrotationtimeunit=minute nsslapd-accesslog-maxlogsize=1

    # ldclt -h localhost -p 389 -b 'dc=example,dc=com' -e esearch -f '(objectClass=*)'

[root@fedora ~]# ls -l /var/log/dirsrv/slapd-localhost/access*
-rw-------. 1 dirsrv dirsrv 524364 May  9 08:24 /var/log/dirsrv/slapd-localhost/access
-rw-r--r--. 1 dirsrv dirsrv 160153 May  9 08:24 /var/log/dirsrv/slapd-localhost/access.20230509-082431.gz
-rw-r--r--. 1 dirsrv dirsrv 159644 May  9 08:24 /var/log/dirsrv/slapd-localhost/access.20230509-082432.gz
-rw-r--r--. 1 dirsrv dirsrv 159519 May  9 08:24 /var/log/dirsrv/slapd-localhost/access.20230509-082433.gz
-rw-r--r--. 1 dirsrv dirsrv 159895 May  9 08:24 /var/log/dirsrv/slapd-localhost/access.20230509-082434.gz
-rw-------. 1 dirsrv dirsrv   1018 May  9 08:24 /var/log/dirsrv/slapd-localhost/access.rotationinfo

[root@fedora ~]# cat /var/log/dirsrv/slapd-localhost/access.rotationinfo
LOGINFO:Log file created at: 09/May/2023:08:24:34 (1683635074)
LOGINFO:Previous Log File:/var/log/dirsrv/slapd-localhost/access.20230509-082434.gz (1683635074) (159895)
LOGINFO:Previous Log File:/var/log/dirsrv/slapd-localhost/access.20230509-082433.gz (1683635073) (159519)
LOGINFO:Previous Log File:/var/log/dirsrv/slapd-localhost/access.20230509-082433.gz (1683635073) (159519)
LOGINFO:Previous Log File:/var/log/dirsrv/slapd-localhost/access.20230509-082432.gz (1683635072) (159644)
LOGINFO:Previous Log File:/var/log/dirsrv/slapd-localhost/access.20230509-082432.gz (1683635072) (159644)
LOGINFO:Previous Log File:/var/log/dirsrv/slapd-localhost/access.20230509-082432.gz (1683635072) (159644)
LOGINFO:Previous Log File:/var/log/dirsrv/slapd-localhost/access.20230509-082431.gz (1683635071) (160153)
LOGINFO:Previous Log File:/var/log/dirsrv/slapd-localhost/access.20230509-082431.gz (1683635071) (160153)
LOGINFO:Previous Log File:/var/log/dirsrv/slapd-localhost/access.20230509-082430.gz (1683635070) (1048576)

**Comment by progier389** [comment]
I suspect that the real issue is that we got several log files generated on the same second with  same file name and they overwrite each other ...

**Comment by mreynolds389** [comment]
> I suspect that the real issue is that we got several log files generated on the same second with same file name and they overwrite each other ...

Makes sense.  I just saw it while preparing a demo for log compression, and as you see I set unrealistic log rotation settings.  Ok closing ticket...
