### ISSUE TITLE
subsuffix are not returned in one level scoped search

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5772]
**Issue Description**
When 

**Package Version and Platform:**
 - Platform: [e.g. Fedora]
 - Package and version: main branch

**Steps to Reproduce**
1. Create an instance with dc=example,dc=com suffix (with entries in the backends)
2. Create a subsuffix just below the suffix with entries:
    dsconf i1 backend  create --suffix ou=foo,dc=example,dc=com --create-entries --be-name foo
4. Run ldapsearch ldapsearch with sub scope:
    ldapsearch -Q -LLL -Y EXTERNAL -H ldapi://%2fvar%2frun%2fslapd-i1.socket -s sub -b dc=example,dc=com '(ou=*)' dn
    (No errors: ou=foo,dc=example,dc=com  is listed)
6. Run ldapsearch with one scope:
    ldapsearch -Q -LLL -Y EXTERNAL -H ldapi://%2fvar%2frun%2fslapd-i1.socket -s one -b dc=example,dc=com '(ou=*)' dn
    (Error:  ou=foo,dc=example,dc=com  is not listed)

**Expected results**
ou=foo,dc=example,dc=com should be listed in both cases

**Additional context**
This behavior confuses some ldap browsers that cannot show any more the entries below sub suffix.

**Comment by mreynolds389** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2219000

**Comment by progier389** [comment]
d261ea27c..407bdaa00  main -> main
   baf4fd400..33e99f980  389-ds-base-3.0 -> 389-ds-base-3.0
   c9d18299a..dc0d81844  389-ds-base-2.5 -> 389-ds-base-2.5
