### ISSUE TITLE
CLI - arg completion is broken

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5785]
**Issue Description**

In Fedora 38, maybe other releases, CLI arg completion broke.  Maybe something changed in python, not sure.  Needs investigation

**Comment by mreynolds389** [comment]
Needed to run:  

activate-global-python-argcomplete

It's now better but not 100% working.  Still investigating

**Comment by mreynolds389** [comment]
Ok everything is working, but I wonder if we should call the  **activate-global-python-argcomplete** script during instance creation? 

We really need argcompletion working out of the box, or else the CLI is very annoying to use.

**Comment by vashirov** [comment]
Fedora bug for python-argcomplete: https://bugzilla.redhat.com/show_bug.cgi?id=2211862

**Comment by mreynolds389** [comment]
This diff seems to be sufficient:

```
diff --git a/rpm/389-ds-base.spec.in b/rpm/389-ds-base.spec.in
index 87af05a59..662a737c9 100644
--- a/rpm/389-ds-base.spec.in
+++ b/rpm/389-ds-base.spec.in
@@ -404,6 +404,12 @@ autoreconf -fiv
   sed -r -i '/^(Protect(Home|Hostname|KernelLogs)|PrivateMounts)=/d' %{_builddir}/%{name}-%{version}%{?prerel}/wrappers/*.service.in
 %endif
 
+for clitool in dsconf dsctl dsidm dscreate
+do
+  register-python-argcomplete "${clitool}" > "/usr/share/bash-completion/completions/${clitool}"
+done
+
 %if 0%{?rhel} > 7 || 0%{?fedora}
 # lib389
 pushd ./src/lib389
```

**Comment by mreynolds389** [comment]
6e04b6fcb..5f9b4d6fe  389-ds-base-2.3 -> 389-ds-base-2.3

**Comment by adelton** [comment]
The change caused regression https://bugzilla.redhat.com/show_bug.cgi?id=2225231.

Please note that the test builds that Miro showed https://bugzilla.redhat.com/show_bug.cgi?id=2211862 used %files properly, not %post.
