### ISSUE TITLE
CI: set minimal permissions on GitHub Workflows

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#5786]
Similarly to this issue: https://github.com/python-ldap/python-ldap/issues/523
We need to set minimal permissions on our GitHub Workflows.

Defining minimal permissions secures you against erroneous or malicious behaviour from external jobs you call from your workflow. It's especially important in case they get compromised.

Setting minimum permissions for workflows is recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and also by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

**Comment by droideck** [comment]
> Unless mistaken, that means that we should also do the same for the ansible and the wiki repositories that also use workflows.

Yep, I can do it after https://github.com/389ds/389-ds-base/pull/5787 is reviewed (and we agreed on the approach).

**Comment by vashirov** [comment]
Release workflow can't generate tarballs with `contents: read` permission. It should be `write`.
