### ISSUE TITLE
UI - switch from webpack to esbuild bundler

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5793]
**Issue Description**

To stay consistent and current with Cockpit (via https://github.com/cockpit-project/starter-kit) we need to move from webpack to esbuild

**Comment by mreynolds389** [comment]
cb83c8f12..0272d9914  389-ds-base-2.3 -> 389-ds-base-2.3

**Comment by droideck** [comment]
6b9a86cc1..fe348d80a  389-ds-base-2.3 -> 389-ds-base-2.3

**Comment by mreynolds389** [comment]
Fix LDIF export suffix selection and other crashes related to webpack/rebuild migration:

fe348d80a..8f797b9b7  389-ds-base-2.3 -> 389-ds-base-2.3

Fix just import selection:

94d69c7d0..8a7e696f8  389-ds-base-2.2 -> 389-ds-base-2.2
e377c9af1..cccc9ef4a  389-ds-base-2.1 -> 389-ds-base-2.1
09e984337..e07780678  389-ds-base-2.0 -> 389-ds-base-2.0
dc4130da5..a4561f4c1  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by droideck** [comment]
a8f062ef9..9e6979e31  389-ds-base-2.3 -> 389-ds-base-2.3
   48834f141..7fbf7bbbd  389-ds-base-2.2 -> 389-ds-base-2.2
   cccc9ef4a..1cdd011eb  389-ds-base-2.1 -> 389-ds-base-2.1
   e07780678..65bcca75a  389-ds-base-2.0 -> 389-ds-base-2.0
   a4561f4c1..e568180d1  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
