### ISSUE TITLE
dtablesize being set to soft maxfiledescriptor limit

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#5804]
**Issue Description**
389ds is not setting dtablesize properly based when systemd is setting the maxfiledescriptors with it's default settings.
     dtablesize stays 1024 which causes massive slowdown once you hit around 950 connection.

**Package Version and Platform:**
 - Platform: Rhel 8
 - Package and version: 389-ds-base-1.4.3

**Steps to Reproduce**
1. Confirm maxfiledescriptors value is set to 1024
2. Create ~950 connections
3. Notice queries are very slow. 
4. Failure to go above  ~970 concurrent connections.

**Expected results**
Support up to 10k connections

**Additional context**
Backport of https://github.com/389ds/389-ds-base/issues/5469

**Comment by jchapma** [comment]
Merged to 389-ds-base-1.4.3

**Comment by tbordaz** [comment]
Hi @jchapma ,  this fix was pushed in 1.4.3

a6f0981de..231f92a55  389-ds-base-1.4.3

Does it apply only in 1.4.3 or all branches up to main ?

**Comment by jchapma** [comment]
The root cause of this issue is when the default connection_table_size is set too low (1024), limiting the number of connections the server can simultaneously support. 

The number of listeners feature https://github.com/389ds/389-ds-base/pull/5090 added extra connection table  monitoring threads along with increasing the default connection table size. This feature was merged into the 389-ds-base-2.3 branch. 

A subset of this feature, code that increases the default connection table size was backported to the below branches:
389-ds-base-1.4.3
389-ds-base-1.4.4
389-ds-base-2.0
389-ds-base-2.1
389-ds-base-2.2

**Comment by tbordaz** [comment]
@jchapma , the ticket looks fixed in all impacted branch. Is it okay to close it ?

**Comment by jchapma** [comment]
@tbordaz, yes i believe so, thanks
