### ISSUE TITLE
RFE: Allow empty export path for db2ldif

### ISSUE THREAD

**Issue by multipleofzero** [389ds/389-ds-base#5822]
**Issue Description**
Until recently, `db2ldif` did not require an export path to be specified and would use a specified default location to create a timestamped file.

A recent commit introduced a check to ensure the targeted export file's parent actually exists. This check is fine if a target filename is provided, but it fails when no filename is provided; a use case that was supported before.

**Package Version and Platform:**
 - Platform: RHEL
 - Package and version: 389-ds-base.x86_64 2.4.1-1.el8
 - Browser: n/a

**Steps to Reproduce**
1. call `db2ldif` w/o providing a name for the target ldif file

**Expected results**
An LDIF export/file with a standard name (containing a timestamp) should be created in the standard location: according to [defaults.inf.in](https://github.com/389ds/389-ds-base/blob/f2c1e44b59c726091a7dcee6046daaeb490f0f77/ldap/admin/src/defaults.inf.in#L63) this would be `@localstatedir@/lib/dirsrv/slapd-{instance_name}/ldif`

**Screenshots**
n/a

**Additional context**
PR #5795

**Comment by mreynolds389** [comment]
8d2517930..e76bfe1d0  389-ds-base-2.3 -> 389-ds-base-2.3
504fb72cf..b674879e9  389-ds-base-2.2 -> 389-ds-base-2.2
a5d708d9b..4b25163e8  389-ds-base-2.1 -> 389-ds-base-2.1
bb75868d7..71544acee  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
