### ISSUE TITLE
dsconf / dscreate should be able to handle lmdb parameters

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5843]
**Issue Description**
lmdb specific parameters should be visible in dsconf

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main

**Steps to Reproduce**
1. Configure an instance with lmdb
2. Run dsconf supplier1 backend config set --help

**Expected results**
Should see the lmdb specific parameters like:
- nsslapd-mdb-max-size
- nsslapd-mdb-max-readers
- nsslapd-mdb-max-dbs 

**Additional context**
dscreate create-template should also propose the nsslapd-mdb-max-size as it is a critical parameter
dscreate interactive should ask for 
 - the bdb/mdb mode
 - the mdb max size if in mdb mode

**Comment by progier389** [comment]
dscreate needs to be able to handle these parameters but we cannot change these value afterwards
 without removing the whole db and recreating it ( lmdb limitation) so I do not think that dsconf should be changed. 
we will have to describe how to change 
see also [issue #5844 ](https://github.com/389ds/389-ds-base/issues/5844) that is related.

**Comment by Firstyear** [comment]
Thinking more about this, I think that we shouldn't have a default size. We should always force the admin to select a size here. That way they are always aware of the choice they need to make and don't have a "surprise you're out of DB space" event in the future. 

We also need to carefully consider how this will work with upgrades in the future too - if we want them to be a manual or hands-off process.

**Comment by progier389** [comment]
Found a regression with dscreate create-template when creating first instance on a newly installed host
(Get a warning about not existing directory in the middle of the template ! )
Opening a new PR

**Comment by progier389** [comment]
Regression fixed by [PR #5950 ](https://github.com/389ds/389-ds-base/pull/5950)

**Comment by droideck** [comment]
e2495b19b..98e03582a  main       -> origin/main
   2cf519d65..b3b72a333  389-ds-base-3.0 -> 389-ds-base-3.0
