### ISSUE TITLE
lib389 should  use filter for tarfile as recommended by PEP 706 -

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5867]
**Issue Description**
Should add tarfile filter every time tarfile.open is called. (To avoid a deprecation warning.)
The impacted locations are:
   1.  lib389.backupFS
   2.  lib389.restoreFS
   3.  lib389.tools.instanceBackupFS
   4.  lib389.tools.instanceRestoreFS
   5.  dirsrvtests/tests/tickets/ticket47988_test.py 

In practice it is more about filling a checkbox than a real issue as the impacted lib389 functions
    are not used  within 389ds nor within  freeipa 
   (IMHO that is plain dead code, BTW this sound logical because backup/restore is directly handled by the ns-slapd binary 
     and lib389 should only act as a wrapper to the online and offline backup/restore tasks )

So I will add:
   tar.extraction_filter = (lambda member, path: member) 
   after each call to tarfile.open 

See: BZ  [2207691](https://bugzilla.redhat.com/show_bug.cgi?id=2207691)

**Package Version and Platform:**
 - Platform: Fedora, RHEL 8
 - Package and version: main 

**Steps to Reproduce**
No reproducer:
    seen by code review  whether tar.extraction_filter is set after tar = tarfile.open(...)
**Result when issue is not fixed:**
```
find . -type f | xargs egrep -n "extraction_filter|tarfile.open" /dev/null 
./src/lib389/lib389/tools.py:303:        tar = tarfile.open(backup_file, "w:gz")
./src/lib389/lib389/tools.py:361:        tar = tarfile.open(backup_file)
./src/lib389/lib389/__init__.py:1380:        tar = tarfile.open(backup_file, "w:gz")
./src/lib389/lib389/__init__.py:1453:        tar = tarfile.open(backup_file)
./dirsrvtests/tests/tickets/ticket47988_test.py:84:    tar = tarfile.open(tarFile, 'r:gz')
```
**Expected result:**
```
find . -type f | xargs egrep -n "extraction_filter|tarfile.open" /dev/null 
./src/lib389/lib389/tools.py:303:        tar = tarfile.open(backup_file, "w:gz")
./src/lib389/lib389/tools.py:304:        tar.extraction_filter = (lambda member, path: member)
./src/lib389/lib389/tools.py:362:        tar = tarfile.open(backup_file)
./src/lib389/lib389/tools.py:363:        tar.extraction_filter = (lambda member, path: member)
./src/lib389/lib389/__init__.py:1380:        tar = tarfile.open(backup_file, "w:gz")
./src/lib389/lib389/__init__.py:1381:        tar.extraction_filter = (lambda member, path: member)
./src/lib389/lib389/__init__.py:1454:        tar = tarfile.open(backup_file)
./src/lib389/lib389/__init__.py:1455:        tar.extraction_filter = (lambda member, path: member)
./dirsrvtests/tests/tickets/ticket47988_test.py:84:    tar = tarfile.open(tarFile, 'r:gz')
./dirsrvtests/tests/tickets/ticket47988_test.py:85:    tar.extraction_filter = (lambda member, path: member)

```

**Comment by vashirov** [comment]
> In practice it is more about filling a checkbox than a real issue as the impacted lib389 functions
are not used within 389ds nor within freeipa
(IMHO that is plain dead code, BTW this sound logical because backup/restore is directly handled by the ns-slapd binary
and lib389 should only act as a wrapper to the online and offline backup/restore tasks )

I checked git log and found that these functions were used to speed up testing:
https://github.com/389ds/389-ds-base/issues/921
https://github.com/389ds/389-ds-base/commit/b5294b46fb613e7595683079369b96ba094cbd3c

These days we use pytest fixtures and recreate instances for each test. So this is indeed a dead code. Maybe we should delete it?

**Comment by progier389** [comment]
I wondered the same before creating the PR but I always hesitate to remove functions outside of a major version change. ( we know that some other projects (like freeipa) use directly  lib389 and (as far as I know) there is no clear documentation of the public API  so we may break something.
My feeling is that we should only solve the problem that we have now and postpone the functions removal 
 That said we may want to create an issue to avoid forgetting it ...
