### ISSUE TITLE
2.4.2 doesn't compile: error: using `.borrow()` on a double reference, which returns `&concread::cowcell::CowCellReadTxn<CacheStats>` instead of borrowing the inner type

### ISSUE THREAD

**Issue by svenstaro** [389ds/389-ds-base#5880]
**Issue Description**
I'm compiling 2.4.2 but I get:
```
error: using `.borrow()` on a double reference, which returns `&concread::cowcell::CowCellReadTxn<CacheStats>` instead of borrowing the inner type
```

**Package Version and Platform:**
 - Platform: Arch Linux
 - Package and version: 2.4.2
 - Browser N/A

**Steps to Reproduce**
Steps to reproduce the behavior: https://gitlab.archlinux.org/archlinux/packaging/packages/389-ds-base/-/blob/main/PKGBUILD

**Expected results**
It should compile

**Additional context**
Build log: [389.log](https://github.com/389ds/389-ds-base/files/12234833/389.log)

**Comment by vashirov** [comment]
This is fixed in https://github.com/389ds/389-ds-base/issues/5861
