### ISSUE TITLE
lmdb import error fails with: Could not store the entry 

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5894]
**What is the problem:**
The lmdb import error with 100k entries fails.

**Product version:**
Fedora, main branch

**How to reproduce the problem:**
```
#Create an instance with lmdb DB
sudo NSSLAPD_DB_LIB=mdb dscreate from-file /home/vagrant/vagrant/inst01.inf

#Create ldif file with 100k entries
sudo dsctl inst01 ldifgen users --number 100000 --suffix=dc=example,dc=com --ldif-file users.ldif

#Import
sudo dsconf inst01 backend import userroot users.ldif
```

**Current behavior:**
See error message:
```
Beginning import job...
Processing file "/var/lib/dirsrv/slapd-inst01/ldif/users.ldif"
Could not store the entry starting at line 23 of file "/var/lib/dirsrv/slapd-inst01/ldif/users.ldif" -- error 32675
Could not store the entry starting at line 28 of file "/var/lib/dirsrv/slapd-inst01/ldif/users.ldif" -- error 32675
Could not store the entry starting at line 33 of file "/var/lib/dirsrv/slapd-inst01/ldif/users.ldif" -- error 32675
Could not store the entry starting at line 38 of file "/var/lib/dirsrv/slapd-inst01/ldif/users.ldif" -- error 32675
thread worker 3 aborted ==> Aborting import.

Import writer thread usage: run: 21.88% read: 29.82% write: 18.09% pause: 4.12% txnbegin: 5.78% txncommit: 20.31% 
Workers finished; cleaning up...
Workers cleaned up.
Thread monitoring returned: -23

Aborting all Import threads...
Import threads aborted.
Closing files...
Import failed.
```

**Expected behavior:**
Import should complete successfully.

**Additional context:**

I didnt debug it but the line numbers in the error message correspond to a newline in the ldif file.

_Originally posted by @jchapma in https://github.com/389ds/389-ds-base/pull/5881#pullrequestreview-1573567496_

Code review of dbmdb_import_add_id2entry_add show that displays the error shows that rc is not initialized
 (so 32675 is a meaningless rabdom value.)
With such a bug, it is a bit surprising that nightly LMDB CI tests run so well ...

**Comment by mreynolds389** [comment]
@progier389 -Should these fixes also be going into the 2.3 branch?

**Comment by progier389** [comment]
This one should get there as it block the verification of a BZ (for the 5881) it is less urgent but it would be nice. 
Should I cherry pick them ?

**Comment by mreynolds389** [comment]
> This one should get there as it block the verification of a BZ (for the 5881) it is less urgent but it would be nice. Should I cherry pick them ?

Please do.  I know people want to start testing lmdb on PHEL 9.3 so all future work should also go back to the 2.3 branch.  Thanks!
