### ISSUE TITLE
pamModuleIsThreadSafe is missing in the schema

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#5920]
**Issue Description**
The ticket #5271 introduces the PAM config attribute: pamModuleIsThreadSafe
It is missing in the schema 

**Package Version and Platform:**
#5271 being applied 1.3.10 and after, this ticket also impact those release

**Steps to Reproduce**
N/A

**Expected results**
pamModuleIsThreadSafe should be described in the schema (pam-plugin.ldif)

**Comment by vashirov** [comment]
dbf456484..f3758a682  389-ds-base-1.3.11 -> 389-ds-base-1.3.11
   9455713f8..33501f35f  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   49d3c04b9..1ca17cf6e  389-ds-base-2.0 -> 389-ds-base-2.0
   b8a017bf3..5196cb0a8  389-ds-base-2.1 -> 389-ds-base-2.1
   20ce92890..706fcca08  389-ds-base-2.2 -> 389-ds-base-2.2
   8d82ebf06..51cbd29b0  389-ds-base-2.4 -> 389-ds-base-2.4
   9572c251d..ef3919ce9  389-ds-base-2.5 -> 389-ds-base-2.5
   86e2e632e..ec29717bd  389-ds-base-3.0 -> 389-ds-base-3.0
