### ISSUE TITLE
Switch default backend to lmdb and bump version to 3.0

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5941]
As part of bdb deprecation handling we should:
 - Change the default database mechanism to lmdb intead of bdb
 - Bump the version to 3.0 
 - Ensure that .github/workflows/pytest.py (CI test workflow) is still running with bdb

**Comment by Firstyear** [comment]
Do we have a process for bdb -> lmdb migration "in place"? Or is it a hands-on migration?

**Comment by progier389** [comment]
FYI: I am working on writing documentation to explain all that.
But in short the idea is to let the user choose:
   - He can go on running with bdb (at least until bdb is removed) 
   - He can use tools: dsctl instance dblib bdb2mdb
   - He can do it by hands (probably the safest method for very big databases)

**Comment by Firstyear** [comment]
So long as there is an automation I'm happy. I'm looking forward to the documentation. :)

**Comment by droideck** [comment]
The document mentioned above and written by Pierre:
https://www.port389.org/docs/389ds/FAQ/Berkeley-DB-deprecation.html

**Comment by progier389** [comment]
There is a migration  tools "dsctl inst dblib bdb2mdb" but we do not trigger it automatically (we do not want to do it because there are some huge db around that may need some planning before getting migrated.)
Anyway, at this point bdb is only deprecated but not yet removed
