### ISSUE TITLE
Disable Transparent Huge Pages

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#5954]
**Description of problem:**
As described in [bug 2068120](https://bugzilla.redhat.com/show_bug.cgi?id=2068120), THP can have negative effects on RHDS performance.
This seems to happen with large caches.
Some customers are getting uncontrolled memory usage while others are seeing high CPU consumption.
It would make sense to either disable THP for RHDS or at least add some messages in the errors logs.
RHDS healthcheck tool should also report when THP is enabled on the system.

**Version-Release number of selected component (if applicable):**
This is impacting all RHDS 11 and 12 versions.

**How reproducible:**
At customer sites.

**Steps to Reproduce:**
1. Configure large caches ( > 50 GB )
2. Check memory and CPU usage when RHDS is under heavy load
3. Disable THP ==> RHDS uses less memory and CPU

**Actual results:**
High memory and CPU usage.

**Expected results:**
Controlled memory and CPU usage.

**Additional info:**
    https://access.redhat.com/solutions/3799821

**Comment by vashirov** [comment]
@tbordaz where do you want me to backport this besides 2.4?

**Comment by tbordaz** [comment]
> @tbordaz where do you want me to backport this besides 2.4?

I know it is a RFE and the backport in 1.4.3 is not priority. But knowing that it is a common issue also in 1.4.3 and possibly an easy backport, I would say back to 1.4.3.

**Comment by vashirov** [comment]
a82c2a595..fcb04abe7  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   37da5ecec..7edfc7add  389-ds-base-2.0 -> 389-ds-base-2.0
   e09d95b32..40081442f  389-ds-base-2.1 -> 389-ds-base-2.1
   3688d6819..5eb779bc6  389-ds-base-2.2 -> 389-ds-base-2.2
   382003bde..dd03a509c  389-ds-base-2.3 -> 389-ds-base-2.3
   1b89a3374..cd7fc221e  389-ds-base-2.4 -> 389-ds-base-2.4
