### ISSUE TITLE
Incorrect file name when downloading 389 source

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#5983]
**Issue Description**
Incorrect file name when downloading 389 source

**Steps to Reproduce**
1. Go to https://github.com/389ds/389-ds-base/archive/389-ds-base-2.4.4.tar.gz
2. Option to save file 389-ds-base-389-ds-base-2.4.4.tar.gz

**Expected results**
 Option to save file 389-ds-base-2.4.4.tar.gz

**Additional context**
Tried with a few other releases and I see the same behaviour. Im using firefox.

**Comment by vashirov** [comment]
This is how GitHub archive function works, it uses format `${REPONAME}-${BRANCHNAME}.tar.gz`. We use `389-ds-base` in the branch name, hence the full name of the archive repeats `389-ds-base`. And this is is why we have release action to release it with a proper name such as https://github.com/389ds/389-ds-base/releases/download/389-ds-base-2.4.4/389-ds-base-2.4.4.tar.bz2

**Comment by jchapma** [comment]
Thanks for the info, I will close this ticket
