### ISSUE TITLE
plugins/accpol_check_all_state_attrs_test.py::test_inactivty_and_expiration CI test fails

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5998]
**Issue Description**
Once timing issue #5997 is fixed. the test fails systematically. 
So if the test is really to test that bind is rejected if it occurs after password has expired for longer than the inactivity limit
then the test case is wrong (config issue ?) or there is a bug in the account policy plugin. 

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main + #5997 fix.

**Steps to Reproduce**
1. See nightly CI tests error.

**Expected results**
Test should pass

**Comment by droideck** [comment]
This PR fixes the test: https://github.com/389ds/389-ds-base/pull/6323
