### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by greergan** [389ds/389-ds-base#6000]
**Issue Description**
The following commands fail

1. autoreconf -fiv
2. ./configure

**Package Version and Platform:**
 - Platform: Ubuntu 23.10
 - Package and version: 389-ds-base-2.4.4.

**Steps to Reproduce**

1. git clone git@github.com:389ds/389-ds-base.git
2. cd 389-ds-base
3. git checkout 389-ds-base-2.4.4
4. autoreconf -fiv

**Expected results**
A usable build configuration

**Screenshots**
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
configure.ac:62: warning: your code may safely assume C89 semantics that RETSIGTYPE is void.
configure.ac:62: Remove this warning and the `AC_CACHE_CHECK' when you adjust the code.
./lib/autoconf/general.m4:2434: AC_DIAGNOSE is expanded from...
configure.ac:62: the top level
configure.ac:30: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: error: /usr/bin/autoconf failed with exit status: 1

**Additional context**
When attempting to use 'configure' after failing step 1 the following errors occurs

configure: error: cannot find required auxiliary files: compile config.guess config.sub missing install-sh

**Comment by vashirov** [comment]
You have missing build dependencies. Install them using `sudo apt build-dep 389-ds-base`.
