### ISSUE TITLE
idletimeout may be ignored.

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#6004]
**Issue Description**
See https://issues.redhat.com/browse/RHEL-17511

**Package Version and Platform:**
 - Platform: redHat
 - Package and version: 9.4
 

**Steps to Reproduce**
1. Have an application that:
     - open a connection
     - bind as an non directory manager user
     - wait longer than idletimeout
2. run: dsconf instance monitor server 
3. See error: number of open connections is 2 instead of 1 

**Expected results**
Connection should be closed

**Additional context**
looks like the timeout is only handled when there are some activity on the other connections.

**Comment by progier389** [comment]
Two points:
   [1] Connection bound on Directory manager are not subject to idletimeout (nor any other resource limits)
                - idletimeout is explicitly disabled while binding as directory manager 
                (This is arguable but that is the way it is coded)
   [2] But idletimeout is still not handled when binding as another user too (unless there are some activity
          on another connection )
          I propose to handle that one by adding a slapi_eq_repeat_rel handler that walk all active connection every seconds
          (Another way would have been to do the test in the listening thread (when the poll times out) but small
           performance impact in these threads have a massive impact on the overall server performance)

**Comment by tbordaz** [comment]
The bug fix is pushed 2.5 and later. It is missing 1.4.3 up to 2.4

**Comment by progier389** [comment]
8928951f3..86b5969ac main -> main
   4f9a28c33..bdb0a72b4  389-ds-base-2.4 -> 389-ds-base-2.4
   37fae334a..1ecd89b9a  389-ds-base-2.3 -> 389-ds-base-2.3
   e4c5fc7ab..8bd8977a7  389-ds-base-2.2 -> 389-ds-base-2.2
   45b692501..61cebc191  389-ds-base-2.1 -> 389-ds-base-2.1
   dc56bf26a..1bf10c86b  389-ds-base-2.0 -> 389-ds-base-2.0
   eef788132..5f8fb8ccd  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   eef788132..5f8fb8ccd  389-ds-base-1.4.4 -> 389-ds-base-1.4.4

**Comment by tbordaz** [comment]
Multiple listener threads was introduced in branch 2.2
Adapt the patch to branches 1.4.3 to 2.1 where there was a single listener
74125a682..f4d55ef4e  389-ds-base-2.1
21ef6b11a..8738bc1f1  389-ds-base-2.0
38e11b1ba..aa59250f4  389-ds-base-1.4.4
3c3e610c7..c37b236d4  389-ds-base-1.4.3

**Comment by tbordaz** [comment]
Removing a test backported by error
95e070f1e..4c7941ff3  389-ds-base-2.4
