### ISSUE TITLE
Pin upload/download artifacts action to v3

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#6016]
**Issue Description**
After update of actions/download-artifact to v4, our PR CI started to fail.
A workaround is to pin to the older version v3.

**Comment by progier389** [comment]
b03738dff..9d00b6d02  389-ds-base-3.0 -> 389-ds-base-3.0
   5451a4abf..d6b11656a  389-ds-base-2.6 -> 389-ds-base-2.6
   60b6a5837..417efec1a  389-ds-base-2.5 -> 389-ds-base-2.5
   56a5d0f60..e6eaa5c7a  389-ds-base-2.4 -> 389-ds-base-2.4
   f6993420b..2767cfecd  389-ds-base-2.3 -> 389-ds-base-2.3
   90ee62e96..b0a3b38a0  389-ds-base-2.2 -> 389-ds-base-2.2
   99a888048..45b692501  389-ds-base-2.1 -> 389-ds-base-2.1
   a722faaef..dc56bf26a  389-ds-base-2.0 -> 389-ds-base-2.0
