### ISSUE TITLE
Troubleshooting of slow user add or modify operation in certain conditions

### ISSUE THREAD

**Issue by vudex** [389ds/389-ds-base#6020]
**Issue Description**
We have a FreeIPA 4.9.11 installation in production that uses the following 389-ds server version:
```
389-ds-base-2.2.3-alt2.x86_64
```
Lately I struggle to add new users to certain groups, that has excessive (can I call the ~100 parents excessive?) number of parents. 389-ds hangs during operation that could take from 2 to 5 minutes on clean deployment. 

I'm attaching illustration of my setup:

![2023-12-26_23-47-49](https://github.com/389ds/389-ds-base/assets/2268164/9dd40c32-e6ac-42c3-8cd0-7410382a71d1)

**Package Version and Platform:**
 - Platform: [AltLinux c10f1](https://packages.altlinux.org/en/c10f1/)
 - Package and version: 389-ds-base-2.2.3-alt2.x86_64
 - Chrome

**Steps to Reproduce**
1. Create 100 groups, in my example those are `group-test-<number>`
2. Create group `user-group` and add this group as a child member of previously created `group-test-*` groups
3. Create 150 users,  in my example those are `user-test-<number>`
4. Add those users to the `user-group` as direct members. Notice that adding time increases as the count reaches 150
5. Created final user for test `test-user`
6. Attempt to add the user to the user-group, observing that the operation takes an extended amount of time and can hang the 389-ds server, rendering LDAP operations against the server impossible and the service unavailable for a period of time.
7. Delete `test-user` from `user-group` and notice the same effect during delete operation.

**Expected results**
The addition of users without causing server lag. The time taken for the operation does not matter significantly, as long as it is done in an asynchronous fashion.

**Additional context**
I am not reporting a bug, but seeking advice and troubleshooting directions. 

- What could be causing these effects, and how can I investigate further?
- Is it normal behavior for such user and group configurations?
- What metrics could I collect to illustrate the problem to maintainers?
- Is this issue more related to FreeIPA or 389-ds? Is this the right place to report the problem?

**Comment by vudex** [comment]
I tried to use instractions, specified for 389-ds hangs troubleshooting, described [here](https://www.port389.org/docs/389ds/FAQ/faq.html#debugging-hangs).

[slapd_stacktraces.tar.gz](https://github.com/389ds/389-ds-base/files/13783573/slapd_stacktraces.tar.gz)

While I was waiting for operation of adding user to the `user-group` I issued gdb command:

```
gdb -ex 'set confirm off' -ex 'set pagination off' -ex 'thread apply all bt full' -ex 'quit' /usr/sbin/ns-slapd `pidof ns-slapd` > stacktrace.`date +%s`.txt 2>&1
```

**Comment by tbordaz** [comment]
Thanks for the backstacks, it looks to me that the server is very busy with Schema Compat plugin. I would suggest to disable that plugin during the provisioning period.

**Comment by vudex** [comment]
@tbordaz ty very much

I did a small test. First one with compat plugin enable and second one with compat plugin disabled:

```
[root@ipa-test /]# time ipa group-add-member user-group --users=another-user-01
0.48user 0.09system 0:52.84elapsed 1%CPU (0avgtext+0avgdata 51332maxresident)k
0inputs+0outputs (0major+9906minor)pagefaults 0swaps


[root@ipa-test /]# time ipa group-add-member user-group --users=another-user-01
0.47user 0.07system 0:00.89elapsed 61%CPU (0avgtext+0avgdata 51432maxresident)k
0inputs+0outputs (0major+9907minor)pagefaults 0swaps
```

Well, what are consequences of disabling pluging completly in production? I don't remember any LDAP clients to be directed to the cn=compat,$SUFFIX 

I read [this description](https://pagure.io/slapi-nis/blob/master/f/doc/ipa/sch-ipa.txt) but it still not clear for me. I guess I can just turn it off, isn't it?
