### ISSUE TITLE
Filter with AND indexed components is tested on each returned entries

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#6030]
**Issue Description**
A filter like '( & (comp_1) (comp_2)...(comp_n))' is tested on each returned entries even if each individual component is indexed. There is an exception if the filter contains only one component. But starting with two components the filter is tested.

If the result set is large (thousands entries) and the test is expensive (complex MR or upload large valueset like members), it can create significant overhead. 

**Package Version and Platform:**
 Need to be confirmed

**Steps to Reproduce**
1. Create 10000 groupofuniquenames and each of them a specific member (foo)
2. index objectclass and uniqueMember in equality (default)
3. compare time search "(uniquemember=foo)" and "(&(objectclass=groupofuniquenames)(uniquemember=foo))"

**Expected results**
The two searches should have similar response time

**Comment by Firstyear** [comment]
Isn't this just the grok-filter issue again?

**Comment by tbordaz** [comment]
@Firstyear your guess is right !
The (in)famous grok-filter is responsible of that.
grok-filter checks that there are no subtypes (in addition to allid), that looks fine to me. But there are internal logic that need to be discussed. I will send a PR soon to start that discussion.

**Comment by tbordaz** [comment]
After deeper investigations I found that the bypass of the filter, with AND filter components, was not the culprit of my testcase. I still have a doubt that we could bypass the filter in such case but I will not have the capacity to work on it right now.
I am closing this ticket. Feel free to reopen it if needed.
