### ISSUE TITLE
dscreate create-template claims replica_id is (str)

### ISSUE THREAD

**Issue by Elwell** [389ds/389-ds-base#6033]
**Issue Description**
Generating a sample template using `dscreate create-template` gives the impression that replica_id can be a string

```
> dscreate  create-template | grep -A3 "^# replica_id"
# replica_id (str)
# Description: Set the unique replication identifier for this replica's database (suppliers only)
# Default value: 1
;replica_id = 1
```

It should be "replica_id (int)"

**Package Version and Platform:**
 - Platform: Opensuse Leap 15.5
 - Package and version: 389-ds-2.2.8~git51.3688d68-150500.3.14.1.x86_64

**Steps to Reproduce**
dscreate  create-template 

**Expected results**
```
# replica_id (int)
# Description: Set the unique replication identifier for this replica's database (suppliers only)
# Default value: 1
;replica_id = 1
```

**Additional context**
setting this to a string (yes, I know the default is 1) crashes the dscreate later when importing template
```
    rid_num = int(rid)
ValueError: invalid literal for int() with base 10: 'polaris'
```

**Comment by vashirov** [comment]
6c6c5a912..f4398df05  389-ds-base-2.0 -> 389-ds-base-2.0
   a1d0557ab..9bc4bb793  389-ds-base-2.1 -> 389-ds-base-2.1
   bcea662a4..18a1c6b55  389-ds-base-2.2 -> 389-ds-base-2.2
   345d67998..d23068dec  389-ds-base-2.3 -> 389-ds-base-2.3
   06051f771..c4b7edf65  389-ds-base-2.4 -> 389-ds-base-2.4
