### ISSUE TITLE
Make dscreate to work during kickstart installations

### ISSUE THREAD

**Issue by moshevds** [389ds/389-ds-base#6046]
**Is your feature request related to a problem? Please describe.**

I want to run dscreate during a kickstart installation (F39).

**Describe the solution you'd like**

The only problem I encountered is that systemctl is not available in a chroot environment. Since lib389 already both supports systems with and without systemd, I was able to slightly alter the systemd checks so that the instance is able to start and install correctly. The two points that I changed are `DirSrv.status` and `DirSrv.start`. Unfortunately, I'm not familiar enough with lib389 to know what impact this may have elsewhere and/or what other places should be changed as well. Therefore, I'm not posting this as a PR just yet.

One additional issue I noticed is that "systemctl is-active" will return exit status 0 in the chroot environment, which lib389 interprets as if the instance is already running. (Arguably this could be seen as a systemctl bug.)

**Additional context**

This is the patch I have included in my kickstart file and it works for my purpose:
```diff
--- /usr/lib/python3.12/site-packages/lib389/__init__.py
+++ /usr/lib/python3.12/site-packages/lib389/__init__.py
@@ -1068,7 +1068,7 @@
         if self.status() is True:
             return

-        if self.with_systemd():
+        if self.with_systemd_running():
             self.log.debug("systemd status -> True")
             # Do systemd things here ...
             subprocess.check_output(["systemctl", "start", "dirsrv@%s" % self.serverid], stderr=subprocess.STDOUT)
@@ -1168,7 +1168,7 @@

         Will update the self.state parameter.
         """
-        if self.with_systemd():
+        if self.with_systemd_running():
             self.log.debug("systemd status -> True")
             # Do systemd things here ...
             rc = subprocess.call(["systemctl",
@@ -1685,6 +1685,16 @@
             return self.systemd_override
         return self.ds_paths.with_systemd
 
+    def with_systemd_running(self):
+        if not self.with_systemd():
+            return False
+        rc = subprocess.call(["systemd-detect-virt", "--chroot",
+                              "--quiet"])
+        if rc == 0:
+            rc = subprocess.call(["systemctl", "is-system-running",
+                                  "--quiet"])
+        return rc == 0
+
     def pid_file(self):
         if self._containerised:
             return "/data/run/slapd-localhost.pid"
```
What additional work is needed to merge this feature into dscreate and/or lib389? I may be able to spend a bit more time on this to create a PR if no big changes are needed. If another approach is needed, then please consider this as the feature request for that.

**Comment by Firstyear** [comment]
If it's in a chroot this could get pretty messy I think, if not impossible. If we don't detect systemd I don't think we will link the unit files so dirsrv won't work at boot. The "non-systemd" case is mainly an internal developer feature to run the server from a prefix.

The other issue is in the chroot we might end up accidentally stomping or mucking up some selinux labels. I think this would need a lot of testing to be sure it's working reliably ....

**Comment by moshevds** [comment]
I was worried about that, and I really don't know where to begin testing for those issues. That is why I didn't post a pull request. I guess there is no real way for me to add this feature in a robust way then. I'd still really like this to be possible, but it's not like we're deploying hundreds of 389ds machines this way. My main purpose is to have the installation procedure documented with executable documentation.

That said, the diff above *does* work "for me". I only changed the behaviour of `DirSrv.status` and `DirSrv.start`, specifically so that the unit files are still created. I also compared the selinux labels for the instance directory, and did not notice a difference. However, I only checked the specific configuration that I need, of course.

Thanks.

**Comment by Firstyear** [comment]
> I was worried about that, and I really don't know where to begin testing for those issues. That is why I didn't post a pull request. I guess there is no real way for me to add this feature in a robust way then. I'd still really like this to be possible, but it's not like we're deploying hundreds of 389ds machines this way. My main purpose is to have the installation procedure documented with executable documentation.
> 
> That said, the diff above _does_ work "for me". I only changed the behaviour of `DirSrv.status` and `DirSrv.start`, specifically so that the unit files are still created. I also compared the selinux labels for the instance directory, and did not notice a difference. However, I only checked the specific configuration that I need, of course.

@droideck What do you think about this? I think if it works outside a chroot is there a reason not to accept his as a PR then?

**Comment by droideck** [comment]
> @droideck What do you think about this? I think if it works outside a chroot is there a reason not to accept his as a PR then?

I think it is worth the PR, sure. It looks okayish at first glance, and we can check more scenarios (like prefix setup and our CI runs) in the PR.
So I'd say, @moshevds, feel free to create PR and we'll go from there. :) Thanks!

**Comment by vashirov** [comment]
> I want to run dscreate during a kickstart installation (F39).

> My main purpose is to have the installation procedure documented with executable documentation.

Could you please elaborate on your use case?

**Comment by moshevds** [comment]
> Could you please elaborate on your use case?

Sure.

We use kickstart for almost all our installations, along with other IaC (infrastructure as code) tools for the maintenance of our machines. In general, we are able to boot a new VM with a particular machine configuration fully automatically. (Usually for testing or reinstallation purposes.) For 389ds, we don't use ldap so much that this particular automation lowers our maintenance burden in any real way. But it is still convenient to have the installation procedure completely documented, and often manual instructions leave room for interpretation or don't get updated when software gets updated. That can lead to hard to resolve problems, especially if the person trying to fix a problem isn't the one who set up the machine initially. When our infrastructure is documented in a way that both humans and machines can understand, all of that becomes easier. That is what I meant with executable documentation. Since we use kickstart installs a lot, it makes sense to me to document our 389ds infrastructure in the same way.

The direct reason why I'm doing this right now is because the previous 389ds installation had a lot of undocumented tweaks that I now have to find and write down. Even though in theory we have every manual step documented, in practice that just isn't the entire story.

If 389ds in the future endorses a particular way of doing IaC that it prefers, that would likely work just as well. Kickstart is just what we use for installations, so it will be easiest to understand for someone who needs to fix something in the future. Personally, I'm excited about immutable infrastructure (CoreOS/Silverblue), although we are not yet actively moving in that direction.

**Comment by vashirov** [comment]
Thanks for the explanation. 
I personally use Ansible for post-install tasks on fresh VMs booted from golden images, but I understand that not everyone can use it. And IIUC you have fire-and-forget VM that does all configuration by itself, correct?

Using kickstart is not something I'd do to achieve this, since kickstart provides a very limited shell (main purpose is to install the OS, afterall), and `%post` was always a hack. But if it was my only option, I'd create in `%post` a systemd unit for [`systemd-firstboot`](https://www.freedesktop.org/software/systemd/man/latest/systemd-firstboot.html) with `ConditionFirstBoot=yes` and install DS on first boot, rather than in a systemd-less environment.

Having said that, I'm not against your approach. Please file a PR, we'll run the tests and see if this change breaks anything.

**Comment by moshevds** [comment]
Yes, our VM installations are fire-and-forget. We actually have a number of other `%post` scripts that can likely be made more robust by doing them on firstboot. Currently we don't have that anywhere, and my main hesitance to do it for the 389ds installation, was that it is just different. I'd rather do that as part of a broader move to gradually modernize our installation process.

Since `dscreate` apparently is already almost capable of installing in a chroot environment, it seemed to me to be the least disruptive way to do it. And I can imagine other people might have reasons to run `dscreate` in a chroot as well, so I will send a PR for this 🙂 (probably tomorrow or next week)
