### ISSUE TITLE
Drop unused pytest markers

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#6051]
**Issue Description**
We have pytest markers such as `bz12345` or `ds1234`. After migration from Pagure to GitHub `dsNNNN` markers no longer point to the right GitHub ticket. I wanted to update them and include in `pytest.ini`, but realized that we no longer actually use these markers. In fact, I use `git log` and `git blame` far more often to identify the related issues.
I discussed this with @bsimonova and we decided to drop these markers altogether. This should also reduce the warnings noise.

**Comment by tbordaz** [comment]
Those Markers are usually push along with a commit message that identify the ticket number. Most of the time the BZ contains that ticket number.
