### ISSUE TITLE
Certificate lifetime displayed as NaN

### ISSUE THREAD

**Issue by Adadov** [389ds/389-ds-base#6061]
**Issue Description**
 HOST_TIME_GMT content depends on user locale. When using cockpit in French (maybe others too) date calculation doesn't work, Date.parse() is unable to parse French format returned by shell running "date" command.

**Package Version and Platform:**
 - Browser: Firefox <= 119
 - Package: cockpit-389-ds

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Set cockpit "Display language" to "French"
2. Open any LDAP entry containing a certificate using "LDAP Browser"
3. The certificate will be displayed as expired since NaN day
![image](https://github.com/389ds/389-ds-base/assets/1457784/cd6c95eb-f13d-424c-84cb-53f20e76dd07)

**Comment by vashirov** [comment]
d5345e72a..d3bb02acc  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   f1cfa741c..b2092b826  389-ds-base-2.0 -> 389-ds-base-2.0
   47eccfbff..3b4044bd4  389-ds-base-2.1 -> 389-ds-base-2.1
   2f5029ec7..bf43865e8  389-ds-base-2.2 -> 389-ds-base-2.2
   d1135cccc..4e17fd6c5  389-ds-base-2.3 -> 389-ds-base-2.3
   dec3183e8..650dc518e  389-ds-base-2.4 -> 389-ds-base-2.4
   93ebf3c53..70d35bac5  389-ds-base-2.5 -> 389-ds-base-2.5
