### ISSUE TITLE
Improve CLI help section for dsidm and general parent arguments

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#6067]
**Issue Description**
We have two issues that make a user's life harder when they use 389 DS CLI tools.

1. When you create an entry with dsidm, the OU where this entry is placed must exist. However, this information, and the required OUs are neither mentioned in --help, the man page, nor does the error message contains any hint.

    Suggestion:
    * dsidm should mention the required OUs both in --help and the man page.
    * It would be nice if the error message could show a meaningful error:
      > Error: 105 - 4 - 32 - No such object - [] - dc=example,dc=com
      
      It's really not self-explaining that it means that ou={people,group,...} is missing

2. When we run:
    ```
    dsctl test db2bak -h
    usage: dsctl [instance] db2bak [-h] [archive]
    ```
    There is no [-v] option before instance_name mentioned, so user will not know he can use it unless he runs "dsctl -h". 

    It should mention [-v] in help like this:
    ```
    usage: dsctl [-v] [instance] db2bak [-h] [archive]
    ```

**Comment by droideck** [comment]
BZ#1 - https://bugzilla.redhat.com/show_bug.cgi?id=2164990
BZ#2 - https://bugzilla.redhat.com/show_bug.cgi?id=2019735

**Comment by droideck** [comment]
For the second case, I investigated the issue from different sides, and I think we have at least three options here:

1. Just add `-v` and `-j` parameters to all of the subparsers.

**Comment by droideck** [comment]
For the second case (`There is no [-v] option before instance_name mentioned`), I tried different approaches, and I think we have at least three options here:

1. Just add `-v` and `-j` parameters to all of the subparsers.
   That won't actually work (or at least, I wasn't able to find how to make it work with argparse).
   If we do so, `-v` is accepted at this position `dsctl [-v] [instance] db2bak [-h] [archive]`, but it's always set to the default `False` because `-v` from a subparser overwrites the value.

2. We can specify `-v` and `-j` at the [shared parent parser](https://docs.python.org/3/library/argparse.html#parents)
   It is how argparse assumes we approach the problem. It is simple, consistent and without any hacks.
   But it will bring a problem, that current way of doing things won't work anymore `usage: dsctl [-v] [instance] db2bak [-h] [archive]`.
   Only this will work: `usage: dsctl [instance] db2bak [-v] [-j] [-h] [archive]`. Hence, we'll need to fix all of the WebUI cmd lines and it may break some customer's scripts.

3. We can modify the help info using the `argparse.HelpFormatter` implementation.
   It will give us fine-grained control over the text, and we can mention that `-v` and `-j` are accepted before the instance name.
   It is a hack, though, and we'll need to keep track of it if we make any changes in `-v` and `-j` or if argparse changes something in its implementation. So, it brings a complexity that can be avoided. 

Also, it's possible that the issue "hidden parent options in a subparser usage" is already reported somewhere here - https://github.com/orgs/python/projects/5/views/10 . I might look through them later (it's a pile of chaos), but we have customers asking for a fix now. So I think we should choose the 2nd or 3rd approach.

What do you think, folks?

**Comment by droideck** [comment]
Issue 6067 - Improve dsidm CLI No Such Entry handling

   ac8c9fe20..29c79c982  389-ds-base-3.0 -> 389-ds-base-3.0
   8aaf66d4f..6da79f751  389-ds-base-2.5 -> 389-ds-base-2.5
   9a060d1e4..c12dad024  389-ds-base-2.4 -> 389-ds-base-2.4
   3f43fd9e6..05eac41a1  389-ds-base-2.3 -> 389-ds-base-2.3
   1c69824e9..563e42150  389-ds-base-2.2 -> 389-ds-base-2.2
   8ec106aa6..a6c24e97f  389-ds-base-2.1 -> 389-ds-base-2.1
   c3ee4c564..0dbff28f4  389-ds-base-2.0 -> 389-ds-base-2.0
   cfb273f9e..af51ea43f  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by droideck** [comment]
47184c795..6fa06a719  389-ds-base-3.0 -> 389-ds-base-3.0
   a40564b84..74f2f25a4  389-ds-base-2.5 -> 389-ds-base-2.5
   f4b7e3348..7715ff141  389-ds-base-2.4 -> 389-ds-base-2.4
   1aca07dbe..545947493  389-ds-base-2.3 -> 389-ds-base-2.3
   c392716d4..62c77454f  389-ds-base-2.2 -> 389-ds-base-2.2
   3c3e38d11..f6563c36b  389-ds-base-2.1 -> 389-ds-base-2.1
   71ed6a459..9f45be601  389-ds-base-2.0 -> 389-ds-base-2.0
   2cc75ffd3..9455713f8  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by Firstyear** [comment]
Thank you @droideck !
