### ISSUE TITLE
Improve error log when running out of memory

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#6073]
**Is your feature request related to a problem? Please describe.**
Need to improve error log message when a large malloc fails as in https://pagure.io/freeipa/issue/9525

**Describe the solution you'd like**
The idea is simply to also log the stack backtrace when a calloc/malloc/realloc fails and requested memory size is larger than
some threshold (let say 1Mb)

**Describe alternatives you've considered**
Logging the stack in case of failure with small size has not much interest as in such case usually the problem is that and the configuration parameters are not adapted to the  the system memory and the failure location is quite random. 

But requiring a large amount of memory is pretty unusual and could be due to uninitialized data or other error, and then the stack is a valuable hint to fix the issue.

**Additional context**
IMHO we should  also adapt the advices to lmdb (some of the tuning mentioned in the error message are now irrelevant)

**Comment by Firstyear** [comment]
I think we can only remove the dbcachesize warning since LMDB relies on the VFS for caching, rather than BDB where we have to malloc pages.

**Comment by tbordaz** [comment]
Usually a failure to malloc leads to an exit or a crash, logging a backtrace at that time has no impact on regular operation. For sure it will help to debug those rare cases. I also wonder if large candidate list could also create big malloc. A possible contributor here could also be the import cache (nsslapd-import-cachesize)

**Comment by progier389** [comment]
FYI: unlike in bdb case, lmdb import does not use the import cache  The import pipeline is very different because of the different database constraints ( single write txn required in lmdb - need to limit the open/close of databases in bdb case 
So in lmdb case there is  only one active entry per worker threads (because there is no way to write in the different dbs at the same time and all subdbs are always open (no file descriptor involved)) while in bdb, worker thread handle a single attribute from all the entries stored in the import cache
