### ISSUE TITLE
Bdb deprecation - Remove explicit dependency to libdb

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#6082]
**Is your feature request related to a problem? Please describe.**
libdb is deprecated and may not be available in future os, the idea is to remove any explicit dependency towards this library. 

**Describe the solution you'd like**

1. Move the db-bdb code out of libback-ldbm.so into a new libback-bdb.so plugin
2. Bundle a custom version of libdb named libdb-5.3-389ds.so built from libdb source rpm 
3. Have a new 389-ds-base-bdb package (flagged as deprecated) that includes libback-bdb.so plugin and libdb-5.3-389ds.so
4. Remove any prerequiste towards libdb from the rpm files
5. Remove DB_File dependency in logconv.pl (will impact the tool performance but that change will buy us the time that we need to rewrite the tool in python.
6. Load dynamically the plugin if configured with bdb and shout loudly if the module is not available

**Describe alternatives you've considered**
Use static library for libdb instead of a shared one

**Additional context**
libdb is deprecated since Fedora 33  [https://fedoraproject.org/wiki/Changes/Libdb_deprecated](https://fedoraproject.org/wiki/Changes/Libdb_deprecated) and the plan is to remove it for upcoming Centos Stream 10

**Comment by progier389** [comment]
Reopening the issue following yesterday discussion:
 The idea is to revert to not using the bundled libdb by default so that Fedora keep still using the old libdb lib
 And as Viktor suggested, the build command will be changed (either using an environment variable or the configure option) for CentOS and RHEL versions.

**Comment by Firstyear** [comment]
What was the reason for the revert of this? I thought it was being bundled so that Fedora could remove libdb?

**Comment by progier389** [comment]
Hi @Firstyear, FYI: it is a timing issue. For Fedora we  plan to still keep libdb in F41 and F42 to let people time to migrate cleanly, but on CentOS 10 and RHEL 10  we need to move now. (That is why we rushed things a bit lately)

**Comment by Firstyear** [comment]
Ahhh thanks for clearing that up :)
