### ISSUE TITLE
gitub warning: Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#6100]
**Issue Description**
We need once again to adapt github actions to limit the amount of warnings: 

[validate](https://github.com/389ds/389-ds-base/actions/runs/7935320982/job/21668197053)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Steps to Reproduce**
1. Look at CI test reports

**Comment by vashirov** [comment]
Also `actions/cache@v3`, `actions/upload-artifact@v3, `actions/download-artifact@v3`. Last time we did the bump, v4 was broken. Hope it works this time :)

**Comment by progier389** [comment]
Fixed by #6191
