### ISSUE TITLE
Typo in Account Policy plugin message

### ISSUE THREAD

**Issue by bsimonova** [389ds/389-ds-base#6110]
**Issue Description**
When saving configuration for Account Policy Plugin, the confirming message says "Config entry cn=config,cn=Account Policy Plugin,cn=plugins,cn=config was successfully seted". It should be 'set'

**Package Version and Platform:**
389-ds-base-2.0.14-7.module+el9dsrv+14845+69b2f526.x86_64
cockpit-389-ds-2.0.14-7.module+el9dsrv+14845+69b2f526.noarch

**Steps to Reproduce**
1. Go to Plugins tab -> Click Account Policy
2. Enable plugin -> restart
3. Create Config
4. Check "Always Record Login"
5. Click Add config

**Comment by tbordaz** [comment]
e555c2a80..4fe22eccb  main
1475453e5..b6f987e0c  389-ds-base-3.0
2541f88e4..5f188e689  389-ds-base-2.5
17805fabc..80f554be5  389-ds-base-2.4
fb6ef0aef..93d456d6f  389-ds-base-2.3
