### ISSUE TITLE
DNA plugin defaults do not include remote BIND method and remote BIND protocol

### ISSUE THREAD

**Issue by abbra** [389ds/389-ds-base#6123]
FreeIPA configures uniform authentication and access methods for DNA plugin on all replicas: it uses SASL GSSAPI and LDAP. In order to set those, IPA installer has to wait until its own server entry is asynchronously created by the DNA plugin and then update the entry. This process takes up to two minutes which is almost a half of time spent on creating IPA server with integrated DNS and external TLS certificates (e.g., without integrated CA).

DNA plugin's configuration entry already allows to specify remote bind DN and remote bind password. 
This is handled by `dna_get_shared_servers()` which pulls `remote_binddn` and `remote_bindpw` from the global config entry unconditionally:
```
...
                server->remote_binddn = config_entry->remote_binddn;
                server->remote_bindpw = config_entry->remote_bindpw;
                server->remote_bind_method = slapi_entry_attr_get_charptr(entries[i],
                                                                          DNA_REMOTE_BIND_METHOD);
                server->remote_conn_prot = slapi_entry_attr_get_charptr(entries[i],
                                                                        DNA_REMOTE_CONN_PROT);
...
```

If we could add similar handling for `remote_bind_method` and `remote_conn_prot`, with an override from the server entry, that would be great. This way we can pre-create the configuration with the same method/protocol values and skip waiting for the server entry to be created from DNA plugin side.

**Comment by abbra** [comment]
I created a proposed PR https://github.com/389ds/389-ds-base/pull/6124

**Comment by tbordaz** [comment]
1a7abef18..c019af140  main
d7e2d8633..99c2989ac  389-ds-base-3.0
c09c0f23d..2bfa8be24  389-ds-base-2.5
45e14d64c..e4c1e7ea4  389-ds-base-2.4
