### ISSUE TITLE
dscreate interactive fails when chosing mdb backend

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#6125]
**Issue Description**
dscreate in interactive mode fails when using mdb as backend

**Package Version and Platform:**
 - Package and version:  389-ds-base (main branch)

**Steps to Reproduce**
1. sudo dscreate  interactive
2. Use default options requiring no user input 
3. Instance creation fails with error: Error: expected string or bytes-like object, got 'int'

**Expected results**
Instance created

**Comment by progier389** [comment]
FYI: Fix is  trivial (and BTW  the crashing stack is showed when using dscreate -v interactive):
src/lib389/lib389/utils.py
1721c1721
<         val,unit = re.fullmatch(SIZE_PATTERN, str(size), flags=re.IGNORECASE).groups()
---
>         val,unit = re.fullmatch(SIZE_PATTERN, size, flags=re.IGNORECASE).groups()

**Comment by jchapma** [comment]
> FYI: Fix is trivial (and BTW the crashing stack is showed when using dscreate -v interactive):

It is, great for a Friday evening

**Comment by jchapma** [comment]
b6f987e0c..2003e376c  389-ds-base-3.0 -> 389-ds-base-3.0
5f188e689..bf0365300  389-ds-base-2.5 -> 389-ds-base-2.5
80f554be5..f52c5f2f0  389-ds-base-2.4 -> 389-ds-base-2.4
