### ISSUE TITLE
Move slapi_pblock_set_flag_operation_notes() to slapi-plugin.h

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#6133]
**Issue Description**

slapi_pblock_set_flag_operation_notes() is currently only available in slapi-private.h, but with the latest changes at add "notes=M" it needs to be available to plugins.

**Comment by droideck** [comment]
https://github.com/389ds/389-ds-base/issues/6112

**Comment by mreynolds389** [comment]
2003e376c..ca378867c  389-ds-base-3.0 -> 389-ds-base-3.0
bf0365300..3f74a6603  389-ds-base-2.5 -> 389-ds-base-2.5
f52c5f2f0..6586fbe6e  389-ds-base-2.4 -> 389-ds-base-2.4
