### ISSUE TITLE
[RFE] Add LMDB configuration related checks into Healthcheck tool

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#6142]
**Description**
Add a warning in healthcheck if bdb is still used.
Add warnings if there's a mismatch in configuration attributes.

**Comment by progier389** [comment]
Issue 6142 - [RFE] Add LMDB configuration related checks into Healthcheck tool (#6143)
 abb6723b7  main -> main
 a7287a3da..f48026f55  389-ds-base-2.5 -> 389-ds-base-2.5
