### ISSUE TITLE
fix healthcheck CI test

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#6146]
**Issue Description**
Some healthcheck CI tests are failing 

**Steps to Reproduce**
sudo pytest -s -v  ./dirsrvtests/tests/suites/healthcheck/healthcheck_test.py

**Expected results**
Tests should pass

**Screenshots**
FAILED dirsrvtests/tests/suites/healthcheck/healthcheck_test.py::test_healthcheck_standalone
FAILED dirsrvtests/tests/suites/healthcheck/healthcheck_test.py::test_healthcheck_standalone_tls
FAILED dirsrvtests/tests/suites/healthcheck/healthcheck_test.py::test_healthcheck_replication
FAILED dirsrvtests/tests/suites/healthcheck/healthcheck_test.py::test_healthcheck_replication_tls
FAILED dirsrvtests/tests/suites/healthcheck/healthcheck_test.py::test_healthcheck_backend_missing_mapping_tree
ERROR dirsrvtests/tests/suites/healthcheck/healthcheck_test.py::test_lint_backend_implementation

**Comment by progier389** [comment]
FYI: I got the same issue while running test after backporting  the lmdb fixes to 2.5 branch
And in fact healthcheck_test.py is not the only one being impacted  healthcheck_config_test.py is also impacted.

I identified a first problem: by default the auditlog is not buffered and healthcheck issue a warning about it.
Guess we should not directly use topology_st but a 
healthcheck_topology module fixture that ensure that the instance is properly configured to have no healthcheck warning by default.

should also improve run_healthcheck_and_flush_log to help the debbuging.
Typically by adding the expected result and the testcase name in the log:
+        log.info(f'Use healthcheck with --json option. Expecting {searched_code}. Testcase is {os.getenv("PYTEST_CURRENT_TEST")}.')
and also log a message if the result is None
