### ISSUE TITLE
ldap-agent fails to start because of permission error

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#6155]
**Issue Description**

**Package Version and Platform:**
 - Platform: Fedora 39
 - Package and version: main branch
 - Browser N/A

**Steps to Reproduce**
1. dnf install -y 389-ds-base 389-ds-base-snmp net-snmp
2. echo master agentx >> /etc/snmp/snmpd.conf
4. systemctl restart snmpd
5. dscreate interactive  (Create a ds instance as usual)
6. edit  /etc/dirsrv/config/ldap-agent.conf to add the new instance
7. systemctl start dirsrv-snmp
8. See the error (instance fails to start)

**Expected results**
dirsrv-snmp service should be able to start

**Additional context**

/run/dirsrv  is created with the wrong group should be root instead of dirsrv so that both 
 ns-slapd and ldap-agent can read and create files in it.
Fix should be in src/lib389/lib389/instance/setup.py around # Setup tmpfiles_d

**Comment by progier389** [comment]
Jira ticket is [https://issues.redhat.com/browse/IDMDS-3497](https://issues.redhat.com/browse/IDMDS-3497)

**Comment by tbordaz** [comment]
3fe566124..eb7e57d77  main
0fb74967f..c3ff6e8ff  389-ds-base-3.0
cf6cdd05b..7cb34ed42  389-ds-base-2.6
cf6cdd05b..7cb34ed42  389-ds-base-2.5

**Comment by tbordaz** [comment]
Hi @progier389 , this fix is needed for a 1.4.3 zstream but it is not backported there. Could you do the backport ?

**Comment by progier389** [comment]
063f58dd0..e7d847aec  389-ds-base-2.4 -> 389-ds-base-2.4
   b4c42837f..822f3607b  389-ds-base-2.3 -> 389-ds-base-2.3
   ec9046b4d..e0c4ec778  389-ds-base-2.2 -> 389-ds-base-2.2
   9623469df..7b9bcda1a  389-ds-base-2.1 -> 389-ds-base-2.1
   70fa953bb..90d537d49  389-ds-base-2.0 -> 389-ds-base-2.0
   4f9fdfbe2..0bd5fbd6e  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
