### ISSUE TITLE
Server crash when using the referential integrity plugin(referint.c)

### ISSUE THREAD

**Issue by iamarty3z** [389ds/389-ds-base#6165]
**Issue Description**
Server crash when using the referential integrity plugin when transactions are used and an error occurs when opening a file for writing

**Steps to Reproduce**
1) enable the plugin using transactions (betxnpostoperation)
2) set delay > =1
3) remove permission to write to the directory where the log file will be created 
4) move entry from containerscope
5) server crash

**Expected results**
Logging an error message and continuing work

**Additional context**
The crash is caused by using an uninitialized mutex **PR_Unlock(referint_mutex))** after the error message and before calling referint_unlock();

**Comment by progier389** [comment]
closing as uplicate of [https://github.com/389ds/389-ds-base/issues/6166](https://github.com/389ds/389-ds-base/issues/6166)
