### ISSUE TITLE
Missing git tags on releases

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#6169]
https://github.com/389ds/389-ds-base/releases/tag/389-ds-base-3.0.3

I noticed this was tagged, but the tag isn't in branch main - the latest tag there was 389-ds-base-3.0.1. Am I missing something about how we're tagging main now?

**Comment by vashirov** [comment]
Due to an oversight we didn't bump version in main to 3.1 when 389-ds-base-3.0 was branched. This will be fixed soon.

**Comment by Firstyear** [comment]
No problem, just wanted to check. Thanks!
