### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#6191]
**Issue Description**

GH Actions display a warning:
>  Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by progier389** [comment]
e030a885f..56a5d0f60  389-ds-base-2.4 -> 389-ds-base-2.4
   6b8dfec75..99a888048  389-ds-base-2.1 -> 389-ds-base-2.1
   9edfd0506..a722faaef  389-ds-base-2.0 -> 389-ds-base-2.0
