### ISSUE TITLE
Should disable WebUI CI tests 

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#6200]
WebUI CI test is systematically failing  for more than a year now. - and it as always been a bit flaky
And we never were able to find the bandwidth to fix it.
The Idea is to disable it because it is one of the last failing test. 

**Describe the solution you'd like**
My feeling is to add a RUN_WEBUI_TEST environment variable and skip the test if it is not set 
 (So the test will still be visible and we may re-enable it if we fix it)

**Describe alternatives you've considered**
Remove "webui" from generate_matrix.py  (like snmp was removed) but IMHO it has two drawbacks:
 - Remove the test visibility 
- Test will still be run by Q/E 

**Additional context**
We need to have a reliable 100% PASS test suite

**Comment by vashirov** [comment]
We already have an env variable `WEBUI` to enable the tests, by default they are skipped:
https://github.com/389ds/389-ds-base/blob/1b26ed9a1ed9a8b2b0e91e4cbad37ec1ad2f604c/.github/workflows/pytest.yml#L104
https://github.com/389ds/389-ds-base/blob/1b26ed9a1ed9a8b2b0e91e4cbad37ec1ad2f604c/dirsrvtests/tests/suites/webui/backup/backup_test.py#L19


So if you want to disable, it's enough to remove this var from the workflows :)
