### ISSUE TITLE
d2entry - Could not open id2entry err 0 - at startup when having sub-suffixes

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#6224]
**Issue Description**
Description of problem:
Sub suffix causes the following error when the Directory Server starts
~~~
```
ERR - id2entry - Could not open id2entry err 0
ERR - dn2entry_ext - The dn "ou=test,dc=example,dc=com" was in the entryrdn index, but it did not exist in id2entry of instance test.
```
~~~

**Package Version and Platform:**
 - Platform: RHEL
 - Package and version: 389-ds-base-2.2.7-3.module+el9dsrv+18864+4949f8c5.x86_64

**Steps to Reproduce**
1. Install 389-ds-base-2.2.7-3.module+el9dsrv+18864+4949f8c5.x86_64
2. Set up as follows

```
DHOST=$(hostname -s)
cat << EOF > /root/$DHOST.inf
[general]
[slapd]
instance_name = $DHOST
root_password = password1
[backend-userroot]
create_suffix_entry = True
suffix = dc=example,dc=com
EOF
dscreate from-file /root/$DHOST.inf
dsconf $DHOST backend create --suffix="ou=test,dc=example,dc=com" --be-name="test" --parent-suffix="dc=example,dc=com" --create-suffix

```
3. Restart the Directory Server and find the ERRs.
```
dsctl $DHOST restart
grep -A1 "Could not open id2entry" /var/log/dirsrv/slapd-$DHOST/errors

```

**Expected results**
No error.

**Additional context**
RHEL Bug:   https://issues.redhat.com/browse/DIRSRV-53

Triaged: https://issues.redhat.com/browse/IDMDS-4306

**Comment by progier389** [comment]
A minor issue related to the internal search that search for referral. 
I think that we should limit the search to a single backend

**Comment by progier389** [comment]
0f46d4339..4e3dc9e88  main -> main
   8e6ce71d3..ae8ab2141  389-ds-base-3.0 -> 389-ds-base-3.0
   dc0d81844..0f35be137  389-ds-base-2.5 -> 389-ds-base-2.5
   9501c34df..43057ebc3  389-ds-base-2.4 -> 389-ds-base-2.4
   99c01b8b0..47672fb37  389-ds-base-2.3 -> 389-ds-base-2.3
   f9c420d11..560b13273  389-ds-base-2.2 -> 389-ds-base-2.2

**Comment by progier389** [comment]
FYI: This problem was triggered by [issue #5598](https://github.com/389ds/389-ds-base/issues/5598) so it should be cherry picked in 2.1 and 1.4.3 too

**Comment by progier389** [comment]
796f703021e961fdd8cbc53b4ad4e20258af0e96
   e8f52e072..81de33cd8  389-ds-base-2.1 -> 389-ds-base-2.1
   33501f35f..fb296d372  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by vashirov** [comment]
@progier389 there is a leftover from merge conflict in https://github.com/389ds/389-ds-base/blob/fb296d3728c1bed1f7c222f9c3e3e699b9856a24/dirsrvtests/tests/suites/ds_logs/ds_logs_test.py#L1225

**Comment by vashirov** [comment]
And in https://github.com/389ds/389-ds-base/blob/81de33cd8113726a06ebb0b962ba34cfdd585cfb/dirsrvtests/tests/suites/ds_logs/ds_logs_test.py#L1288 too

**Comment by progier389** [comment]
Fixed the merge issues:
  9eef6c153..2b541c64b 389-ds-base-2.1 -> 389-ds-base-2.1
  fb296d372..24cc58fc6  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
