### ISSUE TITLE
nsslapd-numlisteners limit is not enforced 

### ISSUE THREAD

**Issue by jchapma** [389ds/389-ds-base#6256]
**Issue Description**
When a invalid value for the attribute nsslapd-numlisteners is used, config normalises the value but the invalid value is written to dse.ldif.

**Package Version and Platform:**
 - Package and version: 389-ds-base-2.3.4-3.el9.x86_64

**Steps to Reproduce**
1. dsconf localhost config get nsslapd-numlisteners
nsslapd-numlisteners: 1
2. dsconf localhost config replace nsslapd-numlisteners=5
Successfully replaced "nsslapd-numlisteners"
3. dsconf localhost config get nsslapd-numlisteners
nsslapd-numlisteners: 4
4. grep nsslapd-numlisteners /etc/dirsrv/slapd-localhost/dse.ldif
nsslapd-numlisteners: 5
5. systemctl restart dirsrv@localhost
6. dsconf localhost config get nsslapd-numlisteners
nsslapd-numlisteners: 4
7. grep nsslapd-numlisteners /etc/dirsrv/slapd-localhost/dse.ldif
nsslapd-numlisteners: 5

**Expected results**
Invalid values should return an operations error and not be written to dse.ldif

**Comment by vashirov** [comment]
f38c97e92..782ee9051  389-ds-base-2.4 -> 389-ds-base-2.4
   470aca016..4dbe43e12  389-ds-base-2.5 -> 389-ds-base-2.5
   fe279afa3..eaf8f90f2  389-ds-base-3.0 -> 389-ds-base-3.0

**Comment by jchapma** [comment]
Thanks @vashirov, I was just going to CP this commit back to relevant branches.
