### ISSUE TITLE
with lmdb a range search may fail to return some entries leading to truncated bulk import

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#6265]
**Issue Description**
Several issue seen after generating ldif with 2000 users and importing it in a replica:

1. The entryid attribute in missing in the suffix entry.
2. Access log shows that the internal search looking for "(parentid>=1)" is not returning all entries but one.
3. When initializing a replica through a replication agreement some entries are missing (because of 2)
4. Once 2. get fixed, the bulk import still fails because the default values for nsds5ReplicaFlowControlWindow and nsds5ReplicaFlowControlPause are not adapted to lmdb (supplier sent the entry faster than bdb and the target replica import them slower

 
**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 3.0.1
 - Browser: N/A

**Steps to Reproduce**
1. Configure two suppliers replication
2. Generate an ldif with 2000 users
3. Import the ldif
4.  search for entryid attribute in the suffix entry
5. search for entries with objectclass=*
6. search for entries with parentid>=1
7. Initialize second replica through first replica agreement.
8.search for entries with objectclass=* on second replica

**Expected results**

- [4] entryid should be 1
- [5] Should have one more entry than [6]
- [7] Initialization should be successful
- [8]  Should return sam,e number of entries than [5]

**Comment by progier389** [comment]
triaged: [https://issues.redhat.com/browse/IDMDS-4506](https://issues.redhat.com/browse/IDMDS-4506)

**Comment by progier389** [comment]
bd5e0ef72..f75b5e24e  main -> main
   7f6266dc1..f23494e76  389-ds-base-3.0 -> 389-ds-base-3.0
   152fbe5ea..af57d1ee6  389-ds-base-2.5 -> 389-ds-base-2.5

**Comment by timdarbydotnet** [comment]
Thanks for the quick fix. When will this be included in the 3.0 docker image?
