### ISSUE TITLE
web console is hanging. 

### ISSUE THREAD

**Issue by sjsong** [389ds/389-ds-base#6302]
**Issue Description**

web  console menu Monitoring --> Repliocation 

click  Repliocation --> webconsole hanging.

web console is hanging. because "dsconf replication monitor" use ~/.dsrc
but "dsconf replication status --suffix=xxxxxx" not use
so request binddn, bindpw

**Package Version and Platform:**
 - Platform: RHEL 8.9
 - Package and version: python3-lib389-1.4.3.39-7.module+el8.10.0+21985+3665ccdb.noarch.rpm
 - Browser chrome

**Screenshots**
![image](https://github.com/user-attachments/assets/aea53e13-797d-4bab-8b08-faa45b495b2c)

**Comment by droideck** [comment]
ad75529c7..97a82e546  389-ds-base-3.0 -> 389-ds-base-3.0
   08e704016..adba69d52  389-ds-base-2.5 -> 389-ds-base-2.5
   3aa6e3b66..1b4b6b599  389-ds-base-2.4 -> 389-ds-base-2.4
   f42fdc114..f26b9102c  389-ds-base-2.3 -> 389-ds-base-2.3
   ccbb8bae3..f05850695  389-ds-base-2.2 -> 389-ds-base-2.2
   37b45981b..d073b7f2d  389-ds-base-2.1 -> 389-ds-base-2.1
   cd07157a6..5117a42ef  389-ds-base-2.0 -> 389-ds-base-2.0
   4465cf496..62b860e7f  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
