### ISSUE TITLE
Wrong set of entries returned for some search filters

### ISSUE THREAD

**Issue by yaonos** [389ds/389-ds-base#6307]
**Issue Description**
389 Directory Server doesn't return the correct set of entries when the search filter is expressed like this :

(|(attribute_1=value_1)(&(attribute_2=value_2)(!(|(attribute_3=value_3)(attribute_4=value_4)))))

This filter does not return the entries that match the (&(attribute_2=value_2)(!(|(attribute_3=value_3)(attribute_4=value_4)))) part of the filter.

Consequently a search with the filter (|(&(attribute_2=value_2)(!(|(attribute_3=value_3)(attribute_4=value_4))))) always returns zero entries.

Note : if the filter is rewitten as (|(attribute_1=value_1)(&(attribute_2=value_2)(!(attribute_3=value_3))(!(attribute_4=value_4)))), that is logicaly equivalet as the first filter, the server returns the expected set of entries.

**Package Version and Platform:**
 - Platform: RedHat Enterprise Linux 8
 - Package and version: observed with 389-ds-base-2.2.9-2.el8.x86_64, 389-ds-base-2.5.1-2.el8.x86_64 and 389-ds-base-3.1.1-1.el8.x86_64

RPM version 2.5.1 was adapted to RHEL 8 from RHEL 9's 389-ds-base-2.5.2-1.el9.src.rpm.
RPM version 3.3.1 was adapted to RHEL 8 from Fedora's 389-ds-base-3.1.1-2.fc41.src.rpm that I downloaded from https://koji.fedoraproject.org/koji/buildinfo?buildID=2519163

**Steps to Reproduce**

1. Configure a new suffix named dc=example,dc=com and initialize it with the content of the file example_ldif.txt that is attached to this bug report
2. Search the content of the directory whith these parameters :
  base   : dc=example,dc=com
  scope  : sub
  filter : (|(telephoneNumber=3456)(&(telephoneNumber=1234)(!(|(uid=user1)(uid=user4)))))
3. The LDAP server returns one entry : uid=user6,ou=person,dc=example,dc=com
4. Search the content of the directory whith these parameters :
  base   : dc=example,dc=com
  scope  : sub
  filter : (|(&(telephoneNumber=1234)(!(|(uid=user1)(uid=user4)))))
3. The LDAP server returns nothing

**Expected results**

The first search is expected to return these entries :
- uid=user2,ou=person,dc=example,dc=com
- uid=user3,ou=person,dc=example,dc=com
- uid=user6,ou=person,dc=example,dc=com
- uid=user8,ou=person,dc=example,dc=com
- uid=user9,ou=person,dc=example,dc=com

The second search is expected to return these entries :
- uid=user2,ou=person,dc=example,dc=com
- uid=user3,ou=person,dc=example,dc=com
- uid=user8,ou=person,dc=example,dc=com
- uid=user9,ou=person,dc=example,dc=com

**Additional context**

This bug has been discovered with other attributes and a slightly different search filter. The sample LDIF file and the filters have been crafted in order to be able to explain this issue.
[example_ldif.txt](https://github.com/user-attachments/files/16707413/example_ldif.txt)

**Comment by tbordaz** [comment]
Thanks for the excellent testcase. JFR

<pre>
"(&(telephoneNumber=1234)(!(|(uid=user1)(uid=user4))))"  returns the valid set

dn: uid=user2,ou=person,dc=example,dc=com
uid: user2

dn: uid=user3,ou=person,dc=example,dc=com
uid: user3

dn: uid=user8,ou=person,dc=example,dc=com
uid: user8

dn: uid=user9,ou=person,dc=example,dc=com
uid: user9
</pre>

then

<pre>
"(telephoneNumber=3456)" returns the valid set

dn: uid=user6,ou=person,dc=example,dc=com
uid: user6
</pre>

So this is the result of both components that show the problem

**Comment by tbordaz** [comment]
The good news is that the indexes are safe, they return a valid candidate list (7 candidates) but because of the filter specificity, it evaluates the intended filter. The filter does not match some entries that it should match. So the bad news is that evaluation of the filter is possibly broken...

**Comment by tbordaz** [comment]
a9c7ff941..dc952e22a  main
6bb4cdec5..cdf482039  389-ds-base-3.0
f9288d340..136644612  389-ds-base-2.5
9bff7b47b..5344fee1a  389-ds-base-2.4
3eb0ea303..c2719abb7  389-ds-base-2.3
1dc8b3c2e..d9e3f3de9  389-ds-base-2.2
7fc0ec3d1..95ee6a61a  389-ds-base-2.1
8436d6b8d..5e2d637c0  389-ds-base-2.0

**Comment by tbordaz** [comment]
This bug only exists in 2.0 and after.
It was introduced with filter optimizer https://github.com/389ds/389-ds-base/issues/5170
The fix #5170 explicitely removed in vattr_test_filter_list_or
<pre>
-        if (only_check_access)
-            continue;

</pre>
Surprisingly all tests pass.
I am reopening in order to verify that those tests are successful

- filter_onelevel_aci_test.py 
- tests under test/libslapd/filter

**Comment by yaonos** [comment]
Hello,
For your record, I have patched our directory server with your fix. This has resolved this issue. No new problem has been observed since then.

**Comment by tbordaz** [comment]
@vashirov checked that both tests  are systematically run filter_onelevel_aci_test.py (nightly) and test_libslapd_filter_optimise (during build (cmocka ./test/libslapd/test.c))
Closing the ticket now
