### ISSUE TITLE
lib389 get_db_lib function may returns the wrong db type

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#6321]
**Issue Description**
lib389 get_db_lib function may returns the default database type instead of the configured one.

**Package Version and Platform:**
 - Platform: CentOS 9
 - Package and version: 389-ds-base-2.5.2-1.el9
 - Browser: N/A

**Steps to Reproduce**
1. Setup an lmdb instance
2. Run dsctl instance healthcheck 
3. See DSBLE0006 and DSBLE0005 errors

**Expected results**
Healthcheck should not display any errors.

**Additional context**
Problem is that  `from backend import DatabaseConfig` generate an ImportError so the call to DatabaseConfig(self).get_db_lib() is bypassed.
It should rather be:`from lib389.backend import DatabaseConfig`

**Comment by progier389** [comment]
Triaged: https://issues.redhat.com/browse/IDMDS-4635

**Comment by vashirov** [comment]
effca98ff..f21ba5e22  389-ds-base-2.5 -> 389-ds-base-2.5
62d967771..3497a865c  389-ds-base-2.6 -> 389-ds-base-2.6
d6ad2aee3..c0cbfc46b  389-ds-base-3.0 -> 389-ds-base-3.0
