### ISSUE TITLE
Does 389ds support sh\python plugins?

### ISSUE THREAD

**Issue by filimonic** [389ds/389-ds-base#6344]
**Is your feature request related to a problem? Please describe.**
I need some custom password sync plugin for very special purpose. In short, I need username and cleartext password exported when user changes its password or when admin resets password.

**Describe the solution you'd like**
I asked ChatGPT about 389ds support of some kind of scripts as plugins and it gave me tons of variants about how to register python file as plugin or use ipa_pwd_extop as runner for external bash script. Nothing work.

**Additional context**
I just want to ask professionals - does 389ds support any kind of external `script` plugins? Please, provide me and example of creating one. Maybe there is a plugin that can run passthrough some operations to external script?

**Comment by tbordaz** [comment]
AFAIK the short answer is no. There is no DS plugin already available that is able to to call an external script. 
I would suggest to use the plugin guide to implement such plugin (like the one you mentioned ipa_pwd_extop).
