### ISSUE TITLE
UI - crash when clicking on database tab

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#6370]
**Issue Description**

This is from a default installation.  Clicking on the Database tab triggers the UI to crash:

```
database.jsx:251 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Function.<anonymous> (database.jsx:251:55)
    at process_queue (cockpit.js:1311:37)
    at cockpit.js:1324:35
    at later_drain (cockpit.js:1205:13)
```

**Comment by vashirov** [comment]
@mreynolds389 what version are you using? I think it might be a duplicate of https://github.com/389ds/389-ds-base/issues/6065 (fixed in main, but not a part of any Fedora release yet).

**Comment by mreynolds389** [comment]
> @mreynolds389 what version are you using? I think it might be a duplicate of #6065 (fixed in main, but not a part of any Fedora release yet).

Yeah is has to be the same - closing this ticket....
