### ISSUE TITLE
UI - add npm "prettier" package

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#6404]
**Issue Description**

Add npm package "prettier" to the UI project.  It currently reports a lot of issues.

**Comment by droideck** [comment]
@mreynolds389 note that I'm currently working on https://github.com/389ds/389-ds-base/pull/6376 and it touches a lot of the code. So, this issue should probably be worked on after my PR is merged...

**Comment by mreynolds389** [comment]
> @mreynolds389 note that I'm currently working on #6376 and it touches a lot of the code. So, this issue should probably be worked on after my PR is merged...

It's a small change just to add the package.  We can run "prettier" later...

**Comment by mreynolds389** [comment]
4648172a1..ec6c2152a  389-ds-base-3.0 -> 389-ds-base-3.0
