### ISSUE TITLE
UI - localization does not handle react nodes/html tags

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#6411]
**Issue Description**

React nodes and html tags are not rendered correctly when using the "_()" localization function:

Screen shots

![image](https://github.com/user-attachments/assets/c689a6c6-8084-4d8b-a169-9260d552bcb6)

![image](https://github.com/user-attachments/assets/7a2392a1-9d3b-4844-81cb-d1954ab21a8f)

**Comment by vashirov** [comment]
See also: https://github.com/389ds/389-ds-base/issues/6059

**Comment by mreynolds389** [comment]
> See also: #6059

Yeah it's the same issue.  I'll close this as a duplicate
