### ISSUE TITLE
on replica consumer, account policy plugin fails to manage the last login history

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#6446]
**Issue Description**
The RFE #5807 allows to manage the last login history. On a consumer in replicated topology, the update of the history fails.
The symptom are, lastloginTime is not updated and an error is logged like
`ERR - acct_update_login_history - Modify error 10 on entry
`

**Package Version and Platform:**
since 2.4.2

**Steps to Reproduce**
A reproducible testcase is provided with the PR

**Expected results**
lastloginTime should be updated and no error logged

**Comment by tbordaz** [comment]
c7d5883e4..6873ced10  main
ab1692782..d9c7a8528  389-ds-base-3.0
df43b938f..027015f4d  389-ds-base-2.5
b4ee661d9..5c56cd377  389-ds-base-2.4
607570f2e..1418137fc  389-ds-base-2.3
b94e03ef0..c745cf78f  389-ds-base-2.2

**Comment by mmatsuya** [comment]
plugins/accpol_test.py::test_acct_policy_consumer test failed, because it checks the lastLoginHistory update too early.

```
        # Verify there is no referral error
        results = supplier.ds_error_log.match('.*.acct_update_login_history - Modify error 10 on entry*')
        assert not results
    
        # Verify that we got 3 values for lastLoginHistory
>       assert len(user_supplier.get_attr_vals_utf8_l('lastLoginHistory')) == 3
E       assert 2 == 3
E        +  where 2 = len(['20250122025850z', '20250122025852z'])
E        +    where ['20250122025850z', '20250122025852z'] = get_attr_vals_utf8_l('lastLoginHistory')
E        +      where get_attr_vals_utf8_l = <class 'lib389.idm.user.UserAccount'>(instance_name="supplier1", dn="test_user_1000").get_attr_vals_utf8_l

dirsrvtests/tests/suites/plugins/accpol_test.py:1381: AssertionError
```
lastLoginHistory was not updated for the last (third) bind operation yet. This can be resolved by just adding a small sleep command.

**Comment by droideck** [comment]
5864298f4..9e4890b73  389-ds-base-2.6 -> 389-ds-base-2.6

**Comment by mmatsuya** [comment]
e171a63 .. 06f9760  main
66a9ee1 .. 92fc2f3  389-ds-base-3.0
86dd51f .. 5ca66ba  389-ds-base-2.5
59ffc64 .. ef705ae  389-ds-base-2.4
fb1954f .. 1fa7d62  389-ds-base-2.3
ddd0ffa .. 906caa7  389-ds-base-2.2
